### ISSUE TITLE
Not found : @std/esm

### ISSUE THREAD

**Issue by ywwhack** [standard-things/esm#1]
When i run `npm i --save @std/esm`, it throws a error, seems like the `@std/esm` module is not in npm register.

![image](https://cloud.githubusercontent.com/assets/8746197/26519095/b7118448-42ee-11e7-84c7-d325944d00c9.png)

**Comment by sinventor** [comment]
I came across the same issue and for the time being I do installation via github using `npm i --save standard-things/esm`.

**Comment by jdalton** [comment]
The project isn't released yet. You're hit it up a bit too early.
