### ISSUE TITLE
[0.10.1] Misleading ERR_REQUIRE_ESM error when requiring mod with earlier version

### ISSUE THREAD

**Issue by clintwood** [standard-things/esm#100]
If module A imports a module B which has an earlier version (semver) for `@std/esm` in its list of dependencies (in either of dep, dev or peer dependencies) the module will fail on import and output an error like `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /absolute/path/to/module/B/index.mjs`.  Similarly this occurs for any dependency down the chain of dependencies from module B on, etc.

This is the case irrespective of using any `esmRequire(...)` or `import x from 'xx'` or whether  `package.json` has `"@std/esm": {...}` options, or if passing options to `const esmRequire = require('@std/esm')(module, {...});` and then using `esmRequire(...)`.

I hope I explained that ok ;)

EDIT: Workaround is to use `"@std/esm": "^0"`  dev/peer/dependencies.

**Comment by jdalton** [comment]
Hi @clintwood!

Could you create a simple repro repo.

**Comment by clintwood** [comment]
From what I can see the issue is related to the combination of `index.mjs` being in the root of the package when there is a dependency of a different version of `@std/esm` to the parent package (if that makes sense).  Here is a repro - [`esm-app`](https://github.com/clintwood/esm-app) which uses [`esm-mod-b`](https://github.com/clintwood/esm-mod-a).

To repro: 
1) clone [`esm-app`](https://github.com/clintwood/esm-app)
2) npm i
3) run `node ./index.js`  - you should see an error
4) in `esm-app` package.json change esm-mod-a tag to `#2.0.0` - repeat steps 2 & 3 - no error
5) in `esm-app` package.json change esm-mod-a tag to `#3.0.0` - repeat steps 2 & 3 - no error

Take a look at the tags 1/2/3.0.0 for  [`esm-mod-b`](https://github.com/clintwood/esm-mod-a) to see the differences.

**Comment by jdalton** [comment]
Looks like this may be an `npm` issue. Your `esm-app` has a `@std/esm` dep of `^0.10.1` while `esm-mod-a` has a dep of `@std/esm` of `^0.9.2` but npm is only installing the dep of `@std/esm` of `0.10.1` which means your `esm-mod-a` is getting the wrong dep and so its checks for the right version of `@std/esm` are failing. By semver pre-v1.0 the ^ stops at the minor version so 0.9.0 and 0.10.0 are treated like major in post-1.0.

**Comment by jdalton** [comment]
Seems to be the case for npm v4 and v5.

**Comment by jdalton** [comment]
Ah found it. Your `std-mod-a` dep has `@std/esm` as a dev dep while `esm-app` has it as a dep which means when you `npm i` `esm-app` you're not installing the deps of `esm-mod-a`.

**Comment by jdalton** [comment]
After tweaking that I found other issues.

**Comment by jdalton** [comment]
Part of it is #99.

**Comment by jdalton** [comment]
I should also tweak it not to look for the dev dep if its a dep of a dep.

**Comment by jdalton** [comment]
The range check of the dev dep is causing the fail. I'll fix this and bump out a new release by the evening.

**Comment by jdalton** [comment]
Thanks for hammering on this stuff. Deps of deps is an interesting and important case to get.

**Comment by clintwood** [comment]
All good, #101 may be mixed in to these two issues too - but I can't say for certain!

**Comment by jdalton** [comment]
Patched by https://github.com/standard-things/esm/commit/9a205f6ad2089925c7fd1e498e8dc28dabae0dcb and https://github.com/standard-things/esm/commit/9a205f6ad2089925c7fd1e498e8dc28dabae0dcb.

I'll cook up unit tests and bump tonight.

**Comment by jdalton** [comment]
v0.10.2 is released 🎉
