### ISSUE TITLE
[0.10.1] .esm-cache dirs being create in all code dirs

### ISSUE THREAD

**Issue by clintwood** [standard-things/esm#101]
I'm getting `.esm-cache` dirs being created in all code directories not just at process.cwd() - is this expected behavior?

**Comment by jdalton** [comment]
Hi @clintwood!

Cache directories tend to live next to the `package.json` that [defines their options](https://github.com/standard-things/esm/blob/0.10.1/src/pkg-info.js#L33).

**Comment by jdalton** [comment]
How you are using `@std/esm`? Do you have a sample repo?

**Comment by jdalton** [comment]
Patch https://github.com/standard-things/esm/commit/91da650f3055e0e9dd8732e845750b3881116e41 to use the cache location of module overriding load options.
