### ISSUE TITLE
Can't import from graphql-server-express

### ISSUE THREAD

**Issue by arackaf** [standard-things/esm#102]
It seems running

```
import { graphqlExpress, graphiqlExpress } from "graphql-server-express";
```

results in the error

> exports.hasOwnProperty is not a function

---

My setup looks like this

```
require = require("@std/esm")(module, { esm: "js", cjs: true });
```

Is this a bug in the loader, or is this package doing something crazy?  I of course worked around things by just using CJS here, but I thought I'd report it in case it was a bug.

**Comment by arackaf** [comment]
Hm, this fails too, with the same error

```
import { makeExecutableSchema, addMockFunctionsToSchema } from "graphql-tools";
```

am I missing a configuration property?

**Comment by jdalton** [comment]
Hi @arackaf!

Can you create a simple repro repo?

**Comment by arackaf** [comment]
Sure, sorry John.  I'd just assumed you had a sandbox already up for this sort of thing.

https://github.com/arackaf/booklist/tree/special/jdd 

and then run 

node app 

after `npm install`. 

The entire project does nothing more than set up your loader, and then imports those things, so there shouldn't be any dumb mongo or S3 connection errors :)

**Comment by jdalton** [comment]
Found it!

One of the modules graphql modules is doing:
```js
for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
```
I was passing `exports` as a `null` prototype Object which would be missing the `hasOwnProperty` method on its prototype. Easy fix.

**Comment by arackaf** [comment]
Saweet!  Would you mind pinging this thread when there's a new version out??? :D

**Comment by jdalton** [comment]
v0.10.2 is released 🎉

**Comment by arackaf** [comment]
You're awesome - thank you so much!
