### ISSUE TITLE
Destructuring parameters - defaults break code

### ISSUE THREAD

**Issue by srigi** [standard-things/esm#103]
code like this is supported & executed in Node 8.3+ without problems:

```js
module.exports = ({ foo, bar = 10 }) => {
  console.log(foo, bar);
}
```

However if I use **ESM** to rewrite it into ES module form:

```js
export default ({ foo, bar = 10 }) => {
  console.log(foo, bar);
}
```

I get `SyntaxError: Unexpected token (1:32)`. Removing default value for `bar` will solve problem, but now I lost default parameter value functionality.

**Comment by jdalton** [comment]
Thanks @srigi!

It's a bug in our object rest/spread extension.

**Comment by jdalton** [comment]
Fixed regression https://github.com/standard-things/esm/commit/db543a81080248f53add952c02e0d4ee09a431ce#diff-1875f4585e50f74858eb185bc435b052 with patch https://github.com/standard-things/esm/commit/91dca28338406d916dcff7d5d064f1c8c4f5f905.

**Comment by jdalton** [comment]
`@std/esm` v0.11.0 is released :tada:

**Comment by srigi** [comment]
Thanks @jdalton, works like a charm.

**Comment by okwolf** [comment]
Is there a unit test to make sure this didn't break again? It seems to have worked through 0.16.0, but is broken again in 0.17.0 😭

**Comment by jdalton** [comment]
@okwolf There [is](https://github.com/standard-things/esm/issues/103#issuecomment-331356583). Can you provide an example of the syntax that's throwing an error?

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/c89e9222331fd37a8a4cffc90378b5d15875d84a and more tests https://github.com/standard-things/esm/commit/b92e53875b7e861fc5ec6a2188ba6c16eb028dde.

**Comment by okwolf** [comment]
@jdalton great catch! I hadn't realized it was only an issue with multiple destructured arguments.
