### ISSUE TITLE
Unable to `module.exports = esModule` without cloning

### ISSUE THREAD

**Issue by arackaf** [standard-things/esm#104]
https://github.com/arackaf/mongo-graphql-starter/blob/special/jdd/index.js#L3

Named exports, in particular `createGraphqlSchema` from

https://github.com/arackaf/mongo-graphql-starter/blob/special/jdd/src/module.js

are not available unless I clone the object, like in the original link above.

To repro, clone that repo, `npm i` then jump into the `test` folder and run `node testRoot`. With the Object.assign from the top-level index.js (or object spread, obviously), it works, and logs "function".  If you remove the clone, and just export the ES module itself

`module.exports = require("./src/module.js");`

it blows up.

**Comment by jdalton** [comment]
Thanks @arackaf!

This is an interesting case of cjs bridge use. I'll add a unit test in the morning and cut a release.

**Comment by jdalton** [comment]
`@std/esm` v0.11.0 is released :tada:
