### ISSUE TITLE
missing esm.js.gz 

### ISSUE THREAD

**Issue by mitel** [standard-things/esm#105]
Hello,
the esm.js.gz does not ship with v0.10.2 via yarn. I had to build from source and copy the file.

thanks

**Comment by jdalton** [comment]
Hi @mitel!

Our package ships with the `esm.js.gz` you can verify it by downloading the tarball:
https://registry.npmjs.org/@std/esm/-/esm-0.10.2.tgz

This is a bug in yarn. It's auto cleaning `.gz` files. You should pop-in to the issue below and show your support for it getting fixed.
https://github.com/yarnpkg/yarn/issues/4450

**Comment by mitel** [comment]
thanks @jdalton , good to know

**Comment by jdalton** [comment]
Resolved by https://github.com/yarnpkg/yarn/commit/a3af4774f3131c64c048d4fdbe6df72d4edc117d.
