### ISSUE TITLE
Unclear error message on invalid import path

### ISSUE THREAD

**Issue by arackaf** [standard-things/esm#106]
Repro repo https://github.com/arackaf/mongo-graphql-adapter/tree/special/jdd-import-const

Swing over to the test directory, and run `node testRoot`

You'll get the error of 

> TypeError: Cannot convert object to primitive value

This is because test/project/schema has an invalid import of

`import { MongoId, String, Int, Float } from "../../src/createGraphQlSchema.js";`

since `../../src/createGraphQlSchema.js";` is an invalid path.

Should the error message be more clear?  It's otherwise quite good about reporting things like 

> XYZ is not a named export of module ABC

**Comment by jdalton** [comment]
In Node 8.5.0 I'm getting
> (node:72576) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Cannot find module ../../src/createGraphQlSchema.js

**Comment by jdalton** [comment]
In Node 7.10.0 I get
> 
```
internal/process/promises.js:60
                              `(rejection id: ${uid}): ${String(reason)}`);
                                                         ^

TypeError: Cannot convert object to primitive value
```

**Comment by jdalton** [comment]
Found it! This explains why I couldn't get `super.name` to work before 💫 
Patched https://github.com/standard-things/esm/commit/feba24ab168b740b1964fdc42e2035ab1d90cbc3.

**Comment by jdalton** [comment]
v0.11.1 is released 🎉
