### ISSUE TITLE
Enable @std/esm on "es:next" node-modules

### ISSUE THREAD

**Issue by martypdx** [standard-things/esm#108]
Not sure if I'm just not configuring this correctly, trying to use @std/esm with es6 style modules in `node_modules`.

Simplest test file `test-esm.mjs`:
```js
import { recursive } from 'acorn/dist/walk.es';
console.log(recursive);
```

Config in `package.json`:
```json
"@std/esm": {
    "esm": "js"
  }
```

Then:
```sh
> node -r @std/esm test-esm.mjs 
/Users/marty/dev/azoth/azoth-compiler/node_modules/acorn/dist/walk.es.js:342
export { simple, ancestor, recursive, findNodeAt, findNodeAround, findNodeAfter, findNodeBefore, make, base };
^^^^^^

SyntaxError: Unexpected token export
```

However, even `"debug": true` in package.json doesn't seem to change anything, have I botched something in configuring this?

**Comment by jdalton** [comment]
Hi @martypdx!

The `@std/esm` package.json options by default are for your package and do not extend to third-party packages. However, using the API you can use your config for them with:
```js
require = require("@std/esm")(module, true)
require("some-third-party/lib.js")
```

**Comment by martypdx** [comment]
@jdalton: Shoot, I'm trying to use @std/esm with ava for testing, so AFAIK not really a place I can hook into "loading" esm to call the API. (Project builds with rollup, so no need for @std/esm during that process).

**Comment by jdalton** [comment]
For AVA we've focused on using `@std/esm` for testing your own packages, in which case you could use the AVA `require` option to include `@std/esm`.  For reaching into others though you could have your initial test script be the one that calls `require = require("@std/esm")...` to setup things from there.

**Comment by martypdx** [comment]
That sounds promising, tried it out still running into issues.

I'm not entirely sure to how to have an ava "initial test script", presumably it would have to run for each forked process. But that aside, trying it for a single test file, I added at the top:

```js
require('@std/esm')(module, { esm: 'js' });
```

I had to remove the `"ava": { "require": "@std/esm" }` from package.json (otherwise gave "Could not resolve required module '@std/esm'" error). But still no luck on subsequent import: `SyntaxError: Unexpected token import`.
 
> For AVA we've focused on using @std/esm for testing your own packages
But isn't it becoming common to use es6 modules versions for tree-shaking? I would think that was fairly common scenario?

**Comment by jdalton** [comment]
This won't do anything:
> require('@std/esm')(module, { esm: 'js' });

The function returned from `require('@std/esm')` is a loader factory, it creates loaders.
So you'll have to assign the resulting loader to a variable to use it. In the examples I just assign it straight to `require = ...`.

> I had to remove the `"ava": { "require": "@std/esm" }` from package.json (otherwise gave `Could not resolve required module '@std/esm'` error). 

The `@std/esm` package needs to be a dep of your current package to use it in this way *(like a dev dep)*.

> But isn't it becoming common to use es6 modules versions for tree-shaking? I would think that was fairly common scenario

Tree-shaking is a tooling thing that's been solved for CJS and ESM. ESM isn't a magic bullet in that regards and still requires things like a [pure-module field](https://github.com/webpack/webpack/pull/5435) to be useful.

If you're having problems the easiest way to get help here is to create a simple repro repo. That way I can dig in and pin point your issue.

**Comment by martypdx** [comment]
@jdalton [Here is repro repo](https://github.com/martypdx/esm-ava). 

Looks like thing I am failing on is setting the esm options via the loader call. FWIW I was able to get babel plugin working with ava following similar pattern. Thanks again.

**Comment by babakness** [comment]
@martypdx This works for me `package.json`

```javascript
  "scripts": {
    "test": "ava"
  },
  "@std/esm": {
    "esm": "js",
    "cjs": true
  },
  "ava": {
    "require": ["@std/esm"]
  },
```

Without a loader

**Comment by jdalton** [comment]
@babakness The option can be shortened to `"@std/esm":"cjs"`. There's an AVA recipe [being added](https://github.com/avajs/ava/pull/1593) 😋
