### ISSUE TITLE
can std/esm run side-by-side with babel-node/babel-register?

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#109]
I was wondering if std/esm can run side-by-side with Babel - e.g. babel-node or babel-register - during development?

This [blog post](https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b) makes the following claim:

> Working with your existing tools like Babel and webpack.
> Playing well with other loaders like babel-register
> (using .babelrc "modules":false)

I went through several github issues here in the repo and their solutions. None of them seemed to be working. I tried a bunch of combinations with Babel v6.x and v7.0 Beta 1 with node v8.5.0.

If it should work side-by-side, could someone point me in the right direction?

**Comment by jdalton** [comment]
Hi @dnalborczyk!

std/esm doesn't augment your source so simple set your entry script to the script std/esm would be loading.

**Comment by dnalborczyk** [comment]
hey @jdalton thanks for this awesome module!

not quite sure what you mean, do you have an example? I literally tried for days to make it work.

I got here originally through https://github.com/babel/babel/issues/6285 but realized that node (_experimental-modules_ doesn't provide any require.extensions.

I really like the spec comliancy, as compared to the Babel module transforms.

**Comment by jdalton** [comment]
If you create a sample repo, I'll PR to it to make your stuff scenario work 😀

**Comment by dnalborczyk** [comment]
sorry for the delay, here is the sample repo:

https://github.com/dnalborczyk/stdesm-babel-test

examples of script _start-3_, _start-6_, and _start-9_ are failing.

thanks for looking into this!

**Comment by jdalton** [comment]
@dnalborczyk Ah, I missed that this was `babel-register`.

With `babel-register` you'll have to run `@std/esm` after `babel-register` until I [patch babel-register](https://github.com/babel/babel/issues/6248). You can use the `node` flag `-r @std/esm` with like:
```json
"start-3": "babel-node -r node_modules/@std/esm app-babel-stdesm.js"
```

**Comment by dnalborczyk** [comment]
thank you @jdalton unfortunately, this doesn't seem to working either :/

I run std/esm after babel-register (index-babel-stdesm.js, start-3)
```
require('babel-register');
require = require('@std/esm')(module, { esm: 'js' });

require('./app-babel-stdesm');
```

which throws an exception

```
/stdesm-babel-test/app-babel-stdesm.js:4
  static test = 'works';
              ^

SyntaxError: Unexpected token
    at Object.<anonymous> (/stdesm-babel-test/index-babel-stdesm.js:4:1)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
```

https://github.com/babel/babel/issues/6248 seems to indicate that the order of loading babel-register and std/esm matters, though it seems that the above should be unrelated, since the order is as suggested?


I also tried your other suggestion and added the script to the repo (start-10).

Babel does not support the _-r (require)_ flag, though I added it temporary in [node_modules/babel-cli/lib/babel-node.js]

```
case "-r":
  args.unshift("--require");
  break;
```

now it's throwing:
```
/stdesm-babel-test/app-babel-stdesm.js:1
(function (exports, require, module, __filename, __dirname) { import foo from './foo';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at loader (/stdesm-babel-test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/stdesm-babel-test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at Object.<anonymous> (/stdesm-babel-test/node_modules/babel-cli/lib/_babel-node.js:154:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stdesm-babel-test@ start-10: `babel-node -r @std/esm app-babel-stdesm.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stdesm-babel-test@ start-10 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by jdalton** [comment]
The [line I wrote](https://github.com/standard-things/esm/issues/109#issuecomment-332720451) should work.

**Comment by dnalborczyk** [comment]
unfortunately, it doesn't (for me).

babel-node doesn't support the -r (--require) flag from node, hence I added it.

_this is just speculation:_ not sure if you ran the script prior, it might just _appear_ to work, since it doesn't seem to throw an exception (not sure if babel-node or node is swallowing it), but there's nothing being written to the terminal. (-> console.log)

just to make sure it's not the version of node I'm using produces different results, I'm on v8.6.0.

**Comment by dnalborczyk** [comment]
@jdalton do you have any other ideas or any advice? appreciate your time!

**Comment by tilgovi** [comment]
I think I can confirm this behavior. The class fields proposal is stage-2. Maybe the parser for esm chokes on it, as was the case with object rest/spread earlier.

**Comment by jdalton** [comment]
> I think I can confirm this behavior. The class fields proposal is stage-2. Maybe the parser for esm chokes on it, as was the case with object rest/spread earlier.

`@std/esm` isn't supposed to support all-the-things. This is the job for babel-register. If babel-register isn't working with `@std/esm` then I suggest you file a bug on them or pitch in on the open ones I've filed. Coming to me asking me to expand the parser to hack around babel-registers lack of support is not the way forward.

**Comment by jdalton** [comment]
As far as I'm concerned there is no `@std/esm` bug here.

**Comment by jdalton** [comment]
> Maybe the parser for esm chokes on it, as was the case with object rest/spread earlier.

The case of object rest / spread was different in that support existed in released Node versions.

* BTW I toned down my reply because it sounded too grouchy :yum:

**Comment by tilgovi** [comment]
All good 😄!

I didn't intend to request anything or suggest a solution. I mostly commented to offer an explanation for everyone.

I agree 💯 with your assessment. Definitely getting babel/babel#6248 solved in the right approach.

**Comment by dnalborczyk** [comment]
thanks a lot @jdalton for looking into this! I kinda had the feeling it might need to be fixed on the Babel side-of-things, but wasn't quite sure. Much appreciated! Thanks for std/esm!
