### ISSUE TITLE
Circular dependency does not load correctly 

### ISSUE THREAD

**Issue by arackaf** [standard-things/esm#112]
Repo https://github.com/arackaf/mongo-graphql-adapter/tree/special/jdd-circular-deps

npm install, then run `node index` from the root.  You should get an error caused by an undefined import.  When you go into a or b and remove the circularity, the error goes away.

**Comment by jdalton** [comment]
Okay!

So we [do have tests for circular references](https://github.com/standard-things/esm/tree/master/test/fixture/cycle) but none for this case.
It looks like we're following the native behavior here though since renaming your `a.js` and `b.js` to `.mjs` and running `node --experimental-modules src/a.mjs` results in:
```
(node:93251) ExperimentalWarning: The ESM module loader is experimental.
ReferenceError: a is not defined
    at file:///Users/jdalton/projects/mongo-graphql-adapter/src/b.mjs:4:10
    at ModuleJob.run (internal/loader/ModuleJob.js:105:14)
    at <anonymous>
```

**Comment by jdalton** [comment]
To solve your issue you can export as a getter:
```js
export default {
  get value() {
    return b.value
  }
}
```
and
```js
export default {
  get value() {
    return a.value
  }
}
```

**Comment by jdalton** [comment]
Hmm actually getters result in 
```
node --experimental-modules src/module.mjs
(node:94558) ExperimentalWarning: The ESM module loader is experimental.
RangeError: Maximum call stack size exceeded
    at Object.get value [as value] (file:///Users/jdalton/projects/mongo-graphql-adapter/src/b.mjs:5:27)
    at Object.get value [as value] (file:///Users/jdalton/projects/mongo-graphql-adapter/src/a.mjs:6:52)
```
