### ISSUE TITLE
Should Error.code be readonly?

### ISSUE THREAD

**Issue by clintwood** [standard-things/esm#113]
I'm using Rollup which modifies the `code` property on a caught `Error` object to [augment](https://github.com/rollup/rollup/blob/b949eb08169115ff66648838cbc4833379bf9440/src/utils/transform.js#L30) `Error.code` for their specific context.

In `@std/esm` `Error.code` is defined as a [getter](https://github.com/standard-things/esm/blob/a851cae50f3d2e62b442cfe5db2f4199031883ac/src/errors.js#L30) so when `rollup` tries to 'augment' the error by setting `code` I get an error thrown by rollup, `TypeError: Cannot set property code of [object Object] which has only a getter`, which is wholly misleading.

I noticed that if you create a standard `Error` object in Node there is no `code` property by default and one is free to add or modify it at will.

So `code` should probably be a writable prop so that libraries like Rollup can 'augment' errors to be more specific for their unique contexts!  This case may not be unique to Rollup as other libraries may do the same!

   PS I couldn't find any specs on the how an `Error` object should behave - but didn't look too hard ;)

**Comment by jdalton** [comment]
Hi @clintwood!

We're following Node's behavior here. See [internal/errors](https://github.com/nodejs/node/blob/28a0af358ac998f94052199dc62a8140e8a11ac5/lib/internal/errors.js#L17-L32). It looks like an oversight on Node's part since folks are modifying the `code`. It's easy enough for use to tweak on our end.

**Comment by jdalton** [comment]
@clintwood Thanks for opening the [rollup issue](https://github.com/rollup/rollup/issues/1658).

I opened a [Node issue](https://github.com/nodejs/node/issues/15658) too.

**Comment by jdalton** [comment]
v0.11.1 is released 🎉

**Comment by jdalton** [comment]
Fixed in Node https://github.com/nodejs/node/commit/42a2a9badb6974e47b98aaee052e9710f34b93e8!
