### ISSUE TITLE
Use recommended semver i.e. release a v1.0.0

### ISSUE THREAD

**Issue by mansona** [standard-things/esm#116]
Howdy 👋 

I may have already said this but thanks a million for such an awesome module 👍 

I want to open a discussion about bumping the current release to a v1.0.0 and to start following the **recommended** npm semver. In this discussion https://github.com/standard-things/esm/issues/66 there was a lot of talk about stabilising the APIs that are being used from node, and although I agree with the discussion and point of it I notice at the end you mention that "Please note I've changed some usage instructions." and released a minor version.

I am assuming that because the instructions have changed this is a breaking change? I have not yet tried it but I would imagine that it won't work for us because we are also doing something non standard https://github.com/standard-things/esm/issues/61 

I understand that by "official" semver documentation any pre 1.0.0 minor release is considered a major breaking change, but I think this is "considered harmful" in the wider npm community. So much so that the official [npm documentation](https://docs.npmjs.com/getting-started/semantic-versioning) states clearly "If a project is going to be shared with others, it should start at 1.0.0, though some projects on npm don't follow this rule."

I can't find a link to the original discussion but npm has now defaulted to version 1.0.0 for all newly init'ed modules since npm@2.0.0 3 years ago: https://github.com/npm/npm/releases/tag/v2.0.0

I think the sentiment from npm is that "integers are cheap" and there is nothing wrong with having a v6.0.0 of this esm loader 😄

**Comment by jdalton** [comment]
Hi @mansona!

> I understand that by "official" semver documentation any pre 1.0.0 minor release is considered a major breaking change

Yep, which is why I have it as a pre 1.0.0 release until it stabilizes *(which should be soon)*.

> I think the sentiment from npm is that "integers are cheap" and there is nothing wrong with having a v6.0.0 of this esm loader

I get it, I do. I'm going on v5 of Lodash. And like Lodash I started at a low pre-1.0 number. It gives a clear signal that things are still early and unstable. The loader should be ready for 1.0 in the next couple of weeks. Giving it time to bake is important because deps like Lodash, which impacts ~150,000 packages, will depend on it.
