### ISSUE TITLE
Code coverage no longer working: nyc + Mocha + @std/esm

### ISSUE THREAD

**Issue by gauntface** [standard-things/esm#117]
With 0.5.X I was able to run my tests as:

```
nyc --require @std/esm mocha ./test/**/*
```

This would enable me to write source code and tests in ESM with code coverage.

After upgrading I can get the tests to run if I move the require into mocha:

```
nyc mocha --require @std/esm ./test/**/*
```

My guess this is because you aren't messing with the system require method like before. Is there any way to get this working or is code coverage a lost cause?

**Comment by jdalton** [comment]
Hi @gauntface!

It depends on how `nyc` is requiring things. The `@std/esm` loader detects its use in `node` params and will enable a more aggressive hook if that's the case. Can you create a simple repro repo for me to look at.

**Comment by gauntface** [comment]
Will try and put together a small repro later tonight.

If you are curious, our test project is here: https://github.com/GoogleChrome/workbox/tree/v3-std-esm-bump (tests are run via `npm run test -- ./test/**/node/**/*.mjs`)

**Comment by grimmr** [comment]
I have been trying to understand the interaction between `std/esm` and `nyc` for the last few days myself because, no matter what I try, I couldn't get it to work. The one thing that stuck out to me is that `nyc` resets `require.extensions`, see [this line](https://github.com/istanbuljs/nyc/blob/425c0fd06ebcaf130ba4a8a261bbf467cad96e85/index.js#L307), since that seems like the wrong thing to do in every case I can come up with.

**Comment by jdalton** [comment]
Hi @grimmr!

It depends on how you've hooked `@std/esm`. If you use the programmatic API it won't hook the traditional `require.extensions`.
#### index.js
```js
require = require("@std/esm")(module)
require("./main.mjs")
```

**Comment by jdalton** [comment]
Okay @gauntface!

I should have a patch for this soon. You'll be able to continue to use:
```shell
nyc --require @std/esm mocha ./test/**/*
```

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/c3059cba46d92d2f303fc0d2ae345d318969e89c and https://github.com/standard-things/esm/commit/0f0b4805944537ce8786bd52aadcb641bb5f9dba.
I'll publish 0.11.3 in the morning.

**Comment by jdalton** [comment]
@gauntface When I upgrade the v3 branch of Workbox to the WIP `@std/esm` of our master branch. I get these test fails:
<img width="644" src="https://user-images.githubusercontent.com/4303/31305625-fed58448-aaf2-11e7-8b8a-2d4ac5fc656d.png">
and
<img width="1027" src="https://user-images.githubusercontent.com/4303/31305630-205c65a0-aaf3-11e7-89f3-470f5c78eb65.png">

Any ideas?

**Comment by jdalton** [comment]
@gauntface I figured it out. Follow-up patching soon.

**Comment by jdalton** [comment]
Fixed it. Even tested it with this workaround comment removed and 💯 workbox tests pass !

<img src="https://user-images.githubusercontent.com/4303/31309381-48548208-ab3a-11e7-84fc-4b1b7cb6a26e.png">

**Comment by jdalton** [comment]
[v0.11.3](https://github.com/standard-things/esm/releases/tag/0.11.3) is released :tada:

**Comment by gauntface** [comment]
Ha ha, thank you @jdalton looks awesome.

A batch of our tests are using proxyquire and seems to be our new problem area. Will dig into how we can get off of it.
