### ISSUE TITLE
Configuration without package.json

### ISSUE THREAD

**Issue by pspeter3** [standard-things/esm#12]
Is it possible to have ambient configuration, such as file extension, without a package.json?

**Comment by jdalton** [comment]
Not yet, but I'd be open to it. It's still a way to explicitly opt-in, which is the main concern.
Do you have names to bikeshed? Maybe `.esmrc`?

**Comment by pspeter3** [comment]
It's actually not an issue of a package.json but the lack of the ability to configure the location of this. So either the ability to set options through environment variables or an environment variable for where to discover the configuration. I want to be able to use this with Bazel/TypeScript and I do not believe TypeScript will output .mjs files for me.

**Comment by jdalton** [comment]
The `std/esm` loader will lookup the closest package.json, excluding `node_modules` boundaries. So you should be able to specify it at a project level. Would that do?

**Comment by pspeter3** [comment]
Probably! I'll attempt it and reopen if it is an issue.
