### ISSUE TITLE
Both vscode & Chrome Inspect debugger have issues with Inline Souremap Encoding 

### ISSUE THREAD

**Issue by t83714** [standard-things/esm#120]
Currently, the inline sourcemap generated by @std/esm is not in base64 encoding.
Here is one example:
```
data:application/json;charset=utf-8,%7B%22version%22:3,%22sources%22:%5B%22/Users/user/Development/node_modules/xyz/index.js%22%5D,%22names%22:%5B%5D,%22mappings%22:%22AAAA%22%7D
```
It seems vscode & chrome inpsector debugger will always assume a data URI for the inline sourcemap is in base64 encoding (even if the `;base64` extension is not included in the data URI scheme).

This will lead to data decoding error. e.g. vscode will report error similart to this:
```
SourceMaps.getMapForGeneratedPath: exception while processing path: /Users/user/Development/node_modules/toyrobotsimulator/index.js, sourcemap: data:application/json;charset=utf-8,%7B%22version%22:3,%22sources%22:%5B%22/Users/user/Development/node_modules/xyz/index.js%22%5D,%22names%22:%5B%5D,%22mappings%22:%22AAAA%22%7D
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
```
Could we please change the inline sourcemap encoding to base64?

**Comment by jdalton** [comment]
Sure I can! Worth noting I haven't seen the issue using Chrome 61 or with [whatever version of inspector](https://github.com/asfktz/devtools-playground) Electron uses.

Are you testing with `node --inspect`? Or uses the inspector within vscode only?

**Comment by jdalton** [comment]
@t83714 Can you file a bug on [vscode](https://github.com/Microsoft/vscode) too with the version number you've used and steps to repro?

**Comment by jdalton** [comment]
Thanks! I'll defer to the vscode bug.

**Comment by jdalton** [comment]
Root caused to `convert-source-map` dep; https://github.com/thlorenz/convert-source-map/issues/59.

**Comment by t83714** [comment]
Any chance for the future version of @std/esm to use base64 encoded data URI.
The current encoding is correct & valid data URI scheme.
However, many data URI decoder implementation assumes base64 encoding by default incorrectly --- tried a few online decoder and it seems many of them didn't work properly.
Change it to base64 will make it less chance it to break --- even it's the issue of other libs.

**Comment by jdalton** [comment]
My main concern is `node --inspect` and Chromium based inspecting (through Electron). Since those cases are covered I rather avoid the overhead of base64 encoding if possible since the source mapping is just a nice-to-have way to avoid seeing the instrumented code behind the scenes.

I'm OK with punting this to vscode or its dependencies.

**Comment by t83714** [comment]
No problem. Thanks for the note.

**Comment by Pokute** [comment]
This bug still happens and it is as you've thought, @jdalton. VSCode's node debugger expects that source maps are formatted in base64. I've managed to hack it to work, but it'll take a while until I can do a PR for ms-vscode.node-debug.

**Comment by jdalton** [comment]
Hi @Pokute!

I'm following along on the VSCode side and have volunteered to do a PR too. If you beat me to it that's great as well. I imagine it's just a few lines. I've outlined the function to modify in the issue thread. See https://github.com/Microsoft/vscode/issues/35978#issuecomment-405813306.

**Comment by jdalton** [comment]
**Update:**

Thanks @Pokute for [patching it](https://github.com/Microsoft/vscode-chrome-debug-core/pull/344)! It should land in tomorrow's Insiders build.
