### ISSUE TITLE
esm bin

### ISSUE THREAD

**Issue by thejameskyle** [standard-things/esm#122]
Trying to find a way that a `babel-node`-like tool for `@std/esm` could exist.

```js
esm-node index.js
```

It wouldn't be hard to do, but I'm wondering if it could go a step further and wrap other executables.

```js
esm-exec ./node_modules/.bin/cmd
```

Could this somehow execute the bin command with `esm-node` instead of `node`? You couldn't just rewrite the shebang, but maybe you could wrap the executable with another file.

**Comment by jdalton** [comment]
📌 *Just a heads up, I have family friends over until Sunday afternoon so my responses may be sporadic or light on details until then.*

**Comment by jdalton** [comment]
Hi @thejameskyle!

Automating hooking up `@std/esm` should be doable. For example your `esm-exec` could move the `bin/cmd` to `bin/_cmd` and make `bin/cmd` invoke `@std/esm` and `module.exports=stdesmRequire("./_cmd")`.
