### ISSUE TITLE
Running jest leads to "TypeError: Path must be a string"

### ISSUE THREAD

**Issue by mknet** [standard-things/esm#124]
My test file

```javascript
let loader = require("@std/esm")(module, { cjs: true, esm: "js" });
const RenderStreamFactory = loader("./RenderStreamFactory.js").default;

let renderStreamFactory = new RenderStreamFactory();

test('adds 1 + 2 to equal 3', () => {
    expect(renderStreamFactory).toBeNull();
  });
```

When im invoking jest vom the CLI I get

```
FAIL  src/RenderStreamFactory.test.js
  ● Test suite failed to run

    TypeError: Path must be a string. Received undefined
      
      at assertPath (path.js:28:11)
      at Object.relative (path.js:1268:5)
```

If I'm using the loader config in another context without Jest it works fine.
Using version 0.11.3 of @std/ESM

Thanks for your help

**Comment by jdalton** [comment]
Hi @mknet!

Could you create a simple repro repo?

**Comment by mknet** [comment]
Hey @jdalton,

yeah, I noticed the other issue but since I got another error back I created a separate issue.

I created a [repro repo with a simple example](https://github.com/mknet/jest-esm-issue). I hope you get the same result.

**Comment by jdalton** [comment]
Thanks @mknet!

I can't repro with jest v21.2.1
<img width="522" src="https://user-images.githubusercontent.com/4303/31742051-3e90c5fe-b40b-11e7-84dd-5a9a5d241930.png">

Maybe you need to clear your `node_modules` folder.

**Comment by mknet** [comment]
Oh boy, yeah, the global installation of jest was outdated. Sorry to bother you and thanks for your help.

**Comment by kelenyo** [comment]
Oh boy ;-)
