### ISSUE TITLE
Suggestion for "require" / "loader"

### ISSUE THREAD

**Issue by olstenlarck-old** [standard-things/esm#125]
Heya! :tada: :)

Don't sure how to call it exactly. The case is that. i want to use the defaults of the `@std/esm` but it still needs a bit boilerplate stuff like:

```js
function isObject (val) {
  return val && typeof val === 'object' && !Array.isArray(val)
}

function esmInteropRequire (id, opts) {
  const ex = require('@std/esm')(module, opts)(id)
  return isObject(ex) && 'default' in ex ? ex['default'] : ex
}

module.exports = esmInteropRequire('./index.mjs')
```

I thought to release it as separate package. But it would be good to have it here, don't you think? So basically, so users may just use it like that

```js
module.exports = require('@std/esm/require')('./path/to/your/michael.mjs')
```

Most of us have `./src` dirs, right? So then we can just convert all of them to `.mjs` extension and have just one `index.js` file in that `src` folder like `./src/index.js` which will be pointed by `main` field. And the `./src/index.mjs` would be pointed by `module` field.

The index.js in the `src` then would just look like that

```js
module.exports = require('@std/esm/require')('./index.mjs')
```

And no one will think for anything. The only thing that would be needed is to add it as `dependency` and you will be spec compliant at maximum. :)

**Comment by olstenlarck** [comment]
That `@std/esm/require` is actually that file

```js
const isObject = require('isobject')

module.exports = (id, opts) => {
  const ex = require('@std/esm')(module, opts)(id)

  return isObject(ex) && 'default' in ex ? ex['default'] : ex
}
```

**Comment by olstenlarck** [comment]
hay there... i'm the same. :D Please ping me here.

**Comment by olstenlarck** [comment]
Btw, jdalton... does `@std/esm` respects the `module` field when loading external modules?

**Comment by jdalton** [comment]
Hi @olstenlarck!

The `module` is needed from the requesting package to base the loader in the correct path (from the `module.filename` so we shouldn't use the `module` object from within the loader itself, like `@std/esm/require`.

Is your main goal to reduce a `.default` property?

> does `@std/esm` respects the `module` field when loading external modules?

It doesn't since it doesn't have an official meaning. When devs have used it in the past it's been for a dev/build-time scenario so I wanted to avoid throwing an unexpected production scenario into the mix.

**Comment by olstenlarck** [comment]
> The module is needed fro

... yea, realized that later ;d

> Is your main goal to reduce a .default property?

Yea. Probably option called `interop: true/false` for that? hm.

Btw, any idea how to make the things to work properly with the `nyc` (or any other coverage flow)? Almost whole day i'm playing to get such job done. Basically, it works - everything runs without errors, but it seems that it can't create reports.

```
$ nyc --reporter=lcov node --require @std/esm test/index.mjs
 ✔ some cool test
$ nyc report && nyc check-coverage
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

the same is if move the `require` flag to nyc, and same if have it in both places.

**Comment by jdalton** [comment]
You're on the right track with `nyc` and `--require @std/esm`.
If you create a small repro repo I'll check into it.

**Comment by olstenlarck** [comment]
Nope. None of the things works.

Finally just remembered the `babel-node`, so it just runs with `babel-preset-env` and `babel-plugin-istanbul`.. 

```
nyc --report=lcov babel-node test/*.mjs
```

:tada: :100:
