### ISSUE TITLE
Cannot add property _esModule, object is not extensive

### ISSUE THREAD

**Issue by arackaf** [standard-things/esm#126]
Repo to repro with

https://github.com/arackaf/test-mongo-graphql-starter.git

npm install, and then `node index` and you should get

This only started happening after the 0.12 upgrade, sorry :( 

> TypeError: Cannot add property __esModule, object is not extensible
    at Object.<anonymous> (c:\GIT\test-mongo-graphql-starter\node_modules\mongo-graphql-starter\src\queryUtilities.js)
    at Object.<anonymous> (c:\GIT\test-mongo-graphql-starter\node_modules\mongo-graphql-starter\src\queryUtilities.js)

**Comment by jdalton** [comment]
No problem! Thank you!

**Comment by jdalton** [comment]
I knew 0.12.0 was going too quiet :yum:

**Comment by arackaf** [comment]
Ugh sorry - I was using that repo repro for more than one thing.  I've updated "mongo-graphql-starter": "0.1.1" to ship with a hard reference to your 0.11.0 loader - just update package.json to be 

"mongo-graphql-starter": "0.1.0"

and it should ship with no loader at all (because I'm a moron) and so with 0.12 in the parent directory, the bug should reproduce.

**Comment by jdalton** [comment]
No prob. I've already repro'd and patched this morning, just figuring out a test case to add :yum:

**Comment by arackaf** [comment]
So what was the problem?  (just curious)

**Comment by jdalton** [comment]
This https://github.com/standard-things/esm/commit/312b3d9ee1697077b5dabc6ee51a9b7ce0449780.

**Comment by arackaf** [comment]
Ha - I meant more, what craziness was my code doing that you hadn't accounted for, which broke your loader?

**Comment by jdalton** [comment]
Its related to `"cjs":true` but beyond that not too sure. I'll cook up a test though.

**Comment by jdalton** [comment]
Added tests https://github.com/standard-things/esm/commit/99e93ec0ab9aae688297f1d36cf0743294bdc6c7.

**Comment by jdalton** [comment]
[0.12.1](https://github.com/standard-things/esm/releases/tag/0.12.1) is released 🎉
