### ISSUE TITLE
EventEmitter observer pattern not working as expected using cjs : true

### ISSUE THREAD

**Issue by MatthieuLemoine** [standard-things/esm#129]
Hi!

EventEmitters are not working as expected when used with `@std/esm` and the cjs option enabled.

When I create an event emitter in a module (emitter.js), set up a listener in another one (index.js) and then call an action that will trigger an event in a third one (action.js), the listener will not be called.

I've created a small reproduction here [MatthieuLemoine/std-esm-events](https://github.com/MatthieuLemoine/std-esm-events).

We can see that in all cases (cjs, esm, esm with cjs : true) the listener will receive the 'Direct call' message. But the 'Indirect call' message will not be received by the listener for the `esm cjs : true` case.

```javascript
// emitter.js
import EventEmitter from 'events';

export const emitter = new EventEmitter();

export const ON_NOTIFICATION_RECEIVED = 'ON_NOTIFICATION_RECEIVED';

export function trigger(text) {
  console.log('emitter.js :::', emitter._events); // will log the listener in the `direct` case but not in the `indirect` one
  emitter.emit(ON_NOTIFICATION_RECEIVED, text);
}

// action.js
import { trigger } from './emitter';

export default function action(text) {
  trigger(text)
}

// index.js
import { emitter, ON_NOTIFICATION_RECEIVED, trigger } from './emitter';
import action from './action'

emitter.on(ON_NOTIFICATION_RECEIVED, console.log); // Will log 'Direct call' but not 'Indirect call'
console.log('index.js :::', emitter._events); // Will log the above listener
action('Indirect call');
trigger('Direct call')
```

It seems that when using `cjs: true`, `index.js` and `action.js` don't share the same reference to the `emitter.js` module.

**Comment by jdalton** [comment]
Thanks @MatthieuLemoine!

This is a regression I recently introduced. I've patched the issue but still need to come up with a unit test to prevent the fail again in the future.

**Comment by jdalton** [comment]
Test added https://github.com/standard-things/esm/commit/af8afdd108ba9a4d6f0c0b2f67d915f91de3506c.
