### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by pspeter3** [standard-things/esm#13]
Would you be open to a PR that enabled a CLI with roughly the following API?

```
esm $SOURCE $TARGET
```

**Comment by jdalton** [comment]
Hi @pspeter3!

What is `$SOURCE` and `$TARGET` in your usage example?

Currently, CLI use is done by
```shell
node -r @std/esm file.mjs
```

**Comment by pspeter3** [comment]
`$SOURCE` and `$TARGET` would be build file paths. I think most of the time I will use the register version but I need to be able to integrate this into a build system which produce CommonJs. Example,

```sh
esm path/to/file.mjs build/path/to/file.js
```

**Comment by jdalton** [comment]
Ah, for file transpiling I think you're better off with Babel. The `std/esm` loader gets into things that aren't as easily transpilable (really more runtime-centric)

**Comment by pspeter3** [comment]
Ah ok 😞. That's totally fair. I like that ESM seems much simpler than Babel. I'll probably use the TypeScript compiler to do the transpile then. Thanks!

**Comment by jdalton** [comment]
To simplify you Babel transforms I recommend [babel-preset-env](https://github.com/babel/babel-preset-env). You can even get super specific with what plugins to exclude. See [our usage](https://github.com/standard-things/esm/blob/0.1.1/.babelrc) as an example.
