### ISSUE TITLE
`require` back into project doesn't work

### ISSUE THREAD

**Issue by mAAdhaTTah** [standard-things/esm#130]
Ok, so I know that title is kinda bad, and I am going to get together a repro case, but here's what I'm doing:

I'm working on a CLI tool that will provide a standardized way of running unit tests for this framework I'm building. The framework uses mocha's [programmatic API](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically) to set up and run the test suite. The CLI uses `@std/esm`, which then (for now) loops back and runs the CLI's unit tests with mocha.

Now, I dug into mocha's internals a bit, and the short version is `run` will go through the list of files added with `addFiles` and `require`'ing them. When it does, I'm getting `SyntaxError: Unexpected token import`. I have this in my package.json:

```json
  "@std/esm": {
    "esm": "js",
    "cjs": true
  }
```

The file it's requring is `.js`. My understanding was that `@std/esm` reads the `package.json` and will compile files in the package, although I'm not sure how that works if it's the root-level.

Short-version: I think the test files should be compiled by `@std/esm` but they're not when the require flow goes `current project (using @std/esm) -> dependency -> current project`.

I will get together a reproducible test case, but I just wanted to flag this in case you had thoughts already.

**Comment by mAAdhaTTah** [comment]
In case that description wasn't helpful (hint: it wasn't), here's a repro repo: https://github.com/mAAdhaTTah/esm-self-require

**Comment by jdalton** [comment]
Hi @mAAdhaTTah!

By default Mocha won't know to use the esm loader. So when it loads files it'll syntax error out. You can let it know by using it's `--require @std/esm` option or changing your invocation in `index.js`:
```js
// from
// require = require('../esm')(module);
// to
require = require('../esm')(module, true);
```
[as](https://github.com/standard-things/esm#getting-started)
> By default, `@std/esm` **only** processes files of packages that opt-in
     with a `@std/esm` options object or `@std/esm` as a dependency, dev
     dependency, or peer dependency in their package.json. However, you can
     enable processing **all** files with specific options by passing an options
     object as the second argument or passing `true` to use the options from
     your package.json.

**Comment by mAAdhaTTah** [comment]
I understand that, if we're running mocha from the command line, but I'm running it programmatically. I require in `@std/esm` at the entry point, which requires in a file that imports Mocha. We then `new Mocha`, add some file paths to the runner instance, and call `run`, which then `require`s in those files. We never leave a context in which the `@std/esm` loader has been bootstrapped. Mocha is simply `require`'ing the test files.

That said, we can ignore the complication of Mocha here, because it's just a `require` call. I've updated the reproducible example to be even simpler. The "mocha" part of the problem is now just a function that calls `require` on whatever path was passed to it. Take a look, maybe that'll clear up what I think the problem is.

https://github.com/mAAdhaTTah/esm-self-require

**Comment by jdalton** [comment]
@mAAdhaTTah As mentioned above you can change your code
```js
// from
// require = require('../esm')(module);
// to
require = require('../esm')(module, true);
```

**Comment by mAAdhaTTah** [comment]
Maybe I don't understand this part of the above description:

> By default, @std/esm only processes files of packages that opt-in with a @std/esm options object.

We don't necessarily want to process packages that haven't opted-in. Passing in `true` there causes `@std/esm` to process all of the dependencies as well, no? We don't necessarily want to process our dependencies; we just want to process packages that have explicitly opted-in with `@std/esm` in the package.json.

I'm pressing on this a bit cuz I understand your intention is to allow a dependency to opt-in to `@std/esm` behavior with the package.json. If that package imports a package w/o `@std/esm`, which then requires in the source package w/ `@std/esm`, it should re-enable process on that package.

Maybe I'm not doing a good job explaining, or I've misunderstood the intention, but my current understanding is this behavior makes it difficult / impossible for that behavior to work as you intended, hence filing this as a bug. Does that make sense?

**Comment by mAAdhaTTah** [comment]
Actually, maybe I am misunderstanding the expected behavior. If a package wants to opt-in to being compiled by `@std/esm`, does it need to do this whole `require('@std/esm')(module)` bit in its entry point as well? Or is `@std/esm` in the package enough, and its the responsibility of the app to do that?

**Comment by jdalton** [comment]
@mAAdhaTTah By default boundary is at the package. However, using the API as I showed above or calling leveraging `node -r @std/esm` or `mocha --require @std/esm` will enable cross package support.

**Comment by mAAdhaTTah** [comment]
That makes sense. My expectation was that when you re-enter said boundary, esm "re-enables".
