### ISSUE TITLE
bare @std/esm should not allow mocha with esm modules, and yet it works

### ISSUE THREAD

**Issue by giltayar** [standard-things/esm#133]
Look at https://github.com/giltayar/playing/tree/master/javascript/esm/std-esm-with-mocha

(it's the simplest package with mocha tests I could devise)

Theoretically, `npm test` shouldn't work. (after `npm i` of course).

Why? Because we run `mocha -r @std/esm test/test.mjs` in `npm test`. Mocha will require `@std/esm` and then _require_ `test/test.mjs`. But `@std/esm` should fail that require because `test.mjs` is an es module with `import`-s in it, and we're not allowed to require es modules in the bare (no options passed) configuration of `@std/esm`.

But it does not fail it, and moreover, the imports work.

So why isn't it failing?

**Comment by jdalton** [comment]
Hi @giltayar!

Support for Mocha is by design. Not working would not be a desirable outcome. As to the specifics for why it's working in this specific case I'll dig in and report back *(but working is a good thing)*.

**Comment by jdalton** [comment]
**Update:**

Okay! I looked into it and the reason it works is once `@std/esm` loads it will treat all subsequent loads like the common JS bridge since they aren't being loaded from a parent module loaded by `@std/esm`.

**Comment by giltayar** [comment]
Yes, I saw that root module must be able to "require" files that are ESM, but aren't they loaded from a module that is "require"-d by mocha and not by mocha (or specifically _mocha) itself?

And, btw, in the esm test files, `import.meta.url` is `undefined`, which is how I found out about the whole thing. So maybe that's the "real" bug.

**Comment by giltayar** [comment]
BTW, thanks for looking it up! I am giving a talk at NodeFest Japan about Native ESM in Node, and would like to, besides explaining about it, also give practical information about transitioning to it. And currently I don't have a good answer for how to migrate tests: native esm will never work until mocha (and others) are changed to support it natively, and this package (std/esm) won't work because `import.meta.url` is `undefined` (I'm assuming this is true for all required mjs modules)

**Comment by jdalton** [comment]
> Yes, I saw that root module must be able to "require" files that are ESM, but aren't they loaded from a module that is "require"-d by mocha and not by mocha (or specifically _mocha) itself?

Mocha is loaded, executes its `--require` flag values, and then loads test files. To reduce risk the `@std/esm` loader [hooks into Node](https://github.com/standard-things/esm/blob/master/src/index.js) in various ways depending on the context. When loaded through the CLI `@std/esm` is hooked at `require.extensions`.

>  and this package (std/esm) won't work because `import.meta.url` is `undefined` (I'm assuming this is true for all required mjs modules)

I don't know about all that, folks are using `@std/esm` with Mocha today and things are working great. You did find a bug though `import.meta.url` is normally populated so I'll fix that up.
