### ISSUE TITLE
Clarify how to load files outside of the package as ESM

### ISSUE THREAD

**Issue by Jamesernator** [standard-things/esm#134]
We're using multiple repositories (in a flat structure rather than nested) and I was trying to use `import()` to load a file from another repository but it doesn't seem to work it just gives a message like: `Must use import to load ES Module: /home/jamesernator/Projects/std-esm-test/other-folder/file.mjs`.

Now I tried using an options object to the loader as suggested [here](https://github.com/standard-things/esm#getting-started). I tried both `require('@std/esm')(module, {})` and `require('@std/esm')(module, { esm: 'mjs' })` but it doesn't seem to change anything so I'm not really sure how to load ESM files in another repository.

**Comment by jdalton** [comment]
Hi @Jamesernator!

Are you talking about a monorepo? Do you have a sample repro repo?

**Comment by Jamesernator** [comment]
Here's a minimal example, just run `npm install` in `repo1` and try running `node index.js`:

[std-esm-test.zip](https://github.com/standard-things/esm/files/1432943/std-esm-test.zip)

It fails for me to load `repo2/other-file.mjs` with the error `Must use import to load ES Module: /home/jamesernator/Projects/std-esm-test/repo2/other-file.mjs`

**Comment by jdalton** [comment]
Hi @Jamesernator!

Not an intuitive error, *I'll tweak that*, but since the loader is opt-in per package and your second package isn't opting-in with an options object or dep then you'll need to force it with:
```js
const loader = require('../../esm')(module, true)
```

**Comment by denisflorkin** [comment]
Not sure if it's a bug or a gap in my understanding.
I'm using std/esm in a project since this morning, everything is fine, I can import external module (native and user module) but one (node-fetch) only works when using the `require(<path>)` syntax.
Did I missed something ?

here's a demo (npm i && npm start):

[repro-esm-nodefetch 2.zip](https://github.com/standard-things/esm/files/1463951/repro-esm-nodefetch.2.zip)

**Comment by jdalton** [comment]
@denisflorkin You found a bug!
