### ISSUE TITLE
Using the module field in package.json

### ISSUE THREAD

**Issue by dburrows** [standard-things/esm#136]
When requiring an esm enabled package from node_modules I kind of expected esm to look at the module field in package.json and use that to work out what file to require. - for example if I have two files index.js and index.es6.js in a published module (that requires esm) and I set main to be index.js and module to be index.es6.js I would have expected index.es6.js to be loaded by esm in my app.

As it is I need to require the right file directly which involves the requiree to know the file structure of the required module.

Is there any way to point esm at the index.es6.js file automatically at present?  If it can't be done automatically would you be open to having a setting  in the esm config of the required module to point it at the ES6/ESM file?

**Comment by jdalton** [comment]
Hi @dburrows!

The "module" field is non-standard and can mean different things in different contexts (e.g. dev vs. prod). With @std/esm you shouldn't need hybrid (both cjs and esm sources). You are engouraged to ship just the esm and use the loader.

**Comment by dburrows** [comment]
I fully understand your point, but unfortunately we are in a transitional period in JS module evolution which makes things difficult, especially when trying to make modules that work well in browser and node environments across multiple apps that have different levels of ES6 support and/or use different build systems (if only I had a magic upgrade button!).

There may well be other ways around this, I will investigate, but worth asking the question in case other users have input. 

Thanks again for you work on this, much appreciated and massively useful ;)

**Comment by jdalton** [comment]
I'd avoid hybrid packages. The advantage of esm is so limited that if you have the slightest need to stay on cjs or umd then I'd just ship that. Simplifies everything 🙂

**Comment by hax** [comment]
@jdalton 

I notice it is not the first issue request `module` support. Could we reconsider `module` usage?

I understand avoiding hybrid packages could simplify many. But as the library author, enforce me rely on `@std/esm` runtime may be too aggressive in current stage. There are already many library authors adopt the hybrid strategy and use `module` field to approach ES module, I hope we can support their efforts.

Another problem of libraries requiring `@std/esm` directly is, it may eventually load many versions of `@std/esm`. I'm not sure whether it would affect performance or cause other problems.

Anyway, I think it could be an opportunity that give the decision of using `@std/esm` to the application author not the library author.

Thank you.

**Comment by jdalton** [comment]
Hi @hax!

Thanks for popping in and also for your help on JSON6!

> There are already many library authors adopt the hybrid strategy and use module field to approach ES module, I hope we can support their efforts.

That's because no other alternative existed at the time. Shipping two code bases with rough equivalence not only inflates the package size but also lets subtle hard to spot bugs in because transpilation is not 💯 compatible. Adding `@std/esm` to a hybrid package offers little win as it's going through an ESM loader when the perfectly runnable CJS code is available.

> Another problem of libraries requiring @std/esm directly is, it may eventually load many versions of `@std/esm`. I'm not sure whether it would affect performance or cause other problems.

The `@std/esm` loader is designed to work with multiple versions of itself. Once `@std/esm` goes 1.0+ multiple versions will be less of a worry since npm defaults to the `^` range.

>  I think it could be an opportunity that give the decision of using `@std/esm` to the application author not the library author.

The `@std/esm` loader is a win for app deving for sure!

**Comment by stereobooster** [comment]
> The "module" field is non-standard and can mean different things in different contexts (e.g. dev vs. prod).

There is this document: https://github.com/rollup/rollup/wiki/pkg.module

It is supported by webpack, rollup (and others ?). Can we have this feature as unlockable? [Example](https://github.com/stereobooster/main-module-browser-test) of `webpack` vs `@std/esm`

**Comment by tilgovi** [comment]
My thought on this is that '.mjs' and '.js' side-by-side is enough to have the "main" field resolve in a progressively enhanced fashion. Webpack 4 seems to be prioritizing .mjs over .js. I see "module" as having limited use going forward.

**Comment by stereobooster** [comment]
> Webpack 4 seems to be prioritizing .mjs over .js.

I suppose you will also need to use extensionless main in that case. 

```
"main": "dist/index"
```

and have two files side by side

```
dist/index.js
dist/index.mjs
```

Here is the question. If I use `"@std/esm": "js"` will I get `dist/index.mjs`?

**Comment by tilgovi** [comment]
I believe so!
