### ISSUE TITLE
[Question] Creating NPM package

### ISSUE THREAD

**Issue by jagi** [standard-things/esm#137]
Hi @jdalton, I didn't know where to ask this question, so I've decided to post it here.

I'm planning to create NPM package (previously I was creating mostly Meteor packages) and I would like to use ES modules. I'm trying to get as much information as possible on what path to follow, what tools to use when creating NPM packages that will take all the benefits of new ES features. I've seen that you're planning to release lodash 5 entirely using ES modules which is what I would like to do. The questions is, are you also planning to release bundles compatible with CJS or UMD too? Or you're going to stop supporting them at all?

I'm asking you because you have broad knowledge about this subject and I would like to learn from best. Maybe you could give some tips on what patterns to follow. Thanks!

EDIT:
I'm also asking this question because not every build tool works so great as Rollup. In Rollup I can take advantage of ES modules and do tree-shaking but in Meteor when using `@std/esm` I can only run such a package on the server. It does not work on the client. I've seen that you've been discussing on Meteor forums problem of ES modules in Meteor but it looks like Meteor is not going to support them for packages anytime soon.

**Comment by jdalton** [comment]
Hi @jagi!

I'll likely offer a webpacked build for use by cdns and others but for the npm package it will just be `@std/esm` since build tools like webpack and rollup can handle it.

**Comment by jagi** [comment]
@jdalton right but tools like Meteor.js can't handle `@std/esm` on the client yet. Maybe support for it will appear in Meteor before lodash 5.

What do you mean by "webpacked build"? Another repository where anyone can build a package for the needed target?

**Comment by jdalton** [comment]
> right but tools like Meteor.js can't handle `@std/esm` on the client yet.

`@std/esm` is a fork of [reify](https://github.com/benjamn/reify) so I have high hopes of future compat.

> What do you mean by "webpacked build"? Another repository where anyone can build a package for the needed target?

Not another repo, just another build target *(webpack is a JS bundler)*

**Comment by jagi** [comment]
> @std/esm is a fork of reify so I have high hopes of future compat

Yes, I've heard about that. Actually, there is a discussion about tree shaking and dead code elimination not only for local code but also npm packages. They will be working on it a milestone is Meteor 1.6.1

> Not another repo, just another build target (webpack is a JS bundler). I'd use that as a build target for CDNs.

I know that webpack is a JS bundler but I haven't heard about webpack being a build target for CDNs. Sorry, for taking your time but could you direct me to some article/blogpost talking about that? I haven't found anything by googling.

**Comment by jdalton** [comment]
> I know that webpack is a JS bundler but I haven't heard about webpack being a build target for CDNs. Sorry, for taking your time but could you direct me to some article/blogpost talking about that? I haven't found anything by googling.

It's not something the CDN is doing, it's what I will provide to the CDNs *(through a build script or hook)*.
