### ISSUE TITLE
Using mocha with --watch doesn't pick up src changes

### ISSUE THREAD

**Issue by jzaefferer** [standard-things/esm#138]
Using mocha without a watcher works great, but with a watcher (`mocha -r @std/esm --watch`) I end up with changes to src/ files being ignored (changes to test/ files are picked up).

I could reproduce it with https://github.com/giltayar/playing/tree/master/javascript/esm/std-esm-with-mocha using this in package.json:
```
"test": "mocha -r @std/esm --watch --watch-extensions mjs test/test.mjs"
```
Then run `npm test` and change `question.mjs` to export something else. Test reruns, should fail, but passes instead.

PS: I've looked through open issues, but couldn't find anything related to mocha's file watcher. Since mocha is generally supported, I figured this might be the better place to report. Fixing this would allow me to kick out babel in a bunch of nodejs projects

**Comment by jdalton** [comment]
Thanks @jzaefferer!

I'll totally look into this!

**Comment by jdalton** [comment]
Ok after looking at this its caused because by default we move esm off of the usual `require.cache` (the `test.mjs` file shouldn't be there either but I'll look into that). Enabling `"cjs": true` will store loaded esm modules on `require.cache` which enables Mocha `--watch` to work again. Since I can detect command-line use and testing/dev-mode is implied I may auto enable the module storage adjustment so things "just work".

**Comment by jzaefferer** [comment]
> Enabling "cjs": true will store loaded esm modules on require.cache which enables Mocha --watch to work again

Nice, that helps! Of course a "just works" would be even better.

While testing that, I noticed that an intermediate `SyntaxError: Unexpected token` ended up as "sticky". Even after fixing the issue, the error kept popping up. Could be related to esm and module caching:
```
SyntaxError: Unexpected token
    at Object.<anonymous> (/mocha-esm-demo/test/credentials.js)
    at Object.<anonymous> (/mocha-esm-demo/test/credentials.js)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /mocha-esm-demo/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/mocha-esm-demo/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/mocha-esm-demo/node_modules/mocha/lib/mocha.js:514:10)
    at loadAndRun (/mocha-esm-demo/node_modules/mocha/bin/_mocha:437:22)
    at rerun (/mocha-esm-demo/node_modules/mocha/bin/_mocha:465:5)
    at /mocha-esm-demo/node_modules/mocha/bin/_mocha:473:7
    at StatWatcher.<anonymous> (/mocha-esm-demo/node_modules/mocha/lib/utils.js:193:9)
    at emitTwo (events.js:106:13)
    at StatWatcher.emit (events.js:191:7)
    at StatWatcher._handle.onchange (fs.js:1487:10)
```

**Comment by jdalton** [comment]
Not too sure on that last bit. I have a patch which makes the cache issue consistent (so now the `test.mjs` isn't cached on `require.cache` either *(which results in a zero test run when rerunning tests when `--watch`)*. I have another patch prepped to enable using `require.cache` when in a CLI or preload scenario *(just need to fix some tests around it)*.

**Comment by jdalton** [comment]
After thinking about this a bit more adding special behavior would go against the follow Node ESM rules by default bit. I'll address this with a doc note.

**Comment by jdalton** [comment]
You'll be able to opt-in to just the shared cache by doing:
```json
"cjs": { "cache": true }
```

**Comment by jzaefferer** [comment]
I've switched to `{ cjs: true }` for now, that helps. Let me know if I can help review the doc note.

About that sticky SyntaxError: Should I file a separate issue with a testcase for that?

**Comment by jdalton** [comment]
> About that sticky SyntaxError: Should I file a separate issue with a testcase for that?

Yes, please!

**Comment by jdalton** [comment]
Added tips section to readme https://github.com/standard-things/esm/commit/d4cc752f08ced3d424aa349dee0594cd91c8bdaa.
