### ISSUE TITLE
Set esm option from the command line

### ISSUE THREAD

**Issue by sholladay** [standard-things/esm#139]
As discussed [on Twitter](https://twitter.com/jdalton/status/917076012617179136), this is a feature request for the ability to enable the `esm: 'js'` option from the command line.

Already, you can do this:
```console
$ node -r @std/esm file.mjs
```

My hope is to be able to do something like this:
```console
$ node -r @std/esm/foo file.js
```

`foo` would merely set the `esm` option and nothing else.

That would be nice because it would allow me to do this in my `.bash_profile`, as a user:
```console
alias node='node -r @std/esm/foo'
```
... and from then on I could simply run ...

```
node server.js
```

... and I could use ES modules while being shielded from all of the shenanigans going on surrounding `.mjs` vs `.js`.

**That would be awesome.** 🎉

**Comment by jdalton** [comment]
Hi @sholladay!

I think I'll tackle this with a `STD_ESM_OPTIONS` environment variable similar to [`NODE_OPTIONS`](https://nodejs.org/api/cli.html#cli_node_options_options). You'll be able to specify a path to a .esmrc file or pass a JSON string of options.

**Comment by okwolf** [comment]
This would make DX nice for libraries using `@std/esm` with common options like `esm` and `cjs` to allow cosuming them without adding this to the `package.json` of the project using them:
```json
"@std/esm": {
  "esm": "js",
  "cjs": true
},
```

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/6712cec6126e5b7178527c0d26582a10736fb8ef.

**Comment by sholladay** [comment]
So is this how I make it work?

```sh
alias node='STD_ESM_OPTIONS={ "esm" : true }" node -r @std/esm';
```
```console
$ node foo.js
```

**Comment by jdalton** [comment]
I went with `ESM_OPTIONS` but ya. I'm going to hold off until v0.18.0 to support it though. So not for another couple days.

**Comment by jdalton** [comment]
v0.18.0 is released 🎉

**Comment by sholladay** [comment]
I assume it has to be valid JSON? I just realized that my example above probably won't work due to the lack of shell quoting around the env var. But I can't surround it with quotes easily since the alias and env var itself are using each type of quote and escaping them [is rather unpleasant](https://unix.stackexchange.com/questions/30903/how-to-escape-quotes-in-shell). I'll play around with it and post when I have something that works.

**Comment by jdalton** [comment]
> I assume it has to be valid JSON? 

You know what assuming does. We support [JSON6](https://github.com/d3x0r/json6).

**Comment by jdalton** [comment]
which means you can have unquoted keys.
