### ISSUE TITLE
Syntax Error when using spread operator inside of exports

### ISSUE THREAD

**Issue by djmadeira** [standard-things/esm#14]
On node 8.1.4, when I use a spread operator inside of a default export, I get a `SyntaxError: Unexpected Token` without a useful stacktrace.

[Minimal test case can be found in this gist](https://gist.github.com/djmadeira/255b81aad527d1a6e6a9b18816965d3f).

**Comment by jdalton** [comment]
Ah nice @djmadeira!

[object-rest-spread](https://github.com/tc39/proposal-object-rest-spread) is stage 3 but Node 8 seems to support it. I'll get it added ASAP.

**Comment by jdalton** [comment]
Update: This is [an acorn limitation](https://github.com/ternjs/acorn/issues/388) at the moment. The existing plugin for it is super out-of-date too so unusable. I've kicked around an implementation but hitting errors so won't get it working tonight.

**Comment by KFlash** [comment]
@jdalton I came across this thread via Acorn issue tracker. I became curious about what is the issue with object rest spread? Acorn's plugin doesn't support import and export, and Babylon plugin has some flaws. Esprima have implemented a basic version of it.
Just curious because I'm working on an experimental ECMAScript parser myself and implemtented this long time ago. You can find it here [here](https://github.com/mindoro/mindoro).

**Comment by boneskull** [comment]
I'm also getting some `SyntaxError`s which are pretty opaque.  Here's an example:

```js
// index.js
require('@std/esm');
require('./main.mjs');
```

```js
// main.mjs
import {foo} from './bar'; // error
```

```js
// bar.mjs
export const bar = 'bar';
// (no "foo" export)
```

The result:

```sh
SyntaxError: Module 'bar.mjs' does not provide an export named 'baz'
    at Object.<anonymous> (/path/to/main.mjs)
    at Object.<anonymous> (/path/to/main.mjs)
    at Module._compile (module.js:573:30)
```

This is more problematic when importing from third-party Node modules, where e.g. `index.js` is only mentioned, but not *which* `index.js`!

**Comment by djmadeira** [comment]
Agreed, stack traces output by this lib are virtually useless, I had to resort to binary searching which import was breaking things by moving a known broken file up and down in the import order until the error changed 😀.

**Comment by jdalton** [comment]
@boneskull 
> SyntaxError: Module 'bar.mjs' does not provide an export named 'foo'

Ah cool I can have it produce the whole file path. That's actually more than the built-in ESM error is from v8 at the moment which states 
> SyntaxError: The requested module does not provide an export named 'foo'

@djmadeira

The stack traces should mimic native. You'll not find the internals of the loader in the trace though as that's not helpful for most. The error like

```
/path/to/file.js:4
a = { ... b}
      ^

SyntaxError: Unexpected token
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
```

Is on par with the built-in experience.

**Comment by boneskull** [comment]
> Ah cool I can have it produce the whole file path. 

that'd probably be sufficient.  either:

- knowing which line has the bad import, *or* 
- the complete filepath to the requested module 

would give developers enough information to debug.  doesn't need to be both, though it couldn't hurt!

**Comment by jdalton** [comment]
I'm going to punt this because I feel this is really acorn's issue. Take it up with them over on https://github.com/ternjs/acorn/issues/388. If I write a plugin I just empower them to kick the can down the road instead of doing what's right for the users.

**Comment by jdalton** [comment]
`@std/esm` v0.7.0+ should no longer choke on object rest spread syntax.
