### ISSUE TITLE
Regression from 0.12.4

### ISSUE THREAD

**Issue by Bibliofile** [standard-things/esm#140]
I am using this package to run tests with `nyc` and `ava`, when upgrading from 0.12.4, all of my tests broke.

Here's a repo for replicating this: https://github.com/Bibliofile/nyc-typescript-esm

If you modify package.json to use 0.12.4 everything works, upgrading to 0.12.5 or 0.13.0 breaks.

**Comment by jdalton** [comment]
This https://github.com/standard-things/esm/commit/d1a44013cf113ab2d4a83d6739f81a94719d1ef9 is the blamed commit.

**Comment by jdalton** [comment]
Good news. I found a way to fix it. Bad news is it's interesting. It comes down to hook priority. Before I didn't have a good way of handling priority. Now though I can make `@std/esm` take priority when it's in a preload scenario `node -r` and take a secondary hook when loaded as part of a cli `nyc --require`. This way both work 😸

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/ecb7d48fd15a41db54882e48d3eba05e8cfe022d and https://github.com/standard-things/esm/commit/21fafe633241910ea92edf8edb5ff44bbc11c62a.

**Comment by jdalton** [comment]
@Bibliofile This is such a cool use case I'm going to add a unit test around it. So rad to see it working. I'll update this issue when I release a new version *(probably in a day or so)*.

**Comment by Bibliofile** [comment]
Right on! Thank you for your work on this project! Besides this one hitch, it has been a huge time saver for me when working on projects meant to be used both in browser bundles and in node packages.
