### ISSUE TITLE
Aliased modules

### ISSUE THREAD

**Issue by rektide** [standard-things/esm#141]
Hey. It'd be lovely to be able to alias modules into place in esm. I'd love to be able to `import readfile from "fs"`, for example, and get a modernized, esm compliant module, like [mz's fs](https://github.com/normalize/mz).

**Comment by jdalton** [comment]
Hi @rektide!

That's a bit out of scope for this project. You're probably better off just using the mz `fs` package directly instead of aliasing.

**Comment by jdalton** [comment]
Just pinging back. The `esm` loader now works with things like [module-alias](https://www.npmjs.com/package/module-alias) or [mock-require](https://www.npmjs.com/package/mock-require).

**Comment by outception** [comment]
quit
