### ISSUE TITLE
potential caching bug with babel-transpiler

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#144]
I just noticed a potential bug which might cause issues eventually and might be also hard to find.

follow up and code examples from: https://github.com/standard-things/esm/issues/143

if someone starts:

```
node --require @babel/register --require @std/esm index.js
```

and afterwards (without any code changes):

```
node --require @std/esm index.js
```

everything keeps working. I suppose because of std/esm's caching.

**Comment by jdalton** [comment]
Hi @dnalborczyk!

I don't think their is anything we can do there. Caches cache. You can specify `"cache": false` in your `@std/esm` options to disable the cache.
