### ISSUE TITLE
New shortcut option for cjs+esm:js.

### ISSUE THREAD

**Issue by jdalton** [standard-things/esm#146]
In talking with @TheLarkInn as `@std/esm` use increases it'd be nice to shorten a commonly reached for options f `"cjs":true` and `"esm":"js"` into a single option. I've opened this issue to bikeshed this a bit.

So much like 
```js
"@std/esm": "js"
```
is short for `"@std/esm": { "esm": "js" }`

```js
"@std/esm": "cjs"
```
would be short for `"@std/esm": { "cjs": true, "esm": "js" }`.

**Comment by jdalton** [comment]
In talking with @TheLarkInn as `@std/esm` use increases it'd be nice to shorten a commonly reached for options f `"cjs":true` and `"esm":"js"` into a single option. I've opened this issue to bikeshed this a bit.

So much like 
```js
"@std/esm": "js"
```
is short for "@std/esm": { "esm": "js" }`

```js
"@std/esm": "cjs"
```
would be short for `"@std/esm": { "esm": "js", "cjs": true }`.

**Comment by jdalton** [comment]
Ok, welp since we're pre-1.0 I went ahead and patched it https://github.com/standard-things/esm/commit/984e4fdc36cb12af1324f4372c693e38bdd35485 and https://github.com/standard-things/esm/commit/bf531b69a408111fa6e66ac033a2230394483392.We can revisit if something better comes along.

**Comment by TheLarkInn** [comment]
Nice! Thanks for this!
