### ISSUE TITLE
@std/esm will execute module more than once and won't cache module result

### ISSUE THREAD

**Issue by t83714** [standard-things/esm#148]
As described [here](https://nodejs.org/api/modules.html#modules_caching), modules should be cached after the first time they are loaded.
However, it seems `@std/esm` will not cache the module evaluation result and will run modules for multiple times.
Two test cases can be found from [Archive.zip](https://github.com/standard-things/esm/files/1465901/Archive.zip).
* Directory testRequire: Modules written using require
* Directory testEsm: Modules written using import & export

Run:
```
node testRequire/test1.js
```
You will see (Correct result):
```
run once...
{ x: 9 }
{ x: 9 }
```

Run (using @std/esm):
```
node -r @std/esm testEsm/test1.mjs
```
You will see (incorrect result):
```
run once...
run once...
{ x: 9 }
{ x: 5 }
```

Run (using [node Experimental ECMAScript Modules](https://nodejs.org/api/esm.html)):
```
node --experimental-modules testEsm/test1.mjs
```
You will see (Correct result):
```
(node:20088) ExperimentalWarning: The ESM module loader is experimental.
run once...
{ x: 9 }
{ x: 9 }
```

**Comment by jdalton** [comment]
Hey @t83714!

Thanks for reporting this.
I think you've hit an interesting case because obviously we cache modules 😋

**Comment by jdalton** [comment]
Hmm after running your test file I can't reproduce your issue.
I had to add a package.json to the `testESM` folder and opt-ed in to `@std/esm`.

#### package.json
```json
{
  "name": "testesm",
  "version": "1.0.0",
  "scripts": {
    "foo": "node -r @std/esm test1.mjs"
  },
  "dependencies": {
    "@std/esm": "^0.14.0"
  }
}
```
then
```shell
npm run foo
```
which produced
```
run once...
{ x: 9 }
{ x: 9 }
```

**Comment by t83714** [comment]
Hi @jdalton,

Thanks for your reply. 

My package.json is actually similar to this (And updated test cases can be found from [testesm.zip](https://github.com/standard-things/esm/files/1466096/testesm.zip)):
```
{
  "name": "testesm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test-esm": "node -r @std/esm ./testEsm/test1.mjs",
    "test-require": "node ./testRequire/test1.js",
    "test-esm-node": "node --experimental-modules ./testEsm/test1.mjs"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@std/esm": "^0.12.2"
  },
  "engines": {
    "node": ">=8.4.0"
  },
  "@std/esm": {
    "esm": "all",
    "cjs": true
  }
}
```

I can confirm my issue can only be reproduced in @std/esm version 0.12.2.
And it seems this issue has been in newer version already.
Thanks again for looking into the issue and sorry for the confusion.
