### ISSUE TITLE
CJS shorthand does not enable all CJS options

### ISSUE THREAD

**Issue by tilgovi** [standard-things/esm#149]
The documentation says that `{ @std/esm: "cjs" }` is a shorthand for`{ "@std/esm": { "esm": "js", "cjs": true }}` but these result in different behavior.

Given the following file:

```js
import { lstat } from 'fs';
```

Running `node -r @std/esm` on it results in an error with the shorthand but not with the long version:

> SyntaxError: Module 'fs' does not provide an export named 'lstat'

Perhaps the first if condition at https://github.com/standard-things/esm/blob/master/src/pkg-info.js#L160 should call `createCJS(true)` and set `cjsOptions`?

**Comment by jdalton** [comment]
Ah, thank you!

**Comment by tilgovi** [comment]
Thank you!
