### ISSUE TITLE
Using `package.json` options and node -r  @std/esm issue

### ISSUE THREAD

**Issue by yogeshgadge** [standard-things/esm#160]
Using `package.json` and `node -r  @std/esm` is not working for me when one of the import has `.js` extension.  

Created a repo https://github.com/yogeshgadge/mjs-mixed-loaders to demonstrate the problem.

3 files - 2 with mjs extension and 1 with js extension as shown below

```javascript
// apple.mjs
import {banana} from './banana.mjs'
//run during loading
banana();
export default function apple() {
    return banana();
}
```

```javascript
// banana.mjs
import fs from 'fs';
import {kale} from './kale.js';
export function banana() {
  return kale();
}
export function bananaMonkey() {}
```

```javascript
import isObject from 'lodash-es/isObject'
// kale.js
export function kale() {
  if (isObject({})) {
    console.log('eating kale with some lodash');
    return 'eating kale with some lodash';
  }
}
export function kite() {}
```

## Following does not work using `node -r @std/esm` 

```bash
node -r @std/esm ard/apple.mjs
```

#159  Does not work with `mocha -r` option

```bash
mocha -r @std/esm --recursive src/*.spec.mjs
```

With Error

> ```
> C:\Users\myuser\projs\github\mjs-in-harmony\src\kale.js:1
> import isObject from 'lodash-es/isObject'
> ^
> 
> SyntaxError: 'import' and 'export' may only be used in ES modules
> 
> ```

With

`package.json`

```
  "@std/esm": {
    "cjs": "true"
  }
```
the error is 

> ```
> import isObject from 'lodash-es/isObject'
> ^
> 
> SyntaxError: 'import' and 'export' may only be used in ES modules
>     at C:\Users\myuser\projs\github\mjs-in-harmony\src\banana.mjs
> 
> ```

With

```
"@std/esm": {
    "cjs": {
      "interop": true
    },
    "esm": "js"
  }
```

I get error

> ```
> C:\Users\myuser\projs\github\mjs-in-harmony\node_modules\lodash-es\isObject.js:31
> export default isObject;
> ^^^^^^
> 
> SyntaxError: Unexpected token export
>     at createScript (vm.js:74:10)
>     at Object.runInThisContext (vm.js:116:10)
>     at Module._compile (module.js:537:28)
>     at Object.Module._extensions..js (module.js:584:10)
> 
> ```

**Comment by jdalton** [comment]
Hi @yogeshgadge!

See the [*"Getting Started"*](https://github.com/standard-things/esm#getting-started) section:

> By default, `@std/esm` **only** processes files of packages that opt-in
with a `@std/esm` options object or `@std/esm` as a dependency, dev
dependency, or peer dependency in their package.json. However, you can
enable processing **all** files with specific options by passing an options
object as the second argument or passing `true` to use the options from
your package.json.
>
>```js
>require = require("@std/esm")(module, options)
>
```

Let me know if that bit can be made more clear.

**Comment by jdalton** [comment]
I wonder if I should change the default behavior. I was conservative with opt-ins to avoid potential conflicts but since it's going through the `-r` flag I think I can lighten up the opt-in bits *(maybe even for the non `-r` use too)*.

**Comment by tilgovi** [comment]
I know I ran into something similar when I tried to set the `useESModules` flag on `@babel/plugin-transform-runtime`. I almost opened an issue to ask about whether it would be possible for the user provide an include list, but I stopped short because I like that this package has very few options right now.

It might be nice to make the opt-in more aggressive, especially when the parse goal can be determined by inspection.

**Comment by yogeshgadge** [comment]
@jdalton I think your conservative approach is reasonable since the options in `package.json` should apply to how the package is consumed. 

However I wish there was a way to specify some command line options or something like `.esmrc` which would apply this to the "runtime/parsetime" for all the import/export chain. Then we could consume `lodash-es`.

I am seeing a number of projects producing `esm5` distributions where the code is compiled for ES5 but the imports/exports are ES6 style. `lodash-es` is one of them. Now with a build system like rollup/webpack things are much easier.

But for things like mocha based tests if the `lodash-es` thing worked it would allow me to run my tests without going through any rollup/webpack pipeline. My tests are written against own `esm5` distribution.   

(Hence I am also trying out --experimental-modules and custom --loaders.)

So short answer is Yes it would help those who just want to execute `esm5` libraries out there in their code. (BTW the term `esm5` is borrowed from angular and angular/material2 projects. I am not sure if there is such a standard thing.)

**Comment by jdalton** [comment]
I like the `.esmrc` file idea, I was wondering what to call it, .stdesmrc, so .esmrc is nice! I know it's similar to putting the metadata in a package.json but I dig the separation of config files.

Now that `@std/esm` isolates its module hooks (doesn't touch the Node core hook) when using its in-file API I can be more aggressive and reach into 3rd-party deps. The concern before was that since it was touching the Node core hook it could impact all-Node packages (not good).

I'm sitting on v0.16.0, so after that I'll push 0.17.0 to enable more things, like `lodash-es`, to just work. I'll report back to this issue with updates.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/3d0e5b3f201134090c37a10126f95dd4ef697f76 and https://github.com/standard-things/esm/commit/fb18511fa9fb2a796adc15f75504e838a3f45fc2.

**Comment by yogeshgadge** [comment]
@jdalton This did not work for my scenario.

```
require = require("@std/esm")(module,{"esm":"js"});
module.exports = require("./src/apple.mjs").default;
```

is not equivalent to 

`.esmrc`

```
{"esm": "js"}
```

The programmatic version worked...I was eating kale...got printed.

> ```
> C:\Users\myUser\projs\github\mjs-in-harmony\node_modules\lodash-es\isObject.js:31
> export default isObject;
> ^
> 
> SyntaxError: 'import' and 'export' may only be used in ES modules
>     at C:\Users\myUser\projs\github\mjs-in-harmony\src\kale.js
> npm ERR! Test failed.  See above for more details.
> ```

If you like to play the code is located https://github.com/yogeshgadge/mjs-mixed-loaders.git
```
node -r @std/esm src/apple.mjs

or 
npm run test
```

My ultimate goal is to successfully run 

```
mocha -r @std/esm --recursive src/*.spec.mjs
```

**Comment by jdalton** [comment]
@yogeshgadge 

Correct the programmatic API is not equivalent to .esmrc or package.json options.

**Comment by yogeshgadge** [comment]
This means my `mocha -r @std/esm --recursive src/*.spec.mjs` will not work.

To get around I have to create a programmatic `js` wrapper for each test;-

```
// file apple.spec.js
require = require("@std/esm")(module,true);
module.exports = require("./apple.spec.mjs").default;
```

then use the following which picks up only `*.js` tests
```
mocha --recursive --watch-extensions js,mjs
```

**Comment by jdalton** [comment]
@yogeshgadge With `--watch` you'll cant to use the option `"@std/esm":"cjs"` or long form `{ cjs: true, esm: "js"}`. See the [tips section](https://github.com/standard-things/esm#tips) for more info.
