### ISSUE TITLE
External loaders/provider support.

### ISSUE THREAD

**Issue by bartosz-m** [standard-things/esm#162]
I'm wondering if `@std/esm` have some support for external loaders/providers?
I'm working on node.js esm loader for livescript. It transpiles livescript -> es6 on the fly but requires recent node.js with --experimental-modules flag. It would be nice if I could make it work also with `@std/esm`

**Comment by jdalton** [comment]
Hi @bartosz-m! 

At the moment it doesn't. You can review the list of supported features [here](https://github.com/standard-things/esm#standard-features).

Initially I thought about supporting `--loader @std/esm` but now that usage is shaking out as `-r @std/esm` as an alternative to `--experimental-modules` I'll look into adding support for the loader hooks. For now, things that work with CJS like how [`@babel/register`](https://www.npmjs.com/package/@babel/register) handles things will work for `@std/esm` *(so the existing ecosystem)*. Is there an equivalent for livescript?
