### ISSUE TITLE
Coverage with nyc interop issue?

### ISSUE THREAD

**Issue by okwolf** [standard-things/esm#165]
I don't believe this issue is related to #28.

I've been playing around with getting code coverage using [`nyc`](https://github.com/istanbuljs/nyc) to work on some projects using `@std/esm` and I've been seeing some weird behavior. My coverage for my CJS using `require()` and `module.exports` works fine before introducing `@std/esm`. So far I get absolutely zero coverage for ESM code called using `@std/esm`. Even more curious, if I move my CJS `require`s after `require = require("@std/esm")(module)` then it appears I've also lost coverage for CJS code called after the `@std/esm require`.

I've thrown together a [small repo](https://github.com/okwolf/nyc-esm-bug) that demos this issue. So far I've played around with `nyc --require @std/esm`/`node -r @std/esm` and related arguments and all I get is:

```console
ReferenceError: require is not defined
    at node_modules/nyc/node_modules/foreground-child/index.js
    at Object.<anonymous> (node_modules/nyc/node_modules/foreground-child/index.js)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
```

or

```console
Transformation error for src/index.js ; return original code exports is not defined
```

Any ideas what magic parameters/incantation will make this work? 🔮

**Comment by dnalborczyk** [comment]
not quite sure how to load it with the code options, but I think the following does what you want:

```
"scripts": {
    "test": "nyc --require @std/esm node src"
```

in addition you could change your index.js to ES6 modules ...
```
import a from './cjs/main';
import b from './esm/main';

a();
b();
```

not sure how nyc calculates code coverage:
```
> nyc --require @std/esm node src

2 + 2 = 4
3 + 5 = 8
-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
All files  |     93.1 |      100 |    85.71 |    92.86 |                |
 src       |      100 |      100 |      100 |      100 |                |
  index.js |      100 |      100 |      100 |      100 |                |
 src/cjs   |       90 |      100 |       80 |    83.33 |                |
  index.js |       80 |      100 |    66.67 |    66.67 |              5 |
  main.js  |      100 |      100 |      100 |      100 |                |
 src/esm   |    93.33 |      100 |     87.5 |      100 |                |
  index.js |    88.89 |      100 |       80 |      100 |                |
  main.js  |      100 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
```


but if you change your esm/index.js e.g. to:
```
export const add = (x, y) => x + y;
export const multiply = (x, y) => {
  return x * y;
};
```
coverage changes to:
```
> nyc --require @std/esm node src

2 + 2 = 4
3 + 5 = 8
-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
All files  |    93.94 |      100 |     87.5 |    86.67 |                |
 src       |      100 |      100 |      100 |      100 |                |
  index.js |      100 |      100 |      100 |      100 |                |
 src/cjs   |       90 |      100 |       80 |    83.33 |                |
  index.js |       80 |      100 |    66.67 |    66.67 |              5 |
  main.js  |      100 |      100 |      100 |      100 |                |
 src/esm   |    93.33 |      100 |     87.5 |    83.33 |                |
  index.js |    88.89 |      100 |       80 |       75 |              4 |
  main.js  |      100 |      100 |      100 |      100 |                |
-----------|----------|----------|----------|----------|----------------|
```

**Comment by okwolf** [comment]
@dnalborczyk thanks for the suggestions: `nyc` does indeed provide coverage for `@std/esm` code using `nyc --require @std/esm node src` if I remove `require = require("@std/esm")(module)` from the source.

However, my use case is for a library that will be run with `npm` or `npx` instead of directly with `node`. Using this:

```json
"scripts": {
    "start": "node -r @std/esm src",
    "test": "nyc --require @std/esm npm start"
  }
```

Works fine for `npm start` still but `npm test` then fails with this error:

```console
> nyc-esm-bug@0.0.1 test 
> nyc --require @std/esm npm start


> nyc-esm-bug@0.0.1 start 
> node -r @std/esm src

/src/index.js:1
(function (exports, require, module, __filename, __dirname) { var cov_1ck250vtpw=function(){var path='/src/index.js',hash='9bfc4671fc8bf3b1edbda27ccb0fd4075dcc9380',global=new Function('return this')(),gcv='__coverage__',coverageData={path:'/src/index.js',statementMap:{'0':{start:{line:4,column:0},end:{line:4,column:6}},'1':{start:{line:5,column:0},end:{line:5,column:6}}},fnMap:{},branchMap:{},s:{'0':0,'1':0},f:{},b:{},_coverageSchema:'332fd63041d2c1bcb487cc26dd0d5f7d97098a6c'},coverage=global[gcv]||(global[gcv]={});if(coverage[path]&&coverage[path].hash===hash){return coverage[path];}coverageData.hash=hash;return coverage[path]=coverageData;}();import cjs from'./cjs/main';import esm from'./esm/main';cov_1ck250vtpw.s[0]++;cjs();cov_1ck250vtpw.s[1]++;esm();


SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at runInThisContext (vm.js:139:10)
    at Object.vm.runInThisContext (/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:142:16)
    at Module._compile (module.js:599:28)
    at Module.replacementCompile (/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module.replacementCompile (/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at /node_modules/nyc/node_modules/append-transform/index.js:62:4
    at /node_modules/nyc/node_modules/append-transform/index.js:62:4
    at Object.<anonymous> (/node_modules/nyc/node_modules/append-transform/index.js:62:4)
```

I've updated my [bug repo](https://github.com/okwolf/nyc-esm-bug) to show this error in case anyone wants to play around with finding a config that will work.

Thanks 🙏

**Comment by dnalborczyk** [comment]
unfortunately I don't know much about the inner workings of _std/esm_ or _nyc_.

I'm kind of guessing that running _nyc_ is similar to running _babel-node_, which I believe is more or less a wrapper around babel/register, but it's just a guess. I'm wondering if nyc should or could be working with a _register_ process as well, and hook into the module loading process for code instrumentation, then one could set the resolution order of any modules themselves.

not sure if this is related, but I found this bug report on nyc: https://github.com/istanbuljs/nyc/issues/628, and it seems when you downgrade to v0.10.1.2 your example works more or less to a certain degree:

```
"scripts": {
    "start": "node src",
    "test": "nyc --require @std/esm npm start"
}
```

though I'm guessing you want to run _npm start_ and _npm test_ independently of each other.

**Comment by okwolf** [comment]
@dnalborczyk thanks for the further digging! You are correct that coverage _mostly_ works (source mapping is a bit funny) with older `nyc` version 10.1.2, but only if I break the `npm start` script by removing `-r @std/esm`.

Why can't all these tools just get along? 😕

**Comment by jdalton** [comment]
The two modes of `@std/esm`, the programatic API and the `node -r` flag, do not mix. They are intended for separate use cases.

For `nyc`, see our [tips section](https://github.com/standard-things/esm#tips), you'll want to use the `nyc `--require` option. There you'd run code that uses the `main.mjs` *(main esm entry)* and for your package consumers the package.json would point to index.js which has the programatic API to export `main.mjs` *(main esm entry)*.

**Comment by okwolf** [comment]
> @jdalton The two modes of `@std/esm`, the programatic API and the `node -r` flag, do not mix. They are intended for separate use cases.

Based on my testing so far, it appears that not only do the programmatic and require modes not mix, but multiple uses of the require mode also don't mix. If that's the case, my only option is the programatic API.

Does the API offer a way to know if `@std/esm` is already loaded, so I can avoid this problem automatically without getting the user involved? Otherwise, it seems my only option is to offer a command line flag for disabling my internal copy of`@std/esm` when you are using a wrapper like `nyc` that needs to have `@std/esm` already loaded before executing you in order to work.

**Comment by jdalton** [comment]
@okwolf 

Ya, after thinking on it more they both should work well together since you could have a dependency that uses the programatic approach. Could you set your repro repo to using the `--require` flag from `nyc` and the programatic API for your package and I'll dig into it to ensure it works.

**Comment by okwolf** [comment]
@jdalton thanks for looking into this! I've pushed your requested changes to: https://github.com/okwolf/nyc-esm-bug

**Comment by okwolf** [comment]
So upgrading to >=0.19.0 seems to be broken with nyc again:

```console
okwolf:nyc-esm-bug$ npm test
> nyc-esm-bug@0.0.1 test nyc-esm-bug
> nyc --require @std/esm node src

Transformation error for nyc-esm-bug/src/index.js ; return original code
istanbul.createInstrumenter is not a function
Transformation error for nyc-esm-bug/src/cjs/main.js ; return original code
istanbul.createInstrumenter is not a function
Transformation error for nyc-esm-bug/src/cjs/index.js ; return original code
istanbul.createInstrumenter is not a function
2 + 2 = 4
3 + 5 = 8
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

I updated the repro to a fairly minimal failing case: https://github.com/okwolf/nyc-esm-bug

There's also a [separate branch](https://github.com/okwolf/nyc-esm-bug/tree/works-with-older-esm) showing it still working fine for 0.18.0.

**Comment by jdalton** [comment]
Thanks @okwolf!

It looks like our scenario test missed this. I'll add another!

**Comment by jdalton** [comment]
Thanks for your patience with this stuff too. I've held off going 1.0 because I know things can get a bit complex. The good news is the hurdles are almost over and smooth sailing is close.

**Comment by okwolf** [comment]
And thank you @jdalton for being patient with all my bug reports! 🐜 

Pretty soon I should start learning how this stuff works so I can contribute in a more meaningful way...
