### ISSUE TITLE
Coverage with Istanbul

### ISSUE THREAD

**Issue by JesterXL** [standard-things/esm#169]
I'm successfully running unit tests:

```shell
"test-nocoverage": "node node_modules/mocha/bin/mocha -r @std/esm './test/unit/**/*.test.mjs'",
```

But coverage isn't working:

```shell
"test": "node node_modules/istanbul/lib/cli.js cover _mocha -- -r @std/esm ./test/unit/**/*.test.mjs --hook-run-in-context --statement 90 --branch 90",
```

<img width="501" alt="screen shot 2017-11-30 at 2 13 12 pm" src="https://user-images.githubusercontent.com/424737/33450056-a1ed8986-d5d8-11e7-8f75-36b8e96aec40.png">

I read a few of the closed `nyc` threads, but struggling to follow where Istanbul is breaking here.

**Comment by jdalton** [comment]
Hi @JesterXL!

Can you create a simple repro repo for me to look at?
