### ISSUE TITLE
import() is available in Script goal

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#18]
As per the grammar in  https://tc39.github.io/proposal-dynamic-import/#prod-ImportCall . `import()` is available in all contexts (Script and Module alike). The following throws an error where it should not.

```js
// entry.js
require('@std/esm');
require('./a');
```

```js
// a.js
import('./b');
```

```js
// b.mjs
// this space left blank
```

```sh
$ node entry.js
/Users/bfarias/Documents/tmp/app/a.js:1
(function (exports, require, module, __filename, __dirname) { import('./b');
```

**Comment by jdalton** [comment]
Thanks @bmeck!

Yep, we have some tests for this. I'll look into what we missed.
