### ISSUE TITLE
Named exports with export default is not working

### ISSUE THREAD

**Issue by eduardojmatos** [standard-things/esm#182]
Hi folks! First, thanks for this awesome project!

I'm using @std/esm on my app and I have an issue to report.

The sample of the issue is very simple:

```JavaScript
// dependency.js
export default const a = 1;
export const b = 2;
```

```JavaScript
// main file
import { a, b } from './dependency';
```

This causes this error: 
```Bash
SyntaxError: Module '/Users/me/project-path/dependency.js' does not provide an export named 'a'`
```

To avoid this I'm removing the `default` option from module:

```
// dependency.js
export const a = 1;
export const b = 2;
```

And on this way, all is fine. Do am I losting some thing or this is really an issue?

**Comment by jdalton** [comment]
Hi @eduardojmatos,

Can you create a small repro repo?

**Comment by eduardojmatos** [comment]
@jdalton yes, for sure!

https://github.com/eduardojmatos/esm-sample/tree/master

**Comment by tilgovi** [comment]
I think this is expected behavior of ES modules. `export default` does not create a named export.

Use this to get what you want:

``` js
export const a = 1;
export const b = 2;
export default a;
```

**Comment by jdalton** [comment]
Yep, @tilgovi is right. You're getting the error because you're not exporting the `a` binding as `a`.

If I renamed the files to `.mjs` and ran it with the `--experimental-modules` flag I get the same error:
```
(node:80495) ExperimentalWarning: The ESM module loader is experimental.
SyntaxError: The requested module does not provide an export named 'a'
    at ModuleJob._instantiate (internal/loader/ModuleJob.js:84:17)
```
However if the code is changed to @tilgovi's suggestion then it works.

**Comment by eduardojmatos** [comment]
Thanks @tilgovi, you're totally right! 

@jdalton thanks for support!

**Comment by fdaciuk** [comment]
Just to complement: you may name _default exported_ as `a` when you are importing:

```js
import { default as a, b } from './dependency'
```

Or:

```js
import a, { b } from './dependency'
```

=)

**Comment by eduardojmatos** [comment]
@fdaciuk yes, but in this case, the problem was the default export. When I changed the way that I was exporting, even this sample that you explained, did works =D
