### ISSUE TITLE
Dynamic import in required files

### ISSUE THREAD

**Issue by jkrems** [standard-things/esm#184]
I'm having a lot of fun (and success) using `@std/esm` to replicate the behavior on node master. 🙌 But I ran into one issue. Given the following files:

```js
// a.js
require('b.js');
```

```js
// b.js - Object.assign to force same output between node master and @std/esm
import('./c.mjs').then(ns => console.log(Object.assign({}, ns)));
```

```js
// c.mjs - this file is just empty
```

The following command works:

```
node -r @std/esm b.js
```

But when trying to run `a.js` instead, it fails:

```
> node -r @std/esm a.js
/path/to/b.js:1
import('./c.mjs').then(ns => console.log(Object.assign({}, ns)));
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:48:7)
    at createScript (vm.js:92:10)
    at Object.runInThisContext (vm.js:151:10)
    at Module._compile (module.js:628:28)
    at Object.Module._extensions..js (module.js:671:10)
```

This is in a project that has `"@std/esm": "^0.18.0",` in its package.json but no further configuration. I can replicate this behavior on latest node 6/8 and nightly.

**Comment by jdalton** [comment]
Hi @jkrems!

Thanks for kicking the tires on the loader. Could you create a simple repro repo for me to look at?

**Comment by jkrems** [comment]
Sure thing! Will look into that when I get back to a computer. :)

**Comment by jkrems** [comment]
Quick test repo: https://gist.github.com/jkrems/ad42a0e2e8a156670239286b5fab0807

Will also try to turn this into a failing test around here unless you are faster.

**Comment by jkrems** [comment]
Added a comment to the gist documenting the expected output when using node nightly.

**Comment by jkrems** [comment]
Example failing test: https://github.com/standard-things/esm/compare/master...jkrems:dynamic-import-indirect?expand=1

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/9d5bab21c1ca15769a7a8d5ace0f64ce82d265ed. Will follow up with a proper test.

**Comment by jkrems** [comment]
Verified on both the gist and the a project using latest master - works! Thanks for the super fast fix! :)

**Comment by jdalton** [comment]
Thanks! I have some unit test debt to pay and I'd like to fix the other open issue before cutting a release. So I'm guessing another 2 days or so.

**Comment by jdalton** [comment]
`@std/esm` [v0.19.0](https://github.com/standard-things/esm/releases/tag/0.19.0) is released :tada:
