### ISSUE TITLE
ESM_OPTIONS usage

### ISSUE THREAD

**Issue by okwolf** [standard-things/esm#188]
I'm trying to use the new `ESM_OPTIONS` available in 0.18.0 and having some issues. I don't see any working usage examples in the [README](https://github.com/standard-things/esm/tree/0aa5c49308fb22d6bda08c177c30823bf33ee674#unlockables), [release notes](https://github.com/standard-things/esm/releases/tag/0.18.0), or #139. I'm guessing based on the [unit tests](https://github.com/standard-things/esm/blob/0aa5c49308fb22d6bda08c177c30823bf33ee674/test/main-hook-tests.mjs#L67) for this feature that `ESM_OPTIONS=cjs` should be supported, but that's not the behavior I'm seeing. Using `"@std/esm": "cjs"` in `package.json` does work, however.

I made a [repo](https://github.com/okwolf/esm-options) that shows the issue, including a [branch](https://github.com/okwolf/esm-options/tree/works-from-package-json) demonstrating the `package.json` property alternative working: https://github.com/okwolf/esm-options.

I look forward to having my obvious oversight on this matter pointed out. I would also encourage including an example of how to properly use this feature for the common `cjs` use case.

**Comment by jdalton** [comment]
Np @okwolf! The use of completely unquoted values like `ESM_OPTIONS=cjs` will be supported in the next release. At moment only unquoted object keys are allowed.

**Comment by okwolf** [comment]
Thanks for the reply @jdalton. So does that mean that any of the following should work?

```console
ESM_OPTIONS='cjs'
ESM_OPTIONS={cjs:true}
ESM_OPTIONS={esm:'js'}
ESM_OPTIONS={esm:"js"}
ESM_OPTIONS={esm:'js',cjs:true}
ESM_OPTIONS={esm:"js",cjs:true}
```

I've tested each and none of them seem to work either 🤔

**Comment by jdalton** [comment]
Hmm okay!

It seems to be giving the default config priority over the environment var. Looking into it.

**Comment by jdalton** [comment]
\*Boop\* https://github.com/standard-things/esm/commit/f4a645251975a727c7c923164f7df39df2a8746d. I'll follow up with another test.

**Comment by okwolf** [comment]
@jdalton thanks for looking into this! I've tested with the latest build from master and it works 👍 

What's the timeline looking like for a new release? Are there any other bugs/features being worked on?

**Comment by jdalton** [comment]
`@std/esm` [v0.19.0](https://github.com/standard-things/esm/releases/tag/0.19.0) is released :tada:
