### ISSUE TITLE
Disable Live Binding?

### ISSUE THREAD

**Issue by EtherTyper** [standard-things/esm#19]
I appreciate that this project aims to be standards-compliant, but I think the option to disable live binding between CJS and compiled ESM like [Node.js will natively](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#491-es-will-not-honor-reassigning-moduleexports-after-evaluation) would be useful.

Thanks,
Eli

**Comment by benjamn** [comment]
That's not what Node is planning to do, according to that document. Reassigning properties of the `exports` object will still be reflected by live bindings. It's just that setting `module.exports` to something completely different will not be honored after a certain time.

Fun fact: if you stick to `const` exports (e.g. `export const name = ...`) then this library (like [Reify](https://github.com/benjamn/reify)) is smart enough to throw away the callback functions used for live bindings after they've been called once.

**Comment by EtherTyper** [comment]
@benjamn That's really cool! Thanks for telling me!
