### ISSUE TITLE
AVA requiring @std/esm does not work

### ISSUE THREAD

**Issue by billyjanitsch** [standard-things/esm#197]
[Here](https://github.com/billyjanitsch/ava-esm) is a minimal test repo using AVA and `@std/esm`. To reproduce the issue, run `npm install` then `npm test`.

`lib/` contains an ESM build. `index.js` activates `@std/esm` and re-exports the default export of `lib/`. In package.json, `module` points to `lib/`, and `main` points to `index.js` with `"@std/esm": "cjs"` for CJS compat. As I understand it, this is a standard setup.

AVA is configured to require `@std/esm`, and to inherit the Babel config in `.babelrc` to transpile its test files (which would be necessary, for instance, if the test files used JSX). This config does _not_ transpile ESM -> CJS. However, `npm test` fails:

```
/Users/billy/work/ava-esm/test.js:1
(function (exports, require, module, __filename, __dirname) { import test from 'ava';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at extensions.(anonymous function) (/Users/billy/work/ava-esm/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/billy/work/ava-esm/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
```

This suggests that `@std/esm` is not working correctly on the test file.

If you remove [the line](https://github.com/billyjanitsch/ava-esm/blob/master/package.json#L9) which tells AVA to use `.babelrc`, `npm test` passes because AVA falls back to its default Babel config which transpiles ESM -> CJS.

**Comment by jdalton** [comment]
Thanks @billyjanitsch!

Our scenario test missed the `"inherit"` option. It looks like [this bit](https://github.com/avajs/ava/blob/965cbc65d82b12019cdf6a3257b3198dd4181b79/lib/process-adapter.js#L80-L82) is the issue:
```js
const precompiled = opts.precompiled[filename];

if (precompiled) {
  sourceMapCache.set(filename, path.join(cacheDir, `${precompiled}.js.map`));
  return fs.readFileSync(path.join(cacheDir, `${precompiled}.js`), 'utf8');
}
```
If `precompiled` was `null` then it would allow `@std/esm` to be used... but as it gets trapped by the precompiled block. \cc @motss.

**Comment by jdalton** [comment]
It doesn't look like there is a way to [disable this precompilation](https://github.com/avajs/ava/issues/709) of ava at the moment.

**Comment by jdalton** [comment]
Removed ava from the [tips section](https://github.com/standard-things/esm/commit/8726a3c2087eb7f23f6d12aafa3d82a5bdc1eb1f) for now.

**Comment by billyjanitsch** [comment]
That's too bad. Thanks for looking into it, @jdalton.

**Comment by jdalton** [comment]
Ah, it's not that bad. I mean packages using `@std/esm` still work with ava. It's just ava handles ESM on their own at the moment. I think they've eventually get more configurable but as it stands ESM still works with ava it's all good.

**Comment by jamestalmage** [comment]
See https://github.com/avajs/ava/pull/1618

**Comment by jdalton** [comment]
Thank you @jamestalmage!
