### ISSUE TITLE
top-level await not working

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#199]
top-level await seems to be not working. not sure if that is a regression (never tried it, until now).

node 9.3.0, std/esm v0.18.0

repro steps:

esmrc:
```
{
  "await": true
}
```

index.js:
```
await 1;
```

cli:
```
node --require @std/esm index.js
```

error:
```
await 1;
^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
```

**Comment by jdalton** [comment]
It looks like I'm only enabling top-level await for ESM. So if you're using the defaults you'd want to make that an index.mjs. I'll expand it to supporting both CJS and ESM though.

**Comment by dnalborczyk** [comment]
@jdalton I had a suspicion, since the docs are mentioning 
> A boolean to support top-level await in the main ES module.

but I thought, if it's not meant to work in CJS, I would have suggested to change the wording to emphasize that the "await" flag _only_ works in ES modules.

Anyhow, I tried the above with ESM (default):

index.**mjs**
```
await 1;
```
esmrc:
```
{
  "await": true
}
```

cli:
```
node --require @std/esm index.mjs
```

... as well as:

index.**js**
```
await 1;
```

```
{
  "esm": "js",
  "await": true
}
```

cli:
```
node --require @std/esm index.js
```

and both are still failing. :/

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/5743e3156eb006f386b102b8ac74cececb41d24e.

**Comment by dnalborczyk** [comment]
just tried top-level await with ESM (default _mjs_ and explicit _js_) and CJS mode on lastest [master](https://github.com/standard-things/esm/commit/28a13ea59e22cdd48ea10613bdb82ed5acaf4bef) - and needless to say, both work now!  :smiley:

Thanks for your amazing work @jdalton !!

**Comment by jdalton** [comment]
`@std/esm` [v0.19.0](https://github.com/standard-things/esm/releases/tag/0.19.0) is released :tada:
