### ISSUE TITLE
what's the performance overhead like?

### ISSUE THREAD

**Issue by capaj** [standard-things/esm#2]
People can use ES6 modules for quite some time with transpilation(babel). How is this different from running a babel with only a `transform-es2015-modules-commonjs` plugin? Is it okay to use in production? How much does it impact the startup time/memory? Because babel eats memory like crazy even with that single transform.

**Comment by jdalton** [comment]
Hi @capaj!

The `@std/esm` loader is a bit different than Babel. The `@std/esm` loader is intended for runtime use, so no build step or pre-publish step is required of the user. When it is released it will be fine for production use. In fact Lodash, the most directly depended upon package in npm, will itself depend upon `@std/esm`.  The esm loader is intended to be quick and impact loading as minimally as possible. There is a 1 time transform cost per ESM module, after that the result is cached and loading is on par with CJS. I'm working to reduce the 1 time transform cost too. We can do this by avoiding a full parse and instead performing only a top-level parse in many situations.

The loader itself when published will be a small < 40kb, zero dependency package:

<img width="114" src="https://cloud.githubusercontent.com/assets/4303/26536528/840cdee8-43fd-11e7-8c4b-5cf8d68da53a.png">

**Comment by andywer** [comment]
Might be worth adding to the README 🙂

**Comment by akowald** [comment]
I noticed around 2x memory usage and startup time in my express/ws app with the default settings. Since I only esm for a single import this is hard to swallow. Is there anything you can recommend trying or is this just par for the course?

**Comment by jdalton** [comment]
Hi @akowald!

Over the last year performance has slipped a bit. I'm in the process of reducing startup back to microseconds from native. As per memory that could be because we use V8 code cache APIs to improve startup and offset some costs (so probably a memory/perf tradeoff). That said, I haven't tracked memory usage so a nice benchmark would be great (as I could dig in and get answers).

**Comment by akowald** [comment]
That's encouraging to hear! Of those two, startup time is probably more important.

In my project that one import doesn't have any dependencies. I tried putting `require = require('esm')(module)` at the top of the file but I get this `SyntaxError: Unexpected token import`. So I was forced to go back to -r esm or putting that line at the top of the entry/index js file were it works just fine. I'm probably missing something.

As for a benchmark, anything you come up will be better than what I tried. The following demonstrates the behavior I ran across. I created a simple project with express-generator: `express --view=pug test`. Then I modified [www](https://github.com/standard-things/esm/files/2229047/www.txt) to spit out some basic information:
```
~/projects/test$ DEBUG=test:* node ./bin/www
  test:server Time to end of www 143 +0ms
  test:server Listening on port 3000 +3ms
  test:server Time to onListening() 146 +0ms
  test:server rss 35.86 MB +1ms
  test:server heapTotal 17.33 MB +0ms
  test:server heapUsed 8.49 MB +0ms
  test:server external 0.07 MB +0ms
~/projects/test$ DEBUG=test:* node -r esm ./bin/www
  test:server Time to end of www 430 +0ms
  test:server Listening on port 3000 +4ms
  test:server Time to onListening() 434 +0ms
  test:server rss 48.5 MB +0ms
  test:server heapTotal 31.33 MB +0ms
  test:server heapUsed 18.19 MB +0ms
  test:server external 0.29 MB +1ms
```
Hope that helps.. Oh I forgot to say thanks for esm, it works like magic!

**Comment by dnalborczyk** [comment]
> I tried putting require = require('esm')(module) at the top of the file that imports it but I get this SyntaxError: Unexpected token import

@akowald do you have a repro for this?

**Comment by jdalton** [comment]
I'm guessing the created require call is in the same file as the ES import syntax (which is incorrect usage). The created require function should be used to load the ESM file.

**Comment by akowald** [comment]
You are correct, was just about to report back. It works now but at little benefit just due to other dependencies in the project. I could start making proxy dependencies but why bother at that point. Thanks again for the help.

**Comment by kenokabe** [comment]
Hi @jdalton , this is out of topic, but since I don't use Twitter, excuse me to ask here. I'm a guy in electron/node issue, and you let me know this brilliant project.
I would like to introduce esm concept/background in my blog in Japanese. Is it ok to translate
https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b
https://medium.com/web-on-the-edge/tomorrows-es-modules-today-c53d29ac448c
Thanks!

**Comment by jdalton** [comment]
@kenokabe That would be great! The newest (most up-to-date) post is the [second one](https://medium.com/web-on-the-edge/tomorrows-es-modules-today-c53d29ac448c). During translation feel free to ping me [](john.david.dalton@gmail.com) with questions or to clarify anything. Let me know when it's published and I'll link to it from our docs too.

**Comment by kenokabe** [comment]
@jdalton That is very kind of you, and yes, I will let you know things. thanks!! :)

**Comment by jdalton** [comment]
@kenokabe 
> Reading and considering the situation described above, I have a feeling with a hope you currently try to merge `esm` to node and NPM, am I wrong?

I don' think that's likely. However, you can manually [compile `esm` into Node](https://github.com/standard-things/esm/wiki/Compile-Node).

> Relating to the question-1, The article was written about 6 months ago, and I wonder what the most updated situation is.

There hasn't been a lot of tangible progress on the official Node front. That said, I'm continuing to improve `esm` in areas like specification compliance, migration paths, performance, and real world usage scenarios.

> I couldn't get the idea looking a the gif demo, is this related to npm init esm?

That demo gif was using `npx` which is a way to do the same thing _(before the `npm init esm` feature in `npm` was released)_.

**Comment by jdalton** [comment]
Oh that demo gif was showcasing the `npm init <create-package>` feature. See [this post](https://blog.npmjs.org/post/174001864165/v610-next0) for more.

**Comment by kenokabe** [comment]
@jdalton I understood:) Thank you for the prompt response!

**Comment by kenokabe** [comment]
@jdalton  It took more time than I'd expected, but finally I've published the translation of your article: [Tomorrow’s ES Modules Today!](https://medium.com/web-on-the-edge/tomorrows-es-modules-today-c53d29ac448c). 

---

#### Translation to Japanese
http://kenokabetech.blogspot.com/2018/09/es-modulesesm-jdalton.html

---

I did my best not to lose the context of your philosophy. 

Although I tried to follow the original format as much as possible, the Twitter quote embedded script does not work well in the above link, however,  for some reason, when the page is opened from the top page, http://kenokabetech.blogspot.com , the embedded script works. I tried to debug and fix it, but it appears to be due to Blogger issue.

 Thank you for the brilliant article, permission to translate and  your cooperation. If you find anything, please give me some feedbacks.

Thanks!

**Comment by EthanDM** [comment]
Is anyone else seeing significantly higher memory usage? I've got a medium sized Express app and it went from 100 MB to 250 MB.

**Comment by jdalton** [comment]
Hi @EthanDM!

There has been a [mention above](https://github.com/standard-things/esm/issues/2#issuecomment-407552023), with Express as well. While I have some ideas, I have nothing concretely actionable. If you have more details or insight _(please post to a new issue)_ it would help me narrow things down and tweak things on our end or report a bug on V8's end.

**Comment by EthanDM** [comment]
@jdalton Just figured out what was causing a large part of the problem - it's related to the cluster module. Partly user error, but the issue wasn't as severe without ESM. I moved the cluster forking outside of my server JS file and it reduced my memory from 250 MB to 130 MB. It's still up from 70 MB, but that's something I'm ok with.

It looks like this:

```
if (cluster.isMaster) {
  // fork clusters
} else {
  require = require('esm')(module)
  module.exports = require('./server')
}
```
