### ISSUE TITLE
comments with dynamic import and cache enabled causing exception

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#203]
_seems like I need to change the title, as dynamic import itself doesn't seem to be broken._

node: v9.3.0
std/esm: master

just noticed this on [master](https://github.com/standard-things/esm/commits/master) while playing with https://github.com/standard-things/esm/issues/199. v0.18 doesn't seem to be effected. I thought it would be fair to write it up now, instead of waiting for the next release.

seems like _comments_ are causing an issue when used with _dynamic imports_ and (default) _cache: true_. static imports don't seem to be effected.

repro steps:

esmrc:
{
  "esm": "js"
}

index.js:
```
// some comment  (same problem with a block comment /* ... */)
import('./some-file');
```

cli:
node --require @std/esm index.js

error:
```
/node_modules/@std/esm/index.js:1
(function(require,module,__shared__){"use strict";const t=module,e=global.Array,i=(global,global,global.Boolean),r=global.Buffer,s=(global,global.Date),n=global.Error,a=(global,global,global.Float64Array),o=(global,global.Infinity),h=(global,global,global,global,global.JSON),c=global.Map,l=(global,global.NaN),u=global.Number,p=global.Object,f=global.Promise,d=global.Proxy,m=global.RangeError,v=(global,global,global.RegExp),g=global.Set,y=(global,global.String),x=global.Symbol,b=global.SyntaxError,w=global.TypeError,_=(global,global,global,global.Uint32Array),k=(global,global.WeakMap),E=(global,global,global,global,global,global,global.process);module.exports=(function(t){function e(r){if(i[r])return i[r].exports;var s=i[r]={i:r,l:!1,exports:{}};return t[r].call(s.exports,s,s.exports,e),s.l=!0,s.exports}var i={};return e.m=t,e.c=i,e.d=function(t,i,r){e.o(t,i)||p.defineProperty(t,i,{configurable:!1,enumerable:!0,get:r})},e.n=funct

SyntaxError: Unexpected token s in JSON at position 1
    at parse (<anonymous>)
    at Function.getMeta (/node_modules/@std/esm/index.js:1:149378)
    at Object.n (/node_modules/@std/esm/index.js:1:156392)
    at Object.s (/node_modules/@std/esm/index.js:1:155874)
    at Object.n [as .js] (/node_modules/@std/esm/index.js:1:151169)
    at Hs.<anonymous> (/node_modules/@std/esm/index.js:1:53951)
    at Hs.<anonymous> (/node_modules/@std/esm/index.js:1:53985)
    at /node_modules/@std/esm/index.js:1:46593
    at gi (/node_modules/@std/esm/index.js:1:46640)
    at qr (/node_modules/@std/esm/index.js:1:53590)
```

the above repro steps fail when being run a **second time (important: without any code changes)**. first time, which creates the cache, works. with _cache: false_ it's always working.

**Comment by jdalton** [comment]
Thanks for the heads up @dnalborczyk!

This is an issue in our master branch meta data parsing. I'm still ironing it out so I expect there's still bugs. I'll add this to a test though, or if you'd like to create a failing test that would rock!

**Comment by dnalborczyk** [comment]
thanks John! I'll give it a try...

**Comment by jdalton** [comment]
Moved to #204.

**Comment by jdalton** [comment]
`@std/esm` [v0.19.0](https://github.com/standard-things/esm/releases/tag/0.19.0) is released :tada:
