### ISSUE TITLE
Not working with nodegit

### ISSUE THREAD

**Issue by raine** [standard-things/esm#206]
Getting this with `nodegit`:

```
% node
> require("@std/esm", { cjs: true, esm: 'js' })
@std/esm enabled
> import * as nodegit from 'nodegit'
Error [ERR_MISSING_MODULE]: Cannot find module ./annotated_commit
```

```
% node
> require('nodegit')
{ StatusFile: [Function: StatusFile],
  Enums:
   { CVAR: { FALSE: 0, TRUE: 1, INT32: 2, STRING: 3 },
     DIRECTION: { FETCH: 0, PUSH: 1 },
     FEATURE: { THREADS: 1, HTTPS: 2, SSH: 4, NSEC: 8 },
     IDXENTRY_EXTENDED_FLAG:
      { IDXENTRY_INTENT_TO_ADD: 8192,
        IDXENTRY_SKIP_WORKTREE: 16384,
        IDXENTRY_EXTENDED2: 32768,
        S: 24576,
        IDXENTRY_UPDATE: 1,
        IDXENTRY_REMOVE: 2,
        IDXENTRY_UPTODATE: 4,
        IDXENTRY_ADDED: 8,
        IDXENTRY_HASHED: 16,
        IDXENTRY_UNHASHED: 32,
        IDXENTRY_WT_REMOVE: 64,
        IDXENTRY_CONFLICTED: 128,
        IDXENTRY_UNPACKED: 256,
        IDXENTRY_NEW_SKIP_WORKTREE: 512 },
     INDXENTRY_FLAG: { IDXENTRY_EXTENDED: 16384, IDXENTRY_VALID: 32768 } },
  DiffLine:
   { [Function: DiffLine]
     getSelfFreeingInstanceCount: [Function: getSelfFreeingInstanceCount],
     getNonSelfFreeingConstructedCount: [Function: getNonSelfFreeingConstructedCount] },
  version: '0.20.3',
  Promise: [Function: Promise] }
```

Not sure if this is a problem with @std/esm or nodegit, but might be something worth looking into.

**Comment by jdalton** [comment]
Hi @raine!

Thanks for reporting. I'll dig in shortly.

**Comment by raine** [comment]
I found this workaround:
```
```

**Comment by jdalton** [comment]
I found the issue:
`nodegit` [is looking for](https://github.com/nodegit/nodegit/blob/708b9dd8b22045dbdd993600828264b12a386d45/generate/templates/templates/nodegit.js#L81-L90) the error code `"MODULE_NOT_FOUND"` and we are providing the [new code](https://github.com/nodejs/node/blob/231b1166cfec42e445613a59286fd7610c0d7481/lib/internal/errors.js#L430) of `"ERR_MISSING_MODULE"`. We should use the old code for CJS.

**Comment by jdalton** [comment]
I'll file an issue with nodegit to support both though as Node will migrate to the new code.

**Comment by raine** [comment]
Thanks @jdalton!

**Comment by jdalton** [comment]
`@std/esm` v0.19.0 is released :tada:

**Comment by raine** [comment]
Hmm, I am getting this on v0.19.7 also. Was it supposed to remedy this?

```
> require("@std/esm", { cjs: true, esm: 'js' })
@std/esm enabled
> import * as nodegit from 'nodegit'
project/node_modules/nodegit/dist/nodegit.js:1
Error [ERR_MISSING_MODULE]: Cannot find module file:///project/annotated_commit
    at importExtension (/project/node_modules/nodegit/dist/nodegit.js:822:5)
    at Object.<anonymous> (/project/node_modules/nodegit/dist/nodegit.js:844:1)
```

**Comment by jdalton** [comment]
It should be, this regression looks like a job for a more thorough scenario test! Thanks for pinging. I'll patch it by today.

**Comment by jdalton** [comment]
@raine I can't seem to repro this with `0.19.7`. Have you tried clearing your `node_modules` folder just in case?

**Comment by raine** [comment]
Looks like it occurs when `package.json` contains `"@std/esm": {"cjs": true, "esm": "js"}`, and works when it doesn't. It's strange because I'm running `require("@std/esm", { cjs: true, esm: 'js' })` where options are the same.

https://github.com/raine/std-esm-nodegit

**Comment by jdalton** [comment]
Ah okay!

**Comment by jdalton** [comment]
Patches https://github.com/standard-things/esm/commit/9fa22a741d1a3361ca2a33578bcddaba1cf9bab3, https://github.com/standard-things/esm/commit/56f1597cb568b32f664c027ffa3e7bff2e8243e0, https://github.com/standard-things/esm/commit/428f2666fabe8cac22f4be24cc6aeeb205601e83

**Comment by jdalton** [comment]
[v0.20.0](https://github.com/standard-things/esm/releases/tag/0.20.0) is released 🎉

**Comment by raine** [comment]
Just tried the latest version and it works. Thanks again, @jdalton.
