### ISSUE TITLE
node gets stuck running files containing '# sourceMappingURL' with --inspect

### ISSUE THREAD

**Issue by Mensu** [standard-things/esm#207]
Hi, I just found that the node process would get stuck when running the following ``index.js`` file with ``node --inspect -r @std/esm index.js``, which may somehow be related to #178 .

```js
console.log('# sourceMappingURL')
console.log('work')

```

- ``@std/esm`` version: 0.18.0
- ``node`` version: 9.2 on macOS, 9.2 on Ubuntu 16.04 and 9.3 on Ubuntu 16.04

- expected behavior: ``node`` exits after printing ``# sourceMappingURL`` and ``work``
- actual behavior: ``node`` gets stuck

I've tried some modifications, which may be helpful for debugging:
- ✅  by removing ``--inspect`` flag: ``node -r @std/esm index.js`` works
- ✅  by turning off source map option of ``@std/esm`` in ``package.json``: ``"sourceMap": false`` works with ``--inspect`` flag
- ✅  by removing the first line <del>console.log('# sourceMappingURL')</del>
- ❌  by commenting the first line: ``// console.log('# sourceMappingURL')`` does not work
- ❌  by adding ``console.log('first line')`` above the first line: node process gets stuck without even printing ``first line``

Originally I found this when importing [``pug``](https://github.com/pugjs/pug), which eventually requires [``clean-css@3.4/lib/imports/inliner``](https://github.com/jakubpawlowicz/clean-css/blob/3.4/lib/imports/inliner.js#L11) containing a regexp ``/\/\*# sourceMappingURL=(\S+) \*\//``

Are there anything I am missing or doing wrong, or is this just a bug? Thanks in advance!

**Comment by jdalton** [comment]
Hi @Mensu!

Can you create a simple repro repo. I haven't been able to reproduce this in the past so without a repro repo this will end up getting closed as `invalid`.

**Comment by Mensu** [comment]
@jdalton Sorry for my late reply. Here's the repro repo: [Mensu/std-esm-repro-issue-207](https://github.com/Mensu/std-esm-repro-issue-207)

I now found that it is NOT related to flag ``--inspect``. It is related to the ``"sourceMap": true`` option. That's why I turned on this option in the repro repo by default.

I also tried requiring from master by the following steps, and node still got stuck...
```
git clone git@github.com:standard-things/esm.git
cd esm
npm i
npm run build:prod
cd ..
node -r ./esm index.js
```

I would be glad if you could check it out again with the repro repo. Thanks in advance!

**Comment by jdalton** [comment]
Thanks @Mensu!

I can repro this.

**Comment by jdalton** [comment]
I fixed the issue locally, will create a unit test and push in a bit.

**Comment by jdalton** [comment]
`@std/esm` v0.19.0 is released :tada:
