### ISSUE TITLE
Integration fails with jest 22 on @std/esm 0.19.0

### ISSUE THREAD

**Issue by JLHwung** [standard-things/esm#208]
@jdalton See you again. 😄

config:
```
"@std/esm": {
    "esm": "all",
    "cjs": true
  }
```

log:
```
SyntaxError: Module '/Users/jh/code/postcss-font-family-system-ui/node_modules/postcss/lib/postcss.js' does not provide an export named 'default'
```
While the error complains about `postcss`, I doubt it should be related to jest modifying module or exports.

The test passes with jest 21 and `@std/esm` 0.17.2

You can check the CI result [here](https://travis-ci.org/JLHwung/postcss-font-family-system-ui/builds/325686736).

**Comment by jdalton** [comment]
Thanks @JLHwung!

Nothing says a `x.x.0` release like `x.x.1` :yum:.
I've identified the issue and am looking at patching it now.

**Comment by jdalton** [comment]
**Update:**

So this turned into a couple bugs! One was how I set the new internal module state. I had set it in a way that recursive loads of a module would stomp on their state. The other was how I handled default package options.

**Comment by JLHwung** [comment]
> Nothing says a x.x.0 release like x.x.1 😋.

Sure, I am pleased to test against every new version and report any related issues.
