### ISSUE TITLE
index.js of package 'redis' evaluated twice with 'vars' option turned on

### ISSUE THREAD

**Issue by Mensu** [standard-things/esm#209]
Hi @jdalton, I just found that when I ran ``node -r @std/esm index.js`` using the following file ``index.js`` with ``"vars": true`` turned on, there would be thrown an error ``TypeError: Cannot redefine property: debugMode``.

```js
import 'redis';
console.log('work');
```

- ``@std/esm`` version: 0.19.0
- ``node`` version: 9.2 on macOS and 9.3 on Ubuntu 16.04
- expected behavior: ``node`` exits after printing ``work``
- actual behavior: ``node`` throws an error ``TypeError: Cannot redefine property: debugMode``

I've tried some modifications, which may be helpful for debugging:
- ✅  by turning off ``vars`` option: ``node -r @std/esm index.js`` works
- ✅  by installing ``@std/esm@0.18.0``: ``node -r @std/esm index.js`` works
- ❌  by using ``require`` instead: ``require('redis')`` does not work
- ❌  by monkey-patching ``Object.defineProperty`` to avoid this problem: then I found that clients created by ``redis.createClient`` would lack methods ``RedisClient#auth`` and ``RedisClient#info``, which are added in [redis/lib/individualCommands.js#203](https://github.com/NodeRedis/node_redis/blob/master/lib/individualCommands.js#L203). I take it that there may be generated several ``RedisClient``s (due to multiple evaluations), and the methods may only be added to one of them (unfortunately, not the one finally exported).

In light of the fact that ``@std/esm@0.18.0`` would not cause this problem, I assume this might be a bug introduced in v0.19.0.

Here's a repro repo: [Mensu/std-esm-repro-issue-209](https://github.com/Mensu/std-esm-repro-issue-209). I would be glad if you could check it out with the repro repo when available. Thanks in advance!

**Comment by jdalton** [comment]
Thanks!

**Comment by jdalton** [comment]
[v0.19.2](https://github.com/standard-things/esm/releases/tag/0.19.2) is released 🎉
