### ISSUE TITLE
Integration fails with jest 22 + node.js 4 on @std/esm 0.19.1

### ISSUE THREAD

**Issue by JLHwung** [standard-things/esm#210]
It's me again. 😁

After upgrading to 0.19.1, node.js 4 complains that
```log
SyntaxError: Unexpected token {
      
      at _load_jsdom (node_modules/jest-environment-jsdom/build/index.js:16:41)
```

node 6, 8, 9 is unaffected. I guess some unbabelified code is executed.

CI Result is [here](https://travis-ci.org/JLHwung/postcss-font-family-system-ui/jobs/325744352).

**Comment by jdalton** [comment]
Hi @JLHwung!

I don't think this is a `@std/esm` issue.
Jest v22 [dropped Node 4 support](https://github.com/facebook/jest/issues/5211#issuecomment-354956892) and JSDOM [now requires](https://github.com/tmpvar/jsdom#jsdom) Node 6 or higher. Let me know if that's not it.

**Comment by JLHwung** [comment]
Hi @jdalton 
While Jest v22 dropped Node 4 support due to jsdom, unofficial node 4 support is added https://github.com/facebook/jest/pull/5134 so we can use jest if test does not depend on JSDOM.

The test passes when specifying
```
testEnvironment: "node"
```
on jest config.

I should have specified `testEnvironment` earlier. Thank you for your great help.
