### ISSUE TITLE
v0.19.1 breaks jest tests with globals

### ISSUE THREAD

**Issue by avaly** [standard-things/esm#212]
Jest has a useful feature to inject [globals](http://facebook.github.io/jest/docs/en/configuration.html#globals-object) into the test environment.

Using `@std/esm@v0.19.1` with jest configured with `globals`, will not make the globals available in the tests.

Minimal code to reproduce:

```diff
diff --git a/test/fixture/scenario/jest/__tests__/test.js b/test/fixture/scenario/jest/__tests__/test.js
index 41a8c26..4731326 100644
--- a/test/fixture/scenario/jest/__tests__/test.js
+++ b/test/fixture/scenario/jest/__tests__/test.js
@@ -3,5 +3,5 @@
 const def = require("../index.js")
 
 test("jest", () => {
-  expect(def).toBe("default")
+  expect(def).toBe("global-foo")
 })
diff --git a/test/fixture/scenario/jest/index.mjs b/test/fixture/scenario/jest/index.mjs
index eb3cab7..35f3d1d 100644
--- a/test/fixture/scenario/jest/index.mjs
+++ b/test/fixture/scenario/jest/index.mjs
@@ -1 +1 @@
-export default "default"
+export default FOO
diff --git a/test/fixture/scenario/jest/jest.config.json b/test/fixture/scenario/jest/jest.config.json
index 873717b..2cca038 100644
--- a/test/fixture/scenario/jest/jest.config.json
+++ b/test/fixture/scenario/jest/jest.config.json
@@ -1,3 +1,6 @@
 {
-  "transform": {}
+   "globals": {
+       "FOO": "global-foo"
+   },
+   "transform": {}
 }
```

Result:

```
  1) scenarios
       should work with jest:
     Error: Command failed: jest --config /home/avaly/dev/forks/esm/test/fixture/scenario/jest/jest.config.json --rootDir /home/avaly/dev/forks/esm/test/fixture/scenario/jest
FAIL fixture/scenario/jest/__tests__/test.js
  ● Test suite failed to run

    FOO is not defined
      ReferenceError: FOO is not defined
          at /home/avaly/dev/forks/esm/test/fixture/scenario/jest/index.mjs:1
          at Object.<anonymous> (file:///home/avaly/dev/forks/esm/test/fixture/scenario/jest/index.mjs:1)
```

**Comment by jdalton** [comment]
Hi @avaly!

Thanks for the heads up. 
So this isn't a regression, right? It hasn't worked and then stopped working?

**Comment by jdalton** [comment]
This is a pretty neat problem to solve but it's doable. As part of Jest's mocks it mocks the compilation of the modules too and uses its own context to compile in. However it's not visible to others than use `vm.runInContext` so I'll have to grab it another way. I dig it!

**Comment by jdalton** [comment]
**Update:**

I can meet this half-way and support `global.FOO` but not `FOO`.

**Comment by avaly** [comment]
@jdalton Thanks for the quick fix!

This should probably be enough with `global.Foo`, but please make this clear in the release notes and the readme docs. Thanks!

**Comment by jdalton** [comment]
[v0.19.2](https://github.com/standard-things/esm/releases/tag/0.19.2) is released 🎉
