### ISSUE TITLE
setting cache in ESM_OPTIONS

### ISSUE THREAD

**Issue by willxy** [standard-things/esm#215]
I'm having some trouble getting `cache` set via `$ESM_OPTIONS`.  

I'm trying:

`#!/usr/bin/env ESM_OPTIONS={esm:"all",cache:false} node -r @std/esm`

and

`#!/usr/bin/env ESM_OPTIONS={esm:"all",cache:"/tmp/cache"} node -r @std/esm`

It seems to be getting the `esm:all` but doesn't seem to be getting the `cache` setting.

It does work if I set it in `package.json`:

```
  "@std/esm": {
    "esm": "all",
    "cache": "/tmp/cache"
  },
```

Anything I'm missing?

**Comment by jdalton** [comment]
Hi @willxy!

While digging into this I uncovered a couple bugs.

Patched by https://github.com/standard-things/esm/commit/1761a4b66579fdd8a61adb161d61849b7076ade7.

**Comment by willxy** [comment]
Awesome.  Works great now.  Thank you!

**Comment by jdalton** [comment]
[v0.19.2](https://github.com/standard-things/esm/releases/tag/0.19.2) is released 🎉
