### ISSUE TITLE
Are there measurable performance gains from the webpack/uglify/gzip build chain?

### ISSUE THREAD

**Issue by jamestalmage** [standard-things/esm#220]
I see a few downsides to deploying packages this way:

1. It is harder for me to dig into my dependency and troubleshoot an issue. With the standard way, I can just edit the contents of unminified `.js` files in my `node_modules` folder.

2. No sharing dependencies with calling code or peer dependencies. If my project also happens to use `acorn`, `magic-string`, etc. I'm going to end up with two copies.

3. Minification can obfuscate malicious code. While I generally trust the authors of `@std/esm`, I would be concerned if shipping minified code became the norm on npm - that's opening the door for someone to [do something nasty](https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5)

---

Are there legit, measured performance gains for what you've done here? If so, is there a write up on those performance gains anywhere?

**Comment by jdalton** [comment]
Hi @jamestalmage!

The `@std/esm` loader is a single, < 80kb, zero dependency, package. It goes out of its way to be a black box. We use portions of acorn and a custom implementation of magic string so much of what we use isn't really sharable. 

We want folks to reach for `@std/esm` so keeping its size small and its dependencies zero is a big step towards that. This is just a tiny package that enables esm nothing more.

**Comment by jamestalmage** [comment]
I get including modified / customized dependencies. Just wondering if there are practical benefits to the webpack / minification / gzip pipeline. I am asking specifically about Node here, the benefit for browser code is clear, but most packages solve that by shipping bundled and minified code in addition to the standard code and using the `browser` field of `package.json`.

**Comment by jdalton** [comment]
>  I am asking specifically about Node here

The `@std/esm` loader will be the only dependency of Lodash v5. The Lodash package impacts ~150,000 other packages.  A single dep install can have several Lodash versions. So for v5 we're reducing its package size from 4mb on disk to ~90kB. That means it will be ~90kB + the 80kB loader. The loader is small so folks that believe in a zero dependency philosophy could make an exception for something that offers a ton of functionality.

**Comment by jdalton** [comment]
Package size is important with things like AWS and Azure Functions or any other size restricted environment.

**Comment by anandthakker** [comment]
@jdalton what's your workflow for debugging `@std/esm` -- do you have a way to step through its original source in a debugger?

**Comment by jdalton** [comment]
Hi @anandthakker!

Are you running into an issue?

**Comment by anandthakker** [comment]
@jdalton I was trying to chase down more details about a "temporal dead zone" warning I was getting, and thought it would be handy to poke around in the debugger at the point where the warning was being produced.  (Specifically: I'm getting the TDZ warning for cyclic dependency between two classes when one of them is exported as a named export, but _not_ when they're both default exports.  Very possible that this is correct: I just wanted to poke around a bit before digging into the spec in more detail.)

**Comment by jdalton** [comment]
Did the warning point you to the right source location?

**Comment by anandthakker** [comment]
It did -- no bug to report, just curious.

**Comment by anandthakker** [comment]
@jdalton a new reason it would be useful to step through: I'm trying to get `@std/esm` working together with `proxyquire`, and it's pretty impractical right now to step into `require()` calls since they go through the minified @std/esm source

**Comment by jdalton** [comment]
For the topic of `proxyquire` see #81 and https://github.com/thlorenz/proxyquire/issues/173.

**Comment by anandthakker** [comment]
@jdalton yeah, I saw those, but I've got something going awry and it's difficult to diagnose.  I understand your reasons for shipping a minified build -- just wanted to note the use case for debuggability here for future reference.
