### ISSUE TITLE
Integration issue with jest and mock-require

### ISSUE THREAD

**Issue by JLHwung** [standard-things/esm#224]
Originally reported by @pahund on https://github.com/JLHwung/postcss-font-family-system-ui/issues/37.

The `mock-require` spies on `Module._load` to return mocked modules and passthrough the other `request`. However, when integrated with `jest` and `esm`, an error is thrown on the generated source of `esm`

```
/* 0 */
/***/ (function(module, exports) {

module.exports = require("path");

/***/ }),
```

the `Module._load` is then called with `"path", undefined` which panic the spy. I don't think `this` should be `undefined` [here](https://github.com/nodejs/node/blob/master/lib/module.js#L608) so I post to this repo.

🤔 Interestingly, both `jest` and `esm` are required to produce this bug, when either of them is removed, the issue can not be reproduced.

I have constructed a minimal gist for reproduction. Please see https://gist.github.com/JLHwung/281f004baa1c40f28cc444f8e49e604f.

**Comment by jdalton** [comment]
Thanks @JLHwung!

I know the root cause. I recently switched to using `mod.require` if I detect a mocked system since I can grab an unmocked `require` but in doing so I forgot to bind it `mod.require.bind(mod)`.

**Comment by JLHwung** [comment]
😄
Ah I should have figured it out 
```
const stdReq = useBuiltins ? require : stdMod.require
```
is the culprit and work on a hotfix.

Looking forward to a new patch release.

**Comment by boblauer** [comment]
Author of `mock-require` here, this bug should be fixed in version `3.0.0`

**Comment by jdalton** [comment]
[v0.19.2](https://github.com/standard-things/esm/releases/tag/0.19.2) is released 🎉

**Comment by pahund** [comment]
💯 I can confirm that the issue is fixed, my Jest tests run as smoothly as ever. **Thank you very much, and keep up the great work!** 💯
