### ISSUE TITLE
Importing async-file is broken since @std/esm v0.19.0

### ISSUE THREAD

**Issue by Meesayen** [standard-things/esm#227]
I'm not sure why, but since `@std/esm` v0.19.0 (v0.19.1 included), importing the package `async-file` creates a RangeError: Maximum call stack size exceeded.

To reproduce it, the following two lines are enough:

```
require = require('@std/esm')(module, { esm: 'js', cjs: true })
require('async-file')
```

Removing the `cjs: true` part will not produce the RangeError.

The version of `async-file` used is the latest, v2.0.2.

**Comment by jdalton** [comment]
Hi @Meesayen!

This seems to be resolved in the master branch.
