### ISSUE TITLE
support for object destructuring with variable assignment

### ISSUE THREAD

**Issue by FND** [standard-things/esm#23]
It appears assigning values to new variable names during object destructuring is currently not supported:

```
$ node -r @std/esm index.js
…/index.js:1
import { noop: fn } from "./util";
             ^

SyntaxError: Unexpected token
```

<details>
    <summary>reduced test case</summary>

```javascript
// index.js
import { noop: fn } from "./util";
```
```javascript
// util.js
export function noop() {}
```
```javascript
// package.json
{
  "@std/esm": {
    "esm": "all"
  },
  "dependencies": {
    "@std/esm": "^0.2.1"
  }
}
```
</details>

&nbsp;
No rush though, there's an easy workaround (unless perhaps if you happen to import identical names from different modules ¯\\\_(ツ)_/¯ ).

Thanks again for your efforts on this!

**Comment by aemino** [comment]
This is old `require()` syntax. The new supported syntax for ES6 modules is `import { name as alias }`.

**Comment by jdalton** [comment]
Thanks for filing the issue @FND!

I'll defer to @aemino's answer.

**Comment by FND** [comment]
Oh, interesting: I knew about `as` for default exports, but figured named exports worked just like object destructuring elsewhere (which seems to be the case with Rollup, anyway) - thanks, @aemino.
