### ISSUE TITLE
dynamic import not working

### ISSUE THREAD

**Issue by maticrivo** [standard-things/esm#232]
I updated from version 0.18.0 to 0.19.2 and now i'm getting the following error when trying to use dynamic imports..

```js
const { initModules } = await import('./api/modules')
                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
```

my app entry point is configured like this:
```js
require = require('@std/esm')(module, { cjs: true, esm: 'js' })
require('./main.js')
```

**Comment by jdalton** [comment]
Hi @maticrivo!

Could you create a simple repro repo for me to look at?

**Comment by maticrivo** [comment]
hey @jdalton 
thanks for the quick response, i have set-up a minified version of my app [here](https://github.com/maticrivo/esm-temp). it has no README or anything so just `npm install && npm start` to start it.
if you modify package.json to use @std/esm version 0.18.0 it works, if you install latest it doesnt.

Thanks for helping :)

**Comment by jdalton** [comment]
Ah, thanks. Yep I spotted the regression. I was cleaning up a code path and thought it was only needed for nested static imports. I'm guessing it was also for dynamic imports in the exported function. I'll patch this up.

**Comment by jdalton** [comment]
[v0.19.3](https://github.com/standard-things/esm/releases/tag/0.19.3) is released :tada:
