### ISSUE TITLE
Update to 0.19.3 breaks ava tests

### ISSUE THREAD

**Issue by dacz** [standard-things/esm#233]
After updating to latest release (0.19.3) I'm getting error with ava

`TypeError: (0 , _ava2.default) is not a function`

After downgradong to 0.19.2, all works ok.

From my package.json

```
scripts: {
   ...
   "test": "cross-env NODE_ENV=test nyc ava",
   ...
},
...
"@std/esm": "cjs",
  "ava": {
    "files": ["index.test.js"],
    "require": ["@std/esm"]
  },
...
```
(package: https://www.npmjs.com/package/max-in-flight )

**Comment by jdalton** [comment]
Ah thank you @dacz!

This has something to do with our Babel interop support with the `"cjs"` option.

**Comment by dacz** [comment]
Thanks for fast reply! I'm happy to wait this to be resolved or am I doing something wrong?

Thanks for @std/esm. Finally the node development I like. I'm using it where I can (and learning it, too). Great work! Thanks

**Comment by jdalton** [comment]
From your repo if I downgrade to `0.19.2` I still get it erroring on unit tests *(cleared all the caches and everything)*.

**Comment by jdalton** [comment]
No matter. Still digging 😋

**Comment by jdalton** [comment]
This is related to the same root issue as #236. Moving there.

**Comment by Lichtjaeger** [comment]
Sorry, but this isn't solved in 0.19.4.

Instead of `import validate from '../src/validate.mjs'` I have to write:
```javascript
import X from '../src/validate.mjs'
const validate = X.default
```

The module declaration is simply:
```javascript
export default function validate(configList = []) {
  // ...
}
```

**Comment by jdalton** [comment]
I'm working through another possibly related issue. This issue however, is resolved complete with a test file. Your issue is likely different enough. If you want you can wait for the next patch release or create a simple repro repo for me to look at,.

**Comment by jdalton** [comment]
[v0.19.5](https://github.com/standard-things/esm/releases/tag/0.19.5) is released :tada:

@Lichtjaeger If you're still experiencing the bug with 0.19.5 please open a new issue with a simple repro repo and I'll fix it ASAP 😋
