### ISSUE TITLE
implement esm option in package.json

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#234]
would be awesome to maintain compatibility to node and implement an **esm** option in package.json, if/when @guybedford's PR https://github.com/nodejs/node/pull/18156(https://github.com/nodejs/node/pull/18156) is being merged into node master - based on: https://github.com/nodejs/node-eps/pull/60.

**Comment by jdalton** [comment]
Thanks for the heads up @dnalborczyk!

I'm following along.

**Comment by jdalton** [comment]
I'm going to mark this as `invalid` for the moment to clear it off the open list since it's not merged yet so there's nothing actionable for us to do at this point in time.

**Comment by jdalton** [comment]
The Node proposal has now morphed into https://github.com/nodejs/node/pull/18392.
