### ISSUE TITLE
Upgrading from 0.18.0 to 0.19.3 breaks babel-register

### ISSUE THREAD

**Issue by feross** [standard-things/esm#236]
Upgrading from 0.18.0 to 0.19.3 causes babel-register to stop recognizing JSX:

```
> nodefoo.com@1.0.0 start /Users/feross/code/nodefoo.com
> node -r @std/esm src/server/start

file:///Users/feross/code/nodefoo.com/src/views/provider.js:12
    <Provider store={store} dispatch={dispatch} theme={config.theme}>
    ^

SyntaxError: Unexpected token <
    at T._compile (file:///Users/feross/code/nodefoo.com/node_modules/pirates/lib/index.js:91:24)
    at Object.newLoader [as .js] (file:///Users/feross/code/nodefoo.com/node_modules/pirates/lib/index.js:96:7)
```

This happens in the NodeFoo repo at the following commit: https://github.com/feross/nodefoo.com/tree/565451104a16224f7f9d41a3c7af6738859b5e56. To reproduce:

1. Clone the repo and checkout commit 565451104a16224f7f9d41a3c7af6738859b5e56
2. Run `npm start` (the server starts)
3. Run `npm i @std/esm@0.19.3`
4. Run `npm start` (the server crashes with the above error)

**Comment by dnalborczyk** [comment]
for what it's worth, it's broken since 0.19.0. I created a couple scenario test cases in a branch, but haven't found time to open a PR yet. will do soon if it's of any help.

**Comment by jdalton** [comment]
I'll take the branch! Pass it my way. Never know if there could be multiple issues that once scenario doesn't catch (my tests are an example of that lol).

**Comment by dnalborczyk** [comment]
the topic is quite complex, so bugs are expected  :smiley:

here you go: https://github.com/standard-things/esm/pull/237

**Comment by jdalton** [comment]
Ok after digging a bit the issue is that for some reason *(still digging)* the export being return is an empty object for these requests.

**Comment by jdalton** [comment]
Okay. I've narrowed the issue down and am working on a patch.

**Comment by jdalton** [comment]
The issue was the I had a loader wide flag for "parsing". When that flag is set I skip execution of modules. This however made modules that jump into the pipeline (like `@babel/register`) ignore their execution and set their exports as empty objects.

**Comment by jdalton** [comment]
Okay, I got all the scenarios passing locally. Will patch and bump this evening.

**Comment by dnalborczyk** [comment]
Wow, nice!!! Thanks for the update!

**Comment by jdalton** [comment]
@dacz  your issue was related touched a different code path so I'll add your scenario too.

**Comment by dacz** [comment]
Thanks!

**Comment by jdalton** [comment]
Patches https://github.com/standard-things/esm/commit/54078f5a6b0591254b2def83bd85b6f8fa10ed66, https://github.com/standard-things/esm/commit/9a86919ca14e295c8539ebf2d4fcde0fbbab02db, https://github.com/standard-things/esm/commit/45f7f1bb806dc9eba92628e5b1a97bf120ebc060.

**Comment by jdalton** [comment]
[v0.19.4](https://github.com/standard-things/esm/releases/tag/0.19.4) is released :tada:

**Comment by feross** [comment]
@jdalton You're so fast.Thanks!
