### ISSUE TITLE
0.19.4 broke postcss-font-family-system-ui

### ISSUE THREAD

**Issue by jonathanong** [standard-things/esm#239]
i went into `postcss-font-family-system-ui`'s entry point and console logged

https://github.com/JLHwung/postcss-font-family-system-ui/blob/master/src/index.js#L3

```js
//eslint-disable-next-line
require = require('@std/esm')(module)
module.exports = require('./main.mjs').default

console.log('index.js')
console.log(module.exports)
// this is `undefined` now
```

@JLHwung @jdalton

**Comment by jdalton** [comment]
Eek. I've spotted the issue.

**Comment by JLHwung** [comment]
There is not much I can do on my side. I will release a patch release as this issue is resolved.

**Comment by jdalton** [comment]
Thanks! For some reason it's not detecting some of its child modules as loaded and so is stuck in an non-finalized state.

**Comment by jdalton** [comment]
Ok I've identified the bug and have a patch working locally. I'm adding a `postcss` test scenario.

**Comment by jonathanong** [comment]
@jdalton thanks!!!

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/0aa02eb1541d0597f618484f5df7cfaaa3410c7b complete with a test to simulate `postcss-font-family-system-ui`.

**Comment by jdalton** [comment]
[v0.19.5](https://github.com/standard-things/esm/releases/tag/0.19.5) is released :tada:
