### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by safarishi** [standard-things/esm#24]
import path from 'path'
import fs from 'fs'

// will occur an ReferenceError
console.log(__dirname)

**Comment by mohsen1** [comment]
`__dirname` is not enabled by default. See the README.

**Comment by jdalton** [comment]
Hi @safarishi!

This follows the [Node rules for ESM](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#451-environment-variables). There is a plan to use [import.meta](https://github.com/tc39/proposal-import-meta) as a replacement in the future (but it's not really fleshed out just yet). When it is we'll adopt. Until then you can use the `"cjs":true` option.
