### ISSUE TITLE
AVA tests are broken after v0.19.2 for default exports

### ISSUE THREAD

**Issue by Lichtjaeger** [standard-things/esm#240]
In addition to #233.

If I use the import statement for default exports with mjs files (`import <packagename> from '<filename>.mjs'`) it results in an object with a "default" property.

This "default" property contains the real default export. This is also true for imports like `import { default as <packagename> } from '<filename>.mjs'`.

[Here](https://github.com/standard-things/esm/files/1638178/esm-ava-test.zip) a ZIP file with a small test project.

Named exports do work.

**Comment by jdalton** [comment]
Hi @Lichtjaeger!

`ava` uses Babel to process test files so you'll want to use the `@std/esm` option of 
```
"@std/esm": "cjs"
```
or long form
```
"@std/esm" {
  "cjs": true,
  "esm": "js"
}
```

Then your tests will work properly.

**Comment by jdalton** [comment]
I added the [`ava` options tip](https://github.com/standard-things/esm/commit/949c080816a678e383fc5a66e2e1b4ac655d63ff) to readme.
When `ava` adds their [how-to](https://github.com/avajs/ava/issues/1590), I'll link to that.

**Comment by jdalton** [comment]
Oops the how-to links is https://github.com/avajs/ava/pull/1593/files

**Comment by Lichtjaeger** [comment]
Is it possible to limit this behavior only to AVA?

I would like to use esm in my source files the most native way. For example, if I use the "cjs" option it will be possible to use `__dirname` and I'm not forced to use `import.meta.url`, so I can accidentally use `__dirname`. If I switch to native esm or copy my code into a project with native esm support this could result in an error.

**Comment by jdalton** [comment]
> Is it possible to limit this behavior only to AVA?

It will be in the next release of AVA. They will make it so that when you use `@std/esm` it will bypass Babel and allow you to load without it.

**Comment by jdalton** [comment]
I'll also look into making sure `.esmrc` files in the test folder can be used.

**Comment by Lichtjaeger** [comment]
Thanks a lot. Sounds great.

**Comment by Lichtjaeger** [comment]
I can confirm: it works with the "cjs" option.

**Comment by jdalton** [comment]
Oh hey, you can also use the option:
```js
"@std/esm": {
  "cjs": {
    "interop": true
  }
}
```
to just get the Babel CJS compat.

**Comment by Lichtjaeger** [comment]
Nice. Do you also know how to make this work with [wallaby.js](https://wallabyjs.com/)?

**Comment by jdalton** [comment]
I've asked at https://github.com/wallabyjs/public/issues/1468.

**Comment by ArtemGovorov** [comment]
Added the [`@std/esm` configuration notes](https://wallabyjs.com/docs/integration/node.html#es-modules) to wallaby docs.

**Comment by jdalton** [comment]
Thank you @ArtemGovorov!
