### ISSUE TITLE
Importing namespaces imports {default: moduleNS}

### ISSUE THREAD

**Issue by mohsen1** [standard-things/esm#25]
When I import `* as path from 'path'` I get `{default: pathModuleNamespace}`:

```
sh-3.2$ node -v
v8.0.0
sh-3.2$ node
> require('@std/esm')
@std/esm enabled
> import * as path from 'path'
undefined
> path.default.join
[Function: join]
```

**Comment by jdalton** [comment]
Hi @mohsen1!

This is the [Node way for ESM](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#46-es-consuming-commonjs). You can use the `"cjs":true` option to enabled importing named exports.
