### ISSUE TITLE
resolve file path

### ISSUE THREAD

**Issue by lastmjs** [standard-things/esm#250]
Is there a function exposed to resolve the file path to the entry point of an ES module from a bare import, like require.resolve?

**Comment by jdalton** [comment]
So I can better understand the ask could you provide pseudo code to illustrate it.

**Comment by lastmjs** [comment]
I'm imagining something like the following: 

```
import { resolve } from '@std/esm';
const filepath = resolve('lodash');
console.log('filepath');
// node_modules/lodash/es/index.js, or whatever the path to the ES module entry point is
```

**Comment by jdalton** [comment]
Ok thanks!

If you unlock CJS vars:
```
{
  "cjs": {
    "vars": true
  }
}
```

The `require` function will be available with its `require.resolve` that supports ESM path resolution.

**Comment by jdalton** [comment]
You can also export `module.exports = require` in a `require.js` and import it into your ES module.

**Comment by lastmjs** [comment]
Absolutely beautiful, thank you
