### ISSUE TITLE
order of --require

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#252]
this is rather a question, than a bug report:

with 0.18.0, the following was working:
```
node --require @babel/register --require @std/esm index.js
```
as well as:
```
node --require @std/esm --require @babel/register index.js
```

that changed with 0.19.x (the exact patch version is hard to determine because of other bugs), and the only way it is working now is the latter:
```
node --require @std/esm --require @babel/register index.js
```

which is perfectly fine if intended? I remember you saying that only one or the other might -- or even should -- work, in another thread.

**Comment by jdalton** [comment]
The intended usage is for `@std/esm` to be required first. If you want to create a simple repro repo I'll dig in and see if it's easy to support both.

**Comment by dnalborczyk** [comment]
sure, I'll add some scenario tests if you want. depending on if it's feasible to make it work (or not) you can ignore/reject/discard the tests.

Though I have one more pressing scenario (bug) which I wanna write up first...

**Comment by jdalton** [comment]
I'm running this
`node -r @babel/register -r @std/esm -r ./mymodule.mjs foo.js` with my local bits and it's working. I'd still appreciate a test though to make doubly sure.

**Comment by dnalborczyk** [comment]
added some tests, and a bit more.

just wanted to stress again, don't make those tests working for me, unless they are intended to work, and/or easy to fix. I don't have a problem with reversing the order of require.  :wink:
