### ISSUE TITLE
Cannot run nyc with @std/esm

### ISSUE THREAD

**Issue by chrisveness** [standard-things/esm#257]
I'm sure this must be really simple, but I cannot work out how to get `nyc` to run with a `@std/esm` app.

I have the following test:

app.js

    import http from 'http';

    const app = http.createServer(function(request, response) {
       response.writeHead(200, { 'Content-Type': 'text/plain' });
       response.end('Hello World');
    });

    export default app;

test.js:

    import supertest from 'supertest';
    import chai      from 'chai';
    const expect = chai.expect;

    import app from './app.js';

    const request = supertest.agent(app.listen());

    describe('Test', function() {
        it('runs a test', async function() {
            const response = await request.get('/');
            expect(response.status).to.equal(200);
            expect(response.text).to.equal('Hello World');
        });
    });

package.json: 

    {
      "name": "stdesm-nyc-test",
      "version": "0.0.0",
      "scripts": {
        "test": "mocha --exit -r @std/esm test.js",
        "cover": "nyc --require @std/esm npm test"
      },
      "dependencies": {
        "@std/esm": "^0.19.7",
        "chai": "^4.1.2",
        "mocha": "^5.0.0",
        "nyc": "^11.4.1",
        "supertest": "^3.0.0"
      },
      "@std/esm": {
        "esm": "js"
      }
    }

Running `npm test` works as expected, but `npm run cover` generates the following:

    > stdesm-nyc-test@0.0.0 cover ~/Documents/node.js-test/stdesm-nyc-test
    > nyc --require @std/esm npm test

    > stdesm-nyc-test@0.0.0 test ~/Documents/node.js-test/stdesm-nyc-test
    > mocha --exit -r @std/esm test.js

    ~/Documents/node.js-test/stdesm-nyc-test/node_modules/@std/esm/index.js:1
    (function(require,module,__shared__){"use strict";var __shared__;const t=module,e=global.Array,i=global.ArrayBuffer,r=global.Atomics,n=global.Boolean,s=global.Buffer,a=global.DataView,o=global.Date,h=global.Error,c=global.EvalError,l=global.Float32Array,u=global.Float64Array,p=global.Function,f=global.Infinity,d=global.Int8Array,m=global.Int16Array,v=global.Int32Array,g=global.Intl,y=global.JSON,x=global.Map,b=global.Math,w=global.NaN,_=global.Number,E=global.Object,k=global.Promise,S=global.Proxy,A=global.RangeError,N=global.ReferenceError,C=global.Reflect,P=global.RegExp,R=global.Set,I=global.SharedArrayBuffer,L=global.String,T=global.Symbol,O=global.SyntaxError,F=global.TypeError,M=global.URIError,D=global.Uint8Array,V=global.Uint16Array,j=global.Uint32Array,U=global.Uint8ClampedArray,Z=global.WeakMap,B=global.WeakSet,z=global.WebAssembly,W=global.decodeURI,q=global.decodeURIComponent,G=global.encodeURI,$=global.en

    Error [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension: ~/Documents/node.js-test/stdesm-nyc-test/node_modules/mocha/bin/mocha
        at module.exports.e.a (~/Documents/node.js-test/stdesm-nyc-test/node_modules/@std/esm/index.js:1:47773)
        at module.exports.e.a (~/Documents/node.js-test/stdesm-nyc-test/node_modules/@std/esm/index.js:1:43236)
        at module.exports.e.a (~/Documents/node.js-test/stdesm-nyc-test/node_modules/@std/esm/index.js:1:38468)
        at Function.module.exports.wi.runMain (~/Documents/node.js-test/stdesm-nyc-test/node_modules/@std/esm/index.js:1:184304)
        at runMain (~/.node-spawn-wrap-28864-41720cbaab39/node:68:10)
        at Function.<anonymous> (~/.node-spawn-wrap-28864-41720cbaab39/node:171:5)
        at Object.<anonymous> (~/Documents/node.js-test/stdesm-nyc-test/node_modules/nyc/bin/wrap.js:23:4)
        at Module._compile (module.js:660:30)
        at Object.Module._extensions..js (module.js:671:10)
        at Module.load (module.js:573:32)
    npm ERR! Test failed.  See above for more details.
    ----------|----------|----------|----------|----------|----------------|
    File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
    ----------|----------|----------|----------|----------|----------------|
    All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
    ----------|----------|----------|----------|----------|----------------|
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! stdesm-nyc-test@0.0.0 cover: `nyc --require @std/esm npm test`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the stdesm-nyc-test@0.0.0 cover script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     ~/.npm/_logs/2018-01-25T16_35_59_512Z-debug.log

Can you advise what I'm doing wrong?

If it's useful, the above files are in a repo https://github.com/chrisveness/stdesm-nyc-test.

**Comment by jdalton** [comment]
Hi @chrisveness !

Node's roadmap currently doesn't support extensionless bin files. So mocha's bin can't be found. You should use `"esm": "cjs"` to enable that.

**Comment by jdalton** [comment]
I wonder since you're using `"esm":"js"` If I should also toggle the path resolve for that. At the moment it's treated as a file resolve issue and not a parse goal issue but in this case since you don't need the extension to get the parse goal the check isn't needed.

**Comment by chrisveness** [comment]
I should have thought of that – I need `"cjs": true` for npm modules, of course.

If I use `"esm": "cjs"`, I no longer get an error, but I get 

    ----------|----------|----------|----------|----------|----------------|
    File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
    ----------|----------|----------|----------|----------|----------------|
    All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
    ----------|----------|----------|----------|----------|----------------|

Is that just because my repro is so minimal? I will have to check later, cannot right now...

I'm perfectly happy using `"esm": "cjs"` if that's all it takes!

Thanks for quick response.

**Comment by jdalton** [comment]
When I run it with `"esm":"cjs"` I get
```
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
 app.js   |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|
```

Might try clearing your cache. I'm going to go ahead and make this "just work" with `"esm":"js"` too.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/992fdb4da34f0ffe19f70f308cb329917f7f774e

**Comment by onlywei** [comment]
@jdalton I am also getting:
```
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```
What cache are you referring to when you asked to clear it?

**Comment by onlywei** [comment]
Ah, I had to add:
```
--extension mjs```

To my call:

```nyc --require @std/esm --extension .mjs mocha ```
