### ISSUE TITLE
Unable to mock modules with sinon

### ISSUE THREAD

**Issue by nscarcella** [standard-things/esm#266]
I'm trying to find a way to mock transitive imports on my unit tests and have found many sources that suggest that something like this should work:

```js
import * as Service from './serviceToMock'
import { someFunctionThatCallsMyOperation } from './controllerThatUsesTheService'
sinon.stub(Service, 'myOperation').return(5)
someFunctionThatCallsMyOperation() // Ends up receiving a 5 as answer
```

Problem is, I'm getting an error that makes me believe `Service` is frozen: `TypeError: Cannot delete property 'myOperation' of [object Module]`.

Is this actually the case? I'm aware that built-in modules get frozen, but these are my own sources.
Is there any known way or better practice to approach this?

**Comment by jdalton** [comment]
Hi @nscarcella!

The namespace object created by `import * ...` is essentially immutable. I could make this mutable but that would be against spec and is avoidable if you expose a `export default Service` object that can be mocked then `import Service from "./serviceToMock"`.

**Comment by nscarcella** [comment]
Thanks, @jdalton! That works for me.

**Comment by jdalton** [comment]
@nscarcella Great! Let me know if anything else comes up!

**Comment by jdalton** [comment]
I'm considering making the object mutable, in a mocking mode, to better address things like https://github.com/webpack/webpack/issues/6979 and https://github.com/webpack/webpack/pull/7132.

**Comment by gmathieu** [comment]
@jdalton in response to https://github.com/webpack/webpack/pull/7132#issuecomment-390522301, looking at the esm tests in that PR covers most use cases https://github.com/webpack/webpack/pull/7132/files#diff-fd1c12466f1a82071f9854ef60ea4936R40: mock an import (`esm.js`) consumed by a file under test (`output.js`). 

I would also add that the mock isn't always a direct import of the file under test. Loaders such as [inject-loader](https://github.com/plasticine/inject-loader) make that assumption which is too limiting. I didn't create a test case for this specific scenario but know it works (we've now upgraded to webpack 4 with the custom plugin that makes exports mutable).

**Comment by jdalton** [comment]
I'm bikeshedding the `options.cjs` name. Which do you all prefer _(other suggestions welcomed too)_:
`unsealedNamespace`, `mutableNamespace`, `writableNamespace`

**Comment by gmathieu** [comment]
I vote for "mutableNamespace"

**Comment by Janpot** [comment]
@jdalton Would you consider something like loader hooks to make it possible to build this in "user-land"?

**Comment by jdalton** [comment]
@gmathieu 

I'm digging `mutableNamespace` too!

@Janpot

Module loader hooks aren't fleshed out enough to adopt and will likely be less powerful than current solutions today, so while they may be an option in the future it isn't super clear at the moment.

Since `esm` is about meeting the ecosystem where it is today and allowing a path forward we'll simply add this to the `cjs` interop options _(on by default)_. A big theme of `esm` is that users can get coding fast, and that things should "just work".

**Comment by Janpot** [comment]
Yep, I understand. It's just that sometimes it seems that node can't get to an implementation of ESM because they have to try to fit in the features that transpilers created to "just make things work". (And I'm saying this without putting any blame of sorts, just as an observation)

**Comment by jdalton** [comment]
> It's just that sometimes it seems that node can't get to an implementation of ESM because they have to try to fit in the features that transpilers created to "just make things work". 

It's not a technical problem, it's a people problem. Technically you [can compile `esm` into Node](https://github.com/standard-things/esm/wiki/Compile-Node) today and have working out-of-the-box ESM.

**Comment by Janpot** [comment]
yes, that's what I meant "can't get to a consensus"

**Comment by Janpot** [comment]
As far as I know, webpack hasn't taken an official stance on this. All I did was question whether non-standard functionality belongs in the core of your tool, or rather in a plugin (if possible). Somebody provided a plugin solution and the issue got closed by the author.
Personally, I think a plugin solution is actually a better developer solution. The flag you create is in the best case temporary (as suggested in that discussion). The plugin system is a permanent feature of the platform.

**Comment by jdalton** [comment]
> As far as I know, webpack hasn't taken an official stance on this.

The instance I was referring to was the broken mocking scenario in webpack 4. In this case the stance is inferred by not addressing the issue.

> All I did was question whether non-standard functionality belongs in the core of the tool, or rather in a plugin (if possible).

In this tool, `esm`, yes. Non-standard functionality is our starting point :yum:

>  Somebody provided a plugin solution and the issue got closed by the author.

Workarounds buried in issues aren't great _(btw [here's](https://github.com/standard-things/esm/blob/5f11d8d64044c79655b82b3487ce5c8129c530d3/webpack.config.js#L22-L42) my take on it)_. Plugins are fine but they should be documented and maybe even pulled into `webpack-contrib`. 

> The flag you create is in the best case a temporary feature (as suggested in that discussion) and in the worst case a flag you have to support forever.

Nothing is forever. A flag would exist until a platform solution comes along or until webbpack dropped it in a major release.

**Comment by Janpot** [comment]
> Non-standard functionality is our starting point

Well, let me adjust then to align more with the spirit of what I mean: "non-standard with no intention to make it a standard, as in, will this feature be specced somewhere"

> Workarounds buried in issues aren't great

agreed

> btw here's my take on it

I think this is a lot cleaner than the solution in the ticket

> For this scenario plugins are fine but they should be documented and maybe even pulled into webpack-contrib.

agreed

> Nothing is forever.

Indeed, nothing is forever, but it's there until somebody removes it. With having and removing it comes a maintenance burden, both for the tool maintainer as well as the user. With a third party plugin you take this burden away from the tool maintainer and place it on a plugin maintainer.

Tbh, take my line of thinking as half philosophical. I understand very well that people want to/have to "get things done".

**Comment by jdalton** [comment]
> Well, let me adjust then to align more with the spirit of what I mean: "non-standard with no intention to make it a standard, as in, will this feature be specced somewhere"

The ecosystem today, regardless of whether parts are-or-are-not likely to be standardized, is our starting point :yum:

> With having and removing it comes a maintenance burden,

In this case the burden is minimal _(for `esm` at least)_.

> Tbh, take my line of thinking as half philosophical. I understand very well that people want to/have to "get things done".

For me the _"get things done"_ has more weight. I've watched folks talk theory/philosophy for years and deliver :doughnut: for users.

**Comment by jdalton** [comment]
@gmathieu @nscarcella Patched https://github.com/standard-things/esm/commit/6fc556c7288a8c55946868c371c1ea5511600373.

**Comment by jdalton** [comment]
**Update**

[v3.0.37](https://github.com/standard-things/esm/releases/tag/3.0.37) and Sinon [v5.0.8](https://github.com/sinonjs/sinon/releases/tag/v5.0.8) have been released. 

This is now possible:
```js
import sinon from 'sinon'
import assert from 'assert'
import * as obj from './index'

assert.equal(obj.foo(), 1)

const spy = sinon.spy(obj, 'foo')

obj.foo(42)
obj.foo(1)

console.log(obj.foo.isSinonProxy) // true
console.log(spy.withArgs(42).calledOnce) // true
console.log(spy.withArgs(1).calledOnce) // true
```

**Comment by Zigur** [comment]
Sorry, I am probably a bit dumb, I've been trying to solve this issue in my tests for a while.
How can I use ``esm`` with webpack running my tests in karma?

I tried to use it like this:

```
require = require('esm')(module, { mode: 'auto' });

const webpackConfig = require('./biosharing_web/webpack/webpack.config.local');
const puppeteer = require('puppeteer');

process.env.CHROME_BIN = puppeteer.executablePath();

webpackConfig.devtool = 'inline-source-map';

module.exports = function (config) {
    config.set({
        browsers: [ 'ChromeHeadless'],
        singleRun: true,
        frameworks: [ 'mocha', 'chai', 'sinon'],
        files: [
            './node_modules/es6-promise/dist/es6-promise.auto.js',
            'biosharing_web/webpack/tests.webpack.js'
        ],
        plugins: [
            'karma-chrome-launcher',
            'karma-phantomjs-launcher',
            'karma-chai',
            'karma-mocha',
            'karma-sourcemap-loader',
            'karma-webpack',
            'karma-mocha-reporter',
            'karma-sinon'
        ],
        preprocessors: {
            'biosharing_web/webpack/tests.webpack.js': [ 'webpack', 'sourcemap' ]
        },
        reporters: [ 'mocha' ],
        webpack: Object.assign(webpackConfig, {
            externals: {
                jsdom: 'window',
                cheerio: 'window',
                'react/addons': true,
                'react/lib/ExecutionEnvironment': true,
                'react-test-renderer/shallow': false,
                'react/lib/ReactContext': 'window',
                'text-encoding': 'window'
            }
        }),
        webpackServer: {
            noInfo: true
        },
        autoWatch: true
    });
};
```

But if I try to stub a module function like this
```
import * as api from './api/graph-api';
const stub = sinon.stub(api, 'getGraphWidget');
```
it fails spectacularly.

**Comment by jdalton** [comment]
Hi @Zigur!

The `esm` loader support and Webpack support are two different things. Webpack will complain about the non-writable property unless a plugin is used.

**Comment by jdalton** [comment]
See [this thread](https://github.com/sinonjs/sinon/issues/1762#issuecomment-391746301) for more info.

**Comment by Zigur** [comment]
@jdalton thanks a lot for the quick reply!

**Comment by bennypowers** [comment]
I came for the library, I stayed for the support 😄 
I'm struggling to mock dynamodb helper methods that I export on an object.

## Helper Module

```js
// /lib/aws/dynamodb.js
import AWS from 'aws-sdk';
import { AWS_REGION as region } from '../../../config';

const apiVersion = '2012-08-10';

const dynamodb = new AWS.DynamoDB.DocumentClient({ apiVersion, region });

const update = params =>
  dynamodb
    .update(params)
    .promise();

export default {
  update: (...args) =>
    console.log('at runtime is update a proxy?', update.isSinonProxy) ||
    update(...args),
};
```

## App Code Module
imports the helper from `../../lib`

```js
import dynamodb from '../../lib/aws/dynamodb';

// this gets called by the apollo mutation resolver for updateDbMutation
export const updateDb = async (id, obj, ownerId) => {
  console.log('in updateDb is update a proxy?', dynamodb.update.isSinonProxy);
  return dynamodb.update(getParams())
    .then(propOr(null, 'Attributes'))
    .catch(respondWithError);
};
```

## Mocks Module

```js
import * as dynamodbModule from '../src/lib/aws/dynamodb';
export const updateStub = sinon.stub(dynamodbModule.dynamodb, 'update');
```

## Test Module

```js
import dynamodb from '../lib/aws/dynamodb';
const { update } = dynamodb;

import { updateStub } from '../../test/mocks.js';

test('call updateDbMutation', function(assert) {
  updateStub.resetHistory();
  updateStub.resolves(mockData);
  console.log('before querying is updateStub a proxy?', updateStub.isSinonProxy);
  console.log('before querying is update a proxy?', update.isSinonProxy);
  return client.query(mutation)
    .then(assertions)
    .catch(assert.fail);
```

## Test Command

```bash
tape -r esm -r './test/mocks.js' -r './test/mockApp.js' 'src/**/*.test.js' | tap-spec
```

# Output

```
before querying is updateStub a proxy? true
before querying is update a proxy? true
in updateDb is update a proxy? undefined
at runtime is update a proxy? undefined
```

So it looks like the reference was set when the app code loaded, and the mocks haven't changed anything, except scoped to the test modules.

**Comment by jdalton** [comment]
Hi @bennypowers!

Thanks for posting a question, but lets move this to a new issue. I don't want to clutter up closed threads.

**Comment by jdalton** [comment]
_Note:_ Just locking the thread because it started to become a catch-all for Sinon questions. The hope is that by locking this issue it will encourage those with questions to open new separate issues.
