### ISSUE TITLE
Help with dependencies

### ISSUE THREAD

**Issue by manico** [standard-things/esm#268]
Not sure if I'm using it wrong or not, but here is the scenario.
I have `uuid` package as dependency, and so does some of my dependencies.
Somehow, when I import  `uuid` dependency that also uses this fails as it clearly loads older package.
When I remove `import` and use standard `require` it works ok.

Here is my bridge:

```
require = require("@std/esm")(module);
module.exports = require("./src/index").default;
```

And here is the settings from package.json:

```
"@std/esm": {
    "cjs": true,
    "esm": "js"
  }
```

So, this messes up dependencies:

`
import uuid from 'uuid/v4';
`

And this is ok:

`
const uuid = require('uuid/v4');
`

**Comment by jdalton** [comment]
Hi @manico!

Could you create a simple repro repo for me to look at?

**Comment by jdalton** [comment]
Closing for lack of a repro. If you post one later I'll totally dig in.
