### ISSUE TITLE
Updating from 0.19.4 to 0.19.5 breaks babel-register

### ISSUE THREAD

**Issue by feross** [standard-things/esm#269]
The same issue as https://github.com/standard-things/esm/issues/236 has cropped up again. The issue was fixed in 0.19.4, but updating to 0.19.5 causes it to reappear. It's also present in the latest version published to npm (currently 0.20.0)

The only substantive commit between 0.19.4 and 0.19.5 appears to be this one: https://github.com/standard-things/esm/commit/0aa02eb1541d0597f618484f5df7cfaaa3410c7b

**Comment by jdalton** [comment]
Can I repro this with nodefoo ?

**Comment by feross** [comment]
Yep, if you take commit https://github.com/feross/nodefoo.com/commit/ef9004d80a4b4fbc7a46569322f211296fbdaa86 and then update @std/esm to 0.19.5, you should see the issue.

**Comment by jdalton** [comment]
Ok so taking your master at https://github.com/feross/nodefoo.com/commit/940c4ce10be3be9624600bc9c6a3b5d522a02c71 upgrading to `"@std/esm": "0.20.0"` then running `npm run test-ava` I got tests to pass.

I did this after running it on 0.19.4 without deleting the `node_modules/.cache` folder between runs.

**Comment by jdalton** [comment]
I then deleted the `node_modules/.cache` folder and reran `npm run test-ava` and got tests to pass again.

**Comment by jdalton** [comment]
I initially received errors because I plugged nodefoo into our master branch loader at version 0.20.0+ but the nodefoo.com package was gated to 0.19.4 so it failed to pass through the loader. I should make that error more clear.

**Comment by jdalton** [comment]
Marking as `invalid` only because it seems to be working with 0.20.0 (with your current master branch as linked to in my previous comment). There is something going on here regarding more helpful error messages and bad state.

**Comment by jdalton** [comment]
Oh I dig this. This is going to be my evening jam. Handling what happens when a version misfire occurs. Neat stuff!

**Comment by jdalton** [comment]
Okay!

So now `@std/esm` will detect when it could be misconfigured and give a better error message. It also automatically marks its cache as dirty, clears it, but will also clear babel/registers as well 😋

**Comment by feross** [comment]
Nice, thanks @jdalton!
