### ISSUE TITLE
Just Installed it, but it can't be found at all

### ISSUE THREAD

**Issue by ermolaevalexey** [standard-things/esm#27]
```
➜  ~ npm install -g @std/esm
+ @std/esm@0.2.1
updated 1 package in 1.783s
➜  ~ node
> require("@std/esm")
Error: Cannot find module '@std/esm'
```
What am I doing wrong? OS X Mavericks, zsh, node 8.1.3

**Comment by parro-it** [comment]
You are installing the module globally, when you need to install it locally. Try to just remove the `-g` flag

**Comment by jdalton** [comment]
Hi @ermolaevalexey!

@parro-it is correct. For more information on global vs local packages see [this npm doc entry and short video](https://docs.npmjs.com/getting-started/installing-npm-packages-globally).

**Comment by Mike-GKA** [comment]
I'm really not an expert in this stuff, but I got a solution.

I wrote a small script:
`#!/bin/bash
cd <yourpath>/localtunnel-server
node -r esm ./bin/server --port 1234
`
Of course <yourpath> must be adapted to your installation.

Starting the server with this script works fine for me.
Also starting this script with pm2 works for me.
