### ISSUE TITLE
node_modules folder inside my test folder confuses npm

### ISSUE THREAD

**Issue by mk-pmb** [standard-things/esm#274]
When I run `npm test` in `mymodule/test`, `@std/esm` v0.19.7 (in Node.js v6.12.3, npm v5.6.0, Ubuntu 14.04.5 LTS trusty) creates a folder `mymodule/test/node_modules`. When I run the same command again,

> npm ERR! enoent ENOENT: no such file or directory, open '/…/mymodule/test/package.json'
> npm ERR! enoent This is related to npm not being able to find a file.

because npm seems to expect my project only has a top-level `node_modules`. Which I'd also prefer, in order to have less entries in my `.gitignore`. Could you make `@std/esm` create the `node_modules` for its cache next to my `package.json`, instead of next to each file that transforms?

**Comment by jdalton** [comment]
I'm guessing you have an `.esmrc` config in your `test` folder? You can modify the config with the `cache` option. I'll look into only creating the cache by default in a package root.

**Comment by mk-pmb** [comment]
Happened with [portmap-parser-180204-pmb-js](https://github.com/mk-pmb/portmap-parser-180204-pmb-js).

**Comment by mk-pmb** [comment]
Might be noteworthy that the effect doesn't happen in the `test` folder of [esmod-pmb](https://github.com/mk-pmb/esmod-pmb-js) itself.

**Comment by jdalton** [comment]
When I run `npm test` I get:
```
> portmap-parser-180204-pmb@0.1.0 test /Users/jdalton/projects/portmap-parser-180204-pmb-js
> node test/all.node.js

file:///Users/jdalton/projects/portmap-parser-180204-pmb-js/test/eve1.mjs:1
TypeError: Cannot read property 'options' of null
```

**Comment by jdalton** [comment]
Nvm, was an artifact of smth I have WIP.

**Comment by jdalton** [comment]
Okay, this is interesting! 

@mk-pmb You are my kind of dev. I ❤️ the unique things you're attempting to do with `@std/esm`.
I'm going to dig in, fix the issue, and then add this as a test scenario so we don't regress it in the future!

**Comment by jdalton** [comment]
Welp, I solved everything but the folder location bit.

**Comment by mk-pmb** [comment]
Thanks! :-) Yeah that

> TypeError: Cannot read property 'options' of null

started to happen when I upgraded to latest `@esm/std` (via esmod-pmb v0.1.2). I had no idea why, but didn't care yet because the npm confusion still occurrs as described.

**Comment by jdalton** [comment]
Patches:

https://github.com/standard-things/esm/commit/0d7729e42e8b1fb62eeb276c049495c3af377568, 
https://github.com/standard-things/esm/commit/ec0a81fdd8a9a53bbd16f0d675905f2726dda372,
https://github.com/standard-things/esm/commit/94c7f559beafafec495a0090391e0998cf93ea8c

**Comment by jdalton** [comment]
Fix cache folder: https://github.com/standard-things/esm/commit/5f3829cb3e0c88c34707f6b69e407a8c7c33c16a

**Comment by mk-pmb** [comment]
Nice! So does it work now? Could you build a new version? I tried that myself, but npm's progress bar for installing the dev deps moves really slow.

**Comment by jdalton** [comment]
I'm still writing a test. I'll publish a release by this evening.

**Comment by mk-pmb** [comment]
Meanwhile I managed to build the new master version and it works for me. Thanks again!

**Comment by mk-pmb** [comment]
To save fellow Europeans from license compatibility considerations: I grant @jdalton permission to use and distribute adaptations of `esmod-pmb` v0.1.1 and/or v0.1.2 under the MIT license in his name.

Would be nice if you could include info about the base material in your `test/fixture/scenario/portmap-parser/node_modules/esmod-pmb/package.json` though. [Serving suggestion](https://gist.github.com/mk-pmb/2ce6ea4a2b2921f2f4132d1d2a9578f7)

**Comment by jdalton** [comment]
Sure thing!

**Comment by mk-pmb** [comment]
Thanks! I upgraded the dependency version in esmod-pmb, now the portmap-parser tests work repeatedly out of the box in fresh installs. :+1:
