### ISSUE TITLE
Problem when using global-prefix with "node -r @esm/std file.js"

### ISSUE THREAD

**Issue by danieldiekmeier** [standard-things/esm#275]
I'm using [Knex](http://knexjs.org/) for a project, which (through a few other dependencies) uses [global-prefix](https://github.com/jonschlinkert/global-prefix).

I think I discovered a bug with `std/esm`, because today, I couldn't start the Knex CLI anymore. I tracked down the problem and put a very simple example in this repository:

https://github.com/danieldiekmeier/global-prefix-problem

Thanks in advance for checking it out. I really enjoy your work with this module! (And with lodash, of course.)

**Comment by jdalton** [comment]
Thank you @danieldiekmeier!

The issue is because of a getter on their export:
```
Object.defineProperty(module, 'exports', {
  enumerable: true,
  get: function() {
    return prefix || (prefix = getPrefix());
  }
});
```

No worries, I'll figure it out.

**Comment by jdalton** [comment]
**Update:**

It's because in the `fallback` they `require(...)` another module that then during the wiring checks the parents `module.exports` which triggers the getter, which triggers the fallback, which triggers the getter...

**Comment by danieldiekmeier** [comment]
That's kind of what I thought – can you prevent this?

**Comment by jdalton** [comment]
Yep, the error is totally preventable. I'll have a patch later in the AM (it's 2AM here)

**Comment by danieldiekmeier** [comment]
No worries, go get some sleep!

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/e4527fdee398efd3735975395b7fd8d4967b5ac1 and https://github.com/standard-things/esm/commit/1186de8ce0c6a5eea582a31586e619cbf9dcc4a4.

**Comment by danieldiekmeier** [comment]
Thanks! ❤️
