### ISSUE TITLE
AVA's "inherit" Babel option still doesn't work

### ISSUE THREAD

**Issue by billyjanitsch** [standard-things/esm#277]
The latest version of std/esm is not playing well with the latest version of AVA when the `{"babel": "inherit"}` option is used to configure the latter. Similar to the behavior I described in #197, but seems to be a different issue with a different error.

[Here's](https://github.com/billyjanitsch/ava-esm) a simple repo demonstrating the issue; run `npm i && npm test` to reproduce. AVA correctly loads std/esm in front of the test file, but Babel fails to transpile the test file, evidenced by the JSX token parsing error. It works if you remove `"require": "@std/esm"` from package.json and `{"modules": false}` from .babelrc.

Not sure whether std/esm or AVA is the culprit here. cc @jamestalmage

**Comment by jdalton** [comment]
At the moment when you opt-in to `@std/esm` with AVA they punt on their Babel pipeline and just use `@std/esm`. I believe it would need to be enhanced to expand to both.

**Comment by jdalton** [comment]
@billyjanitsch Could you do `"require": ["@std/esm", "@babel/register"]`?

**Comment by billyjanitsch** [comment]
Thanks for the info -- I'll file an issue with AVA.

`"require": ["@std/esm", "@babel/register"]` would cause my test files' imports to be transpiled, which I don't want. (AVA's Babel pipeline only transpiles the test files.)

**Comment by jdalton** [comment]
Is it possible to configure which files babel/register handles?
Why not stick with babel for your test files instead of using both std/esm and babel?

**Comment by billyjanitsch** [comment]
While [it's possible](https://babeljs.io/docs/usage/babel-register/#specifying-options) to configure babel-register to avoid transpiling imports of test files, it's impossible for it to transpile test files themselves because scripts in AVA's `require` are run in the same context as the test files (it seems they've made an exception here for std/esm). babel-register can _only_ affect tests' imports.

Sticking with Babel for test files gets a bit convoluted with `"babel": "inherit"`. Presumably if you're using std/esm, you have Babel configured not to transpile modules. But if you're _not_ using std/esm for your test files, you _do_ need Babel to transpile modules for (only) your tests files. You can do this with Babel's [env config](https://babeljs.io/docs/usage/babelrc/#env-option) if you add a `BABEL_ENV` to your test script. This is the workaround I'm using for now.
