### ISSUE TITLE
Cannot print/evaluate with node cli using @std/esm

### ISSUE THREAD

**Issue by oles** [standard-things/esm#279]
Loooove this thing. Well done 👏 

But, an issue: 
`node --print "1 + 1"` returns `2`
`node --require @std/esm --print "1 + 1"` returns `undefined`. 

This is a simplified example, but my use case for this is to get a value from an exported object, and inject that into a bash script :)

**Comment by jdalton** [comment]
Thanks @oles!

I've got it patched locally. Will write tests and push it out today.

**Comment by oles** [comment]
Aaaawesome! ❤️

**Comment by oles** [comment]
... and it works flawlessly. Cheers!
