### ISSUE TITLE
usage pattern for external modules

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#280]
I was wondering about your opinion on [npm/github published] modules using std/esm - since I heard you are planning on moving lodash.next to use std/esm. Do you have already any plans on the approach with lodash?

should std/esm be a _peer dependency_, or rather a _dependency_ of a module?

should (or could) module authors create a cjs bridge file, and point cjs users to load the bridge file explicitly? could that have any potential risks (sync/async module resolution)? in doing so it might spur the adoption of std/esm and esm modules in general.

```javascript
// node_modules/mymodule/package.json
{
    "main": "index.js",
    "devDependencies": {
        "@std/esm": "0.21.7"
    },
    "peerDependencies": {
        "@std/esm": ">= 0.21.0 < 0.21.7"
    }
}
```

```javascript
// node_modules/mymodule/.esmrc
{
  "esm": "js",
  "cache": false
}
```

```javascript
// node_modules/mymodule/index.js
export default 'foo'
```

```javascript
// node_modules/mymodule/cjs.js
require = require('@std/esm')(module);
module.exports = require('./index');
```

```javascript
// app.js
const mymodule = require('mymodule/cjs')
```

as supposed to:
```javascript
// app.js
import mymodule from 'mymodule';
```

**Comment by jdalton** [comment]
> should `std/esm` be a peer dependency, or rather a dependency of a module?

A dependency.

> should (or could) module authors create a cjs bridge file, and point cjs users to load the bridge file explicitly? 

The bridge file is usually the main entry. But sure, you're free to explore other patterns like `mymodule/cjs`.
