### ISSUE TITLE
Top-level await in imported modules not working

### ISSUE THREAD

**Issue by yuhr** [standard-things/esm#281]
`index.js`:
```typescript
require = require("@std/esm")(module, {
  "esm": "js",
  "cjs": true,
  "await": true
});
module.exports = require("./main.mjs").default;
```

`main.mjs`:
```typescript 
import sub from './sub.mjs';
```

`sub.mjs`:
```typescript
await Promise.resolve();
export default {};
```

`node index.js` causes `SyntaxError: await is only valid in async function`. Is this intended behaviour ?

**Comment by jdalton** [comment]
Hi @yuhr!

Yes this is intended we follow [variant C](https://github.com/MylesBorins/proposal-top-level-await#variant-c-top-level-await-can-only-be-used-in-modules-without-exports) of the top-level `await` proposal which states that top level `await` is only available in modules without an `export`s

**Comment by jdalton** [comment]
**Update:**

I added a link to the variant C proposal in the readme. https://github.com/standard-things/esm/commit/fb94343c93eff661af6ec6aa7f4abadf129faa27

**Comment by yuhr** [comment]
Is there any plan to make it configurable like `"await": "variant A"` ?

**Comment by jdalton** [comment]
Not at this time. I dig variant C and that one seems like the most viable.

**Comment by 59023g** [comment]
Great package. Thank you. 
What would you suggest as an alternative to rendering an html string as a module ( as below ). Or rather, if you know, what am I missing architecturally to think this should be allowed? ( Yet isn't per Variant C ):

```
// home_view.js

import * as utils from '../static/utils.js'
import * as server_utils from '../utils/server_utils'

import sortBar from './sortBar'
import sideBar from '../static/sideBar'
import legList from '../static/legList'

export default async ( posts, votes, count ) => {

  let html = ``

  html += `<div class='app-left-pane'>`
  html += await sortBar( count )
  html += await legList( posts, votes )
  html += `</div>`

  html += `<div class='app-right-pane df fdr'>`
  html += await sideBar()
  html += `</div>`

  return html

}
```

**Comment by jdalton** [comment]
Hi @59023g!

Variant C is restricting ESM but CJS should still work with `module.exports` if you want to experiment with that there.
