### ISSUE TITLE
Cannot load another esm package/ esm's require() returns empty

### ISSUE THREAD

**Issue by rektide** [standard-things/esm#282]
Hello.
I've been working on [package-depends](https://github.com/rektide/package-depends), a script to go through a dependency tree. When I run `node --harmony_async_iteration ./index.js`, which is a short esm wrapper script as per the esm usage docs, I get some very odd behavior: [the returned value](https://github.com/rektide/package-depends/blob/master/index.js#L6) from esm's require() is an empty object instead of the various exports in the asked for module. That causes `TypeError: Object.defineProperties called on non-object` [a couple lines later](https://github.com/rektide/package-depends/blob/a6b4d11d42a3a02962db440e23a5f42f2f3225d3/index.js#L10), when it should have the exports from the module it just required.

If I [comment out one specific `import` in the script I am attempting to load](https://github.com/rektide/package-depends/blob/a6b4d11d42a3a02962db440e23a5f42f2f3225d3/package-depends.js#L2), I get the expected exports. This one change alone swaps between getting an empty object from esm's require, and getting the expected exports (however without that `import`, trying to use the code fails).

That alone is an adequate and sufficient statement of cause, demonstrates something that should not be. I've tried putting "debug": true, "warn": true  in my `pkg.@std/esm`, but it does not generate any additional info.

I also noted, from some time with the Linux utility `strace` looking at what files get accessed, that I can't seem to get the depended on `async-iterator-muxer` module to load as an ESM module. I peppered the package.json with [every directive I could](https://github.com/rektide/async-iterator-muxer/blob/c1779e13b14eda867d27f0adfb761d7ecd32c383/package.json#L6-L9) to try to get std/esm to depend on it as a module, but to no avail. At every attempt, the dependency is being loaded as CJS, via it's std/esm CJS index.js wrapper as specified in `pkg.main`. I've tried a lot of permutations including removing the index.js wrapper and making the depended module have ONLY esm but std/esm didn't like that it has `import`'s, even though it's pkg.esm= true & pkg.module & everything else. This was very unexpected. I tend to believe whatever is happening here could well be related to std/esm trying to load this other module as CJS, and creating another std/esm.

Ah ha! I tried a fresh download of my `package-depends` with an npm install, rather than using npm link, like I do in development. Everything works, in this situation, because there is only a single std/esm in use. I believe the issue is that the `async-iterator-muxer` dependency is loading it's own std/esm, because it is going through the index.js wrapper.

How can I develop a library in a manner such that std/esm will see and load it's ESM form, rather than it's wrapper?

**Comment by jdalton** [comment]
Hi @rektide!

Can you explain the setup to create a repro here.

**Comment by rektide** [comment]
```
git clone https://github.com/rektide/async-iterator-muxer
cd async-iterator-muxer
npm install
npm link
cd ..
git clone https://github.com/rektide/package-depends
cd package depends
npm install
npm link async-iterator-muxer
node --harmony_async_iterator ./index.js
```

Thanks John. Sorry this one has such awkward reproduction steps.

**Comment by jdalton** [comment]
Np, what version of Node supports `--harmony_async_iterator`. I tried 8.x and 9.5.0 without luck.

**Comment by rektide** [comment]
Ugggh, my typo. It's `--harmony_async_iteration`. Editing the above instructions to reflect. 9.5.0 definitely, and I think recent 8.x too but less sure.

**Comment by jdalton** [comment]
The `package-depends` repo seems to have several typos around `mxuer` -> `muxer`, a missing `muxer` reference in `async _deps`, and then a missing package.json in the `async _findModule` call.

**Comment by rektide** [comment]
I just pushed a bunch of fixes to `package-depends` that cover those. They definitely inhibited it from running. But in the test setup above, it shouldn't get anywhere near that far. There should very quickly be a `TypeError: Object.defineProperties called on non-object`.

**Comment by jdalton** [comment]
With those fixes when I run as per your instructions I'm getting
```
➜ node --harmony_async_iteration index.js
{ AsyncIteratorMuxer: { AsyncIteratorMuxer: [Getter], default: [Getter] },
  bad: true,
  'async-iterator-muxer': 'what' }
{ ex: [Function: AsyncIteratorMuxer] }
{ PackageDepends: [Function: PackageDepends] }
{ dep: '@std/esm' }
{ dep: 'async-iterator-muxer' }
{ dep: 'pn' }
{ dep: 'promise-race-predicated' }
{ dep: 'unknown-filter' }
```

**Comment by rektide** [comment]
That's a good run, atm. I'm reproducing your results locally too with my own reproduction steps. There's got to be some missing element to my reproduction steps, but I'm not sure what it is. Trying to find out what it is.

**Comment by rektide** [comment]
I've spent 10 minutes trying to find any difference between my reproduced environment and the original env that wasn't working, and I can find nothing that explains the different behaviors I'm seeing.

This reproduced instance suits my desired development path, does what I want, and works.

This was super weird, and I'd really like to get further to the bottom of this bizarre env, but I've already used way way too much of your time & you've been so unbelievably kind for doing so. I'm going to close this issue for now, and if I can find a better steps to reproducing, find out what's so special about the original environment, I'll try to raise any issues I find, along with better steps. Thank you a million times John. Please accept my humble apologies.

**Comment by jdalton** [comment]
Hey, no problem!

Thank you so much for digging `@std/esm` and helping hammer on it.
If you stumble upon the root cause feel free to ping back in this issue and I'll get it worked out 😸
