### ISSUE TITLE
Make use of "module" field in package.json to determine which file to import

### ISSUE THREAD

**Issue by Jovaage** [standard-things/esm#285]
I've seen that packages like [vue](https://github.com/vuejs/vue/blob/dev/package.json#L6) have implemented the use of [this proposal](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md).

Would it be possible to have `@std/esm` use the `"module"` field in package.json files to determine the entrypoint to the package?

I have a current case where this would be useful.  
I have a package, written in with esm. To enable use of this package without having the user install and use `@std/esm`, I've pointed the `"main"` field at my `index.common.js` file, which essentially uses the first og three ways listed in the "getting started" section in the readme.
If `@std/esm` would respect `"module"`, it could circumvent `index.common.js`, and go straight to the esm `index.js` in projects that already have `@std/esm` enabled.

**Comment by jdalton** [comment]
`@std/esm` can be used as a dependency for your package.
It's the main win for enabling CJS code in Node 4+ to run ESM. Is `@std/esm` too big of a dependency? I guess I'm confused. Can you clarify the ask a bit more.

**Comment by jdalton** [comment]
Related to #136.
