### ISSUE TITLE
How to delete from cache?

### ISSUE THREAD

**Issue by bensampaio** [standard-things/esm#287]
I have a use case where I need to remove a module from cache. With CJS you can do: `delete require.cache[moduleName]`. Is there a way of doing the same with ESM?

**Comment by jdalton** [comment]
Hi @bensampaio!

Yes you can unlock CJS interop to expose ESM on `Module._each` and `require.cache`.
```json
{
  "cjs": {
    "cache": true
  }
}
```

**Comment by bensampaio** [comment]
Thank you @jdalton! Will this be supported when Node releases ESM? I cannot find documentation for `Module._each`. Should I be using that instead of `require.cache`?

**Comment by jdalton** [comment]
I typoed. I meant `Module._cache`. Node hasn't worked out how caches will be exposed yet.

**Comment by aral** [comment]
Just as an update, `Module` is not accessible (Node 14.x). Afaik, there is no way to get at / manipulate the Node ESM cache at the moment. (Which is quite a shortcoming.)
