### ISSUE TITLE
Any ways to directly use ES6 syntax in .js files?

### ISSUE THREAD

**Issue by OshotOkill** [standard-things/esm#29]
I checkout the docs and specify `@std/esm` property as `{"esm": "js"}` in `package.json`, however it doesn't work:

<img width="1084" alt="2017-08-13 1 51 49" src="https://user-images.githubusercontent.com/6079112/29246493-e1a08010-802e-11e7-8e36-8a34c2f3662c.png">

Anything wrong with my configuration or it cannot be used like that ?

**Comment by jdalton** [comment]
Hi @OshotOkill!

Yes as in the readme example your module entry that calls `@std/esm` can't use `import` or `export` but the files it requires can.

**Comment by OshotOkill** [comment]
I gave it a try but still didn't understand the running mechanism:

<img width="1033" alt="2017-08-13 10 53 37" src="https://user-images.githubusercontent.com/6079112/29250747-853e0ff8-807a-11e7-94d4-458095b9df21.png">

I expected it to be `0` rather than `undefined`

**Comment by jdalton** [comment]
No prob. Keep an eye on #15. Once that's resolved we'll be cook'n with gas!

**Comment by jdalton** [comment]
Fixed with v0.3.0 🎉
