### ISSUE TITLE
esm/Svelte SSR does not always recognize import/export

### ISSUE THREAD

**Issue by EmilTholin** [standard-things/esm#290]
Using esm for Svelte SSR works great, but when a Svelte component is the first thing to be required, esm does not seem to recognize `import`/`export`.

E.g this works great:

```javascript
const { square } = require('./module.js');
require('svelte/ssr/register');
const app = require('./App.html');

console.log(app.render().toString());
```

But this gives rise to an error, like [this basic repro illustrates](https://github.com/EmilTholin/esm-svelte):

```javascript
// Works great if square is imported on its own first
// const { square } = require('./module.js');
require('svelte/ssr/register');
const app = require('./App.html');

console.log(app.render().toString());
```

**Comment by jdalton** [comment]
The severside rendering is blowing my mind. I'd dig more info on how you use `std/esm` and Svelte to enable this rad workflow.

**Comment by EmilTholin** [comment]
I've been using [esm and Svelte as outlined in the docs](https://svelte.technology/guide#server-side-api) for a quite a while with [svelte-routing](https://github.com/EmilTholin/svelte-routing), and its been working perfectly, but I noticed that it stopped working if I moved/removed all imports before `require('svelte/ssr/register');`. 

I don't have much knowledge of the inner workings of either the Svelte compiler or esm, so I'm not sure I can come with much valuable information.

**Comment by EmilTholin** [comment]
I apologize. It seems like the exact module the Svelte component imports has to be imported, or it will not work.

```javascript
// const { square } = require('./module.js');
// This doesn't work either. 'square' has to be imported.
const { cube } = require('./module2.js');
require('svelte/ssr/register');
const app = require('./App.html');

console.log(app.render().toString());
```

**Comment by jdalton** [comment]
By doesn't work does it throw an error?

**Comment by jdalton** [comment]
Ah yep, I see.

**Comment by jdalton** [comment]
Ok @EmilTholin!

I'll hammer on this today and get it working 😄

**Comment by jdalton** [comment]
Found the issue. You're using an older version of `@std/esm`. It works with the current master branch. So I'm guessing will work with the latest release too 😋

**Comment by jdalton** [comment]
No problem @EmilTholin!

Thanks for hammering on `@std/esm`! Feel free to post bugs anytime.
