### ISSUE TITLE
node_modules imports lose referential equality in 0.23.0

### ISSUE THREAD

**Issue by billyjanitsch** [standard-things/esm#294]
As of std/esm@0.23.0, it seems that imports from node_modules/ outside the std/esm chain are not referentially equal to the same imports within the std/esm chain.

[Here](https://github.com/billyjanitsch/esm)'s a small repo to demonstrate. If you downgrade to std/esm@0.22.0, it works fine.

**Comment by jdalton** [comment]
Thanks @billyjanitsch!

I'll fix that up.

**Comment by jdalton** [comment]
The issue is that with the CJS interop unlocked  we add the `__esModule` marker for the exports so AVA *(which you have still using Babel instead of `std/esm`)* will load it as regular CJS while it's also loading a proxied exports for live bindings. To fix this if we add `__esModule` we'll nix the proxy since you're likely using Babel.

**Comment by billyjanitsch** [comment]
Thanks for the quick patch, @jdalton!

Upgrading std/esm to 0.23.1 fixes the issue, but the issue persists if I [tweak the re-export](https://github.com/billyjanitsch/esm/commit/4671635b8a2e99a9771f1d58d9f4d9a9b4f7d517#diff-1a7639840c1699303af8d03d6672c403). I would expect this to work because [my test compares a property](https://github.com/billyjanitsch/esm/blob/master/test.js#L6) on the object, not the object itself. This worked in 0.22.0.

**Comment by dnalborczyk** [comment]
@billyjanitsch  I haven't looked entirely through your repro repository (just this bit: https://github.com/billyjanitsch/esm/commit/4671635b8a2e99a9771f1d58d9f4d9a9b4f7d517#diff-1a7639840c1699303af8d03d6672c403), but _object spread_ is essentially creating a shallow copy of your object, hence you wouldn't have the handles on the references.

**Comment by billyjanitsch** [comment]
I know; see the other link. Obviously `a !== {...a}` but `a.foo === {...a}.foo`.

**Comment by dnalborczyk** [comment]
check the type of _foo.bar_. I think you created a property on both sides of the operator and therefore checking _undefined === undefined_.

**Comment by dnalborczyk** [comment]
it's gotten too late. :smiley: I got the types mixed up (with flow types), but you are comparing the values of the properties... I'll have to look at the entirety tomorrow.

**Comment by billyjanitsch** [comment]
It's true in general when `foo` is an object, including when `bar` exists. e.g. `const foo = {bar: {}}; foo.bar === {...foo}.bar`

The test output confirms that both properties exist, and the test would pass if they didn't.

**Comment by jdalton** [comment]
Ah thanks @billyjanitsch!

This is because those happen to be bound methods and we process them a bit differently. It's fixable.

**Comment by jdalton** [comment]
**Update:**

The unwrapping of proxies is kind of a bandaid. I'll instead have it so that the `module.exports` of a bridged module doesn't have proxies at all. This will ensure seamless Babel compat (no matter how you pick/pluck methods/imports).
