### ISSUE TITLE
cjs module in dual mode module container loads wrong module

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#296]
hey John, I found some time to digg into the bug I thought I discovered creating the scenario test for: https://github.com/standard-things/esm/issues/286 and https://github.com/standard-things/esm/pull/288

_sorry, I wasn't able to file it at the same time as the mentioned above, as I initially thought it was failing to error if a required module was missing, little did I know it was requiring another module silently. :smiley: I thought it was related and would go away once the above was fixed._

it seems, in the dual scenario, a cjs module in a dual mode module container, would wrongly load (require) an esm (mjs) module.

node v9.6.1
std/esm v0.23.0

repro: https://github.com/dnalborczyk/stdesm-dual-mode

```
  "scripts": {
    "start-stdesm-js": "node -r @std/esm index.js",
    "start-stdesm-mjs": "node -r @std/esm index.mjs",
    "start-node-mjs": "node --experimental-modules index.mjs"
  }
```

_edit: changed the script names_

**Comment by jdalton** [comment]
Patched! It was a memoization issue between cjs/esm.

**Comment by dnalborczyk** [comment]
cool, thanks once again!
