### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by capaj** [standard-things/esm#3]
I have a file called mod.js which contains only `export default 'bbb'` and when I try to import it I get this:
```
node
> require("@std/esm")
[Function]
> import b from './mod'
/home/capaj/git_projects/tests/es-module-loader/mod.js:4
export default 'bbb'
^^^^^^
SyntaxError: Unexpected token export

>
```

Why is that? Shouldn't this make es6 modules importable?

**Comment by rauschma** [comment]
I’m getting:

```text
> require('@std/esm');
[Function]
> import './test.js';
/Users/rauschma/tmp/test.js:1
(function (exports, require, module, __filename, __dirname) { import {format} from 'util';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```

`test.js` looks like this:

```js
import {format} from 'util';

console.log(format('%s %s!', 'Hello', 'world'));
```

**Comment by capaj** [comment]
@rauschma yeah I think it only can import CJS files for now.

**Comment by jdalton** [comment]
Folks, this project is not released yet.
You can't npm install the package from the registry at moment.

**Comment by jdalton** [comment]
The REPL works fine. At the moment the esm loader requires you to opt-in by making it a dependency, dev-dependency, or peer dependency in your project. So it won't enable its functionality without that. While this makes sense for normal package use I may re-evaluate that for REPL use.

Please keep hammering on it but keep in mind this project is pre-release and is not published to the npm registry yet.

**Comment by rauschma** [comment]
Makes sense, thanks for the answer!

**Comment by juliocanares** [comment]
same issue here using 0.10.0 getting 

```
export default (sequelize, Sequelize) => {
^^^^^^
```

**Comment by jdalton** [comment]
@juliocanares Can you create a simple repro repo for me to look at?

**Comment by juliocanares** [comment]
@jdalton sure, here it is https://github.com/juliocanares/export-repro

**Comment by juliocanares** [comment]
now it's throwing this error
```
Error [ERR_MISSING_MODULE]: Cannot find module address
```

**Comment by juliocanares** [comment]
My bad, I forgot to correctly import the module `./{module-name}`. the export statement works in the repro repo too, but still not working in my main project.

**Comment by jdalton** [comment]
Ya, this is hijacking an unrelated thread. Want to move this to email (john[dot]david[dot]dalton[at]gmail[dot]com)
