### ISSUE TITLE
clean install doesn't work since 0.2.1

### ISSUE THREAD

**Issue by reimertz** [standard-things/esm#30]
```
Error: ENOENT: no such file or directory, open '/Users/reimertz/Library/Mobile Documents/com~apple~CloudDocs/_/repos.nosync/nes-o-png/node_modules/@std/esm/esm.js.gz'
```

**Comment by reimertz** [comment]
just use 0.2.0 until this is solved and published as 0.2.3.

```
npm i @std/esm@0.2.0 
```

**Comment by jdalton** [comment]
Hi @reimertz!

I can't reproduce. The version that slipped through without an `esm.js.gz` was v0.1.0. All others should have them. You can easily verify by using downloading them:

https://registry.npmjs.org/@std/esm/-/esm-0.2.2.tgz
https://registry.npmjs.org/@std/esm/-/esm-0.2.1.tgz
https://registry.npmjs.org/@std/esm/-/esm-0.2.0.tgz

**Comment by jdalton** [comment]
If you're using yarn checkout #105.

**Comment by jdalton** [comment]
Resolved by https://github.com/yarnpkg/yarn/commit/a3af4774f3131c64c048d4fdbe6df72d4edc117d.
