### ISSUE TITLE
0.23.0 does not support node 5 either

### ISSUE THREAD

**Issue by Avaq** [standard-things/esm#300]
The [0.23.0 release notes](https://github.com/standard-things/esm/releases/tag/0.23.0) list that Node 4 support has been dropped. However, [my builds also are failing](https://github.com/fluture-js/Fluture/pull/227) (with the same error message) on Node 5. I'm fine with that, but I just wanted to make sure this is intentional and you are aware of it.

**Comment by jdalton** [comment]
Node 5 is no longer supported by Node *(not part of its LTS support matrix)* so not considered.
See https://github.com/nodejs/Release#release-schedule
