### ISSUE TITLE
Re-export of previously exported class fails to compile

### ISSUE THREAD

**Issue by anandthakker** [standard-things/esm#301]
Running `node -r @std/esm` on the following,

```js
export class MyClass {}
export {MyClass as MyClassAlias}
```

results in an error:

```
export {MyClass as MyClassAlias}
        ^^^^^^^

SyntaxError: Export 'MyClass' is not defined in module
```

If `class MyClass{}` is not exported (or exported after it's declared), the error does not occur.

**Comment by jdalton** [comment]
Ah nice! This is a parse error that slipped in. I'll fix it by this evening.

**Comment by jdalton** [comment]
**Update**:

[v0.23.3](https://github.com/standard-things/esm/releases/tag/0.23.3) is released 🎉
