### ISSUE TITLE
Cyclic dependency with a named class export causes temporal dead zone warning

### ISSUE THREAD

**Issue by anandthakker** [standard-things/esm#302]
@jdalton I've been looking at the spec, but I'm still not sure whether or not this behavior is correct.  

Given:

a.mjs:
```js
import B from './b.mjs';
class A {
    static something() {
        this.b = new B();
    }
}
export {A}
```

b.mjs:
```js
import {A} from './a.mjs'
class B {
    stuff() {
        A.something();
    }
}
export default B
```

`node -r @std/esm a.mjs` results in `Warning: @std/esm@0.23.2 detected possible temporal dead zone access of 'A' in file:///Users/anand/c/mapbox/scratch/classbug/a.mjs` -- but if `a.mjs` is changed to use a default rather than named export, the warning does not occur.

**Comment by jdalton** [comment]
Hi @anandthakker!

Our wording for the warning is "possible TDZ access" since we can't be for sure in our detection. In this case it's fine. You can disable warnings with the `@std/esm` option `warnings:false`.

**Comment by anandthakker** [comment]
Gotcha.  Thanks @jdalton!

**Comment by jdalton** [comment]
I may be able to narrow the warning down to non-class members and only for `let` or `const` bindings. I'll dig in.

**Comment by jdalton** [comment]
Hey @anandthakker! I can totally detect this better. I'm working on a patch that would make this warning limited to `const`/`let` bindings in this scenario.

**Comment by specialkk** [comment]
I was just about to ask this same question. I have `detected possible temporal dead zone access of 'default'` for a few of my classes involved in cyclic dependencies. Thanks for looking into this!

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/524fce34e12e33f95606cc2030ef56ffc0e5678d and https://github.com/standard-things/esm/commit/95c216e7b339a67254593f20ebecaa000b5ea036.

**Comment by jdalton** [comment]
[v0.23.4](https://github.com/standard-things/esm/releases/tag/0.23.4) is released 🎉
