### ISSUE TITLE
Who is ESM meant for?

### ISSUE THREAD

**Issue by jleach** [standard-things/esm#304]
I write modules all the time for my node apps; they just don't get published via NPM. Is ESM for me or for module publishers? Also, can it be used with babel? I have to use it because my run time environment is node 6 and I can't live without async/await and it already converts imports into require.

Good Javascript Jabber Podcast interview BTW.

**Comment by jdalton** [comment]
Hi @jleach!

> Is ESM for me or for module publishers?

It's for you and module publishers.

>  Also, can it be used with babel?

Yes, you can disable Babel transpilation of `import`/`export` with the Babel `modules:false` option.
