### ISSUE TITLE
regression bug in 0.25.2

### ISSUE THREAD

**Issue by arackaf** [standard-things/esm#309]
Repo: https://github.com/arackaf/booklist/tree/special/jdd-mar-8 that branch specifically

`npm i` 

drop into `node-src\graphqlSetup`

run `node index`

You should get `SyntaxError: 'import' and 'export' may only be used in ES modules`

This works fine in prior versions.

**Comment by jdalton** [comment]
Hi @arackaf!

The [`"esm":`](https://github.com/arackaf/booklist/blob/special/jdd-mar-8/app.js#L1) option was renamed to `"mode":` in in [v0.25.0](https://github.com/standard-things/esm/releases)

**Comment by arackaf** [comment]
@jdalton sorry about that.  I'm curious though, have you considered detecting if an `esm` option is present, and erroring out with a note about how the option changed? Might help folks upgrading.

**Comment by miljan-aleksic** [comment]
@jdalton, could you please support back the `esm` option and add a deprecation notice when detected it use? Suddenly braking workflows is a bad idea and especially when it is not clear where it is coming from.

Anyway, thank you for this excellent tool :)

**Comment by arackaf** [comment]
True, but honestly a tweaked error message here would probably help a lot, and not be too hard to add (I wouldn't think)
