### ISSUE TITLE
Question: Absolute imports or alias

### ISSUE THREAD

**Issue by manico** [standard-things/esm#312]
Hi,

is there an option to use aliases for import paths, similar to how webpack uses them.

Example, to use this:

`import config from '@/config';`

instead of:
`import config from '../../../../config';`

Thank you. :)

**Comment by jdalton** [comment]
Hi @manico!

No there isn't right now.
As the Node loader implementation is ironed out we'll support it which will allow you to remap paths.

**Comment by o-alexandrov** [comment]
Please update the status of this issue

**Comment by kenberkeley** [comment]
Any update?

**Comment by zeckdude** [comment]
How's this looking

**Comment by SparK-Cruz** [comment]
I need this, any consensus?
