### ISSUE TITLE
Node Execution stops if I require this package

### ISSUE THREAD

**Issue by AndyOGo** [standard-things/esm#314]
Node verison is `v9.4.0`.

I want to load es modules within my `webpack.config.js`, like:

```js
// eslint-disable-next-line no-global-assign
require = require('esm')(module, { mode: 'auto' }); // my script exits here

console.log('I'm lost in space');

module.exports = {
  entry: '...'
};
```

May I do something wrong 🤔

**Comment by jdalton** [comment]
Hi @AndyOGo!

This is because I haven't published the renamed package yet. So until I do it's still using the old name, `@std/esm`. I should publish it by this afternoon to smooth over the confusion.

**Comment by AndyOGo** [comment]
Got it. Thanks

**Comment by jdalton** [comment]
For the current `@std/esm` usage see the [v0.25.2](https://github.com/standard-things/esm/tree/0.25.2#stdesm) release.
