### ISSUE TITLE
default settings with v3.0

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#315]
just applied the new and shiny v3.0, congrats!! 

_edit:_ nevermind, everything seems to work as expected! (I was in the wrong folder)

**Comment by jdalton** [comment]
No problem @dnalborczyk!

Thanks for digging in!

**Comment by dnalborczyk** [comment]
ah, just noticed, the **hickup** came from the now non-existent { mode: "js" } option in .esmrc, which I thought I deleted the file, but in the wrong folder.

**Comment by jdalton** [comment]
I should throw for invalid modes... at the moment I just silently coerce them to supported values... in this case to `"strict"`.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/341622f8e56297d1d8d663b77e386ba776ac3fac.
