### ISSUE TITLE
Error: async hook stack has become corrupted

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#316]
just switched to _esm_ v3 in another project, and low and behold it blew up 😃 

```console
Error: async hook stack has become corrupted (actual: 6, expected: 1)
 1: node::Environment::AsyncHooks::pop_async_id(double) [/usr/local/bin/node]
 2: node::Start(v8::Isolate*, node::IsolateData*, int, char const* const*, int, char const* const*) [/usr/local/bin/node]
 3: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [/usr/local/bin/node]
 4: node::Start(int, char**) [/usr/local/bin/node]
 5: start [/usr/local/bin/node]
 6: 0x4
```

after digging for a bit, I noticed that the CJS options are all turned on by default. I wasn't aware of that.

anyhow, former CJS module _default imports_ became _undefined_, and caused a chain reaction of events and the above to appear.

minimum to reproduce:

index.js:
```javascript
process.nextTick(() => x)  // x is undeclared
```

console:
```console
node -r esm index.js
```

**Comment by dnalborczyk** [comment]
btw, _nextTick_ was just a bad guess...

the actual node functionality in the code was calling something along those lines:

```javascript
import http from 'http'
const { createServer } = http
const server = createServer()
import foo from 'some-node_modules-cjs-module'

server.listen(3000, () => foo.nowUndefined())
```

I haven't looked into how _server.listen_ is implemented.

**Comment by jdalton** [comment]
Naw, you pin pointed the exact issue. I have a patch now, just writing the unit test.

**Comment by dnalborczyk** [comment]
now thinking about it for a bit, I was wondering how the _cjs default imports_ became _undefined_, because the node-build-ins still seem to work both ways (they didn't become undefined).

std/esm v0.25.2, { mode: "js" } required the following (_note, namedExports not activated_):
```javascript
import http from 'http'
const { createServer } = http
```
with esm v3.x, default options, the above and the below works:
```javascript
import { createServer } from 'http'
```

is there a certain mechanism which would/could cause this to happen? could it be that the [node_module] module was likely babel-transpiled? I'm a little bit confused 😃

**Comment by jdalton** [comment]
I'm not sure how one became `undefined`. Can you reproduce the `undefined` result now?

**Comment by dnalborczyk** [comment]
let me check ...

**Comment by dnalborczyk** [comment]
it's a _TypeScript-transpiled_ module with a _default_ export, in this particular case: https://github.com/apollographql/subscriptions-transport-ws

```javascript
import subscriptionsTransportWS from 'subscriptions-transport-ws'
console.log(subscriptionsTransportWS)
```
with ...
```json
{
  mode: "auto",
  cjs: true
}
```
the output is:
```console
{ [Function: MessageTypes]
  GQL_CONNECTION_INIT: 'connection_init',
  GQL_CONNECTION_ACK: 'connection_ack',
  GQL_CONNECTION_ERROR: 'connection_error',
  GQL_CONNECTION_KEEP_ALIVE: 'ka',
  GQL_CONNECTION_TERMINATE: 'connection_terminate',
  GQL_START: 'start',
  GQL_DATA: 'data',
  GQL_ERROR: 'error',
  GQL_COMPLETE: 'complete',
  GQL_STOP: 'stop',
  SUBSCRIPTION_START: 'subscription_start',
  SUBSCRIPTION_DATA: 'subscription_data',
  SUBSCRIPTION_SUCCESS: 'subscription_success',
  SUBSCRIPTION_FAIL: 'subscription_fail',
  SUBSCRIPTION_END: 'subscription_end',
  INIT: 'init',
  INIT_SUCCESS: 'init_success',
  INIT_FAIL: 'init_fail',
  KEEP_ALIVE: 'keepalive' }
```
with ...
```json
{
  mode: "auto",
  cjs: false
}
```
the output is:
```console
{ SubscriptionClient: [Function: SubscriptionClient],
  SubscriptionServer: { [Function: SubscriptionServer] create: [Function] },
  default:
   { [Function: MessageTypes]
     GQL_CONNECTION_INIT: 'connection_init',
     GQL_CONNECTION_ACK: 'connection_ack',
     GQL_CONNECTION_ERROR: 'connection_error',
     GQL_CONNECTION_KEEP_ALIVE: 'ka',
     GQL_CONNECTION_TERMINATE: 'connection_terminate',
     GQL_START: 'start',
     GQL_DATA: 'data',
     GQL_ERROR: 'error',
     GQL_COMPLETE: 'complete',
     GQL_STOP: 'stop',
     SUBSCRIPTION_START: 'subscription_start',
     SUBSCRIPTION_DATA: 'subscription_data',
     SUBSCRIPTION_SUCCESS: 'subscription_success',
     SUBSCRIPTION_FAIL: 'subscription_fail',
     SUBSCRIPTION_END: 'subscription_end',
     INIT: 'init',
     INIT_SUCCESS: 'init_success',
     INIT_FAIL: 'init_fail',
     KEEP_ALIVE: 'keepalive' },
  GRAPHQL_WS: 'graphql-ws',
  GRAPHQL_SUBSCRIPTIONS: 'graphql-subscriptions' }
```

which I suppose is correct, I'm guessing the _namedExport_ is more targeted towards _non-transpiled_ modules?

**Comment by dnalborczyk** [comment]
I think the behavior between _cjs: true/false_ is changing depending on if there's a _default_ parameter being exported from a cjs module (or not.)

**Comment by jdalton** [comment]
It looks like `subscriptions-transport-ws` is exporting
```js
[ '__esModule',
  'SubscriptionClient',
  'SubscriptionServer',
  'default',
  'GRAPHQL_WS',
  'GRAPHQL_SUBSCRIPTIONS' ]
```
With `cjs.interop` set to `true`, as it is by default, then we respect the `__esModule` interop flag which says "Treat this more like an ESM export". So when you do  `import subscriptionsTransportWS from 'subscriptions-transport-ws'` you get the `.default` export of `subscriptions-transport-ws`.

When you disable `cjs.interop` we treat it as any plain cjs export in which the `.default` is the full `module.exports` object. 

The `cjs.interop` flag allows your bridged ESM -> CJS modules to be picked up as ESM by things like Babel or TS ([with `--esModuleInterop`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop)) too.

**Comment by dnalborczyk** [comment]
aaaaaaah, ok, that makes sense now. Thanks for the clarification! Much appreciated!
