### ISSUE TITLE
upgrage from 0.24.0 to 0.25.2 broke tests

### ISSUE THREAD

**Issue by AllNamesRTaken** [standard-things/esm#318]
Hi,
got this after upgrading to 0.25.2, downgrading to 0.24.0 fixes it:
> mocha -r @std/esm ./dist/test/*Test.js

import { should } from "chai";

SyntaxError: 'import' and 'export' may only be used in ES modules

**Comment by jdalton** [comment]
Hi @AllNamesRTaken!

The v[0.25.0](https://github.com/standard-things/esm/releases/tag/0.25.0) update renamed the `esm` option to `mode`.

**Comment by AllNamesRTaken** [comment]
Thanks.
