### ISSUE TITLE
Is it possible for mjs to do `process.mainModule === module`?

### ISSUE THREAD

**Issue by ratson** [standard-things/esm#320]
I find https://github.com/standard-things/esm/issues/299 talking about exposing `process.mainModule`, but could not find an example using it.

When I tried `node -r esm main.mjs`
```js
import _ from 'lodash'

const { sum } = _

export default sum

if (process.mainModule === module) {
  console.log(sum([1, 2]))
}
```
it gives `ReferenceError: module is not defined`

Is this use case not supported?

**Comment by jdalton** [comment]
Hi @ratson!

What version of `@std/esm` or `esm` are you using?

**Comment by ratson** [comment]
How can I forget this, I am testing it with "^3.0.6".

**Comment by jdalton** [comment]
Thanks @ratson!

In `esm` the `.mjs` file is [locked down](https://github.com/standard-things/esm#features):
> :lock: `.mjs` files are limited to basic functionality without support for `esm` options.

So to enable this you'll need to use `.js`.

**Comment by ratson** [comment]
Thanks, @jdalton I got it working with `node -r esm main.js`.
Is that mean there is no equivalent for ESM?

**Comment by jdalton** [comment]
> Is that mean there is no equivalent for .mjs?

Correct. `.mjs` is not fully baked yet so it's support is limited. There is currently no `process.mainModule` support in `.mjs`.
