### ISSUE TITLE
misleading SyntaxError when esm used with Babel

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#322]
"SyntaxError: esm@3.0.6 is not enabled" can be misleading.

_reduced repro steps:_

index.js
```javascript
import.meta
```

```console
node -r esm -r @babel/register index.js
```

**important:** _@ babel/plugin-syntax-import-meta_ must not be loaded. not sure who's throwing the syntax error, babel or esm.

This regex seems to be part of the issue: https://github.com/standard-things/esm/blob/3a574ea08c19bd899755f4d652a8f0188a95deef/src/hook/module.js#L48

_edit: everything works fine with esm only:_
```console
node -r esm index.js
```

**Comment by jdalton** [comment]
Thank you @dnalborczyk!

Yes, confirmed it's that regexp! Patch incoming shortly.

**Comment by dnalborczyk** [comment]
thanks John!
