### ISSUE TITLE
Cannot import "jsonpath", which uses "Module#_compile()"

### ISSUE THREAD

**Issue by njam** [standard-things/esm#326]
It's the first time I hear about [jsonpath](https://github.com/dchester/jsonpath) and about `Module._compile()`. I'm not sure whether *esm* can do anything about this. The underscore in front of `_compile()` doesn't look promising..

Reproduce:
```console
$ node --version
v9.8.0

$ cd $(mktemp -dt)
$ npm install esm jsonpath
$ node -r esm --eval 'import jsonpath from "jsonpath"'

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at dirname (path.js:1331:5)
    at Object.<anonymous> (/tmp/tmp.p10pqgABuj/node_modules/jsonpath/lib/aesprim.js:15:11)
```

The code in question is here: [jsonpath/lib/aesprim.js](https://github.com/dchester/jsonpath/blob/master/lib/aesprim.js#L15).

Any ideas?
Feel free to close this again, if this is not something *esm* can/should fix.

**Comment by jdalton** [comment]
This is something we totally should be supporting, so you've found a bug with our `--eval` support. I'm guessing we aren't providing the `__filename` as needed.

**Comment by jdalton** [comment]
Ya, I found the issue (or cause) the `filename` is getting turned into `null` somewhere. Digging...

**Comment by jdalton** [comment]
[v3.0.8](https://github.com/standard-things/esm/releases/tag/3.0.8) is released 🎉

**Comment by njam** [comment]
Works like a charm. Thank you very much!
