### ISSUE TITLE
esm v3.x doesn't throw SyntaxError anymore for non-exising exports

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#327]
repro:

```javascript
// index.js
import { foo2 } from './bar'
```

```javascript
// bar.js
export const foo = true
```

```console
// with esm default options
node -r esm index.js
```

the std/esm v0.25.4 line still throws (tested with mode: "js")

**Comment by jdalton** [comment]
Hi @dnalborczyk!

This is part of the `cjs` interop. I can experiment with disabling this bit as I've been bit by not getting notified of missing exports too.

**Comment by dnalborczyk** [comment]
I thought I tried to turn off cjs interop for the above to test in v3 as well if I'm not mistaken. I might have to check that again ...

that would be a **REALLY** nice to have if technically feasible, otherwise it unfortunately removes one of the advantages of using esmodules :confused:

**Comment by jdalton** [comment]
[v3.0.8](https://github.com/standard-things/esm/releases/tag/3.0.8) is released 🎉
