### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by pokatomnik** [standard-things/esm#328]
Hello!
Thank you for this module, It's really great.
I have a question. Is this package ready for production?  Or shall I use this thing only for development?

**Comment by jdalton** [comment]
Hi @pokatomnik!

It's intended for both dev and [production use](https://github.com/standard-things/esm/blame/master/README.md#L3) 🙌

**Comment by jdalton** [comment]
For use in published packages you'll want to use the in-file API:
```
// Provide options as a parameter, environment variable, or rc file.
require = require("esm")(module/*, options*/)
module.exports = require("./main.js").default
```

**Comment by pokatomnik** [comment]
Thank you, It's wonderful!
