### ISSUE TITLE
Feature Request: add ability to override module resolution

### ISSUE THREAD

**Issue by kenotron** [standard-things/esm#331]
Flex point had been added in jest to allow for something like moduleNameMapper or moduleDirectories. In trying to integrate jest and esm in a largish codebase, I found that there's no way to directly override in esm. This is a feature request to allow for this as a flex point in esm as well to synchronize the settings of resolve logic between jest & esm when doing something like esm-jest.

**Comment by jdalton** [comment]
Hi @kenotron!

Just to be clear flex point isn't a library right? You're saying a flex point is in jest that allows it to do something like `moduleNameMapper` and `moduleDirectories`?

With `cjs` interop `esm` will use the same wiring that CJS uses so if it's overridable in CJS it should transfer to `esm`. That's where I'd like that kind of feature to stay. So if it's not working that way then that's something for us to dig into.

**Comment by kenotron** [comment]
flex point isn't a lib :) just a saying :)

It seems jest has some internal mapper functionality that isn't exposed in esm. I might have to now monkey patch esm to get this sort of thing. What I'm looking for is some way to do aliasing that is on par with jest, webpack or typescript... unfortunately it doesn't seem like truly in the spirit of this project, but having a hook would be pretty nice...

**Comment by jdalton** [comment]
There will eventually be loader hooks in Node for ES modules. We'll adopt those for sure. If you're looking to make something work today though. You should go down the path of making it work for CJS then seeing if `esm` can just hop on that.

**Comment by kenotron** [comment]
Trying to override the module._resolveFilename won't work with esm it seems
...

**Comment by kenotron** [comment]
The way one would go about doing this would be the same hooks that esm is doing really. However, esm takes over the resolution logic in a way that hides all the hook points as far as I can tell. What one would want to do with CJS is something like this: https://www.npmjs.com/package/module-alias

With esm, it seems I'll have to actually FORK it to expose the right hooks maybe... I'm still digesting this codebase, but I'm very new to it, so it'll take some time to find the right place to add the hook (frankly it would be nice to do it at the hook/module or hook/require)

**Comment by tilgovi** [comment]
My sense is that there's deliberately no hooks because `esm` is trying to bridge the gap to future Node behavior, not a tool that's around indefinitely to hook module loading.

I have had no problem using `esm` with `@babel/register` and `babel-plugin-module-resolver`. You can either run with `@babel/register` as your hook, then, or compile with babel before publishing and use `esm` in production without hooking the resolver further.

**Comment by tilgovi** [comment]
Apologies if I'm just lacking understanding of the details, though. I could see how maybe for a testing tool like jest it might be hard to register a hook before `esm`, depending on how things are invoked. I hope my comment helps.

**Comment by jdalton** [comment]
> Trying to override the module._resolveFilename won't work with esm it seems

I regressed something in `esm` is all. I'll fix it up.

**Comment by kenotron** [comment]
This is 💯. I'll be able to replace a bunch of transformer weirdness with
this in our pipeline!

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/b95fc469650b09daebb785d5edaf508200f7f613.

**Comment by kenotron** [comment]
I wanted to follow up! Aliasing now WORKS. See: 
https://github.com/kenotron/esm-jest/commit/624b9524ee698f5cbd16ee2481dc4cd0dec52e42
