### ISSUE TITLE
Does not work with native bindings

### ISSUE THREAD

**Issue by novemberborn** [standard-things/esm#332]
I'm trying to import https://github.com/cryptocoinjs/secp256k1-node. It exports bindings against a native module: https://github.com/cryptocoinjs/secp256k1-node/blob/master/bindings.js. Something goes wrong though when trying to call its exported methods.

With `test.js`:

```
import crypto from 'crypto'
import secp256k1 from 'secp256k1'

secp256k1.privateKeyVerify(crypto.randomBytes(32))
```

And `node -r esm test.js` I get a `TypeError: Illegal invocation`.

It works fine if I use `require()` instead.

**Comment by jdalton** [comment]
Thanks @novemberborn!

I found the issue. It was related to how we detect native methods. I have it fixed locally.

**Comment by novemberborn** [comment]
@jdalton great! I've installed a Git checkout and that seemed to work. Let me know when this is released and I'll double-check with the npm release. Thanks for the quick response!
