### ISSUE TITLE
v0.22.0 was the last version to work in electron 1.8.x

### ISSUE THREAD

**Issue by jsg2021** [standard-things/esm#333]
Tried updating some dependencies today, and electron won't start with 0.23+...  I'm trying to follow the init but electron is crashing when I try to inspect

**Comment by jdalton** [comment]
Hi @jsg2021!

Have you tried [`esm`](https://www.npmjs.com/package/esm)?

**Comment by jdalton** [comment]
Could you reproduce the issue with a minimum repro of `esm` + a simple hello world app.

**Comment by jdalton** [comment]
Ok, @jsg2021!

I have it fixed locally. I'll publish it tonight.

**Comment by jsg2021** [comment]
Thanks! Sorry i didn’t publish a repro. I’ll make sure to do that next time.

**Comment by jdalton** [comment]
No problem! Thanks for hammering on it!

**Comment by jdalton** [comment]
[v3.0.13](https://github.com/standard-things/esm/releases/tag/3.0.13) was released :tada:

**Comment by jdalton** [comment]
While I fixed the fail I didn't fix Electron [patching](https://github.com/electron/electron/blob/787bc8570382e98c4f204abff05b2af122e5a422/lib/common/reset-search-paths.js#L27-L37) `Module._resolveFilename` just right, so I'll follow-up in the morning with a more-proper patch (should make things work with `import` too).

**Comment by jsg2021** [comment]
awesome thanks!
