### ISSUE TITLE
Question/maybe-bug: importing named exports from commonjs not working?  

### ISSUE THREAD

**Issue by jsg2021** [standard-things/esm#334]
I updated my app to use esm@3.0.14 (was previously using @std/esm@0.22.0) and imports like `import {cpus} from 'os';` stopped working... i had `cjs: {namedExports: true, interop: true}` in my options... did this get removed?

More generally, is the overall movement to not allow named import syntax on cjs modules?

**Comment by jdalton** [comment]
Hi @jsg2021!

It should be working. I'll dig in.

**Comment by jdalton** [comment]
Ok, I double checked in Node and Electron and `import {cpus} from 'os';` works with zero configuration in `esm@3.0.14`. You might try deleting your `node_modules` folder and making sure things like your `package-lock.json` are updated.

**Comment by jsg2021** [comment]
Check out this: https://github.com/jsg2021/example-electron-app/
![screen shot 2018-03-29 at 12 13 11 pm](https://user-images.githubusercontent.com/577453/38102972-92def36a-334a-11e8-9e25-9c2435819663.png)

**Comment by jsg2021** [comment]
there is no lock in that project, just `npm i && electron .` will reproduce it.

**Comment by jdalton** [comment]
Found the issue.

You're using `.mjs` which is locked down in `esm`. Switch to `.js` and it should just work.

**Comment by jsg2021** [comment]
okay, thats what I was wondering. so, to clarify... `.mjs` files will not honor cjs options? And I'm inferring that the future official interop between the two system is heading towards not allowing named imports from cjs modules? Just trying to understand. :)

**Comment by jdalton** [comment]
> And I'm inferring that the future official interop between the two system is heading towards not allowing named imports from cjs modules? Just trying to understand. :)

No worries. The future interop hasn't been ironed out yet which is why it's locked down.
