### ISSUE TITLE
pm2 script start

### ISSUE THREAD

**Issue by dkebler** [standard-things/esm#335]
Having a bit of trouble getting pm2 to start my app.  Little help please.

First off this works fine
`/opt/wifi/server$ node -r @std/esm sbc`

But when try to run it form a pm2 config.js file it says it can't find the script.
```
    {
      name      : 'wifi-server',
      cwd       : '/opt/wifi/server',
      script    : 'sbc --node-args="-r @std/esm"',
      watch     : true
    }

`[PM2][ERROR] script not found : /opt/wifi/server/sbc --node-args="-r @std/esm"`

guess it's not really recognizing the `sbc.mjs` file maybe cause it's not really using @std/esm? and thus doesn't know what an .mjs file is.

Does @std/esm need to be loaded globally?  It's only in the node_modules folder of /opt/wifi/server.
but I thought setting the cwd would take care of that

**Comment by jdalton** [comment]
Hi @dkebler!

I haven't worked with a pm2 config (only command-line).
I'm guessing it has something to do with which directory the config is using to resolve packages.

This works for me
```shell
npx pm2 start main.js --node-args="-r esm"
```

*Note: btw `@std/esm` is discontinued in favor of `esm`.*

**Comment by jdalton** [comment]
It looks like the config [should have a `node_args` field](http://pm2.keymetrics.io/docs/usage/application-declaration/#general).
```
{
"node_args": "-r esm"
}
```

**Comment by jdalton** [comment]
The simple solution is to use `.js` for ESM to get things to just work with today's projects. `.mjs` is going to be the least working option since it's locked down and no `esm` options apply to it.
