### ISSUE TITLE
TypeError: Cannot assign to read only property 'loaded' of object '[object Object]'

### ISSUE THREAD

**Issue by pimlie** [standard-things/esm#337]
It seems that there might be an issue when you include the same file through different paths. I am testing a simple singleton pattern for a config class that should be accessible throughout my module and always refer to the same dataset.

But when I try my current setup I get the following error:
```js
    TypeError: Cannot assign to read only property 'loaded' of object '[object Object]'

      3 | module.exports = requireModule('./esmindex').default
      4 | 
      
      at node_modules/esm/esm.js:1:115758
      at node_modules/esm/esm.js:1:115775
      at module.exports.t.a (node_modules/esm/esm.js:1:157500)
      at module.exports.t.a (node_modules/esm/esm.js:1:115025)
      at module.exports.t.a (node_modules/esm/esm.js:1:145249)
      at Module.<anonymous> (node_modules/esm/esm.js:1:210719)
      at y (node_modules/esm/esm.js:1:135374)
      at Object.<anonymous> (test/common/index.js:5:18)
```

Probably better to show by example:
<details>
  <summary>index.js </summary>
  <p>

```js
// index.js
const requireModule = require('esm')(module, {})

module.exports = requireModule('./esmindex').default

```

  </p></details>

<details>
  <summary>esmindex.js</summary>
  <p>

```js
// esmindex.js
import Config from './config'
import Sub from './sub'

export default {
  Config,
  Sub
}

```

  </p></details>

<details>
  <summary>config.js</summary>
 <p>

```js
// config.js
class Config {
  init(data) {
    this.data = data
  }
}

export default new Config()
```
</p></details>
<details>
  <summary>sub/index.js</summary>
 <p>

```js
// sub/index.js
import { Config } from '../'

const configTest = () => {
  console.log(config)
}

export default configTest
```
</p></details>

**Comment by pimlie** [comment]
Never mind, this was of course caused by the `import { Config } from '../'` in `sub/index.js` which indeed makes the module loads twice. A direct include of the config class in sub was the solution: `import Config from '../config'`

**Comment by jdalton** [comment]
Hi @pimlie!

Could you create a repro repo for this. I'd like to dig into this scenario a bit more.

**Comment by pimlie** [comment]
Hi, thanks for digging in. Hopefully its not just an ID107 error of my doing ;)

Please check here: https://github.com/pimlie/repro-esm-337 When I run `node index.js` on this repo I get an export error. Not sure why, I dont have this error in my full project.
```
SyntaxError: ES Module 'file:///repro-esm-337/index.js' does not provide an export named 'Config'
```
When I run the jest test `./node_modules/.bin/jest test/esm.test.js` I get
```js
    TypeError: Cannot assign to read only property 'loaded' of object '[object Object]'

      1 | const requireModule = require('esm')(module, {})
      2 | 
    > 3 | module.exports = requireModule('./esmindex').default
      4 | 
      
      at node_modules/esm/esm.js:1:115758
      at node_modules/esm/esm.js:1:115775
      at module.exports.t.a (node_modules/esm/esm.js:1:157500)
      at module.exports.t.a (node_modules/esm/esm.js:1:115025)
      at module.exports.t.a (node_modules/esm/esm.js:1:145249)
      at Module.<anonymous> (node_modules/esm/esm.js:1:210719)
      at y (node_modules/esm/esm.js:1:135374)
      at Object.<anonymous> (index.js:3:18)
```

**Comment by jdalton** [comment]
Hi @pimlie!

There is a bug here. The bug is that the state wasn't being shared when Jest was used so the error didn't occur in it. The error is because you're calling the bridge file from within the modules you're bridging, `sub/index.js` importing the `../index.js` bridge, this creates a circular reference which presents itself as the initial `../index.js` load as not having a populated `module.exports` yet since `sub/index.js` hasn't loaded to populate it which is why you get the error
```
ES Module 'file:///repro-esm-337/index.js' does not provide an export named 'Config'
```

A have a fix locally so you get the same error when running Jest.

**Comment by pimlie** [comment]
@jdalton Thank you for the quick fix, can confirm the issue is solved :+1:
