### ISSUE TITLE
Should not be using `require.extensions`

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#35]
`import` is picking up and using `require.extensions`. 

```js
// entry.js
require.extensions['.coffee'] = require.extensions['.js'];
require('@std/esm');
require('./a');
```

```js
// a.mjs
import 'coff.coffee';
```

```js
// coff.coffee
process.exit(1);
```

**Comment by jdalton** [comment]
Does `import` just accept `.js` and `.mjs` ?

**Comment by bmeck** [comment]
Only the files listed in the EP, https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#3313-file-search . never defers to `require` etc.

**Comment by jdalton** [comment]
Ah so `".mjs", ".js", ".json", ".node"`. 👌
