### ISSUE TITLE
The ESM option 'mode' is invalid. Received 'cjs'

### ISSUE THREAD

**Issue by motss** [standard-things/esm#354]
Is there a way to debug this? I kept having this issue after upgrading to `esm` from `@std/esm`.

### package.json

```json
...
"scripts": {
  "debug": "node --inspect -r esm dist/index.js"
},
...
```

### Error

```sh
Error: The ESM option 'mode' is invalid. Received 'cjs'
    at Object.Module._extensions..js (module.js:660:10)
```

**Comment by jdalton** [comment]
Hi @motss!

Make sure you unset the `ESM_OPTIONS` environment variable if you've set it and double check your configs (in your package.json or .esmrc files).
