### ISSUE TITLE
import.meta can not be used in if statement

### ISSUE THREAD

**Issue by ratson** [standard-things/esm#356]
esm version: 3.0.15

Run `node -r esm main.mjs` with content
```js
if (Array.isArray(import.meta)) {
}
```

Get this error
```
if (Array.isArray(import.meta)) {
                  ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
```

**Comment by jkrems** [comment]
Unrelated note on this code specifically: That `if` condition will always be false. Doesn't invalidate that it shouldn't be a `SyntaxError`. :)

**Comment by jdalton** [comment]
Thanks @ratson!
