### ISSUE TITLE
Snapshotting CJS exports

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#36]
Dunno if this one has a sane solution without punching `require('module').Module.prototype.load` pretty hard...

https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#491-es-will-not-honor-reassigning-moduleexports-after-evaluation

```js
// entry.js

require('@std/esm');
require('./mutates');
global.incr();
require('./a')
```

```js
// a.mjs
import assert from 'assert';
import v from './mutates';
assert.strictEqual(v, 1);
```

```js
// mutates.js
global.incr = () => module.exports++;
module.exports = 1;
```

**Comment by jdalton** [comment]
Thanks @bmeck!

We'll need to add a test for this for sure.

**Comment by jdalton** [comment]
Ok checking back, we seem to snapshot appropriately when running within the hook. The example presented above is running in the bridge file which is before rules can be imposed. I'll be adding a round of unit tests over the next couple of days to solidify support.

**Comment by bmeck** [comment]
Different example not using the bridge file:

```js
// a.mjs
import b from './b';
console.log('a', b); // prints 1
import('./c');
```

```js
// b.js
module.exports = 1;
process.nextTick(()=>module.exports++);
```

```js
// c.mjs
import b from './b';
console.log('c', b); // prints 2
```

**Comment by jdalton** [comment]
Thanks! That's super interesting!
