### ISSUE TITLE
Problem when importing a module in two different ways

### ISSUE THREAD

**Issue by eole1712** [standard-things/esm#361]
Hi there,

### Description
I have an import problem when I try to use a package that has a dependency in common with my own code. The problem comes from the fact that I do my import via esm and module via babel's transpiled code.

I finally managed to identify and isolate the problem, I will explain it to you.

### Example

Okay, let's start with a basic code where I import bluebird and try to access the map method.

```
import bluebird from "bluebird";
console.log(bluebird.default.map);
```

I can execute this code with `node -r esm` without problem.

I'm transpillating now this code with https://babeljs.io/repl : 
<img width="1439" alt="screen shot 2018-04-12 at 14 19 13" src="https://user-images.githubusercontent.com/11462388/38676818-844ae1fc-3e5c-11e8-9c9c-d3a992d8b153.png">
[src](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=JYWwDg9gTgLgBAIwDYFcCmDhQCZwGZQQhwBEy6mOJA3AFC0DGEAdgM4RJoB0SEA5gApyGLNi7Y0eAIYokMLiClgAlHSA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=6.26.0&envVersion=)

Same, I can execute this code with `node -r esm` without problem.

The problem is that if I put these two parts of code in two different files and import these two files into my index.js in any order, when executing via `node -r index.js` I have the following error : `Cannot read property 'map' of undefined ` which means my bluebird.default is undefined in the transpiled version of the code.

I created a public repository to isolate the bug, if you want to try to reproduce it, I hope it will help you !
https://github.com/eole1712/esm-require-with-and-without-babel

### My environment 
esm version: 3.0.17
node version: 8.11.1
npm version: 5.5.1

Please tell me if you need more information or my help to try to understand / fix the problem. 😄

**Comment by dnalborczyk** [comment]
when you `import x from bluebird` with esm, x is already the exported `default`

```javascript
import bluebird from 'bluebird'

bluebird.default // undefined
bluebird.default.map // throws
```

it's just a shorter (alternative) syntax of doing:
```javascript
import { default as foo} from 'bluebird'
foo // default value
```
or
```javascript
import * as bar from 'bluebird'
bar.default  // default value
```

**Comment by jdalton** [comment]
Hi @eole1712!

> Okay, let's start with a basic code where I import bluebird and try to access the map method.
```js
import bluebird from "bluebird";
console.log(bluebird.default.map);
```

I can't. I get an error
```
node -r esm foo.js
file:///Users/jdalton/projects/esm-require-with-and-without-babel/foo.js:1
TypeError: Cannot read property 'map' of undefined
```

As @dnalborczyk mentioned it looks like your imports are just a bit off.
If you change your repro repo code to 
```js
export default () => bluebird.map;
```
and the equiv Babel form your repro repo code will work.
