### ISSUE TITLE
Option to strip shebang

### ISSUE THREAD

**Issue by mk-pmb** [standard-things/esm#365]
Hi! I'd like to `esmRequire()` files that are valid ESM except for the first line, which happens to be a shebang (starts with `#!` and is meant as a line comment). I'd like even more if this ability could propagate to my `esmRequire()`-d files' import statements, dynamic imports and (in case of CJS modules) `require()`s.
Is there/ could you add an option to strip shebangs from the source, and/or to configure a custom pre-parse source transform function?

Update: For unknown reasons I can't reproduce the error. Now instead it looks like ignoring shebang is the default behavior. If so, could you explain it in the readme?

**Comment by jdalton** [comment]
Hi @mk-pmb!

Yes, shebangs are ignored. This is nothing new in Node-land so not worth documenting.
