### ISSUE TITLE
esm not working when referencing a file in a different package

### ISSUE THREAD

**Issue by davidgilbertson** [standard-things/esm#366]
Note: after writing out the below I resolved the issue by making esm the same version in both repos, but still it's not ideal that the app might now break if the esm versions don't match.

----

I have two apps in the same repo. `app1` and `app2`. Both of them have `esm` installed (and listed in their respective `package.json` files).

I have a file `constants.js` that uses `export` that I would like to share between the two.

If I have `constants.js` in the `app1` directory and import it like `import constants from './constants.js'` then everything works fine.

Now, if I move that file into `app2` and update my import to `import constants from '../app2/constants.js'` I get the error:
```
/Users/davidg/www/mono/app2/constants.js:5
export default constants;
^^^^^^

SyntaxError: esm@3.0.16 is not enabled for /Users/davidg/www/mono/app2/constants.js
    at new Script (vm.js:51:7)
    at Object.Module._extensions..js (module.js:671:10)
```

There definitely isn't a syntax error, because by simply moving the file into a directory that has a package.json file with `esm`, it will fail. Moving it out again will work.

In fact, I can go into `app2/package.json` and just delete the `esm` dependency (not even uninstall it) and the import will then work.

This happens if I require `esm` using `-r esm` in my npm script, *or* by using `require('esm')`.

Does this mean esm is looking for a parent `package.json` file relative to the file being imported, then something goes wrong because it's a different package?

Is this a use case that even should be supported? (I'd like it to be :))

**Comment by jdalton** [comment]
Hi @davidgilbertson!

A repro is worth a thousand words (or what ifs). If you could provide a simple repro repo I can dig in more. Thanks!

**Comment by davidgilbertson** [comment]
I was hoping to. I'll plea the standard copout answer of *I was busy at work*.

@dnalborczyk I had 3.0.16 in `app1` and `3.0.18` in `app2`. Updating `app2` to `3.0.18` fixed it.

**Comment by jdalton** [comment]
@davidgilbertson 
> I was hoping to. I'll plea the standard copout answer of *I was busy at work*.

Cool. Thanks, no rush.

> I had 3.0.16 in `app1` and `3.0.18` in `app2`. Updating `app2` to `3.0.18` fixed it.

Were you pinning to specific versions or using `~` or `^`?

**Comment by jdalton** [comment]
[v3.0.20](https://github.com/standard-things/esm/releases/tag/3.0.20) is released :tada:
