### ISSUE TITLE
[question] Investigate using cherow instead of acorn?

### ISSUE THREAD

**Issue by calebboyd** [standard-things/esm#367]
I noticed there is a particular concern for the size and speed of esm. I've been following [cherow](https://github.com/cherow/cherow) for a while and version 1.4 just landed. It appears to have a lot of performance (and size) advantages that might be worth exploring. I'm not super familiar with all the customization done here with acorn, so this is more of a fyi.

**Comment by jdalton** [comment]
Thanks @calebboyd!

You're right that we focus on perf and size. I'm aware of `cherow` but haven't looked at it in several months. We highly customize Acorn to remove unneeded checks and expand syntax support. If someone were to experiment that would be super appreciated.
