### ISSUE TITLE
Compatibility with Browserify?

### ISSUE THREAD

**Issue by 59023g** [standard-things/esm#371]
Any luck with bundling? I am working on it now.

**Comment by jdalton** [comment]
I haven't tried. The `create-esm` initializer will set the `module` field in the `package.json`. I was on the fence about setting the `browser` field too as that's presuming a bit more. But the gist would be the same. You set your `browser` field in the `package.json` to the `main.js` ESM entry module (using the usage example as a reference)_.

**Comment by 59023g** [comment]
Hey, thanks for the pointer @jdalton 

This worked `node_modules/.bin/browserify --entry ./src/index.js --node --no-bundle-external --ignore-missing -g ascjsify > build/bundle.js` using ascjsify, but not for the browser modules. 

So I need to step back and think on this. 

Will fork and PR if relevant. 

Peace

**Comment by jdalton** [comment]
@59023g Great, thank you!
