### ISSUE TITLE
Question about singleton

### ISSUE THREAD

**Issue by ratson** [standard-things/esm#373]
I am not sure if this is a bug or a feature, requiring `.mjs` and `.js` is possible.
I have created a repo to demo the problem, https://github.com/ratson/bug-esm-singleton
It can be run with the following commands,
```
npm install
node -r esm main.mjs
```

While the following output make more sense
```
singleton.mjs
```

It prints 
```
singleton.js
singleton.mjs
```

Is this an expected output for ESM in Node?

**Comment by dnalborczyk** [comment]
> I am not sure if this is a bug or a feature

might be actually both :smiley: depending on how you look at it.

a lot of things regarding module loading in node are still in flux, but as it stands, you [can't require 'mjs' file extensions](https://nodejs.org/api/esm.html#esm_unsupported) in node itself.

you can try it out yourself:

```javascript
// consumer.js
require('./singleton.mjs')
```
and run:
```console
node --experimental-modules main
```

throws:
```console
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /path/bug-esm-singleton/singleton.mjs
```

the part which might contribute to more confusion is that the esm loader allows requiring mjs file extensions, and you end up with 2 singletons.

```javascript
// consumer.js
require('./singleton.mjs')
```
and run:
```console
node -r esm main
```
prints:
```
singleton.mjs
singleton.mjs
```

there's a certain order how file-extensions are resolved and rules what they can contain. e.g. mjs files can't contain cjs modules (require/module.export). cjs and es6 modules also create their own scope, es6 modules use bindings...

supporting js file extensions for ES6 modules is a feature of the esm-loader, and so far, not supported by the experimental loader from node itself.

though there's some light on the horizon with a working group for node modules now, and hopefully things will progress in the right direction.

Hopefully 'mjs' will be an experimental thing of the past and quickly forgotten!
