### ISSUE TITLE
Moving from @std/esm  and now getting  SyntaxError: Missing export from a cjs module

### ISSUE THREAD

**Issue by dkebler** [standard-things/esm#375]
I had a whole library of modules working with `@std/esm`.   I am now moving to your lastest just `esm`

If I understand correctly I don't need to set `cjs` any more but when npm/yarn comes across a module that loaded fine before now I get

```
file:///home/david/AllData/hacking/active-dev-repos/uci/uci-base/node_modules/@uci/mqtt/src/client.mjs:1
SyntaxError: Missing export 'connect' in ES module: file:///home/david/AllData/hacking/active-dev-repos/uci/uci-base/node_modules/async-mqtt/index.js
```
here is the module I am trying to import.   You can see it `module.exports` the module in question.
https://github.com/mqttjs/async-mqtt/blob/master/index.js

In my module I am importing like this.
`import { connect } from 'async-mqtt'`

which worked just fine with `@std/esm` and  `@std/esm: cjs` in my package.json.

Just need some help sorting out what has changed and what to do about it.

Even though I understand now cjs is "100%" on by default I tried adding `"esm":{"cjs":true}` to my package.json but it didn't help.

**Comment by jdalton** [comment]
Hi @dkebler!

Thanks for taking the upgrade!

With `esm` the `.mjs` file is [locked down](https://github.com/standard-things/esm#features)
> :lock: `.mjs` files are limited to basic functionality without support for `esm` options.

This is because it's experimental and I don't want to expand functionality to it that may not exist. If you change your extension to `.js` things should work.

**Comment by dkebler** [comment]
I went down the .mjs rabbit hole when I starting using @std/esm.  I have over a dozen modules (and their files) that use the extension .mjs at this point.   So you can see that I don't want to go "backwards".   Would it be better just to stick with @std/esm?  Not grokking why esm won't work with .mjs files I thought that was the whole point?

**Comment by jdalton** [comment]
The intent of `@std/esm` was to allow folks to opt-in to cjs interoperability. The problem is I found it was giving folks a false sense of security or comfort with `.mjs`. The `.mjs` file may or my not expand its cjs interoperability. Since that is the official path for support expanding it beyond what's allowed can cause compat issues down the road. So by flipping it and allowing interop in `.js` _(as the ecosystem already does)_ it allows `.mjs` to grow, however it will. This is also how others like Webpack and Babel 7 treat `.mjs` _(locked down)_. I wouldn't switching to `.js` as a step back. It's like you stepped into an alternate universe with `.mjs` which may or may not materialize.

**Comment by dkebler** [comment]
ok so if I go though all my modules and change every .mjs to .js I won't have to go "back to the future" later ever to .mjs??  If so no problem I'll do it.   

If I understand you correctly your `esm` can now tell the difference between esm coded modules and cjs modules without having to depend on the file extension? Is that what you mean by interoperability?  If so fine, super great a no brainer for me all files to `.js`

**Comment by jdalton** [comment]
Correct with `esm` the `.js` file will always have :100: interoperability enabled by default _(it's configurable)_. As `.mjs` develops `esm` will expand support to align with whatever Node does.

`.js` is the way to go for compatibility and interoperability for sure.

**Comment by dkebler** [comment]
Just reporting....I switched to all .js on a couple modules and now my tests all pass.  Thx for clarification.
