### ISSUE TITLE
instanceof check failing as of 3.0.27

### ISSUE THREAD

**Issue by chadxz** [standard-things/esm#378]
In my package [awry](https://github.com/chadxz/awry) I have some `instanceof` checks in my tests. These aren't terribly important, but I found it odd that they were passing in 3.0.26 of `esm` and failing in 3.0.27.

Any idea why that might be?

specifically these tests:
https://github.com/chadxz/awry/blob/04c882f3864e2b1749d0823452be72e9e3e90fe0/test/api/index.spec.mjs

**Comment by jdalton** [comment]
No need for a repro. I narrowed it down to https://github.com/standard-things/esm/commit/c36988de6d3ffc5d85dd81a87974b4cf50b3c922.

**Comment by jdalton** [comment]
Fixed it locally changing 
```
if (isUnexposed &&
    extname(filename) === ".mjs") {
```
to
```js
if (isUnexposed ||
    extname(filename) === ".mjs") {
```

I'll have a new released published by this afternoon.

**Comment by chadxz** [comment]
Cool. thank you

**Comment by jdalton** [comment]
Patch https://github.com/standard-things/esm/commit/11614f1c505180407b0668412145731bd4a6d36d.
