### ISSUE TITLE
HTMLCommentOpen stops working in .js files

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#38]
Strangely, HTMLCommentClose (`-->`) appears to work.

```js
// entry.js
<!--
require('@std/esm');
require('./a')
-->
```

```js
// a.js
<!--
-->
```

**Comment by jdalton** [comment]
Thanks @bmeck, I think?

Whoah HTMLComments valid in Node?
This may be an acorn limitation.

**Comment by bmeck** [comment]
HTMLComments is valid in all Script goals

**Comment by jdalton** [comment]
Ah related to https://github.com/ternjs/acorn/issues/572.

**Comment by jdalton** [comment]
It looks like they aren't allowed in module code (or don't have the same meaning).

**Comment by bmeck** [comment]
Correct, they are not valid in Module code, but this is hitting *all* `.js` files not ones in the Module goal

**Comment by jdalton** [comment]
Ah, ok!

**Comment by jdalton** [comment]
Fixed by https://github.com/standard-things/esm/commit/65cc9cf6c576035b8dd67bee8c49d48b9cc22809.
I'll be adding a round of unit tests over the next couple of days to solidify support.
