### ISSUE TITLE
private fields in node 10 with harmony flag

### ISSUE THREAD

**Issue by neyasov** [standard-things/esm#381]
```// test1.mjs
class A {
  #x = 1

  constructor(x) {
    this.#x = x
  }
  x() {
    return this.#x
  }
}
```
`node --harmony ./test.mjs` No errors
`node --harmony -r esm ./test.mjs` SyntaxError: Unexpected character '#'

**Comment by jdalton** [comment]
Hi @neyasov!

Yep, it's on my todo.

**Comment by jdalton** [comment]
[v3.0.30](https://github.com/standard-things/esm/releases/tag/3.0.30) is release 🎉
