### ISSUE TITLE
Unable to mock builtin modules like `fs`

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#382]
Hi again. In the wake of https://github.com/standard-things/esm/issues/379.

For example this one works with `mockRequire('fs', { readFile: 123 })`:

```js
const { readFile } = require('fs')
module.exports = readFile
```

this one doesn't:

```js
export { readFile as default } from 'fs'
```

or even:

```js
import fs from 'fs'
export default fs.readFile
```

**Comment by jdalton** [comment]
Doh, yap I can see we're in the code I missed it :)

**Comment by jdalton** [comment]
Good news!

It looks like I have this working locally.
I'll commit a test and patch soon.

**Comment by jdalton** [comment]
[v3.0.30](https://github.com/standard-things/esm/releases/tag/3.0.30) is release 🎉
