### ISSUE TITLE
Unable to unmock an import

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#383]
Sorry :)

`mockRequire.stop()` doesn't work, so I tried to narrow it down manually:

```js
// file.js
export default 'file'
```

```js
// test.js
import { resolve } from 'path'
import Module from 'module'

const fullPath = resolve('./file')
const originalLoad = Module._load

Module._load = (request, ...rest) => {
  if (request === './file') {
    console.log('!!!')

    return {
      default: 'mock'
    }
  }

  return originalLoad(request, ...rest)
}

import('./file')
  .then(console.log)
  .then(() => {
    Module._load = originalLoad

    delete Module._cache[fullPath]
    delete require.cache[fullPath]

    return import('./file')
  })
  .then(console.log)
  .catch(console.error)
```

```sh
$ node -r esm test.js
```

Same "mock" log both times, one "!!!" log, feels like some tough internal cache.

**Comment by deepsweet** [comment]
Also it's not possible to "remock" already mocked things, which I believe has the same reason.

**Comment by jdalton** [comment]
Good news!

It looks like I have this working locally.
I'll commit a test and patch soon.

**Comment by jdalton** [comment]
Closed by https://github.com/standard-things/esm/commit/ce475285f4d243c93068d87e4fba39548be31552.

**Comment by jdalton** [comment]
[v3.0.30](https://github.com/standard-things/esm/releases/tag/3.0.30) is release 🎉
