### ISSUE TITLE
Import relative to project root

### ISSUE THREAD

**Issue by MattSturgeon** [standard-things/esm#384]
(If not already) it would be awesome to have the option to import relative to the project root. With require there are a few options like the [`rfr`](https://www.npmjs.com/package/rfr) package or binding to `require.main` and with babel you have plugins like [this](https://github.com/entwicklerstube/babel-plugin-root-import) available.

Anything along these lines to reduce the amount of `../../../` in imports would be appreciated!

**Comment by jdalton** [comment]
Hi @MattSturgeon!

There are lots of ways to handle this and baking each and every one into `esm` doesn't seem like the right call. Instead you can use `rfr` or babel with `esm` to load ESM modules if you so choose.

**Comment by MattSturgeon** [comment]
Apologies if I wasn't clear: I'm asking if it is possible to resolve paths relative to the project root using `import` syntax and without preprocessors like babel. `rfr` would be a different syntax, as it is built on top of commonjs.

Is there a way to customize path resolution within esm? I can't see anything obvious in your README.

**Comment by MattSturgeon** [comment]
So if I want to use `import thing from '/thing'` esm syntax I am stuck with standard path resolution and the only option for root base resolution is commonjs syntax?

**Comment by MattSturgeon** [comment]
Setting `NODE_PATH=.` and `cjs.paths: true` is a good enough solution for now.

**Comment by oles** [comment]
Checked out https://github.com/ilearnio/module-alias ?
