### ISSUE TITLE
Unable to mock module with inline object

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#386]
The example from #383 just stopped giving any logs since 3.0.30.

Narrowed down, no logs:

```js
import mock from 'mock-require'

mock('./file', {
  default: 123
})

import('./file')
  .then(console.log)
  .catch(console.error)
```

Fine:

```js
import mock from 'mock-require'

//mock('./file', {
//  default: 123
//})

import('./file')
  .then(console.log)
  .catch(console.error)
```

Also fine:

```js
import mock from 'mock-require'

mock('./file', './file2')

import('./file')
  .then(console.log)
  .catch(console.error)
```

So it seems like it works only with "file-to-file" mock and not with inline objects.

**Comment by deepsweet** [comment]
Also it feels like unmocking doesn't work too if module was mocked with an object, will test it more...

**Comment by jdalton** [comment]
@deepsweet Thanks for continuing to dig into this. I didn't know `mock-require` allowed specifying an object. I have it working locally. I'll add it and a test and release _(probably today)_.

**Comment by jdalton** [comment]
[v3.0.31](https://github.com/standard-things/esm/releases/tag/3.0.31) is released 🎉
