### ISSUE TITLE
electron ES module import in renderer not following esm package resolution

### ISSUE THREAD

**Issue by devingfx** [standard-things/esm#387]
Hi!

I'm using `esm` with electron. The nodejs part of loading ES module works great but I can't figure out how to make the renderer process (aka BrowserWindow) to use esm also for module resolution.

I want to be able to unify the way scripts are loaded because it's a bit weird to be able to use `import` syntax in main process but still having to use `require` in the renderer process!
```html
<script>
const { remote } = require( 'electron' )
</script>
```
so I want to be able to:
```html
<script type="module">
import { remote } from 'electron'
</script>
```
but because the chromium process is able to use ES module imports, it use the browser path resolution and so I have this error:
`Uncaught TypeError: Failed to resolve module specifier 'electron'`

Is there a way to tell the `BrowserWindow` class to use esm instead? Or a way to teach the browser where to import 'global' module names?

I finally tried to import electron from the node_modules folder directly:
```html
<script type="module">
import { remote } from './node_modules/electron/index.js'
</script>
```
but now I have this error:
`Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.`

**Comment by devingfx** [comment]
Maybe something like this in `index.js` (bootstrap file) to enable `esm` to modify the require function that stand in BrowserWindow instances:
```javascript
const { BrowserWindow } = require('electron')
BrowserWindow.prototype.require = require("esm")( module/*, options*/ )

require = require("esm")( module/*, options*/ )
module.exports = require( `./${require('./package.json').module}` || "./main.js" )
```
This is just a way to illustrate the idea because the require method does not exist and the renderer module is to be initialized for each instance instead of here...

**Comment by Tundon** [comment]
So this could be solved with a simple preload script (when creating BrowserWindow, they have an option to pre-load a script), with a simple script as below:
```javascript
var _require = require("esm")(module)

process.once('loaded', () => {
  global.require = _require
})
```
And in your `index.html` file, require your main script in renderer
```html
<script>
  require('path/to/your/renderer/script.js')
</script>
```
Now that `script.js` can use whatever `esm` has brought us:
```javascript
import '...'
export ...
```
@jdalton BrowserWindow actually integrates node environment into its javascript environment. Hopefully next time if anyone asks related again, this solution would help. And thanks for the great work, I love Electron + ESM. Cheers.

**Comment by devingfx** [comment]
Hey! I just had an idea:

Is it posible to give the overrided `require` some string of ecmascript to execute?

Like so it can be implemented this way:

pre-load script:
```javascript
var _require = require("esm")(module)

process.once('loaded', () => {
  global.require = _require
  [...document.scripts]
    .filter( s=> s.type == "esm" )
    .map( s=> _require.fromString(s.textContent) )
})
```
html pages:
```html
<script type="esm">
import { BrowserWindow } from 'electron'
</script>
```

**Comment by Invincibl-e** [comment]
> Hey! I just had an idea:
> 
> Is it posible to give the overrided `require` some string of ecmascript to execute?
> 
> Like so it can be implemented this way:
> 
> pre-load script:
> 
> ```js
> var _require = require("esm")(module)
> 
> process.once('loaded', () => {
>   global.require = _require
>   [...document.scripts]
>     .filter( s=> s.type == "esm" )
>     .map( s=> _require.fromString(s.textContent) )
> })
> ```
> 
> html pages:
> 
> ```
> <script type="esm">
> import { BrowserWindow } from 'electron'
> </script>
> ```

Have you found a better way to solve this problem? It looks like this code is no longer available.

**Comment by devingfx** [comment]
Nope
