### ISSUE TITLE
Unable to unmock nested import

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#389]
```js
// file.js
export { default } from './file2'
```

```js
// file2.js
export default 'file2'
```

```js
// test.js
import Module from 'module'

const originalLoad = Module._load

Module._load = (request, ...rest) => {
  if (request === './file2') {
    console.log('!!!')

    return {
      default: 'mock'
    }
  }

  return originalLoad(request, ...rest)
}

import('./file')
  .then(console.log)
  .then(() => {
    Module._load = originalLoad

    return import('./file')
  })
  .then(console.log)
  .catch(console.error)
```

```sh
$ node -r esm test.js
```

Works as expected with `request === './file'` instead of `request === './file2'`.

**Comment by jdalton** [comment]
Hi @deepsweet!

You'll have to clear the module cache:
```js
  .then(() => {
    Module._load = originalLoad
    Reflect.deleteProperty(Module._cache, path.resolve('./file.js'))
    return import('./file')
  })
```
This will log
```
!!!
[Module] { default: { default: 'mock' } }
[Module] { default: 'file2' }
```

**Comment by deepsweet** [comment]
It doesn't log that :(

**Comment by jdalton** [comment]
![](https://user-images.githubusercontent.com/4303/39741226-e887df9e-524d-11e8-815c-6dc3523c0f95.gif)

**Comment by deepsweet** [comment]
Ok, now I'm really confused.

Even with latest Node 10 I have:

```
$ node -r esm tmp/
!!!
[Module] { default: { default: 'mock' } }
[Module] { default: { default: 'mock' } }
```

**Comment by deepsweet** [comment]
Are you sure that I don't need something from master pushed there after 3.0.31?

**Comment by deepsweet** [comment]
![esm](https://user-images.githubusercontent.com/266822/39742676-e416834e-528d-11e8-8bfe-ca6d2cf5904a.gif)

Hope that I'm not insane.

**Comment by deepsweet** [comment]
So I checked out this repo and tried it like you did, with `-r ./index.js`. Same:

```
!!!
[Module] { default: { default: 'mock' } }
[Module] { default: { default: 'mock' } }
```

**Comment by jdalton** [comment]
Can you create a simple repro repo. That would help see what the differences in our setups are.

**Comment by deepsweet** [comment]
Oh my god. While creating a repo I found the issue (there is no way I can explain it though). If the files are in any folder then it doesn't work. If files are just in the root then it's fine.

![esm](https://user-images.githubusercontent.com/266822/39761079-a48d17f4-52c6-11e8-9408-ba838eba3faf.gif)

Files are identical.

**Comment by deepsweet** [comment]
https://github.com/deepsweet/esm-test

**Comment by jdalton** [comment]
Repro repos are the best! 😋

**Comment by deepsweet** [comment]
Do you have any idea? :)

**Comment by jdalton** [comment]
Yep!

This is because in my example of clearing the cache I was using a non-robust approach to demonstrate that clearing the cache is needed. In your example using `path.resolve('./file.js')` will use the current working directory as it's base. Since that is the root of the repo (in this repro) it's path will not be of the file.js in folder but of file.js in root and so it will delete the incorrect entry (or empty entry).
