### ISSUE TITLE
`await` is not a valid BindingIdentifier

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#39]
https://tc39.github.io/ecma262/#sec-identifiers-static-semantics-early-errors

```js
// a.mjs
let await = 1;
```

**Comment by jdalton** [comment]
Thanks @bmeck!

It seems odd that acorn missed this. I'll redirect to them.
Moved to https://github.com/ternjs/acorn/issues/581.

**Comment by jdalton** [comment]
Fixed by https://github.com/standard-things/esm/commit/65cc9cf6c576035b8dd67bee8c49d48b9cc22809.
I'll be adding a round of unit tests over the next couple of days to solidify support.
