### ISSUE TITLE
Unable to unmock nested import of builtin module

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#390]
[repro repo](https://github.com/deepsweet/esm-issue) ©

```sh
$ node -r esm index.js
```

**Comment by deepsweet** [comment]
Also, why logs says `{ default: 123 }` and not `{ readFile: 123 }`?

**Comment by jdalton** [comment]
Hi @deepsweet!

This is still a cache clearing issue.
You can see that if you remove the entire cache it will report the correct results.
```
Module._cache = {}
```

**Comment by deepsweet** [comment]
So clearing entire cache is the only way? I tried to clear cache for specific file.

**Comment by deepsweet** [comment]
This helps:

```js
Reflect.deleteProperty(Module._cache, path.resolve('./file.js'))
Reflect.deleteProperty(Module._cache, path.resolve('./file2.js'))
```

But for example if I write my own mocking library then how do I know these related files?

**Comment by deepsweet** [comment]
Ok, I'm going to iterate over cache and look for related parents. Sorry for all the noise, it looks like I finally have no more issues.

**Comment by deepsweet** [comment]
Just to let you know that I ended up with my own ["ESM mocking library"](https://github.com/deepsweet/mocku) which I will keep in sync with `esm` loader because that's my personal use case now. Thanks for all the help, I can finally write tests.

**Comment by jdalton** [comment]
Awesome @deepsweet!
