### ISSUE TITLE
instanceof for builtins not working as expected in 3.0.32

### ISSUE THREAD

**Issue by marklu** [standard-things/esm#391]
It appears that esm@3.0.32 introduced a bug on how `instanceof` is handled with NodeJS builtins.

```
const EventEmitter = require('events')
const Stream = require('stream').Stream

const myObject = new Stream()
console.log(myObject instanceof EventEmitter)
/* true in vanilla Node.js, false with esm 3.0.32 */
```

This works as expected with esm@3.0.31.

**Comment by jdalton** [comment]
Thanks @marklu!

**Comment by jdalton** [comment]
[v3.0.33](https://github.com/standard-things/esm/releases/tag/3.0.33) is released :tada:
