### ISSUE TITLE
How to use with builtin modules?

### ISSUE THREAD

**Issue by Nicholi** [standard-things/esm#393]
I am completely new to the ESM space, and just trying to make sense of what to do. From your video presentation I took it that you can make an ES module that can be consumed by both CJS/ESM with no special dependencies for the consuming application. Only my module requires (lol) 'esm', not the consuming application... unless thats totally wrong? Everything seems to work fine, until the module attempts to utilize a node builtin module, like say 'path'.

The consuming application is throwing a curious error, which I can't make sense of.
> file:///home/nicholi/Documents/node/testesm/node_modules/@myscope/testesm/main.js:1
> TypeError: Cannot read property 'options' of null
>     at Object.Module._extensions..js (module.js:663:10)

I am assuming I'm missing something obvious... or one of the config options (but I have no idea which flags to turn on/off). Here is a barebones sample of what I'm trying to do. Both the ESM module (where it is loading in 'path'), and a consuming application loading it via normal CJS.

**ES Module**
package.json:
```
{
  "name": "@myscope/testesm",
  "version": "1.0.0",
  "main": "index.js",
  "module": "main.js",
  "dependencies": {
    "esm": "^3.0.33"
  }
}
```
index.js - totally standard
```
'use strict';

// Set options as a parameter, environment variable, or rc file.
require = require('esm')(module/*, options*/);
module.exports = require('./main');
```
main.js
```
// no idea which of these notations i should be using, none of them work
import path from 'path';
const {basename} = path;
//import * as path from 'path';
//const path = require('path');

export const a = 'ayyyyyy';

export default class Empty {
  constructor() {
  }

  test() {
    console.log('yo');
  }

  test2() {
    console.log(path.basename('/this/path/isnt/really.real'));
  }
}
```

**CONSUMING APPLICATION**
package.json:
```
{ 
  "name": "runesm",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "@myscope/testesm": "^1.0.0"
  }
}
```

index.js:
```
// loading as CJS (?)
const {default: Empty, a} = require('@myscope/testesm');

console.log('const a:', a);

let testEsm = new Empty();

testEsm.test();
testEsm.test2();


```

**Comment by jdalton** [comment]
Hi @Nicholi!

Can you create a simple repro repo with the latest 3.0.34.

**Comment by Nicholi** [comment]
Absolutely, let me get on that.

**Comment by Nicholi** [comment]
Haha ok, seems to work great now. Glad it was just a bug and not something I was fundamentally getting wrong.

**Comment by jdalton** [comment]
> Haha ok, seems to work great now. 

I was hoping it was related to the issue I had just fixed :yum:
