### ISSUE TITLE
3.0.34: ReferenceError: xxx is not defined in circular import

### ISSUE THREAD

**Issue by DaddyTrap** [standard-things/esm#394]
With the following 3 files running with `node -r esm circular.js`, I got the `ReferenceError`.

```
.
├── circular1.js
├── circular2.js
└── other.js
```

```javascript
// circular1.js
import * as Other from './other';
import './circular2';

console.log(Other.some_val);
```

```javascript
// circular2.js
import './circular1';
```

```javascript
// other.js
export const some_val = 42;
```

Expected output is simply `42`, but the actual output is as follows

```
42
file:///home/daddytrap/Work/issue/circular1.js:4
console.log(Other.some_val);

ReferenceError: Other is not defined
    at Object.<anonymous> (file:///home/daddytrap/Work/issue/circular1.js:4:7)
    at Object.<anonymous> (file:///home/daddytrap/Work/issue/circular1.js:1)
```

---

This is the repo how i reproduce: [DaddyTrap/esm-issue-394](https://github.com/DaddyTrap/esm-issue-394)

I got this error in 3.0.30, 3.0.33 and 3.0.34, however, i can run it with 3.0.10 ! Hope this can help.

Thanks !

**Comment by jdalton** [comment]
Thanks @DaddyTrap!

**Comment by jdalton** [comment]
Tests https://github.com/standard-things/esm/commit/2d774895376b6ffc51e07ad6e240e4b813d3960e.

**Comment by jdalton** [comment]
**Update:**

[v3.0.35](https://github.com/standard-things/esm/releases/tag/3.0.35) is released :tada:
