### ISSUE TITLE
Unable to export Reflect

### ISSUE THREAD

**Issue by rektide** [standard-things/esm#396]
```
export {
  Reflect
}
```

and 

```
export default Reflect
```

both do not run, producing a `SyntaxError: Export 'Reflect' is not defined in module`.

I believe this should be valid.

As a workaround, I am currently doing:

```
const r = Reflect
export { r as Reflect}
export default r
```

And this seems to work. It would be good if the native `Reflect` was directly usable, as per the top two, non-working examples.

**Comment by jdalton** [comment]
Hi @rektide!

ES modules work by exporting bindings. The builtin `Reflect` or other builtins like `Array`, `Math`, etc. are not bindings and so cannot be directly exported. This is why when you created a local binding `r` it would export.
