### ISSUE TITLE
V3.0.34 not working with jest.

### ISSUE THREAD

**Issue by gbahamondezc** [standard-things/esm#398]
Thanks a lot for this awesome module!

I'm trying to run my jest test with esm  it's failing with this error:

<img width="933" alt="screen shot 2018-05-14 at 3 31 44 pm" src="https://user-images.githubusercontent.com/22915623/40019053-1c933584-578c-11e8-9802-181766ed3cbc.png">

My package.json

```json
{
  "dependencies": {
    "esm": "^3.0.34"
  },
  "scripts": {
    "start": "node -r esm index.js",
    "test": "node -r esm node_modules/.bin/jest"
  },
  "esm": {
    "mode": "auto",
    "await": true,
    "cjs": {
      "vars": true,
      "interop": true,
      "namedExports": true
    }
  },
  "devDependencies": {
    "jest": "^22.4.3"
  }
}
```

**index.js**
```js
import modulex from './modulex';
console.log(modulex);
```

**modulex.js**
```js
export default {
    name: 'im module x'
};
```

**test.js**
```js
import modulex from './modulex';

test('Test', () => {
    console.log(modulex);
});
```

When i run  ```yarn start # or npm start```  everything works without problems, so i guess the configuration it's fine.

**Comment by dnalborczyk** [comment]
@gbahamondezc jest is not supported yet, but @jdalton is working on it.

you can follow up here: https://github.com/facebook/jest/issues/4842

**Comment by gbahamondezc** [comment]
@dnalborczyk  ok, thanks 👍
