### ISSUE TITLE
Doesn't work with webpack-serve using its --require or -r flag - "Unexpected token import"

### ISSUE THREAD

**Issue by oles** [standard-things/esm#399]
You inspire me, John-David. Really cool to see you're pushing and inspiring others to make ESM awesome. All my projects recently has "esm" inside its devdeps :+1: 

Which brings me to this issue. `webpack -r esm` works perfectly, but `webpack-serve -r esm` does not. 
I could not find any issues regarding it here nor on https://github.com/webpack-contrib/webpack-serve

The same config file is used by both `webpack` and `webpack-serve`, but the later complains about `Unexpected token import`

Seems like `webpack-serve` is doing some magic to its require implementation: https://github.com/webpack-contrib/webpack-serve/pull/83 - and it seems like this issue is on their cape.

Any suggestions before I open an issue there as well?

**Comment by oles** [comment]
Ohhh....

> This module will not implement TypeScript, Babel, nor any other preprocessor support. You must feed it regular JavaScript. Note: This will not change.

https://github.com/webpack-contrib/webpack-serve/issues/65#issuecomment-374040611

**Comment by oles** [comment]
Got it working using a tip inspired from https://github.com/webpack-contrib/webpack-serve/issues/51#issuecomment-376035797

`node -r esm ./node_modules/webpack-serve/index.js`

Though neither ideal and quite intuitive, it's okay for now. I'll open an issue over at `webpack-serve`, using this as a reference.

**Comment by oles** [comment]
Opened at https://github.com/webpack-contrib/webpack-serve/issues/138

**Comment by jdalton** [comment]
Thanks @oles!

**Comment by oles** [comment]
@Jamesernator Done: https://github.com/oles/webpack-serve-esm

Thanks for looking into this :+1:
