### ISSUE TITLE
non-`file:` specifiers are not valid

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#40]
protocol relative works fine since there is a base URI relative to the importing module.

https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#33-es-import-path-resolution

```js
// a.mjs
import "http://google.com";
import "https://google.com";
```

**Comment by jdalton** [comment]
Thanks @bmeck!

We currently don't allow non-file specifiers and throw an error like:
```
Error [MODULE_NOT_FOUND]: Module 'http://google.com'not found
```

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/957cc132aaa53aab38dad7c12dc3df49ed42d277 to align with Node in throwing a `ERR_INVALID_PROTOCOL` for this case.
