### ISSUE TITLE
Import query

### ISSUE THREAD

**Issue by moose56** [standard-things/esm#407]
Hi,

Looking for some advise about how to approach a use case with esm. Give the following 'old school' example:

````js
const Thing = (some_condition)
    ? require("file.js").Constructor1
    : require("file.js").Constructor2;
````
How does this work in the new world? So far I have:

````js
const module = await import("file.js");
const Thing = (some_condition)
    ? module.Constructor1 
    : module.Constructor2;
````
Is this the way or am I missing something to allow for not having an `await` (or `.then()`)?

**Comment by dnalborczyk** [comment]
@moose56  Are you asking how to conditionally load a module? otherwise there is no need for `dynamic import` at all.

your cjs example could be simplified to:
```javascript
const { A, B } = require("./file")
```

and the esm (ES6 modules) example could be simplified to:
```javascript
import { A, B } from "./file"  // depending on what (cjs/esm) and how the module in 'file' is being exported
```
