### ISSUE TITLE
v3.0.35: TypeError: Reflect.getPrototypeOf called on non-object

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#408]
esm v3.0.35 (node 10.1.0), throws TypeError:

```console
(node:34709) UnhandledPromiseRejectionWarning: TypeError: Reflect.getPrototypeOf called on non-object
(node:34709) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

sorry, not much information, I can try to create a repro if needed ....

**Comment by dnalborczyk** [comment]
> I think it's related to a649a48.

I can confirm. error starts happening at this commit. the exception itself is also being swallowed somehow at this commit. in addition, it seems to be a runtime exception ...

**Comment by jdalton** [comment]
[v3.0.36](https://github.com/standard-things/esm/releases/tag/3.0.36) is released :tada:

**Comment by dnalborczyk** [comment]
Thanks @jdalton !! v3.0.36 fixed it!
