### ISSUE TITLE
3.0.35: some regression with local file mocking

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#409]
Hello again.

Tried to upgrade `mocku` to 3.0.35 – https://github.com/deepsweet/mocku/pull/1

2 tests "scoped file: unmock" and "not scoped file: mock" started to return correct results which were wrong before, I just somehow missed it and didn't report here.

But one test "scoped file: mock" now returns an empty `{}` object instead of a mock. Works fine with `3.0.34`, you can try to run them with `yarn start test` or `npx start test`.

**Comment by cabbiepete** [comment]
Same thing occurs for 3.0.36

**Comment by jdalton** [comment]
> 2 tests "scoped file: unmock" and "not scoped file: mock" started to return correct results which were wrong before, I just somehow missed it and didn't report here.

Nice!

> But one test "scoped file: mock" now returns an empty {} object instead of a mock. Works fine with 3.0.34, you can try to run them with yarn start test or npx start test.

Yes, I know the root cause. I had added an optimization to remove binding setters for things that normally only happen once (like returning the namespace object from a dynamic import). With mocking however that assumption is no longer true. I'll look into if I can find a balance between the two.

**Comment by jdalton** [comment]
I've removed the problem optimization for now and will work on a unit test using mocku to ensure it continues to work _(for that at least)_.

**Comment by jdalton** [comment]
**Update:**

In a future release I may add a `mock` option to better support scenarios like #266 and allow optimizations for the common case _(unmocked)_.

**Comment by jdalton** [comment]
**Update:**

[v3.0.37](https://github.com/standard-things/esm/releases/tag/3.0.37) is released :tada:

**Comment by cabbiepete** [comment]
Confirm it fixes the issue for me also.
