### ISSUE TITLE
query/hash in URL doesn't cause re-evaluation

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#41]
Resolution on pathname is correct, but doesn't re-evaluate

```js
// a.mjs
import assert from 'assert';
import one from './b';
import two from './b?2';
import three from './b#3';
assert.strictEqual(one, 1);
assert.strictEqual(two, 2);
assert.strictEqual(two, 3);
assert.strictEqual(global.v, 3);
```

```js
// b.mjs
global.v = global.v || 0;
export default ++global.v;
```

**Comment by jdalton** [comment]
Thanks @bmeck!

I didn't know it should cause re-evaluation. I thought maybe they were just stripped out. Is re-evaluation covered in the EPS docs?

**Comment by bmeck** [comment]
it is covered more thoroughly on the web doc, but it is in EP since URL matching is from web spec.

https://url.spec.whatwg.org/#url-equivalence

https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier and EP don't set those flags to ignore query/hash.

**Comment by jdalton** [comment]
🆒

**Comment by jdalton** [comment]
Closed by https://github.com/standard-things/esm/commit/b56ce4e9ad20bf9605818a84ba42973a90e43627.
I'll be adding a round of unit tests over the next couple of days to solidify support.
