### ISSUE TITLE
"SyntaxError: Unexpected token ."

### ISSUE THREAD

**Issue by novemberborn** [standard-things/esm#410]
I get `SyntaxError: Unexpected token .` with 3.0.35 and 3.0.36. It's fine with 3.0.34. I've cleared caches.

I can't share the project code, and I've tried to reproduce the same module layout, but the problem does not occur. Anyway, here's the first part of the module:

```js
import {microGraphql} from 'apollo-server-micro'
import {formatError} from 'graphql'
import graphqlIsoDateTypes from 'graphql-iso-date'
import GraphQLScalarTypes from 'graphql-scalar-types'
import {makeExecutableSchema} from 'graphql-tools'
import {json, send} from 'micro'

import typeDefs from '../schema'
import {redacted1} from './redacted1'
import {IS_DEVELOPMENT} from './env'
import * as resolvers from './graphql-resolvers'
import {redacted2, Redacted3} from './redacted2-3'
import {redacted4} from './services/redacted4'

const schema = makeExecutableSchema({
  typeDefs,
  resolvers: {
    DateTime: graphqlIsoDateTypes.GraphQLDateTime,
    // Other resolvers
    ...resolvers
  }
})
```

With `debug: true` and `sourceMap: false` I get the following stack trace:

```
/project/lib/graphql.js:16
  _5ef‍.t("typeDefs",typeDefs),
       ^

SyntaxError: Unexpected token .
    at Module.e (/project/node_modules/esm/esm.js:1:85020)
    at he (/project/node_modules/esm/esm.js:1:209563)
    at /project/node_modules/esm/esm.js:1:211206
    at module.exports.t.a (/project/node_modules/esm/esm.js:1:211446)
    at Module._ (/project/node_modules/esm/esm.js:1:220204)
    at Module.g._compile (/project/node_modules/esm/esm.js:1:183243)
    at Object.c (/project/node_modules/esm/esm.js:1:220662)
    at Object.o (/project/node_modules/esm/esm.js:1:219738)
    at Object.<anonymous> (/project/node_modules/esm/esm.js:1:217129)
    at /project/node_modules/esm/esm.js:1:119705
```

What's odd is that if I remove an import, say `import * as resolvers from './graphql-resolvers'`, the code works. Or, if I use `typeDefs: typeDefs` (or rename the `typeDefs` import).

**Comment by jdalton** [comment]
Thanks @novemberborn!

This is due to our TDZ detection. Could you search your `node_modules/.cache/esm` folder for the cache file containing `.t("typeDefs",typeDefs)` _(a text editor like vscode should be able to do that)_ and then github gist me the source. It's an invalid transform _(so creating a syntax error)_.

**Comment by jdalton** [comment]
You don't need to share the whole file just the line or lead-in and tail-end of the source around the syntax error.

**Comment by jdalton** [comment]
Our temporal dead zone (TDZ) transform is new, so we're still shaking bugs out of it.

**Comment by jdalton** [comment]
Ah I see the transform error. We're transforming the property shorthand which we should totally not be doing. I'll have a patch this evening 😋

**Comment by jdalton** [comment]
**Update:**

[v3.0.37](https://github.com/standard-things/esm/releases/tag/3.0.37) is released :tada:
