### ISSUE TITLE
Instantiation of HoistableDeclarations prior to Evaluation

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#42]
All HoistableDeclarations are instantiated and available at the time of hooking up bindings:

https://tc39.github.io/ecma262/#sec-moduledeclarationenvironmentsetup (towards the end you can see the list of things that gets hoisted prior to eval)

```js
// a.mjs
// this file never evaluates to any meaningful effect

// it kicks off a circular dep on 'b'
import {b_fn} from './b';

// it exports a hoistable delcaration a_fn, this is setup while graph is instantiating
function a_fn() {return b_fn();};
export {a_fn};
```

```js
// b.mjs
import assert from 'assert';

// grabs 'a'
import {a_fn} from './a';


// it exports a hoistable delcaration b_fn, this is setup while graph is instantiating
const v = {};
function b_fn() {
  return v;
}
export {b_fn};

// evaluation of this line happens before 'a' starts evaluating
// a_fn successfully is called since it was setup during instantiation
assert.strictEqual(a_fn(), v);
```

The hoistable declarations can also be part of a special form of `export default`.

**Comment by jdalton** [comment]
Thanks @bmeck!

Can you explain what the current behavior is and what the expected result is?

**Comment by bmeck** [comment]
the strictEqual should pass. `v` passes through `a_fn` even though `a.mjs` has not evaluated yet. all hoistable declarations are allocated prior to beginning evaluation of the ESM graph.

**Comment by jdalton** [comment]
Just to clarify `b.mjs` should be exporting `b_fn` right?

Pulling in @benjamn on this since I believe it would be interesting for Reify too.

**Comment by bmeck** [comment]
@jdalton yes, both are exporting prior to evaluating

**Comment by jdalton** [comment]
Can you update your example to clarify.

**Comment by bmeck** [comment]
updated

**Comment by benjamn** [comment]
In this example, `b_fn` is never exported from `b.mjs`. Does the problem persist after that problem is fixed?

**Comment by bmeck** [comment]
@benjamn yup, still exists. must have messed up in copy pasta.

**Comment by benjamn** [comment]
This is going to be tricky to fix, because the compiler relies on `require`, and there's a cycle between `require("./a")` and `require("./b")` in the generated code.

In particular, `a.mjs` can't get anything from `b.mjs` until after calling `require("./b")`:
```js
let b_fn;
module.watch(require("./b"), {
  b_fn(v) { b_fn = v; }
});
```
But calling `require("./b")` results in `b.mjs` calling `a_fn()`, which calls the imported `b_fn` variable in `a.mjs`, before the `require("./b")` call has returned in `a.mjs`.

**Comment by bmeck** [comment]
IDK the internals but I suspect this should be slightly changed to pseudocode:

```js
// a.mjs
module.exports = new ESM;
function a_fn() {...}
export('a_fn', a_fn); // notifies all the watchers of this cache key
const b_path = resolve('./b');
// start watching for b_path / b_fn
var b_fn;
watch(b_path,  {b_fn(v) {b_fn = v;}})
const b = require(b_path); // grabs the ESM interface
// ...
```

```js
// b.mjs
module.exports = new ESM;
function b_fn() {...}
export('b_fn', b_fn); // notifies all the watchers of this cache key
const a_path = resolve('./a');
var a_fn;
watch(a_path, {a_fn(v) {a_fn = v;}}); // already set, so it is hooked up immediately
const a = require(a_path);
a_fn();
```

This moves all the `watch` bits to occur prior to any evaluation.

**Comment by benjamn** [comment]
That's roughly how the API that `module.watch` replaced used to work. I'll spare you the historical details, but @jdalton and I felt the problem with an API that resolves a string is that its implementation ends up calling `require(id)` for a dynamic identifier, which is impossible for bundlers to analyze statically.

In other words, it's tempting to go back to something like
```js
module.watch("./b", {
  b_fn(v) { b_fn = v; }
});
```
but then your bundler would need to understand `module.watch("./b", ...)` as something special, like `require("./b")`.

**Comment by bmeck** [comment]
for bundlers the value of the resolve shouldn't change, could you just put the string into the require as well?

**Comment by benjamn** [comment]
Unfortunately,
```js
const id = require.resolve("./b");
require(id);
```
doesn't work in Webpack (haven't checked Browserify), even though it might seem like it should.

**Comment by bmeck** [comment]
I was thinking more like:
```js
const id = require.resolve("./b");
require("./b");
```

**Comment by benjamn** [comment]
You've persuaded me there has to be a way for `a.mjs` to register its interest in `b.mjs` before `b.mjs` evaluates, but I'll have to keep thinking about the best way to achieve that. Thanks!

**Comment by benjamn** [comment]
Part of the reason `require("./b")` is a black box is that we have to call at least once to discover the `exports` it's going to return, and `b.mjs` gets evaluated as a side effect of calling `require("./b")`.

I seem to recall @jdalton has some experience with overriding the initial value of the `exports` object, which might allow the parent module to know in advance what the `exports` object is going to be?

**Comment by jdalton** [comment]
Just to pop in. Since `@std/esm` hides its implantation away and isn't exposed to webpack (webpack sees just standard esm code) I'm cool with whatever makes it work.

**Comment by jdalton** [comment]
Cleaning up the issue a bit to remove off topic bits. I've got this working locally.

**Comment by jdalton** [comment]
Fixed by https://github.com/standard-things/esm/commit/ca9716bbea36e367c32de48f3df0ae553f3ca989.
