### ISSUE TITLE
3.0.37: Oneline re-export throws a syntax error

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#422]
Hi.

I've tried hard but couldn't narrow this down and extract into a small reproducible example, probably the issue requires some conditions and environment, so here is a live project: https://github.com/deepsweet/start

```sh
yarn
yarn list --pattern esm
# 3.0.36
yarn start
```

Expected result:

```sh
One of the following task names is required:
...
```

Then:

```sh
yarn upgrade esm@3.0.37
yarn start
```

```sh
SyntaxError: Missing export 'istanbulInstrument' in ES module: /.../@start/packages/plugin-lib-istanbul/src/index.ts
```

But if I change `packages/plugin-lib-istanbul/src/index.ts` from:

```js
export { default as istanbulInstrument } from './instrument'
export { default as istanbulReport } from './report'
export { default as istanbulThresholds } from './thresholds'
```

To:

```js
import istanbulInstrument from './instrument'
import istanbulReport from './report'
import istanbulThresholds from './thresholds'

export { istanbulInstrument }
export { istanbulReport }
export { istanbulThresholds }
```

Then it works again:

```sh
yarn start
```

```sh
One of the following task names is required:
...
```

🤔

**Comment by jdalton** [comment]
Thanks @deepsweet!

I know the general area that's causing this issue. I'll dig into it today.

**Comment by jdalton** [comment]
\cc @StreetStrider: This is likely related.

**Comment by jdalton** [comment]
**Update:**

[v3.0.38](https://github.com/standard-things/esm/releases/tag/3.0.38) is released :tada:
