### ISSUE TITLE
colon in filename oddity?

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#43]
colons appear to make files never able to be found?

```js
// a.mjs
import './colons%3Awork'
import './colons:work'
```

```js
// colons:work.js
// this space left blank
```

**Comment by bmeck** [comment]
might look into using `require('url').URL` if possible.

**Comment by jdalton** [comment]
What is the expected behavior for both `'./colons&3awork'` and `'./colons:work'`

**Comment by bmeck** [comment]
in URL resolution they are just colons since `./` kicks it to pathname bit.

**Comment by bmeck** [comment]
oh. yes, both should work. forgot to actually state that.

**Comment by jdalton** [comment]
Would it be possible for you to show a vanilla WHATWG usage that producing a decoded `file://` protocol path containing a ":".

**Comment by bmeck** [comment]
```
new URL('file://localhost/test:123')
new URL('./test:123', 'file:///')
```

**Comment by jdalton** [comment]
and the `&3a` encoded one...

**Comment by bmeck** [comment]
sleepy typo, should use `%`

```js
new URL('file://localhost/test%3A123')
new URL('./%3A', 'file:///')
```

When canonicalized in https://github.com/nodejs/node/blob/master/lib/internal/url.js#L1370 it becomes `:`

**Comment by jdalton** [comment]
Ah 👌, I was super confused 😄

**Comment by jdalton** [comment]
What form of decode do you do? I noticed that `decodeURI` doesn't decode `%3a`. Is it more the old school `unescape()`?

**Comment by bmeck** [comment]
That function does things in very specific ordering, but uses `decodeURIComponent` for the split up chunks it makes.

**Comment by jdalton** [comment]
Closed by https://github.com/standard-things/esm/commit/3b0244a48a7c483b509d0ec4c57f75d5a779f42d. I'll be adding a round of unit tests over the next couple of days to solidify support.
