### ISSUE TITLE
3.0.37+: Different interop of CJS with dynamic import

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#432]
Hi.

Found this while using [istanbul-lib-instrument](https://cdn.jsdelivr.net/npm/istanbul-lib-instrument@1.10.1/dist/index.js):

```js
import('istanbul-lib-instrument')
  .then(console.log)
  .catch(console.error)

export default 123
```

3.0.36:

```sh
[Module] {
  createInstrumenter: [Function: createInstrumenter],
  default:
   { createInstrumenter: [Function: createInstrumenter],
     programVisitor: [Function: programVisitor],
     readInitialCoverage: [Function: readInitialCoverage] },
  programVisitor: [Function: programVisitor],
  readInitialCoverage: [Function: readInitialCoverage] }
```

3.0.37+:

```sh
[Module] {
  createInstrumenter: [Function: createInstrumenter],
  programVisitor: [Function: programVisitor],
  readInitialCoverage: [Function: readInitialCoverage] }
```

I believe that old behavior is correct, but you know this better.

(Also it throws "Cannot read property 'exports' of undefined" without any export like `export default 123`, why?..)

**Comment by jdalton** [comment]
The `[Module]` output of 3.0.37+ is the correct one. Previously we only detected `__esModule` interop if the package also exported a default property.

> (Also it throws "Cannot read property 'exports' of undefined" without any export like export default 123, why?..)

That's a bug on us. We track an `exports` property so must have a place where the object is nullish.

**Comment by deepsweet** [comment]
So even if module is technically CJS but it contains the right `__esModule` interop then it's not a mandatory to dynamically import it as "namespace"? I have different behaviors with different CJS packages, and it feels like now it matters how exactly they were transpiled from ESM to CJS.

**Comment by deepsweet** [comment]
ok, I think I _finally_ got it :)

**Comment by jdalton** [comment]
[v3.0.39](https://github.com/standard-things/esm/releases/tag/3.0.39) is released :tada:
