### ISSUE TITLE
Usage programatically?

### ISSUE THREAD

**Issue by ThisIsMissEm** [standard-things/esm#433]
Hi!

I have several projects where we have a few require extensions, and we're also using flow-remove-types. Rather than having that code duplicated in each project, I wanted to create a package as `@org/bootstrap` and have that take care of everything, so I could just do `node -r @org/bootstrap <filename>`

However, I can't seem to get this to work — I'm not sure why, but esm's require just doesn't hook-in correctly from that bootstrap module.

This leaves me with having to do `node -r @org/bootstrap -r esm <filename>`

The `@org/bootstrap` code looks like:

```js
var fs = require("fs");

require.extensions[".graphql"] = function(localModule, filename) {
  localModule.exports = fs.readFileSync(filename, "utf8");
};

require("flow-remove-types/register")({ all: true });
```

I then also had the line for `require('esm')(module)` in there, but that didn't work.

**Comment by jdalton** [comment]
Hi @ThisIsMissEm!

The `esm` loader supports being used at the application level `node -r esm` and the package level `require=require("esm")(module)`. 

The application level hooks directly into the global module system while the package level creates an isolated instance _(that does not hook into the global module system)_.

If you want to leverage the package level API to hook into the global module system you might be able to with something like

```js
const esmLoader = require("esm")(module)
require.extensions[".js"] = esmLoader("module")._extensions[".js"]
```

**Comment by ThisIsMissEm** [comment]
Hi JDD, 

Thanks for the quick response; shall be using this shortly!

Yours,
Emelia
