### ISSUE TITLE
3.0.37+: "Cannot set property default of [object Module] which has only a getter"

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#435]
Hi.

Got another one which I couldn't extract, it's failing only there: https://github.com/deepsweet/mocku/pull/2

`test/index.ts` file, `scoped file: unmock` test:

1) Throws  `Cannot set property default of [object Module] which has only a getter`. If I remove `Reflect.deleteProperty(Module._cache, key)` from the `unmock` function source then the error is gone (but ofc path in not unmocked).

2) If I remove `unmock('./fixtures/scoped/file')` from `scoped file: unmock` test at all then it fails on next one in which I'm trying to re-mock the same path again and it says the same `Cannot set property default of [object Module] which has only a getter`. This time it's more or less understandable because I can say that in order to mock the same path again first you have to unmock it. But I think it's the same issue where some "only a getter" place has become really tough.

Sorry if it sounds a bit messy.

**Comment by jdalton** [comment]
Thanks @deepsweet!

**Comment by jdalton** [comment]
**Update:**

[v3.0.39](https://github.com/standard-things/esm/releases/tag/3.0.39) is released :tada:
