### ISSUE TITLE
Breaks accessing global variables from Chrome debugger

### ISSUE THREAD

**Issue by natew** [standard-things/esm#436]
Before using esm I could do the following in Node and then use Chrome debugger to attach to it:

```
global.test = 1
```

And in chrome debugger attached:

```
console.log(test)
```

With esm it shows a very strange stack trace. First it shows some stuff coming from esm:

![image](https://user-images.githubusercontent.com/12100/40626307-933f82f6-626c-11e8-8b0a-d0061a1b096e.png)

Further up the stack trace for some reason it's showing stuff happening in a setInterval in another area:

![image](https://user-images.githubusercontent.com/12100/40626313-a00a8026-626c-11e8-894d-579229f5e748.png)

If i type out:

```
global.test
```

In the repl it does work there, but not doing the regular `test`.

Should note: doing this running node like:

```
node -r esm --inspect=127.0.0.1:9000 _/index.js
```

And using node 9.8.0

**Comment by jdalton** [comment]
Hi @natew!

I can't seem to reproduce this locally. What version of `esm` and Chrome debugger are you using?
I see there is an [nw](https://nwjs.io/) directory in your paths. I haven't tested `esm` with NW. If you could provide a simple repro repo (project). I might be able to dig into it a bit more.

**Comment by natew** [comment]
Not using nw that’s just my initials :). Ok guess that’s not intended
behavior. I’m using pretty vanilla stuff.

Am using the global npm module to define things that could be it. I’ll try
creating a repro.

**Comment by jdalton** [comment]
Thanks @natew!

Yep, erroring is not intended so if you can narrow down a repro case we'll totally dig into it.
