### ISSUE TITLE
3.0.37+ breaks behavior of new keyword when accessing class under import

### ISSUE THREAD

**Issue by specialkk** [standard-things/esm#437]
In a module that imports `myExport` from another module that has a class `MyClass` as a property, attempting to instantiate `MyClass` with
```javascript
new myExport.MyClass()
```
can sometimes result it the error
```
[Error] TypeError: _d7e‍.t is not a constructor
```

It seems like this kind of transformation lost a set of parentheses and attempts to call the `.t` as a constructor.

in 3.0.36:
```javascript
new (_6c5‍.t("myExport",myExport)).MyClass()
```
in 3.0.37:
```javascript
new _e8e‍.t("myExport",myExport).MyClass()
```

I was really struggling to consistently reproduce this since there seems to be some caching happening that I'm not fully aware of. Sometimes the transformed result would remain as `new myExport.MyClass()`, but after resetting my shell session, it changes to be one of the above without even touching the source files.

Anyway, here's a pretty minimal reproduction that should help explain:

```javascript
// index.js
import { myExport } from './module';

// the affected transformation only seems to happen with circular dependencies?
export default 'foo';

const fn = () => {
  new myExport.MyClass()
}

console.log(fn.toString());
```

```javascript
// module.js
import foo from './index';
export const myExport = {
  MyClass: class MyClass { }
}
```

**Comment by jdalton** [comment]
Thanks @specialkk!

I've been tweaking the TDZ instrumentation and this got regressed.

**Comment by specialkk** [comment]
I find it seriously impressive with how dedicated you are at keeping that issue counter down at 0. Do you ever find time to sleep?

Thanks for fixing these!

**Comment by jdalton** [comment]
[v3.0.39](https://github.com/standard-things/esm/releases/tag/3.0.39) is released :tada:
