### ISSUE TITLE
"esm" field in package.json doesn't work, .esmrc does

### ISSUE THREAD

**Issue by babakness** [standard-things/esm#439]
In `package.json`

```javascript
"esm": {
    "mode": "all"
},
```

Doesn't work. This in `.esmrc` does

```javascript
{
    "mode": "all"
},
```

**Comment by jdalton** [comment]
Hi @babakness!

Could you create a repro repo for me to check out?

**Comment by babakness** [comment]
Here is a repo to review

https://github.com/babakness/pg-nested-json-query

To re-iterate, it seems that the `esm` configuration place in `package.json` is ignored. Removing the `.esmrc` file will cause imports to break despite the configuration in `package.json`
