### ISSUE TITLE
protocol relative `localhost` should work

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#44]
```js
// a.mjs
import '//localhost/path/to/thing'
import 'file://localhost/path/to/thing'
```

Should be the same.

**Comment by jdalton** [comment]
Thanks @bmeck!

Oh snao, even without the `file://` protocol (so no protocol)? Is that covered in the EPS?

**Comment by bmeck** [comment]
`//` is protocol relative and EP provides `file:` base locations for URL resolution, so yes.

**Comment by jdalton** [comment]
Closed by https://github.com/standard-things/esm/commit/a64711eafa385e55614ebe8048052c3b0fabbb52.
I'll be adding a round of unit tests over the next couple of days to solidify support.
