### ISSUE TITLE
esm@3.0.42 can't import vue-loader

### ISSUE THREAD

**Issue by silveryiris** [standard-things/esm#442]
#### Minimal error reproduce
https://github.com/silveryiris/esm-vue-loader-import-error

#### Test command

````
npm run start
````
or 
````
node -r esm index.js
````

#### Error message

TypeError: Cannot read property 'value' of undefined

#### Summary
It was ok with esm@3.0.41 but failed with esm@3.0.42.
Not sure where the problem is :(

**Comment by dnalborczyk** [comment]
I can confirm, same issue with:

`import BabelMinifyPlugin from 'babel-minify-webpack-plugin'`

**Comment by jdalton** [comment]
On it.

**Comment by silveryiris** [comment]
I just trace back error source with 
````
node_modules\@vue\component-compiler-utils\dist\parse.js
````
At line no.5 :

```` 
const compiler = require('vue-template-compiler');
````

This line Is failed at the script , hope it can save some debug time.

**Comment by jdalton** [comment]
Thanks @silveryiris and @dnalborczyk!

I have some test debt to pay. I'm hopping if things settle a bit I can spend a few days just catching up on tests to help prevent regressions like this.

**Comment by dnalborczyk** [comment]
take your time, man. just make sure you don't burn out!  :wink:

**Comment by jdalton** [comment]
[v3.0.43](https://github.com/standard-things/esm/releases/tag/3.0.43) is released :tada:

**Comment by dnalborczyk** [comment]
needless to say: fixed!!  :smiley:

**Comment by jdalton** [comment]
Splitting out `cjsNamespace` and `esmNamespace` properties into mutable variants allows me to provide `.mjs` files with immutable namespaces and others, that opt-in to mutable namespaces, the mutable variants without contaminating `.mjs` files.  Mutable namespaces are handy for spys/stubs/mocks.
