### ISSUE TITLE
Forwarding exports do not work since 3.0.35

### ISSUE THREAD

**Issue by oliver----** [standard-things/esm#444]
In my projects I am having a root `index.js` which forwards exports from indexes in sub-directories, such as
```
export * from './src/index'
```
For example in my tests I use the root index in a similar way as how others would be using the published library. 
For instance a `test/Foo.test.js` could look like this:
```
import test from 'tape'
import { Foo } from '../index'
test('Foo test', (t) => {
  let foo = new Foo()
  ...
})
```
Then I run the test via `node --require esm test/Foo.test`

This pattern was working with 3.0.34, but not after that and is still not working in version 3.0.44.

Now esm complains that `Foo` is not exported by `index.js`, so it seems to have lost track of the forwarded symbols.

**Comment by oliver----** [comment]
This is how the error looks like:

```
/path/to/project/test/Foo.test.js:1
import test from 'tape'

SyntaxError: Missing export 'Foo' in ES module: file:///path/to/project/index.js
    at Object.<anonymous> (file:///path/to/project/test/Foo.test.js:1)
```

**Comment by jdalton** [comment]
Hi @oliver----!

I think this is a spec compliance nit that I may have fixed (which is showing up as a fail for you).
My spec forwarding with `*` will forward all __but__ the default export. So the only way to forward it would be like `export { default as Foo } from "mod"`.

If you could create a repro repo I could dig in and tell you for sure though.

**Comment by oliver----** [comment]
Hey @jdalton,

here you are: https://github.com/oliver----/esm-444

**Comment by oliver----** [comment]
```
git clone https://github.com/oliver----/esm-444.git
cd esm-444
npm install
npm test
```

**Comment by jdalton** [comment]
It's a :bug:!

**Comment by oliver----** [comment]
Sweeet ;)

**Comment by jdalton** [comment]
![](https://user-images.githubusercontent.com/4303/40868731-b8cd8512-65c4-11e8-9e01-4f39763e02bd.gif)

**Comment by oliver----** [comment]
💯

**Comment by oliver----** [comment]
Confirmed. Is working!

**Comment by oliver----** [comment]
@jdalton thanks!

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/f51444ac7eccaf41f88d05e9beed56be4fc0c670; Tests https://github.com/standard-things/esm/commit/7bd6ee23518fa3fe6bc9e5313879e8ea2a7a5361 and https://github.com/standard-things/esm/commit/6e9a632a4080addfc5802d69c4b92237960eee05.

**Comment by jdalton** [comment]
[v3.0.45](https://github.com/standard-things/esm/releases/tag/3.0.45) is released 🎉

**Comment by oliver----** [comment]
Nice!

**Comment by oles** [comment]
@jdalton 👏👏👏
