### ISSUE TITLE
Globals not available when using node -r esm

### ISSUE THREAD

**Issue by natew** [standard-things/esm#445]
So isolated it down to this:

## index.js

```
global.hi = 123

setInterval(() => {
  console.log('hi')
}, 1000)
```

and run with `node -r esm --inspect=127.0.0.1:9000 index.js`

and then attach to the debugger with Chrome remote inspector and type `hi`:

![image](https://user-images.githubusercontent.com/12100/40877240-2f268336-6632-11e8-804b-b7c3bb338f2b.png)

**Comment by jdalton** [comment]
Hi @natew!

Make sure you're in the correct. Context (from the drop down).

<img width="251" src="https://user-images.githubusercontent.com/4303/40880229-be064f12-6661-11e8-8f4e-1ccb20554e90.png">
