### ISSUE TITLE
Forwarding exports do not work (cont'd)

### ISSUE THREAD

**Issue by oliver----** [standard-things/esm#447]
While the fix for #444 works for a single forwarded symbol, it doesn't for a second one. 

Updated the repro example https://github.com/oliver----/esm-444

```
git clone https://github.com/oliver----/esm-444.git
cd esm-444
npm install
npm test
```

**Comment by jdalton** [comment]
Aw, this bug turned my assumptions about forward exports upside down :yum:
I have a patch locally, adding a test.

**Comment by oliver----** [comment]
Hehe, lemme know when you have a commit. I'll test with one of my real projects :)

**Comment by oliver----** [comment]
@jdalton Ahhh 😄  I think now you have nailed it 💪

**Comment by jdalton** [comment]
Thanks for double checking. I'll likely do a cleanup pass in the morning before publishing the next release.

**Comment by oliver----** [comment]
![You are awesome](https://media.giphy.com/media/g9582DNuQppxC/giphy-downsized.gif)

**Comment by jdalton** [comment]
[v3.0.47](https://github.com/standard-things/esm/releases/tag/3.0.47) is released :tada:

**Comment by oliver----** [comment]
Awesome!
Thank you very much!
