### ISSUE TITLE
exact match specifier for directories

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#45]
spec phrasing/ bug, unclear that the file search algorithm is re-entrant when it returns the specifier in https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#3313-file-search .

easily seen by using require, which is what the spec is conforming to in this case.

given a dir structure of:

```
b.js
b/index.js
```

```js
// have the same result of 
// `b/index.js`
require('./b')
require('./b/')
```

```js
import './b'; // should give `b/index.js`, gives incorrect `b.js`
import './b/'; // gives the correct `b/index.js`
```

Will update spec this week to state it is reentrant.

**Comment by jdalton** [comment]
Thanks @bmeck!

In your `import` case are you saying that `import './b/'` does not evaluate to `./b/index.js`?

**Comment by bmeck** [comment]
`./b/` has the correct behavior, `./b` currently does not for import

**Comment by jdalton** [comment]
I'm confused. Can you update your example with what is given and what should be given for the `import` clauses.

**Comment by bmeck** [comment]
updated

**Comment by jdalton** [comment]
Interesting so `require` and `import` should ideally behave the same and we've introduced some wonkiness.

**Comment by bmeck** [comment]
yes, spec was poorly phrased is the thing to blame I think

**Comment by benjamn** [comment]
In my testing, `require("./b")` evaluates `b.js`, not `b/index.js`.

**Comment by benjamn** [comment]
And if I'm reading [3.3.1.3](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#3313-file-search) correctly, appending `.js` to `./b` gives an exact match for `b.js`, so `import "./b"` should evaluate `b.js` too. Why would the directory fallback kick in here?

**Comment by bmeck** [comment]
@benjamn native node require? without @std/esm?

**Comment by bmeck** [comment]
@benjamn found the disconnect, whew boy... 

*if* `d/package.json` exists **any** contains a valid `"main"`, then `require` will use `d/package.json#main` instead of a file, this is purely a spec bug and we can close this

**Comment by benjamn** [comment]
😌
