### ISSUE TITLE
dependancy extending Console class causes TypeError

### ISSUE THREAD

**Issue by LeafHacker** [standard-things/esm#450]
Tried adding esm to a small [discord bot](https://github.com/ImpactDevelopment/ImpactBot/tree/esm) which uses [klasa](https://github.com/dirigeants/klasa), however I was unable to get it to run.

I expect to get `Error: An invalid token was provided`, however instead I get a `TypeError` parsing a klasa class:

```
./node_modules/klasa/src/lib/util/KlasaConsole.js:1
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (./node_modules/klasa/src/lib/util/KlasaConsole.js:11:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

```js
// ./node_modules/klasa/src/lib/util/KlasaConsole.js
const { Console } = require('console');
/* ... */

class KlasaConsole extends Console { /* ... */ }
```

I can only reproduce this with `-r esm` in my npm start command .

I've tried this with the latest klasa and their esm branch, with no difference in result. I've also tried having `esm.mode` set to default and `"strict"`. There are currently no mjs files, so that shouldn't be causing issues...

**Comment by jdalton** [comment]
Ah thanks, this is an easy fix. It's totally my bug.

**Comment by jdalton** [comment]
**Update:**

[v3.0.48](https://github.com/standard-things/esm/releases/tag/3.0.48) is released :tada:
