### ISSUE TITLE
Way to run before every script in package.json

### ISSUE THREAD

**Issue by lavelle** [standard-things/esm#454]
Is there a good way to run this before every script in package.json?

I've been setting it via `NODE_OPTIONS="-r esm"`, but then i have to paste that into every script in package.json (we have dozens). It would be nice to have a global location to make it available to every `yarn run X` command, since it's needed everywhere (main build, unit tests, linting, etc) if I'm going to convert all build build scripts.

I was thinking I could do something clever like put 

```
global.require = require('esm')(module);
```

in my `.babelrc.js` since that is loaded everywhere, but I'm guessing it's run too late because I still get syntax errors.

**Comment by jdalton** [comment]
Hi @lavelle!

A util to add things to package scripts with a glob pattern 
_(using [globby](https://www.npmjs.com/package/globby) and [golden-fleece](https://www.npmjs.com/package/golden-fleece))_ would be rad!

Good to know the `-r` flag is supported in `NODE_OPTIONS`!

For your case you could run a script that aliases `node` as `node -r esm`.
```shell
alias node="$(which node) -r esm"
```
That may be to much system muckery though. I don't have a very good answer, sorry. But if you find or create something that helps please let me know!
