### ISSUE TITLE
bindings lose TDZ

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#46]
LexicalBindings in TDZ are converted to `undefined` when instantiating.

```js
// a.mjs
import './b.mjs';
// `a` is in TDZ until this line is done evaluating (after 'b' finishes)
const a = 'a';
export {a};
```

```js
import {a} from './a';
console.log(a); // in TDZ, should throw; instead it currently prints `undefined`
```

**Comment by benjamn** [comment]
If we found a way to avoid calling the setter function that updates `a`, would the TDZ error be thrown correctly? In other words, is TDZ dynamically disarmed after the first assignment?

**Comment by bmeck** [comment]
I'm not sure entirely what you mean. TDZ is remove after the variable binding initializer expression is evaluated. So not on first assignment exactly.

**Comment by benjamn** [comment]
What I'm wondering is if we generate code like
```js
let a;
module.watch(require("./a"), {
  a(v) { a = v; }
});
console.log(a);
```
and the `module.watch` call does not end up calling the callback function, will `console.log(a)` throw a TDZ error?

I suspect not, because `let a` is deliberately uninitialized (or implicitly initialized to undefined).

Does that make more sense?

**Comment by bmeck** [comment]
correct, to have TDZ be emulated you need to use some form of a getter for variable access that can be removed where the variable should be initialized during evaluation.

**Comment by benjamn** [comment]
This seems like something that should be configurable, like how Babel implements TDZ if you really want it. I don't have an opinion on whether it should be opt-in or opt-out, though.

**Comment by bmeck** [comment]
I'm pretty hefty on the opt-out of TDZ side if spec compliance is a goal.

**Comment by jdalton** [comment]
Let's worry about all that jazz after we get the correct behavior in place 😋

**Comment by benjamn** [comment]
Well, here's a strawperson idea:
```js
let a = module.TDZ_SENTINEL_OBJECT;
module.watch(require("./a"), {
  a(v) { a = v; }
});
console.log(module.checkTDZ(a));
```

**Comment by benjamn** [comment]
One improvement I just thought of: `module.watch` can immediately call all the setters with the `module.TDZ_SENTINEL_OBJECT`, so we don't have to expose that in the generated code:
```js
let a;
module.watch(require("./a"), {
  a(v) { a = v; }
});
console.log(module.checkTDZ(a));
```

**Comment by jdalton** [comment]
Something I noticed with `--experimental-modules` is that changing `a.mjs` to
```js
const a = 'a'
export {a}
import './b.mjs'
```
and running will still error:
```
(node:38502) ExperimentalWarning: The ESM module loader is experimental.
ReferenceError: a is not defined
    at file:///path/to/b.mjs:2:13
    at ModuleJob.run (internal/loader/ModuleJob.js:105:14)
    at <anonymous>
```

**Comment by bmeck** [comment]
@jdalton `b.mjs` will still evaluate before `a.mjs` which means `const a` in all forms from `a.mjs` won't evaluate and remove the TDZ. All those should be throwing.

**Comment by jdalton** [comment]
Cool!

For now I think I'll throw a warning with `"debug":true` when we hit cyclical imports with `undefined` values to highlight that their may be a TDZ issue.
