### ISSUE TITLE
v3.0.49: default import with auto mode and missing exports should error

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#468]
repro:

```javascript
// foo.js
console.log('module loaded');
```

```javascript
// index.js
import foo from './foo';
// {}

import { default as foo } from './foo';
// {}

import * as foo from './foo';
// [Module] { default: {} }

export { default as foo } from './foo';
// ReferenceError: foo is not defined  (wrong exception)

export { default } from './foo';
```

when run in ESM `strict mode` with mjs file extensions the above examples are throwing correctly.

_update: not sure if it is a regression._

_update: changed the title. just noticed that it only fails to throw if **no export** is being declared._

**Comment by jdalton** [comment]
Hi @dnalborczyk!

In auto mode since there is no export or import in your example it's treated as a CJS file which has an auto-default.

**Comment by dnalborczyk** [comment]
do you mean this by `default`?
```
const foo = require('./foo');
// {}
```

wouldn't it make more sense to treat the file - if unknown (missing import, export, 'use module') - like an ES6 module, if `imported`, and like a CJS file when `required`? that shouldn't break anything. or is there something I'm missing regarding sync/async loading? at least one would get parity with 'mjs' -- and I suppose the ES spec, as well as an exception that `default` doesn't exist.

**Comment by jdalton** [comment]
A CJS module that doesn't export anything will have an empty `module.exports` object. 
This is reflected in the namespace object:
```js
// [Module] { default: {} }
```
which is how CJS is handled in ESM in Node.

**Comment by dnalborczyk** [comment]
I see, I get the reasoning, but I think the situation in this case is different.

> wouldn't it make more sense to treat the file - if unknown (missing import, export, 'use module') - like an ES6 module if imported, and like a CJS file when required? that shouldn't break anything. or is there something I'm missing regarding sync/async loading? at least one would get parity with 'mjs' -- and I suppose the ES spec, as well as an exception that default doesn't exist.

don't you think ES6 modules should take precedence in this case?

**Comment by jdalton** [comment]
The treating them differently by the way they are included (`require` or static/dynamic `import`) is one way. I've gone with the unambiguous parsing route as that's where the ecosystem is _(it's what other tools do to handle unknown parse goals)_.
