### ISSUE TITLE
cycles make invalid imports work

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#47]
```js
// a.mjs
import './b.mjs';
```

```js
// b.mjs
import {DOES_NOT_EXIST} from './a';
```

**Comment by jdalton** [comment]
The fix https://github.com/standard-things/esm/commit/d38f0db2f0f551a0a466ad12346e777c70c96bd7 is not super great, but it does validate the entry once it finishes loading. It could benefit from #46.
