### ISSUE TITLE
Node-esm executable

### ISSUE THREAD

**Issue by rektide** [standard-things/esm#474]
Hello.

I love using esm so much. The one downside I face regularly is that I'm not aware of a means to make an executable script with esm. Typically my node scripts once started with: `#!/usr/bin/env node`, but I don't believe there's any way to do this with esm. As a result, I have a very inconsistent & somewhat cumbersome/crufty task of either:
1. Creating a wrapper script in CJS that imports esm & loads & executes the underlying esm script ([method #1](https://github.com/standard-things/esm#getting-started)).
2. Add the script as a target in package.json's scripts, using node -r esm ([method #2](https://github.com/standard-things/esm#getting-started)). Notably this doesn't work for anything i want globally.

If there were a node-esm executable, I could `#!/usr/bin/env node-esm` and avoid both of these limited, hacky, cumbersome approaches that keep my fantastic beautiful EcmaScript Module world scripts from being as clean and nice and boilerplate free as they could be.

As ever, this project is AMAZING & so well maintained it bowls me over. This is how ESM ought to be in node! TY!

**Comment by jdalton** [comment]
I dig it! I'm going to move this straight to #475.
