### ISSUE TITLE
SyntaxError in REPL

### ISSUE THREAD

**Issue by andrenarchy** [standard-things/esm#476]
When I run `node -r esm` and type the following function I get `SyntaxError: Unexpected token` after the second line:

```javascript
function test () {
  console.log('test')
}
```

Running `node` without `-r esm` works just as expected.

**Comment by jdalton** [comment]
Thanks @andrenarchy!

**Comment by jdalton** [comment]
**Update:**

[v3.0.53](https://github.com/standard-things/esm/releases/tag/3.0.53) is released 🎉

**Comment by andrenarchy** [comment]
Thanks a lot @jdalton, just confirming that this solved the issue I had in a more complex setting. :raised_hands:
