### ISSUE TITLE
Feature Modification Request: Reverse mainFields

### ISSUE THREAD

**Issue by onlywei** [standard-things/esm#477]
Hi, this is sort of a continuation of #473. After using `v3.0.52` in action for a couple of days I realized that it makes more sense for the package-author to be the one to decide what field application's receive when importing via `esm`.

The application-author really has no idea what packages in the wild are doing. They should not have to go read each package's package.json file to figure out whether or not the packages they install will work with the "mainFields" array. Maybe some packages use "module", some use "esnext", or even something else. It's quite difficult from the application-author perspective to properly choose the priority of these mainFields.

To be specific, I think that the package-author should have the ability to do this:
```json
{
  "name": "example-package",
  "main": "cjs-bridge.js",
  "module": "index.js",
  "esm": {
    "mainField": "module"
  }
}
```

Then, the application-author would not have to do any additional configuration, and automatically import the "module" field from packages that are configured in this way.

@jdalton What do you think?

**Comment by jdalton** [comment]
Hi @onlywei!

I want to avoid having folks add more metadata to their packages when they aren't a user of `esm`. Instead we could just encourage folks to migrate to the `'module'` field _(many have since esnext was the thing-before-the-module-field)_.
