### ISSUE TITLE
Wrapping non-Errors into pseudo-Error

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#48]
it appears that Objects without a `.stack` are being wrapped into some kind of Error-like type instead of being passed through normally:

```js
// a.mjs
import assert from 'assert';
const v = global.v = {};
import('./b').catch(err => assert.strictEqual(err, v));
```

```js
// b.mjs
throw global.v;
```

**Comment by jdalton** [comment]
Fixed by https://github.com/standard-things/esm/commit/e1e684e64acab20737db850e126db6c73492063a.
I'll be adding a round of unit tests over the next couple of days to solidify support.
