### ISSUE TITLE
missing process.env.xxx with jest and esm

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#480]
just for reference, I don't think the versions matter:

esm: v3.0.55
jest: v23.2.0
node: v10.5.0

I forked a project and converted the code incl. tests from ava to use _esm_ and _jest_.

it seems that the "global" **process** object, and/or the **process.env** object is being cloned - or re-created? I haven't debugged it yet.

some tests are setting the "global" env variable prior running the test functions. if run without esm, it works, running with esm, fails. 

not quite sure if this is a bug with _jest_ or _esm_, or just intended behavior.

might be best explained with some code: https://github.com/dnalborczyk/esm-jest-repro

**Comment by jdalton** [comment]
Hi @dnalborczyk!

This is because jest is mocking the `process` object so it's not the real one.
```js
require("process") === process // will be `false` in the jest test code
```
It would be nice if the `esm` loader could have access to these mocked globals though. I'll see about adding an option to specify them.

**Comment by dnalborczyk** [comment]
thanks @jdalton for the info! though I'm surprised that the test only doesn't work when esm is being required - but works without.

though your comment made me thinking that explicitly requiring *process* (then non-mocked?) maybe would do:
```javascript
require = require('esm')(module)
const process = require('process')

process.env.test = 'some-value'
```

which made the scenario work!

not sure if anything should be done on esm's side of things?

**Comment by jdalton** [comment]
Jest runs its code in its own unique vm context (different than the default vm context) so I can simulate this with the global at least by detecting that the context is different and running it in a similar one.
