### ISSUE TITLE
Circular import that worked in 3.0.39 is not working in 3.0.52

### ISSUE THREAD

**Issue by jfirebaugh** [standard-things/esm#481]
I'm trying to upgrade [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js) to esm 3.0.52 and running into an error related to a circular import.

Here's a reduced test case: https://gist.github.com/jfirebaugh/425ab1b911437e6707d1daa3ffb1bd23

With 3.0.39, `node -r esm a.js` runs successfully.

With 3.0.52:

```
~/Development/scratch $ node -r esm a.js 
file:///Users/john/Development/scratch/c.js:2
const exported = { A };

ReferenceError: A is not defined
    at Object.<anonymous> (file:///Users/john/Development/scratch/c.js:2:28)
    at Object.<anonymous> (file:///Users/john/Development/scratch/c.js:1)
```

Is this a regression in esm, or should this form of circular imports never have worked, and I need to eliminate the circular import?

**Comment by jdalton** [comment]
Hi @jfirebaugh!

Thanks for digging into this! It looks like v3.0.52 is correct and that the previous allowance was the bug. I converted your `a.js`, `b.js`, and `c.js` examples to `.mjs` and ran them with `node --experimental-modules ./a.mjs` and got the same error:

```
node --experimental-modules ./a.mjs
(node:41344) ExperimentalWarning: The ESM module loader is experimental.
ReferenceError: A is not defined
    at file:///Users/jdalton/projects/esm/c.mjs:2:20
    at ModuleJob.run (internal/modules/esm/module_job.js:96:12)
```
