### ISSUE TITLE
Esm corrupts jest's exported constructor.

### ISSUE THREAD

**Issue by Pokute** [standard-things/esm#482]
I found this bug when trying to tweak create-react-app -made app's tests. The code works properly without `-r esm` and fails really weirdly with it. It seems that while it runs the right constructor function properly, the resulting object doesn't have the correct prototype. I don't think that react (or react-create-app' is crucial for this test case, but it's this one is less than a minute to set up.

To test:  
`npx create-react-app esm-crats-test --scripts-version=react-scripts-ts`
`cd esm-crats-test`
`git init` (forgot this initially)
`yarn add esm`

Run `yarn run test` to verify that non-esm version works properly. Quit test with `q`.

Run `./node_modules/react-scripts-ts/bin/react-scripts-ts.js -r esm test --env=jsdom` which will fail.

**Comment by jdalton** [comment]
**Update:**

[v3.0.57](https://github.com/standard-things/esm/releases/tag/3.0.57) is released :tada:
