### ISSUE TITLE
Cannot `import {rollup} from 'rollup';` using esm.

### ISSUE THREAD

**Issue by coreyfarrell** [standard-things/esm#485]
I've tried the following `.esmrc`:
```js
{
	mainFields: ['module', 'jsnext:main', 'main'],
	cjs: {
		vars: true,
		interop: true,
		namedExports: true
	}
}
```

Create `index.mjs`:
```js
import {rollup} from 'rollup';
```

Run it:
```
$ node -r esm ./index.mjs 
file:///usr/src/tmp/index.mjs:1
SyntaxError: Missing export name 'rollup' in ES module: file:///usr/src/tmp/node_modules/rollup/dist/rollup.js
```

I verified that my `.esmrc` is being found by adding an invalid option (esm threw an error for that).  The rollup package.json lists `dist/rollup.js` as the `main` script so I know this is being used instead of the `module` or `jsnext:main` which point to `dist/rollup.es.js`.  When I couldn't get `esm` to look at the `module` field I tried the `cjs` settings which I would expect to make it to find the named export from the CJS module.  This seemed to have no effect though I can verify the following script does not assert:
```js
const assert = require('assert');
const mod = require('rollup');

assert.ok(mod.__esModule === true);
assert.ok(typeof mod.rollup === 'function');
```
So I believe the rollup CJS module contains the correct exports for interop + namedExports to work.

**Comment by jdalton** [comment]
Hi @coreyfarrell!

The `.mjs` file is locked down and will not support any `esm` options. In addition rollup's es6 builds do not export any bindings.

**Comment by jdalton** [comment]
**Update:**

Related to https://github.com/gulpjs/interpret/issues/52.

**Comment by coreyfarrell** [comment]
@jdalton I cannot use `import rollup from 'rollup';` because the rollup ESM module does not provide a default export and babel finds the rollup ESM.  My original plan was that my module's package.json would contain `"main": "index"` without extension but I've had to go with `"main": "index.js", "module": "index.mjs"`.  This way `node -r esm` and `node --experimental-modules` will only find the CJS variant (index.js).  Babel and other tools which look at the `module` field of package.json will load my module's `index.mjs` and then successfully load rollup.

**Comment by jdalton** [comment]
Ah!

In that case you can do
```json
"mainFields": ["module", "main"]
```
and use `.js` instead of `.mjs`. The `esm` loader will not find an `.mjs` file in the `module` field since `.mjs` is locked down, but it will find the `rollup.es.js` in the `"module"` field of rollup. So then 

#### index.js
```js
import {rollup} from 'rollup';
```
would work.
