### ISSUE TITLE
How to import from non-path namespaces

### ISSUE THREAD

**Issue by samselikoff** [standard-things/esm#486]
I'm trying to use esm to read in some ES6 files during the node build of my Ember project.

Currently these ES6 files import from both local paths and from other namespaces:

```js
import foo from './foo';
import bar from 'some-thing/bar';
```

When I try to run esm, the `foo` import works but the `bar` one doesn't. I get the error

> Cannot find module some-thing

I'm not sure how Ember CLI is wiring everything up to make the `some-thing` namespace available as an import, but I'm wondering if it's possible to configure ESM so that it would work for these modules too.

FWIW these modules are all under the current directory where my main module is running – they're under an `/addon` folder. (So for example, the `bar` module from the above example _really_ lives at `./addon/bar.js`.)

(Btw – I have little node experience and if this is a non-standard thing to do I just don't know. I believe these modules are currently resolved in the browser in my app.)

(Update: `some-thing` is the name of the current package, so I guess what I'm asking is how can I use absolute paths starting with the current package name?)

**Comment by dnalborczyk** [comment]
I have not used Ember nor the CLI, but the github readme states that it is using Babel for any ES6 transpilation, which I assume includes ES modules.

The **esm** module (as it stands) can only be used for any code that runs in node.js. Ember code runs  in the browser -- unless Ember also supports SSR (server side rendering) like e.g. React.

**Comment by samselikoff** [comment]
These are modules that run in the browser, but Ember's CLI has node build-time stuff too.

My goal is to grab these modules, and use esm to also make them available to my node-land code (so I can do some build-time stuff with them).

And if I have to change some stuff in how the modules are importing things that's okay too. Just wondering if esm has a way to support it.

**Comment by jdalton** [comment]
Hi @samselikoff!

If you can produce a simple repro I can take a look at it. If Ember is doing some re-wiring behind the scenes we can look into making sure our CJS API contracts are correct-enough for things to just work.

**Comment by dnalborczyk** [comment]
gotcha. In theory that should be doable, but I don't know anything about the Ember-cli. Maybe someone else can chime in.

could you give a concrete example, or maybe a link to a topic of what you are trying to do 
 https://ember-cli.com/

**Comment by jdalton** [comment]
@samselikoff Can you add to the example how ember-cli makes it work with CJS?

**Comment by samselikoff** [comment]
I don't think it does... I think it uses Babel to turn everything into AMD modules, and the imports work at run-time in the browser.

Again my knowledge doesn't go very deep here but that's my understanding. (And if this means these sorts of imports shouldn't be done in node-land that's OK too.)

**Comment by samselikoff** [comment]
And my current attempt of using esm inside my Ember app works, for every module _other_ than the current one. (So `import _pick from 'lodash/pick'` works, for example.)

**Comment by jdalton** [comment]
Ah, AMD does have path aliasing/mapping options. 
You might be able to achieve this with [`module-alias`](https://www.npmjs.com/package/module-alias) or [`link-module-alias`](https://www.npmjs.com/package/link-module-alias).

**Comment by samselikoff** [comment]
Gotcha. Looks like both packages say not to use in libraries, as the behavior won't work when consumed by other libraries/applications.

Guess I'll have to bite the bullet and use relative paths everywhere for now! Thanks for your help.
