### ISSUE TITLE
no "global" object with esm v3.0.56+ and jest

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#487]
this might be a regression from: https://github.com/standard-things/esm/issues/480 with https://github.com/standard-things/esm/commit/bca504a0aaf9f23e04fc6b93baf2484cb91af8f2

problem: an **esm** imported ES6 module has no **global** object when used with **jest**.

edit: repro https://github.com/dnalborczyk/esm-jest-repro/tree/jest-no-global

**Comment by jdalton** [comment]
Interesting!

I added some more tests for globals [here](https://travis-ci.org/standard-things/esm/builds/398887723?utm_source=github_status&utm_medium=notification) which are passing but I can confirm your fail repro too. (I also upgraded my version of jest to 23). Will dig in.

**Comment by dnalborczyk** [comment]
if it helps, downgrading to v3.0.55 works...

**Comment by jdalton** [comment]
I have a fix though I'm still trying to get a repro in my test suite 
(outside of your repo, which does repro).

**Comment by jdalton** [comment]
[v3.0.60](https://github.com/standard-things/esm/releases/tag/3.0.60) is released :tada:
