### ISSUE TITLE
v3.0.61 some globals missing

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#488]
still converting tests to use **esm** and **jest** and noticed that some (other) globals are missing.  😕

scenario is the same as https://github.com/standard-things/esm/issues/487, and the same repro can be used: https://github.com/dnalborczyk/esm-jest-repro/tree/jest-no-global (with v3.0.61, fixes global)

I made a list based of: https://nodejs.org/api/globals.html. not sure if the list is conclusive , nor do I know if everything *even should exist* (e.g. __dirname, require, etc.):

| global object | status |
| ------------- | ------------- |
| Buffer | exists |
| __dirname | exists |
| __filename | exists |
| clearImmediate | exists |
| **clearInterval** | **does not exist** |
| **clearTimeout** | **does not exist** |
| console | exists |
| exports | exists |
| global | exists |
| module | exists |
| process | exists |
| require | exists |
| setImmediate | exists |
| **setInterval** | **does not exist** |
| **setTimeout** | **does not exist** |
| **URL** | **does not exist** |
| **URLSearchParams** | **does not exist** |

in addition:

| global object | status |
| ------------- | ------------- |
| **util** | **does not exist** *(note: global.util does not exist as well)* |

**Comment by jdalton** [comment]
Hmm okay!

Before I was using the global jest provides us (not the real global). It looks like what they are providing is a little incomplete. I can mesh the two globals (using the real global to fill in the gaps of jest).

**Comment by jdalton** [comment]
Thanks for the detailed report btw. It's always super helpful to see something like that.

**Comment by dnalborczyk** [comment]
no problem! same goes back to you, thank you!!!

**Comment by dnalborczyk** [comment]
btw, I forgot to mention, I'm sure you know: **URL** and **URLSearchParams** only exist in node v10+

I also just noticed that **util** is a node.js *global* as well. I'll add it to the list above.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/19efd9acef5d3e38de7239d6bd7e89db83842ba0 and https://github.com/standard-things/esm/commit/508f2ecfb204f76c1d1afc74b4b8ac2778a9d335.

**Comment by jdalton** [comment]
@dnalborczyk 
> just curious, is this reproducible without jest and esm?

I have a few hunches. I suspect it has to do with an object uses as the context for multiple `vm.Script` instances.

**Comment by jdalton** [comment]
**Update:**

[v3.0.62](https://github.com/standard-things/esm/releases/tag/3.0.62) is released :tada:

**Comment by dnalborczyk** [comment]
nice, thanks!! all tests are passing! :smiley:
