### ISSUE TITLE
Thrown Errors cause re-evaluation

### ISSUE THREAD

**Issue by bmeck** [standard-things/esm#49]
Something we could make clearer in Node spec by explicitly stating we are not using `require.cache` rather than implying it.

For Web throwing an error at runtime does not remove ESM from the Module Map. The EP does not mention `require.cache` since it is using its own cache, but we could be clearer that we are not using that & we are matching Web behavior on this.

Will update sometime this week with clearer wording.

```js
// a.mjs
import assert from 'assert';
import('./b').catch(
  err => {
    import('./c').then(
      () => assert.fail('should not re-evaluate same module path')
    )
  }
);
```

```js
// b.mjs
import './c.mjs';
```

```js
// c.mjs
// this should *always* throw errors since it only evaluates once
if (!global.ok) {
  global.ok = true;
  throw new Error;
}
```

**Comment by jdalton** [comment]
Closed by https://github.com/standard-things/esm/commit/f803d23da4510e5c63e89e939d6f65c0968a6f93.
I'll be adding a round of unit tests over the next couple of days to solidify support.
