### ISSUE TITLE
esm+jest tests crash with console.warn()

### ISSUE THREAD

**Issue by Pokute** [standard-things/esm#491]
https://github.com/Pokute/esm-jest-warning-crash

esm+jest tests crash with console.warn()

Run `npm run test` to see output without errors.

Run `npm run test-esm` to see output with `TypeError: stream.removeListener is not a function.` error.

The bug reproduction requires at least two `.test.js` files.

**Comment by jdalton** [comment]
Thanks @Pokute!

I'll dig in.

Minor note: Using `npx` you can make the test invocation:
```
"test-esm": "npx -n='-r esm' jest"
```

**Comment by jdalton** [comment]
[v3.0.63](https://github.com/standard-things/esm/releases/tag/3.0.63) is released :tada:

**Comment by damianobarbati** [comment]
@jdalton may `"setupFiles": "esm"` in jest config be useful to avoid firing jest through npx to use esm?
