### ISSUE TITLE
consider implementing "export namespace from" [proposal]

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#494]
https://github.com/tc39/proposal-export-ns-from (I guess it's not really a proposal anymore, but rather an addition)

related to: https://github.com/standard-things/esm/issues/495

@jdalton since you are also involved in this "proposal" I thought it would be a good idea to spearheading this and add it to `esm` :blush:

it seems there's pretty much consensus in the committee: https://github.com/tc39/tc39-notes/blob/master/es9/2018-05/may-22.md#9ib-normative-add-export--as-ns-from-mod-to-export-production-and-module-semantics and they are waiting for implementers.

If implemented, I think this wouldn't even need to go behind a flag (similar to `dynamic import` and `import.meta`, stage 3)

**Comment by jdalton** [comment]
Yeah, this is a good thing to add support for.

**Comment by jdalton** [comment]
Welcome new core maintainer @dnalborczyk!

If you're up for tackling this the areas to tweak would be 

 * [src/acorn/parser/import.js](https://github.com/standard-things/esm/blob/master/src/acorn/parser/import.js)
 * [src/visitor/import-export.js](https://github.com/standard-things/esm/blob/master/src/visitor/import-export.js)
 * [test/export-tests.mjs](https://github.com/standard-things/esm/blob/master/test/export-tests.mjs)
 * maybe [test/compiler-tests.mjs](https://github.com/standard-things/esm/blob/master/test/compiler-tests.mjs)

**Comment by jdalton** [comment]
From the TC39 meeting this week @leobalter requested implementers take a swing at implementing this, so we can do our part there too.

**Comment by damianobarbati** [comment]
Cool! Do we have this on esm?

**Comment by jdalton** [comment]
@damianobarbati Not yet.

**Comment by jdalton** [comment]
Bugs are now ironed out :tada:
