### ISSUE TITLE
consider implementing "export default from" proposal, stage 1

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#495]
https://github.com/tc39/proposal-export-default-from

related to: https://github.com/standard-things/esm/issues/494

I don't remember if this one was a little bit more controversial, or if it had possible issues. I kinda lost track :/

this could possibly go behind a flag, similar to `top-level-await`, stage 1.

**Comment by jdalton** [comment]
Hi @dnalborczyk!

There were two proposals I assisted in championing last-July. This one, [proposal-export-default-from](https://github.com/tc39/proposal-export-default-from) and [proposal-export-ns-from](https://github.com/spectranaut/proposal-export-ns-from/) _(I should probably support this one)_. The one at stage 1 (`proposal-export-default-from`) is a bit more controversial so would need another champion to take it up _(or I could again)_.

If there's enough user interest in it then I'll consider it, but for now I'd like to hold off.

**Comment by dnalborczyk** [comment]
makes sense. 👍

**Comment by FallingSnow** [comment]
@jdalton What's your position on implementing `export-ns-from`?

**Comment by dnalborczyk** [comment]
@FallingSnow already done: https://github.com/standard-things/esm/releases/tag/3.1.0

**Comment by FallingSnow** [comment]
Awesome! Just realized my `Line 1: Unexpected token as` was actually coming from `esprima`.

Thank you!
