### ISSUE TITLE
Supporting ES5/Browserify?

### ISSUE THREAD

**Issue by mattdesl** [standard-things/esm#497]
I don't know much about this module but it's come up in errors and stack traces multiple times while trying to browserify/bundle different npm modules that rely on it. From a glance at the README it seems like it was not designed to work alongside frontend bundlers, some of which still assume UMD + plain ES5 syntax as a common denominator (and then augment with "modules" package.json field and so forth for more advanced ES6 features).

Is there any plan to support browserify/bankai and similar frontend tools that assume UMD, rather than ES builds?

Here's a couple issues I've filed in other modules that are related to `esm` —

https://github.com/transitive-bullshit/random/issues/3
https://github.com/tmcw/wcag-contrast/issues/35

**Comment by jdalton** [comment]
Hi @mattdesl!

When you use `npm init esm` or `yarn add esm` the `package.json` is initialized with the `module` field that points to the ESM entry `main.js` _(bypassing the `index.js` bridge)_. For browser use with browserify/webpack you can use  the `browser` field in the same way.

**Comment by jdalton** [comment]
**Update:**

I've updated [`create-esm`](https://github.com/standard-things/create-esm) which is used by `npm init esm` and `yarn create esm` to add the `browser` field as well as the `module` field.
