### ISSUE TITLE
Error message TypeError: Cannot read property 'module' of undefined

### ISSUE THREAD

**Issue by koolkt** [standard-things/esm#499]
With version =< 3.0.64 I get the error message ```TypeError: Cannot read property 'module' of undefined```

I run ```node -r esm ./src/index.js``` where index.js contains just ```console.log('Helo world')```

Everything works fine with evrsion 3.0.63

Does anyone knows why that is?

Thank you.

**Comment by jdalton** [comment]
Hi @koolkt!

Could you create a simple repro repo.
I did touch bits around `console` so it is likely a regression.

**Comment by koolkt** [comment]
Its litterally just ```console.log('Hello world')``` the only module installed is esm.
But when I try to use versions after 3.0.63 on more complex projects I have a lot of errors with modules not found. Do you still want me to create the repo?
Thanks.

**Comment by jdalton** [comment]
Yes please. I cannot repro locally

**Comment by borisding** [comment]
HI,

I'm having issue with `module` stuff after upgrading to the latest version (also verified with version 3.0.64), which is causing error for `module-alias` that I'm using. 

Note sure if this is the same with reported issue here.

Created a simple repo for you to verify: https://github.com/borisding/test-esm.git

Thanks!

**Comment by jdalton** [comment]
**Update:**

Reproduced it with Node 6 👍

**Comment by borisding** [comment]
Hi @jdalton ,

>  What version of Node are you seeing the issue on?

it's with Node 8 on both platforms. FYI.

Thanks!

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/074f0fbda55cfb6b0152a3269396d918d7d9e53b; Test https://github.com/standard-things/esm/commit/ed1c8561e98999bc22986c6de79cd0d9aa987dd0;

**Comment by jdalton** [comment]
**Update:**

[v3.0.66](https://github.com/standard-things/esm/releases/tag/3.0.66) is released 🎉
