### ISSUE TITLE
esm@3.0.71 is failed with express with pm2

### ISSUE THREAD

**Issue by silveryiris** [standard-things/esm#504]
It's failed with `esm`@3.0.71 but successes with `esm`@3.0.70
`pm2` will startup as normal but failed after a few seconds.

## Environment
`node` version 10.6.0
`npm`@6.2.0
`pm2`@2.10.4

Ubuntu server 18.04

## Represent bug repository
https://github.com/silveryiris/esm-error-with-pm2

`npm run start` 
 => `pm2 start server/server.js --node-args='-r esm'`

## Used packages
    "esm": "^3.0.71",
    "express": "^4.16.3",
    "pug": "^2.0.3"

**Comment by jdalton** [comment]
Thanks @silveryiris!

**Comment by jdalton** [comment]
Narrowed it down to this commit https://github.com/standard-things/esm/commit/e2d0f6d0e0f28e9831dc73b29c1cdc3ba88aa014.

**Comment by jdalton** [comment]
Tests https://github.com/standard-things/esm/commit/141f5787047ea6a138454c56089e09873793a898.

**Comment by jdalton** [comment]
**Update:**

[v3.0.72](https://github.com/standard-things/esm/releases/tag/3.0.72) is released :tada:
