### ISSUE TITLE
Enable REPL hook when loaded via --require

### ISSUE THREAD

**Issue by frangio** [standard-things/esm#51]
Running `node -r @std/esm` doesn't enable the REPL hook like `require('@std/esm')` does.

Some of the following properties don't have the same values in the former case:
https://github.com/standard-things/esm/blob/e458cd6fcd945630a1441ae41ddf491088a63377/src/hook/repl.js#L18-L22

In particular, `rootModule.id` is `'internal/preload'` instead, and `rootModule.parent` is `null` (instead of `undefined` 😕). The rest are the same.

**Comment by jdalton** [comment]
Ah neat!

**Comment by frangio** [comment]
I tried changing the `if` to also accept those values but it doesn't seem to work. There must be a problem elsewhere too. It'd be nice to be able to load it like this too. 🙂

**Comment by Jamesernator** [comment]
I hit this as well trying to create a script to `node --require "$NODE_GLOBAL/lib/node_modules/@std/esm/"`.

An official cli REPL would be nice similar to babel's `babel-node` but for `@std/esm`, maybe if `@std/esm` is installed globally it could add a `esm-node` or something like that.
