### ISSUE TITLE
instanceof return failed for module 'readable-stream' PassThrough and core module 'stream' Stream

### ISSUE THREAD

**Issue by dtrung127** [standard-things/esm#510]
I have a problem when using `esm` with `instanceof` operator as in the following code:

```javascript
const Stream = require('stream').Stream;
const PassThrough = require('readable-stream').PassThrough;
new PassThrough() instanceof Stream
```
The `instanceof` operator return `true` when running without `esm`. But it return `false` when running with `esm`

**Comment by dnalborczyk** [comment]
thank you @dtrung127 !

repro: https://github.com/dnalborczyk/esm-repros/tree/issue-510

**Comment by jdalton** [comment]
[v3.0.72](https://github.com/standard-things/esm/releases/tag/3.0.72) is released :tada:
