### ISSUE TITLE
esm@3.0.71 is failed with nyc / mocha 

### ISSUE THREAD

**Issue by regseb** [standard-things/esm#511]
_esm_ used with _nyc@13.0.0_ and _mocha@5.2.0_ is failed in 3.0.71 and successes in 3.0.70. Maybe the same problem as in https://github.com/standard-things/esm/issues/504.

To reproduce : [testcase.tar.gz](https://github.com/standard-things/esm/files/2211083/testcase.tar.gz). Execute `npm test` (`nyc --require esm mocha test.js`) and `"foo"` isn't display.

* _node_ : v10.7.0
* _npm_ : 6.2.0

**Comment by jdalton** [comment]
Yep, imma lump them together.

**Comment by jdalton** [comment]
**Update:**

[v3.0.72](https://github.com/standard-things/esm/releases/tag/3.0.72) is released :tada:
