### ISSUE TITLE
Deeper import wipes out process.env.* set in previous imports

### ISSUE THREAD

**Issue by deepj** [standard-things/esm#515]
Hello,
I guess this is a problem of esm. I guess esm causes this behaviour.

I have this tree of import which is loaded by mocha.

**/test/mocha.opts**

```
--require esm
--require ./test/init
--file ./test/global-hooks.js
--recursive
--check-leaks
```

**/test/init.js**
```js
// Enforce NODE_ENV to test environment for all tests.
process.env.NODE_ENV = 'test'

import Sinon from 'sinon'
import SinonChai from 'sinon-chai'
import Chai from 'chai'
import ChaiAsPromised from 'chai-as-promised'
import ChaiHTTP from 'chai-http'
import ChaiJSONSchemaAJV from 'chai-json-schema-ajv'
import knexInit from '../db/knexInit'
```

**/db/knexInit.js**

```js
import Knex from 'knex'
import { Model } from 'objection'
import knexConfig from '../knexfile'

const init = () => {
  console.log(process.env.NODE_ENV) // test
  const knex = new Knex(knexConfig)

  Model.knex(knex)
}

export default init
```

**/knexfile.js**

```js
// See https://github.com/tgriesser/knex/issues/1232
module.exports = require('./db/knexConfig').default
```

**/db/knexConfig.js**
```js
import {
  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_USER,
  DATABASE_NAME,
  DATABASE_PASSWORD,
  DATABASE_URL,
  DATABASE_SSL_FLAG,
  DATABASE_POOL_MIN,
  DATABASE_POOL_MAX,
} from '../config'

console.log(`knexConfig: ${process.env.NODE_ENV}`) // test
```

**/config/index.js**

```js
console.log(`in test: ${process.env.NODE_ENV}`) // undefined

const ENVIRONMENT = process.env.NODE_ENV || 'development'
process.env.NODE_ENV = ENVIRONMENT

if (['development', 'test'].includes(ENVIRONMENT)) {
  /* eslint-disable global-require */
  const dotenv = require('dotenv-flow')

  dotenv.config()
}
```

This is not a problem if I have this.

**/test/mocha.opts**

```
--require esm
--require ./test/env
--require ./test/init
--file ./test/global-hooks.js
--recursive
--check-leaks
```

I just added `/test/env.js` where I have only this.

```
// Enforce NODE_ENV to test environment for all tests.
process.env.NODE_ENV = 'test'
```

This block is removed from `/test/init.js`

Then in `/config/index.js` `process.env.NODE_ENV` is set to `test` correctly instead of `undefined` .

```js
console.log(`in test: ${process.env.NODE_ENV}`) // test

const ENVIRONMENT = process.env.NODE_ENV || 'development'
process.env.NODE_ENV = ENVIRONMENT

if (['development', 'test'].includes(ENVIRONMENT)) {
  /* eslint-disable global-require */
  const dotenv = require('dotenv-flow')

  dotenv.config()
}
```

I hope the description above is good enough :)

**Comment by deepj** [comment]
@jdalton here https://github.com/deepj/esm-import-process-bug

Let me know if you need something from my side.

**Comment by deepj** [comment]
I totally forgot to mention I use `esm 3.0.72`

**Comment by jdalton** [comment]
Thank you @deepj! I'll dig into this soon.

**Comment by jdalton** [comment]
Okay @deepj!

After digging into this I spotted a problem in your test scenario [here](https://github.com/deepj/esm-import-process-bug/blob/8b4583e3aac52e419d961db3ba998cc28d6d75d6/import-process-fail/test/init.js#L1-L5)
```js
// Enforce NODE_ENV to test environment for all tests.
process.env.NODE_ENV = 'test'

import Chai from 'chai'
import knexInit from '../db/knexInit'
```

The static imports are hoisted (by spec) before the `process.env.NODE_ENV = 'test'` assignment which is why you're seeing the values you are. You can avoid this by moving your test environment setup to its own module and statically importing it before the others or using dynamic import to load the other modules.

**Comment by deepj** [comment]
@jdalton OK, thanks for explanation and your help. Could you forward me to the spec, please? I'd like to learn more about that. I saw more people to do the same thing.

BTW: I come from Ruby land where I can freely use

**./spec_helper.rb**

```ruby
ENV['RACK_ENV'] = 'test'

require_relative('something/else/script.rb') 
```

**./something/else/script.rb**

```ruby
puts ENV['RACK_ENV']
```

In this case I'll see 'test' in the output.
