### ISSUE TITLE
Circular dependencies 3.0.71 -> 3.0.72

### ISSUE THREAD

**Issue by timoxley** [standard-things/esm#519]
https://github.com/timoxley/esm-symlinks-test

This repo has a few symlinked packages, `a`, `b`, `c`:
```js
  "dependencies": {
    "esm": "3.0.72",
    "a": "file:./a",
    "b": "file:./b",
    "c": "file:./c"
  }
```
These packages depend on each other:
```js
// ./a/index.js:
import 'b'
import 'c'
console.log('A')
```
```js
// ./b/index.js:
console.log('B')
```
```js
// ./c/index.js
import 'a'
console.log('C')
```

```js
// ./root.js
import 'c'
import 'b'
import 'a'
console.log('ROOT')
```

Try checkout the above repo then `npm install` then `npm test`, which runs `./root.js` under `esm`.

It will spit out a bunch of stuff like:

```
B
B
B
B
A
C
A
C
A
C
A
C
A
C
A
C
A
C
```

Afterwards, change the version of `esm` in `package.json` to `3.0.71`, `npm install` again and try `npm test`, it will spit out:

```
B
A
C
ROOT
```

The new behaviour in `3.0.72` is breaking my app because previously "singleton" modules (e.g. db drivers & loggers) are now being reevaluated multiple times and are creating different instances when they definitely should not.

Not sure which behaviour is more spec compliant but I'm hoping the `3.0.72` changes are in error.

**Comment by jdalton** [comment]
Hi @timoxley!

Likely a dup of #514 (seems to be working with the master branch.
