### ISSUE TITLE
__dirname is not defined

### ISSUE THREAD

**Issue by vaclav-purchart** [standard-things/esm#52]
It seems that standard nodejs constants are not accessible inside transcripted code.

**Steps to reproduce:**
file: main.mjs
`console.log(__dirname)`

**Actual result:**
> `ReferenceError: __dirname is not defined`

**Expected result:**
> prints a valid directory

**Comment by bmeck** [comment]
This behavior is correct as per the EP : https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#451-environment-variables

Please wait until `import.meta.url` is standardized for having similar capibilities in ESM. You can import CJS variables by exporting them from CJS files for now.

```js
// main.mjs
import variables from './cjs.js';
const {__dirname} = variables;
console.log(__dirname);
```

```js
// cjs.js
module.exports = {__dirname, __filename, require};
```

**Comment by jdalton** [comment]
Hi @vaclav-purchart!

You can also [unlock](https://github.com/standard-things/esm#unlockables) CJS features like `__dirname` and others with the `"cjs":true` option.

**Comment by Firanolfind** [comment]
Hi @vaclav-purchart ,
try this variant

```
import Path from 'path';
const __dirname = Path.resolve();
console.log(__dirname);
```
