### ISSUE TITLE
Loading basically anything using esm with a pnpm installation fails

### ISSUE THREAD

**Issue by onlywei** [standard-things/esm#520]
Please see this repro: https://github.com/onlywei/repro--pnpm-esm-rollup-plugin-yaml

I've narrowed this down to only happening in version 3.0.72 and it does not happen in 3.0.71.

**Comment by jdalton** [comment]
Hi @onlywei!

Dup of #514.

**Comment by jdalton** [comment]
**Update:**

[v3.0.73](https://github.com/standard-things/esm/releases/tag/3.0.73) is released :tada:
