### ISSUE TITLE
reference mismatch with esm imports and hapijs/lab

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#524]
Just for fun I pulled down and converted [`hapi`](https://github.com/hapijs/hapi) to use es modules with `esm`, and to my surprise, the test suite running with [`lab`](https://github.com/hapijs/lab) converted to use es-modules worked out-of-the-box with `esm` as well !! Really amazing!!! :smiley:

the test suite produced one single bug. Not sure if that is a `lab`-specific issue.

**repro in the works ...**

_speaking of amazing: debugging the failed test case with [ndb](https://github.com/GoogleChromeLabs/ndb) was short of amazing as well!! just worked out-of-the-box with `esm`!!_

**Comment by jdalton** [comment]
Thanks for digging in! Do you know off hand what the reference mismatch was with.
I've seen it in the past with some things so have some idea.

**Comment by dnalborczyk** [comment]
I literally thought I had it ... and then it slipped away.
sometimes I have the feeling `esm` is self-healing :smiley:

I might have to check in the converted `hapi` repo for you to have a look at.

**Comment by dnalborczyk** [comment]
here is a repo of the above "issue", although I'm not sure if it really is an issue - but it might help to uncover some underlying or hidden problem when `esm` is being used programmatically and with the cli.

https://github.com/dnalborczyk/esm-repros/tree/issue-524

when you run the tests with `npm test`, they will pass. you have to [comment out this line](https://github.com/dnalborczyk/esm-repros/blob/issue-524/test/test-2.js#L6) to make it fail.

**Comment by dnalborczyk** [comment]
btw, the `hapi` tests with `lab` are fully succeeding!!

@jdalton don't spend any time on this if you see no value. it's clearly being used in a way it wasn't meant to be.

**Comment by jdalton** [comment]
This is an interesting issue in how we share and access state. It's a legit bug. In the deferred getter for the builtin entries I don't check if the entry has already been created (I assume if it had a deferred getter added that means it wasn't found in the cache). However, in this case the deferred getter is added in one place and before the getter is tripped (to create the entry) the entry is created in another.
Checking the builtin cache before creation on the getter resolves the issue.

**Comment by jdalton** [comment]
test debt 💰💰

**Comment by jdalton** [comment]
**Update:**

@dnalborczyk I'm adding a new label to issues that I have not added tests for. You can follow along with [this query](3A). We'll remove the label from issues as the test addition PRs are merged.

**Comment by dnalborczyk** [comment]
@jdalton  good idea! :+1:

**Comment by jdalton** [comment]
@dnalborczyk I fixed the query link. Some of them, like the Electron ones, aren't practical to test in an automated way but are good to be aware of.
