### ISSUE TITLE
Mocha Testing

### ISSUE THREAD

**Issue by mansona** [standard-things/esm#53]
Hey folks 👋 

First of all, fantastic library 🎉  thanks a million!

I'm a little bit stuck on converting a 'common' internal library and running the embedded mocha tests. My first attempt was to convert **everything** including the mocha tests to .mjs but then it looks like mocha looses track of the `describe()` statements that are defining the tests.

So at this stage I was thinking "maybe mocha tests need to be run the Old Fashioned Way™️" and I converted my mocha tests back to .js files and imported the Module Under Test using your fancy "bridge" method in index.js: 

```
require('@std/esm');
module.exports = require('./main.mjs').default;
```

but then the runtime starts to fall over and give me things like: 

```
  1) <test name> Uncaught error outside test suite:
     Uncaught TypeError: Cannot convert object to primitive value
```

I figure I'm on the edge of what is possible right now because it is likely that the Mocha team need to add some support for this but I'm wondering if anyone has had any success so far? If we could put together a simple mocha testing example I can work up from there 👍

**Comment by tilgovi** [comment]
For your second approach, watch for #15 to be closed.

**Comment by jdalton** [comment]
Hi @mansona!

For mocha you can use the `mocha --require @std/esm path/to/test.js` in combo with the `@std/esm` option of:
```
"@std/esm": "js"
```
In your package.json.

**Comment by mansona** [comment]
Didn't have to watch for long 😂  I'll try it now and report back 👍
