### ISSUE TITLE
cache: no persistence when app is being terminated

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#530]
`node` v10.7.0
`esm` 3.0.72

it seems that caching files are being flushed out and persisted when the process exits.

no caching files are being created when the process is being terminated.

repro:
```javascript
setTimeout(() => void 0, 100000)
```

```shell
kill -TERM pid
```

e.g., if one develops with `control+c` (SIGINT), one would never get any caching files.

`esm` could either flush the files right away when generated, or intercept (listen to) the kill signal. not quite sure which would be better. kinda leaning towards sooner than later, but I don't know about any possible performance implications.

**Comment by jdalton** [comment]
We want to defer this to app ending/exiting. We currently listen to `on("exit")`
https://github.com/standard-things/esm/blob/1271c2dac60864b6bfa8fe0997cd7eb6a0bdda5d/src/caching-compiler.js#L240-L241

So something to tie that to the SIGINT would be preferable.

**Comment by dnalborczyk** [comment]
do you think "extracting" the handler and attaching it to the signal events is enough?

```javascript
  function handleExit() {
    // ...
  }

  realProcess
    .once("exit", handleExit)
    .once("SIGINT", handleExit)
    .once("SIGTERM", handleExit)
```

**Comment by dnalborczyk** [comment]
> I'm sure sindresorus has one

true that :smiley:

I started writing some `cache` tests, and there seems to be some weird edge cases (tested manually).
I file them the next coming days ...

**Comment by jdalton** [comment]
Cool!

BTW are you done with the `scenario-tests` branch? For future use you could create the branches on your git fork then pull them over in a PR to avoid adding them to the primary repo.

**Comment by dnalborczyk** [comment]
ah, ok. no problem. I'll remove it. not happy with it [yet]...

**Comment by dnalborczyk** [comment]
nice!!

I can add some tests to my `cache` tests if needed?

**Comment by jdalton** [comment]
Yes, please. I'll not likely turn down tests.

**Comment by jdalton** [comment]
**Update:**

[v3.0.72](https://github.com/standard-things/esm/releases/tag/3.0.73) is released :tada:
