### ISSUE TITLE
esm breaks for mapbox-gl-js between v3.0.49 and v3.0.50

### ISSUE THREAD

**Issue by mourner** [standard-things/esm#533]
We're relying on `esm` for tests in [mapbox-gl-js](https://github.com/mapbox/mapbox-gl-js), and so far it has been working great, but it broke somewhere between v3.0.49 and v3.0.50. Sorry for an involved test case:

- Clone https://github.com/mapbox/mapbox-gl-js
- Set "esm": "3.0.50" in `package.json`
- Run `yarn`
- Run a test with `./build/run-node test/unit/style/style.test.js` (`./run-node` is running node with `flow-remove-types` and `esm`)

With v3.0.50, there's the following error (turned on `debug: true`):

```
→ ./build/run-node test/unit/style/style.test.js 

/Users/mourner/projects/mapbox-gl-js/src/index.js:37
    Style,
                ^
/Users/mourner/projects/mapbox-gl-js/src/index.js:37
ReferenceError: Style is not defined
    at Object.<anonymous> (/Users/mourner/projects/mapbox-gl-js/src/index.js:37:17)
    at sl (/Users/mourner/projects/mapbox-gl-js/node_modules/esm/esm.js:1:196539)
    at Object.run (/Users/mourner/projects/mapbox-gl-js/node_modules/esm/esm.js:1:195899)
    at Object.<anonymous> (/Users/mourner/projects/mapbox-gl-js/src/index.js:1:86)
    at Module.<anonymous> (/Users/mourner/projects/mapbox-gl-js/node_modules/esm/esm.js:1:210830)
    at Xl (/Users/mourner/projects/mapbox-gl-js/node_modules/esm/esm.js:1:204717)
    at /Users/mourner/projects/mapbox-gl-js/node_modules/esm/esm.js:1:206276
    at ru (/Users/mourner/projects/mapbox-gl-js/node_modules/esm/esm.js:1:206512)
    at Module.g (/Users/mourner/projects/mapbox-gl-js/node_modules/esm/esm.js:1:216451)
    at Module.Rn.u._compile (/Users/mourner/projects/mapbox-gl-js/node_modules/esm/esm.js:1:65330)
```

v3.0.72 has the same error. With v3.0.49, it runs without errors. We've only noticed now because `Yarn.lock` was pinned to v3.0.39 which works correctly too.

Looking at commits, it might have something to do with cycle detection? Not sure.

**Comment by dnalborczyk** [comment]
it's definitely a `circular dependency` issue.

if you'd remove https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/worker_pool.js#L8 the issue goes away.

node `--experimental-modules` throws he same:
```shell
(node:47117) ExperimentalWarning: The ESM module loader is experimental.
ReferenceError: Style is not defined
    at file:///mapbox-gl-js/src/style/style.mjs:3:16
    at ModuleJob.run (internal/modules/esm/module_job.js:96:12)
```

**Comment by jdalton** [comment]
Thanks for opening an issue @mourner!

The diagnosis from @dnalborczyk sounds correct. The good news is now I think any further progress on being more correct for circular references will allow some code paths instead of restrict so less likely to have bad code slip by.

To avoid this circular reference you can break it down to smaller shared parts. For example you could create a data module that has the `workerCount` in it that is used by `mapboxgl` and the `worker_pool`.

Related to #481.

**Comment by mourner** [comment]
@dnalborczyk @jdalton thanks so much for the help! This is definitely an issue on our side, sorry for not investigating deeper this before reporting. I just automatically assumed it's a bug because it worked before, but it's great that it's more aligned with the spec now.

**Comment by dnalborczyk** [comment]
@mourner  no problem!
> I just automatically assumed it's a bug because it worked before

I probably would have assumed the same.

btw, I think https://github.com/mapbox/mapbox-gl-js/blob/master/package.json#L113 has no meaning anymore (or it's _true_ by default now -- not sure what the option was about).
