### ISSUE TITLE
top level async iterator

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#534]
not sure if this is a bug or a feature request - or neither: not sure if `async iterators` is part of the `top-level-await proposal`.

```javascript
const imports = [
  import("./a.js"),
  import("./b.js")
]

for await (const i of imports) {}

// throws: 
// for await (const i of imports) {}
//    ^
// SyntaxError: Invalid or unexpected token
//      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/f13ed28bdc0f7d30e0b9134d52a8b67b06dfdfb4; Related to https://github.com/acornjs/acorn/pull/712.

**Comment by dnalborczyk** [comment]
@jdalton   thanks for the quick implementation!!

uh, I think we need a condition for node `v10+` support only in the tests. I'll add it soon...

btw, do you think it needs to be fixed on the babel side of things as well? https://github.com/babel/babel/pull/7637

**Comment by jdalton** [comment]
No need, I have it fixed locally.

**Comment by jdalton** [comment]
Good catch on the babel side. Pinging them with a bug isn't a bad idea.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/7abe703cf53f1857cee53b3061ee49278382d221.

**Comment by jdalton** [comment]
**Update:**

[v3.0.73](https://github.com/standard-things/esm/releases/tag/3.0.73) is released :tada:
