### ISSUE TITLE
Issue with obtaining named exports from CommonJS modules

### ISSUE THREAD

**Issue by spencerwilson-optimizely** [standard-things/esm#536]
Repro repo: https://github.com/spencerwilson-optimizely/esm-issue

That has two modules, `index.js` and `index.mjs` that each try to import a named export from the CommonJS module `math.js`.

When trying to `import { add }` from math.js,
```
SyntaxError: Missing export name 'add' in ES module: file:///Users/swilson/code/ava-test/src/math.js
```
(using node 10.7.0, npm 6.1.0)

I'm not totally sure if it's a bug or within the purview of `esm` to use `import` statements against CommonJS modules.

Please let me know if I can provide any other info. Thanks!

**Comment by spencerwilson-optimizely** [comment]
bah, I guess it's because from the POV of ES modules, CommonJS modules only have a default export, not named exports. Which makes sense, since CommonJS modules may have an export _named_ `default`, and there's no way to backwards-compatible way to support both that and promoting all of the exports to named exports as well.

Perhaps this issue could be considered a request to clearly document this behavior? Would you accept a PR doing so?

**Comment by jdalton** [comment]
Hi @spencerwilson-optimizely!

This is by design. The `.mjs` file extension is locked down 🔒 and will not respect any `esm` options. If you want CJS/ESM interop you should use `.js` instead and things will just work.
