### ISSUE TITLE
exported default function (incl. async+generator) has wrong `name` property

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#538]
_divided it up into 2 bugs_

repro:

```javascript
// test.js
export default function () {}
// export default function * () {} // same
// export default async function () {} // same
// export default async function * () {} // same
```

```javascript
import assert from 'assert'
import test from './test.js'

assert.strictEqual(test.name, "default")

// + expected - actual
// - 'default‍'  <- the `t` seems to be "slightly" off
// + 'default'

assert.strictEqual(test.name.length, "default".length)
// + expected - actual
// - 8
// + 7
```

seems like some [unwanted] character sneaked in ... :grinning:

works with `--experimental-modules`

**Comment by dnalborczyk** [comment]
just digged through the [code a bit](https://github.com/standard-things/esm/blob/master/src/visitor/import-export.js#L21).

related: https://github.com/standard-things/esm/issues/183 https://github.com/standard-things/esm/pull/187

**Comment by jdalton** [comment]
Yep, I have a local patch should get it pushed today.

**Comment by dnalborczyk** [comment]
amazing job!!! `esm` is becoming **rock-solid**!!

I have one more `star import` related bug. I'll file it in a minute.

btw, do you have a time frame in mind for a release? I can't remember a release with [so many days and commits](https://github.com/standard-things/esm/releases/tag/3.0.72) passing by without a release. :grimacing:

**Comment by jdalton** [comment]
I'll try to cut a release this evening.
