### ISSUE TITLE
Add web mode?

### ISSUE THREAD

**Issue by justinfagnani** [standard-things/esm#54]
On the web, any import, no matter the extension of the file, is loaded as a module.

Could esm add a web mode so that behavior is preserved? This would make it easier for web-compliant modules to be used in node.

**Comment by jdalton** [comment]
Hi @justinfagnani!

The web has the out-of-band signal of the `type="module"` attribute. With `@std/esm` you can [unlock](https://github.com/standard-things/esm#unlockables) unambiguous parsing so files with   `import`/`export`/`"use module"` are treated as ESM

**Comment by justinfagnani** [comment]
@jdalton oh that's awesome!

So the other thing I'd want for a web-compatible mode is to disallow named imports and require all import specifiers start with "./", "../", or "/". What do you think about an unlockable feature for that?

**Comment by jkrems** [comment]
Would "starts with /" actually do anything reasonable for a web-compatible module? Especially in absence of `import.meta.url`?

**Comment by citycide** [comment]
@justinfagnani I think for web compat you'd also need to require extensions in the import url.

```js
import thing from './this-file.js'
```

And what's wrong with named imports? I'm not aware of that being disallowed in browsers.

**Comment by justinfagnani** [comment]
@citycide names are definitely disallowed by browsers. They have no way to resolve them. See tep 2 here: https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier

**Comment by justinfagnani** [comment]
Also, an extension isn't required, but no resolution of the specifier should happen. If the file actually doesn't have an extension, that's fine.

**Comment by jdalton** [comment]
You can write Node esm modules in a way that's web compatible. I've done this for [lodash-es](https://www.npmjs.com/package/lodash-es). I think a lint plugin is more appropriate for enforcing web compat rules.

**Comment by citycide** [comment]
@justinfagnani 

> names are definitely disallowed by browsers. They have no way to resolve them. See step 2 here: html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier

Ah, terminology mixup... I was thinking `import { a } from` as 'named imports'.

@jdalton I agree and think `esm` should stay focused on Node as that's the problem domain here.

**Comment by tilgovi** [comment]
I've been looking at similar thoughts and found that eslint-plugin-import has an extensions setting you can use to force use of explicit extensions. It won't do the path bit out of the box, but it does have pluggable resolvers. With a simple URL resolver that doesn't do any modules folder resolving, this could be made to work outside @std/esm, in the linter.

**Comment by justinfagnani** [comment]
@citycide as for domain, since npm is increasingly used for front-end packages, we may need a way to load web-compatible modules in node even after node gets native module support. The project could be used as a way to shim web-compatible behavior onto node no matter what node decides to do.

**Comment by bmeck** [comment]
@justinfagnani I would suggest moving the web forward with some form of aliasing manifest or hook as has been talked about in the past several times.

**Comment by justinfagnani** [comment]
@bmeck I don't have much control over what the web or node does, I'm just stuck in the middle.

And, I would also suggest that node figure out a way to do modules in a way at least somewhat more compatible with the web, like treating any imports as to a module, and not allowing imports of CommonJS, since they don't actually buy you much anyway. Then we don't have to worry about code that tries to import non-modules on the web, and we can at least shim `require` to read from a pre-compiled bundle of CJS.

**Comment by bmeck** [comment]
@justinfagnani we have had this discussion many times over. we can discuss it again somewhere else if you want.
