### ISSUE TITLE
tc39/test262

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#543]
I took a stab at running `esm` against the **ECMA Test Suite** [tc39/test262](https://github.com/tc39/test262) and it's looking pretty darn good so far!!

I included only https://github.com/tc39/test262/tree/master/test/language/module-code [for now]

I also added the `"use modules"` pragma, since otherwise `esm` thinks of some files as `cjs modules`. that being sad, I'm still thinking that behavior should be changed for the longer good  :confused:

`236` tests are `passing`
`16` tests I marked `pending` (in order to investigate)

out of the `16 pending` are:
- 4 tests using [export * from ns](https://github.com/standard-things/esm/issues/494)
- [1 test](https://github.com/tc39/test262/blob/master/test/language/module-code/privatename-valid-no-earlyerr.js) uses a `stage 3` private class fields

- some others seem like legit bugs, I'll report back here.

@jdalton regarding `private class fields`, would you rather have users go through Babel for syntax parsing and/or compilation? Which I believe the Babel plugin is not quite ready yet, but I sense it'll be _very soon_. There's also already several `--harmony` flags regarding private fields in node v10+ (for V8). (not quite sure why there is more than one flag though, I haven't looked into the differences).

I'm in the midst of automating the test run, so we can include it in the `esm test suite`. there's some small portions missing, plus the code needs some serious TLC.

_PR coming ..._

**Comment by dnalborczyk** [comment]
TODO: reminder for `dynamic imports`: https://github.com/tc39/test262/pull/1588

we could run against this branch temporarily and see what it does (and whitelist/blacklist if needed)

**Comment by jdalton** [comment]
@dnalborczyk 

WOW!!!!!!!!! 

This is so nice! I'm floored here. Thank you so much for digging into this!

> 1 test uses a stage 3 private class fields

We [should parse](https://github.com/standard-things/esm/blob/master/src/acorn/parser/class-fields.js) private class fields, so if it's erroring there then that's a bug on us. The rest is up to Node with the `--harmony` flag. We don't transform syntax beyond ESM support and rely on Node for support of object rest/spread, async, async generators, BigInt, etc.

**Comment by jdalton** [comment]
> I also added the "use modules" pragma, since otherwise esm thinks of some files as cjs modules. that being sad, I'm still thinking that behavior should be changed for the longer good

Instead use the `.mjs` extension. It's strict mode and should be fine for conformance testing.

**Comment by jdalton** [comment]
Moved to #550.

**Comment by dnalborczyk** [comment]
> This is so nice! I'm floored here. Thank you so much for digging into this!

thank you!! much appreciated!  👍 

> Oh, I see now. When testing locally changing all the extensions might be a pain and a quick "use module" addition is nice since you don't have to track down all the deps and rename them.

that wouldn't be a problem as well, the way the test run is setup. I just have a **really** distaste of 'mjs'. :confounded:

> The test262 tests are probably assuming some out-of-band way to signal that the parse goal is "module". With browsers that's the type="module" attribute. With Node --experimental-modules it's .mjs (though more ways to signal are coming). The esm loader allows signaling the "module" goal with a variety of options, including the "use module" directive.

ah, thank you! I'll get back to you with some thoughts on that later! I'm probably missing some things for the whole picture.

> We should parse private class fields, so if it's erroring there then that's a bug on us. The rest is up to Node with the --harmony flag. We don't transform syntax beyond ESM support and rely on Node for support of object rest/spread, async, async generators, BigInt, etc.

I probably forgot the `--harmony` flag in the test run then if it's supported by `esm`. I didn't look into it at the time at writing who was throwing (`esm` vs. `node`)

**Comment by jdalton** [comment]
The `esm` loader now passes all applicable test262 tests :tada:

**Comment by dnalborczyk** [comment]
yeah, I noticed!

absolutely amazing job!!!  🎉🎊
