### ISSUE TITLE
test262 bug: multiple visited star cycle export

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#544]
[opening seperate issues for tracking purposes]

>     Modules can be visited more than once when resolving bindings through
>     "star" exports as long as the exportName is different each time.

test case:
https://github.com/tc39/test262/blob/master/test/language/module-code/instn-iee-star-cycle.js

```shell
SyntaxError: Missing export name 'y' in ES module: file:///test262/test/language/module-code/instn-iee-star-cycle-2_FIXTURE.js
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by jdalton** [comment]
Thanks @dnalborczyk!

This comes down to a validation glitch on our part. The good news is the `y` export is being resolved. It's just our check needs adjusting.

**Comment by jdalton** [comment]
**Update:**

I have this patched locally.
