### ISSUE TITLE
test262 bug: trailing comma in export declaration

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#545]
[opening seperate issues for tracking purposes]

> ExportsList in ExportDeclaration may include a trailing comma

test case: https://github.com/tc39/test262/blob/master/test/language/module-code/instn-iee-trlng-comma.js

```javascript
export { a , } from './instn-iee-trlng-comma_FIXTURE.js';
export { a as b , } from './instn-iee-trlng-comma_FIXTURE.js';
```

```shell
assert.sameValue(a, 333, 'comma following named export');

ReferenceError: a is not defined
      at file:///test262/test/language/module-code/instn-iee-trlng-comma.js:129:24
      at Generator.next (<anonymous>)
```

**Comment by jdalton** [comment]
This isn't about the trailing comma. It's the self circular reference if I had to guess.

**Comment by jdalton** [comment]
Confirmed this bug is a dup of #544.
