### ISSUE TITLE
test262 bug: named export without an exports list

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#546]
[opening seperate issues for tracking purposes]

> A NamedExport without an ExportsList contributes to the list of requested
    modules

test case:
https://github.com/tc39/test262/blob/master/test/language/module-code/instn-resolve-empty-export.js

```shell
ReferenceError ::  file:///test262/test/language/module-code/instn-resolve-empty-export_FIXTURE.js:113
0++;
^
SyntaxError: Assigning to rvalue
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by jdalton** [comment]
I believe the reference error is the expected result. What do you interpret the expected result to be?

**Comment by jdalton** [comment]
Side note, acorn's parse errors are not as pretty as native. I've tried to improve them when I can. This is a case where builtin is much nicer

```js
0++;
```
Acorn: SyntaxError: Assigning to rvalue
Chrome: Invalid left-hand side expression in postfix operation

**Comment by jdalton** [comment]
ahh and I just caught the bug. Acorn is throwing a syntax error instead of a reference error.

**Comment by jdalton** [comment]
Filed this as an acorn bug https://github.com/acornjs/acorn/issues/714.

**Comment by jdalton** [comment]
If the acorn bug is not addressed (in a reasonable time) I'll look into tackling it with a plugin.

**Comment by dnalborczyk** [comment]
ah, yeah, sorry, I should have mentioned the `ReferenceError` vs. `Syntax Error`.

I logged the expected exception from the test case, which, I just noticed, is part of the above exception trace. Makes it kinda confusing ...

**Comment by dnalborczyk** [comment]
for what it's worth:

`Chrome`: Uncaught ReferenceError: Invalid left-hand side expression in postfix operation
`Safari`: ReferenceError: Postfix ++ operator applied to value that is not a reference.
`Firefox`: SyntaxError: invalid increment/decrement operand

either Firefox is wrong, or it's controversial, or not well defined in the spec?

I wonder what `IE`/`Edge` opinion is on that matter, but `Parallels` is freezing up lately

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/344f8c29505583f2302231345e9e5594e7477394 to defer more errors to the runtime instead of Acorn.

**Comment by jdalton** [comment]
[v3.0.75](https://github.com/standard-things/esm/releases/tag/3.0.75) is released :tada:
