### ISSUE TITLE
test262 bug: lexically-scoped function declarations

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#547]
[opening separate issues for tracking purposes]

> Function declarations are interpreted as lexically-scoped in module code

test cases:
https://github.com/tc39/test262/blob/master/test/language/module-code/parse-err-hoist-lex-fun.js
and
https://github.com/tc39/test262/blob/master/test/language/module-code/parse-err-hoist-lex-gen.js

I suppose the same is true for `async function` declarations, `classes` etc.

**Comment by jdalton** [comment]
I filed this as an acorn bug: https://github.com/acornjs/acorn/issues/714

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/6d4e59ed59054883f849fe49ee38eb5bd5e2eaea.

**Comment by jdalton** [comment]
[v3.0.75](https://github.com/standard-things/esm/releases/tag/3.0.75) is released :tada:
