### ISSUE TITLE
Cannot find module error with nyc and import from directory

### ISSUE THREAD

**Issue by davedoesdev** [standard-things/esm#548]
Please see https://github.com/davedoesdev/esm-nyc-bug

**Comment by jdalton** [comment]
Thank you @davedoesdev!

**Comment by jdalton** [comment]
**Update:**

Patched https://github.com/standard-things/esm/commit/57f1695d5c21da2509006426bb17b635fa469a9a.

**Comment by davedoesdev** [comment]
Confirm fixed - thanks!
