### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by tmanderson** [standard-things/esm#55]
I'm seeing this error:
```
`SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'`
```

Sorry if this is completely my mistake, but I can't seem to find anything in the README referring to the `sourceType: module` setting?

My package.json contents:
```json
"engines": {
  "node": "8.1.2"
},
"dependencies": {
  "@std/esm": "^0.3.0",
  "chalk": "^2.1.0"
},
...
"esm": {
  "esm": "all",
  "cjs": true
}
```

I'm running my script with the following command:
```
$> node -r @std/esm src/index.js
```

Where index.js contains:

```javascript
'use module';
import chalk from 'chalk';
```
I've also tried `import chalk from './node_modules/chalk` and `./node_modules/chalk/index` with no luck.

I have verified that `chalk` is installed. Thanks!

**Comment by jdalton** [comment]
Hi @tmanderson !

That's a parse error from acorn. I'm unable to repro in similating your setup. Would you mind creating a simple repro repo so that I can take a look.

**Comment by tmanderson** [comment]
Heya, @jdalton – [sure can](https://github.com/tmanderson/simple-import-esm)!

**Comment by jdalton** [comment]
Thanks @tmanderson!

You've got the options specified incorrectly.
It should be the key `"@std/esm": { "esm":"all", "cjs":true}`. Your path to chalk can be restored to just `"chalk"` after that. Also since you've specified `"all"` for your esm support the `"use module"` directive isn't required. 😋

**Comment by tmanderson** [comment]
@jdalton, ah! I gotcha. Had a feeling it might be something like that.

Thanks for the quick response!

**Comment by jdalton** [comment]
BTW I [updated the parser error message](https://github.com/standard-things/esm/commit/06d73f98320b9ae92eaaaa17ef5de70eb71caba8) to avoid confusion with `@std/esm` options.

**Comment by tmanderson** [comment]
Ah, very nice. I'm hoping that'll save someone from the same mistake!

Thanks again.

**Comment by theKashey** [comment]
@jdalton - you should clearly indicate in README that one has to include additional information into the packages.json, or "this magic" will not work.
As I think - most if people will try to run this with *.js file, not mjs.
In ideal - add the ability to execute anything in `all` mode.

**Comment by jdalton** [comment]
@theKashey I do

><img width="90%" src="https://user-images.githubusercontent.com/4303/29483325-ac6c1ffc-8458-11e7-8b8b-f84ea3fa2834.png">

**Comment by theKashey** [comment]
Yep, but this is not very clear :(
# Will _NOT_ work out of the box for JS files. See below.
As for me - I have read the medium article, tried to run scripts, checked readme.. And understand my problem only here.

**Comment by jdalton** [comment]
@theKashey Would you be up for creating a PR to update the readme?

**Comment by theKashey** [comment]
Will do my best.
