### ISSUE TITLE
Instanceof fail  with symbolic link

### ISSUE THREAD

**Issue by GMartigny** [standard-things/esm#551]
Hi,
I use [Lerna](https://lernajs.io) in a multi-repo which create symbolic links between local packages. When using esm with it, tests for constructor fails. Whether you run `instance instanceof Constructor` or `instance.constructor === Constructor`, both fails.

I don't reproduce the bug when imported file aren't symbolic links.

Here's a [repro-repo](https://github.com/GMartigny/esmInstanceofBug) to demonstrate.

**Comment by dnalborczyk** [comment]
thank you @GMartigny !

following your steps:

> To reproduce run :
> 
> npx lerna bootstrap
> node
> require("esm")
> import "./index.js"
> It should log false two time in the console instead of true.

my output is:
```shell
> require("esm")
esm enabled
> import './index.js'
instanceof false
== false
undefined
```

**Comment by dnalborczyk** [comment]
just reading your repo code ...

> It should log false two time in the console instead of true.

I guess you mean the opposite:  should log `true` two time in the console instead of `false`?

**Comment by dnalborczyk** [comment]
@jdalton this seems to be a regression.

@GMartigny  in the interim you might be able to use `esm v3.0.71`, your reduced repo seems to work, unless you need other bugfixes from patch 72 and above.

**Comment by jdalton** [comment]
For testing we can avoid pulling in various projects and test the root issues.
In this case symlinks fall into a couple buckets we don't have covered by tests.

  * hard links (of files and folders)
  * symlinks of folders in paths to a file 
    _(e.g. `/a/path/this-is-a-symlink/the-file-is-not-a-symlink.js`)_

**Comment by GMartigny** [comment]
Since I update to esm@3.0.75, another error pops up. This is not reproduce by my example repo tho.

When I run `npx nyc ava` (but not when I do `npx ava`) I get a bunch of `TypeError: Cannot read property 'f' of undefined`. Should I open another issue ?

**Comment by jdalton** [comment]
Moving `needs tests` label to #717 and moving forward with that issue while locking this issue.
