### ISSUE TITLE
"this" should be undefined in es modules

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#554]
with `esm` and `--experimental-modules`:

```javascript
// index.mjs
import assert from 'assert'
assert.strictEqual(this, void 0) // pass
```

`node -r esm index.js`
```javascript
// index.js
import assert from 'assert'
assert.strictEqual(this, void 0)

// AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
// + expected - actual
// - {}
// + undefined
```

also fails with `use modules` pragma, and esm options `{"mode":"all"}`

**Comment by jdalton** [comment]
Hi @dnalborczyk!

You'll want to disable `options.cjs.vars` for it to be `undefined`.

**Comment by dnalborczyk** [comment]
it's a little confusing to me, I thought any `es module` would behave like a spec'ed es module?

**Comment by dnalborczyk** [comment]
repro:

```
ESM_OPTIONS={cjs:false,mode:"all"} node -r esm index.js
```

```javascript
// index.js
console.log(this)
// {}
```

**Comment by jdalton** [comment]
> ah, this didn't work:
```shell
ESM_OPTIONS={cjs:false,mode:"all"} node -r esm test.js
```

Gotta quote that option, `ESM_OPTIONS='{cjs:false,mode:"all"}'` else what is received is `{cjs:false,mode:all}` which is not parsed as JSON6.

>  it's a little confusing to me, I thought any es module would behave like a spec'ed es module?

The zero config route we enable CJS interop for everything but .mjs.

**Comment by dnalborczyk** [comment]
> Gotta quote that option, ESM_OPTIONS='{cjs:false,mode:"all"}' else what is received is {cjs:false,mode:all} which is not parsed as JSON6.

aaaaaaaaaah, my bad! should we throw maybe?

> The zero config route we enable CJS interop for everything but .mjs.

gotcha. I suppose that makes sense to port projects over to `es modules`. later on one can lock them down with cjs:false?

**Comment by jdalton** [comment]
Patched `ESM_OPTIONS` to support unquoted values.
