### ISSUE TITLE
Unexpected behavior of console.log/util.inspect

### ISSUE THREAD

**Issue by Khaazz** [standard-things/esm#555]
It seems like esm overrides eval somewhere.
I made a script that create a Map object, add 2 values and then call `eval('Map Object created as string')`;
If I use normal node to execute that script it works just fine and shows the Map with values inside.
However if I use `node -r esm` to execute that script, it shows the Map as empty;
![image](https://user-images.githubusercontent.com/32022851/43980649-49901f18-9cef-11e8-9fd7-12ebee20dd93.png)
index.js being:
![image](https://user-images.githubusercontent.com/32022851/43980663-57560108-9cef-11e8-8687-71854be96e1f.png)

This seems to happen for both `Map` and `Set`
Is there is any reason it is behaving this way?
I need to see what is inside `Map` or `Set` with the `eval` function so I was surprised to find this out.

**Comment by dnalborczyk** [comment]
I don't know for certain, but I don't think that has anything to do with `eval`, but rather with console.log, and/or util.inspect (not sure how it's been implemented in node internally)

`node -r esm`
```javascript
util.inspect(new Map([[1,2]]))  // Map {}

console.log(new Map([[1,2]])) // Map {}
```

**Comment by Khaazz** [comment]
If I try to `eval('eval')`.
I get the following result:
![image](https://user-images.githubusercontent.com/32022851/43981759-6f8e832c-9cf3-11e8-86ed-28a7e694b884.png)
If that help?

I only assumed it was `eval` because of that.

**Comment by Khaazz** [comment]
Alright, thanks for the fast answer and clearing my doubt about this issue!
Looking forward for the possible fix :+1:

**Comment by jdalton** [comment]
[v3.0.75](https://github.com/standard-things/esm/releases/tag/3.0.75) is released :tada:
