### ISSUE TITLE
test262 bug: The `default` keyword must not contain unicode escape sequences

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#561]
seems to be a `regression on master`. no repro with latest release version.
I'll add it to the test262 skiplist.

https://github.com/tc39/test262/blob/master/test/language/export/escaped-default.js

```javascript
throw "Test262: This statement should not be evaluated."

export d\u0065fault 0
```

**Comment by jdalton** [comment]
[v3.0.75](https://github.com/standard-things/esm/releases/tag/3.0.75) is released :tada:
