### ISSUE TITLE
test262 bug: It is a Syntax Error if the BoundNames of ImportDeclaration contains any duplicate entries

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#562]
I think this one slipped through the cracks, as it errors, just too late and for the wrong reason. I'll add it to the test262 skiplist.

fun fact: `--experimental-modules` also tries to load module `'z'`

https://github.com/tc39/test262/blob/master/test/language/import/dup-bound-names.js

```
throw "Test262: This statement should not be evaluated.";

import { x, y as x } from 'z'
```

**Comment by jdalton** [comment]
[v3.0.75](https://github.com/standard-things/esm/releases/tag/3.0.75) is released :tada:
