### ISSUE TITLE
ReferenceError: require is not defined when using esm@3.0.75 with ava@1.0.0-beta.5.1

### ISSUE THREAD

**Issue by kniels21** [standard-things/esm#563]
@jdalton I have been using ava@1.0.0-beta.5.1 for testing and have run into an error related to esm@3.0.75. Looking at your integration tests I noticed tests for Node 6 when testing compatibility with ava and nyc fail with the same error. 

Below is the error I am encountering:
const Chalk = require('chalk').constructor;
`ReferenceError: require is not defined`

Is this an issue that is being addressed? thanks for your time.

**Comment by jdalton** [comment]
Hi @kniels21!

This appears to be an issue with the `force` option being too forceful and applying to more than just config loads.

**Comment by jdalton** [comment]
**Update**

[3.0.76](https://github.com/standard-things/esm/releases/tag/3.0.76) is released :tada:
