### ISSUE TITLE
Can’t import named lodash exports

### ISSUE THREAD

**Issue by remcohaszing** [standard-things/esm#564]
I just tried updating esm from 3.0.72 to 3.0.76. Now my lodash import fails.

Relevant code:

```js
import { promisify } from 'util';

import { mapValues, memoize } from 'lodash-es';
```

```
router boot error:  file:///path/to/file.mjs:1
import { promisify } from 'util';

Error: Cannot load ES module from .mjs: file:///path/to/node_modules/lodash-es/lodash.js
    at file:///path/to/file.mjs:1
    at Generator.next (<anonymous>)
```

If I change the code to use *lodash* instead of *lodash-es*, I get a different error instead.

```
router boot error:  [file:///path/to/file.mjs:1
SyntaxError: Missing export name 'mapValues' in ES module: file:///path/to/node_modules/lodash/lodash.js]
```

For this to work, I added a *.esmrc.js* file as well (side note: because *.esmrc.mjs* didn’t work)

```js
module.exports = {
  cjs: {
    namedExports: true,
  },
};
```

**Comment by dnalborczyk** [comment]
@remcohaszing 

I'm assuming you are using `.mjs` file extensions? if so, the behavior you are experiencing seems to be correct, and is essentially a `bug in v3.0.72`.

the `mjs` mode in `esm` tries to simulate the behavior of node `--experimental-modules`. in that mode, you can have `named imports` only from node built-in modules (such as `fs`, `http`...), but no named imports from any other `cjs` module. I agree, it's all a little confusing. Anyhow, keep in mind that `--experimental-modules` is still under heavy development, and should not be used on any production system.

My advice (which is my own and personal): forget about `mjs`, use `esm` (lock it down to whatever mode you like), and start developing.

**Comment by dnalborczyk** [comment]
more info regarding your exceptions:

`lodash-es` is a es module, **but** with a **js** file extension:

```javascript
// file.mjs
import { promisify } from 'util'  // works, because it's a node built-in module

import { mapValues, memoize } from 'lodash-es'  // does not work
// as 'mjs' can not load es modules from any other file extension than 'mjs'
// hence the exception:
// `Error: Cannot load ES module from .mjs: file:///path/to/node_modules/lodash-es/lodash.js`
```
you can try to run the above with node --experimental-modules and you should get a similar error.

for your second case using `lodash`, which is a **cjs** module (module.exports)
```javascript
import { mapValues, memoize } from 'lodash'  // does not work
// as 'mjs' modules can not load `named imports` from `cjs` modules (except node's own)
// hence the exception:
// SyntaxError: Missing export name 'mapValues' in ES module: file:///path/to/node_modules/lodash/lodash.js]
```

if you feel strong about `mjs`, you could use `lodash` with `mjs` by importing the `default` or the entire `namespace` (haven't tried, but should work)
```javascript
// file.mjs
import _ from 'lodash'
// or:
import * as _ from 'lodash'
```

**Comment by jdalton** [comment]
Hi @remcohaszing!

Do you have a project or small repro repo I can look at to better understand the issue?

**Comment by jdalton** [comment]
**Update:**

@remcohaszing Closing as invalid just because I cannot reproduce an issue. Please feel free to ping back with any additional questions or issues.
