### ISSUE TITLE
module load failure: origin of module unknown when used with babel/register

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#565]
not sure if it's a bug, if it's fixable, or if it is even `esm`s responsibility.

used with babel/register it's quite hard to pinpoint which module is throwing:

```shell
file:///project/node_modules/pirates/lib/index.js:1
SyntaxError: Missing export name 'default' in ES module: file:///project/packages/api/src/config/index.js
    at Object._compile (file:///project/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

I can create a repro, if needed? I could even try to create a test case rather ... or both.

**Comment by jdalton** [comment]
Can you try it without `esm` and see if the error is still obstructed by pirates?
I suspect this is a babel/register issue since they use pirates for module compiler wiring.

**Comment by dnalborczyk** [comment]
just tried it without `esm`, and it's hard to tell, because you can feed `babel` any import/export which isn't a syntax error, and the import works. there's no check if anything on the module namespace was exported or not. if it doesn't exist, it's just `undefined`.

I also noticed another problem:
if one is to switch from `babel-modules` to `esm`, it'll throw an exception. That also happens if one would switch from `esm` to `babel-modules`

if I switch from `babel-modules` to `esm` -- e.g. preset-env, { modules: false }
```javascript
// foo.js
export const a = 1
```

```javascript
// index.js
import { d } from './foo.js'
```

```shell
node -r esm -r @babel/register index.js
```

```shell
/esm/565/foo.js:1
export var a = 1; # <== notice, this seems to be the babel-transpiled code, possible cache?
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:74:7)
    at Object._compile (/esm/565/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by jdalton** [comment]
I believe this is a `pirates` issue for obstructed errors.

The `@babel/register` cache issue is a mix of us and them. They could clean their cache when they detect a config change. We should update our heuristic for more V8 aligned error messages we added.

**Comment by dnalborczyk** [comment]
oh, I see. do you mean that once the `babel module transform` is being `turned off`, babel still feeds itself from it's own cache, and not from what `esm` is feeding it?

**Comment by jdalton** [comment]
Yep, though I'm going to adjust this and just not cache unless you opt-in explicitly with `@babel/register`. This should clear up some of the confusion (you've seen it as auto-healing) so things just work without worrying about it.

**Comment by dnalborczyk** [comment]
i must admit, because of the random hickups, which often went away when clearing the cache, my projects usually use:

```
ESM_OPTIONS={cache:false} BABEL_DISABLE_CACHE=1 nodemon -r esm -r @babel/register src
```
