### ISSUE TITLE
bridge mode ignores cache option

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#566]
repro:

#1 creates cache nonetheless
```javascript
require = require('esm')(module, { cache: false })
module.exports = require('./index.js')
```

#2 creates cache in `node-modules/.cache/esm`
```javascript
require = require('esm')(module, { cache: './temp' })
module.exports = require('./index.js')
```

#3 creates twice the amount of cache files, if started once with no options, and once set to `cache: false`
```javascript
// start once:
require = require('esm')(module)
module.exports = require('./index.js')
```

```javascript
// then start again with:
require = require('esm')(module, { cache: false })
module.exports = require('./index.js')
```

_edit:_
I'm guessing that the cache generator takes the esm options into account (which makes sense), hence #3 creates twice the amount of cache files.

**Comment by jdalton** [comment]
Is #558 a good place for tests?

**Comment by dnalborczyk** [comment]
yeah. want me to add those?

**Comment by jdalton** [comment]
Yes please! I'll add a test for #567.

**Comment by dnalborczyk** [comment]
added some tests https://github.com/standard-things/esm/pull/558/commits/dbfa50def42c3d44dc7cbe81feaf79b3aae9940e

**Comment by jdalton** [comment]
[v3.0.78](https://github.com/standard-things/esm/releases/tag/3.0.78) is released :tada:
