### ISSUE TITLE
option "mainFields" not working

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#567]
I was trying to use `esm` from a module authors perspective, and I was hitting a bunch of road blocks.
now, I also have to admit that I'm not sure what the expectations are around that topic reading the docs.

I think I just file away ....

given a module ~, using `esm`~ I think it's unneccassary that the module is using `esm` for this issue
```javascript
// foo.js
export const a = true
```

```json
{
    "name": "mod",
    "module": "foo.js"
}
```

given an app, referencing that module
```shell
npm i ../mod
```

```javascript
// index.js
import { a } from 'mod'
```

```json
{
    "name": "app",
    "dependencies": {
        "mod": "file:../mod",
        "esm": "3.0.77"
    }
}
```

```shell
ESM_OPTIONS='{"mainFields":["module"]}' node -r esm index.js

# file:///repros/esm/mod/index.js:1
# Error: Cannot find module 'mod'
#    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

are my assumptions correct and this is a bug, or am I using this incorrectly? or is this not meant to be supported?

**Comment by jdalton** [comment]
Tests https://github.com/standard-things/esm/commit/49bc045f06136f08b618ff6b5b2a43bf671f36ce.

**Comment by jdalton** [comment]
[v3.0.78](https://github.com/standard-things/esm/releases/tag/3.0.78) is released :tada:
