### ISSUE TITLE
ESM doesn't work with ts-node/register if no caches exist

### ISSUE THREAD

**Issue by stevefan1999** [standard-things/esm#568]
# Reproduction
Simply run `node -r esm -r ts-node/register/transpile-only -r tsconfig-paths/register ./test.ts` 

test.ts:
```ts
import { TestRunner, TestSet } from 'alsatian'
import { TapBark } from 'tap-bark'

async function main(): Promise<void> {
  // ...
}

main()
  .then()
  .catch(e => {
    console.error(e)
    process.exit(1)
  })

```

But it failed with:
```ts
file:///~/test.ts:4
async function main(): Promise<void> {
                     ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```
If I use a top-level register wrapper (i.e. `test.entry.js` and use `require('esm')` trick), it runs fine but nobody likes writing extra files right?

Of course, if I removed that single typing, everything works, although that means I will have to explicitly disable `tslint` by `/* tslint:disable */`. It's no good.

**Comment by stevefan1999** [comment]
@dnalborczyk https://github.com/stevefan1999/lerna-yarn-workspaces-example

**Comment by jdalton** [comment]
Interesting. At one point I tested `ts-node` and it was working.

**Comment by stevefan1999** [comment]
@jdalton Well, if you don't include types, it does work. A similar story should occur to Flow as well.

**Comment by dnalborczyk** [comment]
not sure if [flow-remove-types](https://github.com/flowtype/flow-remove-types) works, but babel/register with [babel-plugin-transform-flow-strip-types](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-flow-strip-types) definitely works. I'm using it, and there are `esm` tests.

**Comment by jdalton** [comment]
**Update:**

Ok so the reason it's failing with traditional `ts-node` usage is because is registering its hooks first. This is why when it's loaded by the `esm` bridge things work (because `esm` can register first). Let me see if there's something to do.

**Comment by jdalton** [comment]
**Update:**

The `-r ts-node/register/transpile-only` looks like a winning route. I've identified the issue on our end preventing it from working.

**Comment by jdalton** [comment]
**Update:**

The fix was to use the main entry itself for the options check when the parent entry isn't available _(as is the case for the main script)_.

**Comment by jdalton** [comment]
[v3.0.78](https://github.com/standard-things/esm/releases/tag/3.0.78) is released :tada:

**Comment by stevefan1999-personal** [comment]
Just a little notice that I had a regression, was still testing, will re-open a new issue if confirmed.
