### ISSUE TITLE
SIGINT & SIGTERM handling

### ISSUE THREAD

**Issue by novemberborn** [standard-things/esm#569]
https://github.com/standard-things/esm/commit/be0fc683c56ec294bb5666460165b43c2661c5ae adds handlers for `SIGINT` and `SIGTERM` to ensure caches are persisted when the process is terminated.

https://github.com/standard-things/esm/commit/2e44cb89abfa95071a4e7a934946c91c0933a75d fixes the handlers to ensure the process exits when those signals are intercepted.

I see two problems with this. For one, the behavior is observable. If you run this snippet, take the PID that's written, and run `kill -term %PID`, you get the resulting output (I used Node.js 10.8.0):

```console
❯ node -e "child_process.spawn(process.execPath, ['-e', 'console.log(process.pid);setTimeout(()=>{},3600e3);'],{stdio:'inherit'}).on('close', console.log)"
95280
null 'SIGTERM'
```

Note the difference with this snippet, which exits with code 143:

```console
❯ node -e "child_process.spawn(process.execPath, ['-e', 'console.log(process.pid);setTimeout(()=>{},3600e3);process.on(\'SIGTERM\',()=>process.exit(143))'],{stdio:'inherit'}).on('close', console.log)"
95568
143 null
```

The same goes for `SIGINT`. This actually [caused test failures in AVA](https://github.com/avajs/ava/pull/1910). Some tests run AVA's CLI in a child process, and explicitly terminate it. Assertions were on `code` being `null`, which as of `esm@3.0.75` is no longer the case.

The forced exit will also break programs that themselves manage `SIGINT` and `SIGTERM`, e.g. to guarantee a graceful server shutdown. If *any* of their dependencies loads `esm` those processes will just exit, unless they first remove all other `SIGINT` and `SIGTERM` handlers.

---

I'm not sure whether this behavior should be opted in to, or only apply when `esm` is used as the process entry point. However I don't think it should affect the process when `esm` is loaded as a transitive dependency.

**Comment by dnalborczyk** [comment]
thanks @novemberborn ! you are right. I [had created a WIP test](https://github.com/standard-things/esm/pull/558/commits/087927f4cf7dc855e7f7dcacb2a8a23715f52ffe), which is failing, because of the `signal` not being received by the `esm`-used test. I haven't found the time yet to look into the failure and file it as a bug. the test was passing [before this commit](https://github.com/standard-things/esm/commit/2e44cb89abfa95071a4e7a934946c91c0933a75d).

**Comment by novemberborn** [comment]
Thanks @jdalton.

As an application developer, I wouldn't mind manually flushing the `esm` cache and setting up my own signal handlers. That could even be a nice companion package if the flush methods are exposed.

As an application developer who's output is a Docker image, it would even be quite interesting to be able to prime the cache during the Docker build.

**Comment by jdalton** [comment]
[v3.0.78](https://github.com/standard-things/esm/releases/tag/3.0.78) is released :tada:
