### ISSUE TITLE
document named exports via `import { ... } from ".."` in the REPL

### ISSUE THREAD

**Issue by Jamesernator** [standard-things/esm#57]
`@std/esm` correctly doesn't allow `import { readFile } from "fs"`, however this seems to still work fine in the REPL which implies that the behavior of `import { ... }` is different in the REPL than using `@std/esm` directly in a file.

It'd be nice to just have a note in the README that this behavior is different (I assume its intentional at least).

**Comment by jdalton** [comment]
Sure. Yes, I auto [unlock](https://github.com/standard-things/esm#unlockables) the `"cjs":true`  feature when in the REPL because it's a bit of a hybrid environment loading CJS and ESM from input to input.

Would you be up for submitting a PR to add the doc note?

**Comment by jdalton** [comment]
Closed by #59.
