### ISSUE TITLE
[pattern] instanceof RegExp is false in Jest 

### ISSUE THREAD

**Issue by clarkdo** [standard-things/esm#570]
Reproducible repo: https://github.com/clarkdo/esm-issue

The repo is made by `jest`, `babel` and using `esm` to load module dynamicaly.

Issue: After use esm to import any js, `/pattern/ instanceof RegExp` will become false.

Expect: `/pattern/ instanceof RegExp` should always be true.

Steps:

1. yarn install
2. yarn test

BTW: issue only happened in latest release 3.0.77

**Comment by dnalborczyk** [comment]
thank you @clarkdo for the report and the repro!

although I don't understand the use case, `/pattern/ instanceof RegExp` is not so much the issue, it seems that the JavaScript/V8 builtins are pointing to another reference.

```javascript
const promise = Promise
esm(module)("./main.js")
console.log(Promise === promise) // false
```

**Comment by clarkdo** [comment]
Yes, you’re right, a lot of built-in objects are reset

**Comment by jdalton** [comment]
[v3.0.78](https://github.com/standard-things/esm/releases/tag/3.0.78) is released :tada:
