### ISSUE TITLE
Call site calculation fails despite fixes for Jest in 3.0.77

### ISSUE THREAD

**Issue by charandas** [standard-things/esm#573]
Starting with this `depd` [issue](https://github.com/dougwilson/nodejs-depd/issues/28), @jdalton helped resolve some of the issues I was seeing in `esm` itself.

v3.0.77 brought in those improvements. I have since tried to incorporate the new version in my Jest tests with `sequelize` but still encountering some edge cases.

I have updated the [repro repo](https://github.com/charandas/depd-repro-jest) to show 1 failing test and 1 passing test. When it fails, it fails with the exact same error that has been happening in `depd` prior to `esm@v3.0.77`.

```
  ● Test suite failed to run

    TypeError: callSite.getFileName is not a function

      at callSiteLocation (node_modules/depd/index.js:252:23)
      at depd (node_modules/depd/index.js:111:14)
      at new Logger (node_modules/sequelize/lib/utils/logger.js:23:17)
      at Object.<anonymous> (node_modules/sequelize/lib/utils.js:15:16)
      at Object.<anonymous> (node_modules/sequelize/lib/sequelize.js:7:15)
```

My interpretation of the failure is that if I require/import sequelize before `esm` patches require, then after `esm` kicks in, it can still work with sequelize.

However, if I let esm kick in first, then the same issues persist. It would be hard to control the import order of depedencies to make Sequelize happy, hence reporting this as a bug in `esm`.

/cc @dougwilson

**Comment by jdalton** [comment]
Hi @charandas!

This will be fixed by the same fix for #570. I didn't quite get the issue fixed from before.

**Comment by jdalton** [comment]
Closed by https://github.com/standard-things/esm/commit/5e1f401334d78d4387ae8c40531b658a9c36894f.

**Comment by charandas** [comment]
@jdalton I have been running this evening with the [commit](https://github.com/standard-things/esm/commit/fbc253cc3c1eca36df05c90a7975ef63fc3dcf22) next to this one, and now my packages are giving me some grief independent of `jest`, but in a very specific circumstance of within node docker containers based off of `debian`.

I use macOS for my development. All my esm based packages provide an entrypoint with patched require, and using node locally, I can `require` my packages fine.

With the docker containers hosting those same node versions (v10 is what I tested with), I get this instead:

```
TypeError: Cannot read property 'package' of undefined
    at Object.<anonymous> (/src/node_modules/@myhandle/some-esmed-package/node_modules/esm/esm.js:249:51)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

On investigating `esm` code that this is happening at, I see this:

```
// Declare `shared` before assignment to avoid the TDZ.
let shared

shared = loadESM()
console.log(shared) // I added this line, and fair enough, it prints {}

defineProperty(makeRequireFunction, shared.symbol.package, { // L249 at which the complain is arising
  __proto__: null,
  value: true
})
```

Please share if you have some advice or if you need any other info I can provide.

**Comment by jdalton** [comment]
@charandas No worries. That error means it's not building _(not likely a real issue)_.

**Comment by jdalton** [comment]
[v3.0.78](https://github.com/standard-things/esm/releases/tag/3.0.78) is released :tada:

**Comment by charandas** [comment]
Hurray. It works now! I have more issue to report, in context of `jest`, making it now.
