### ISSUE TITLE
import only returns last export out of multiple exports in jest realm

### ISSUE THREAD

**Issue by charandas** [standard-things/esm#576]
### main.js

```
export { default as something } from './models/something'
export { default as someOtherThing } from './models/some-other-thing'
export { MODEL_NAMES } from './constants'
```

### index.js

```
require = require('esm')(module) // eslint-disable-line no-global-assign
module.exports = require('./main')
```

### esm options in package.json
```
  "esm": {
    "cjs": true
  },
```

### Expected behavior (in any realm including Jest)
```
import package from './'
// package has something, someOtherThings, MODEL_NAMES
```

### Actual behavior (in Jest realm only)
```
import package from './'
// package has  MODEL_NAMES only
```

### version
esm@3.0.79

**Comment by jdalton** [comment]
Hi @charandas!

Could you create a small repro so I can better see how you're using it in Jest.

**Comment by jdalton** [comment]
Ah ok. No worries. Thanks for filing an issue anyways. Please feel free to file for anything else you find. It's no problem if it turns out to not be a real issue 🙃
