### ISSUE TITLE
Default exports don't create a binding

### ISSUE THREAD

**Issue by tomdale** [standard-things/esm#578]
Perhaps I'm misreading the spec, but I believe default exports still create a binding in module scope. In `esm`, anything that is a default export cannot be re-exported as a named export.

Trivial reproduction:

```js
export default function foo() {
}

export { foo }
```

This throws with:

```
> node -r esm index.
file:///Users/tomdale/Code/esm-test/index.js:4
export { foo }
         ^^^

SyntaxError: Export 'foo' is not defined in module
    at Object.Module._extensions..js (module.js:654:10)
```

**Comment by jdalton** [comment]
Yep, you are right. We actually hoist too so `foo` is available for export. The error is coming from an identifier validation pass we're doing (and not including the function declaration). I'll patch that up.
