### ISSUE TITLE
[Regression since 3.0.75] Crash when working with Istanbul

### ISSUE THREAD

**Issue by GMartigny** [standard-things/esm#579]
Following #551, I upgrade to 3.0.75 and get an exception:

	TypeError: Cannot read property 'f' of undefined
      at Object.<anonymous> (file:///pencil.js/modules/image/image.js:1)
      at Generator.next (<anonymous>)
      at file:///pencil.js/node_modules/nyc/node_modules/append-transform/index.js:62:4
      at extensions.(anonymous function) (file:///pencil.js/node_modules/require-precompiled/index.js:16:3)
      at file:///pencil.js/node_modules/nyc/node_modules/append-transform/index.js:62:4
      at require.extensions.(anonymous function) (file:///pencil.js/node_modules/ava/lib/process-adapter.js:100:4)
      at Object.<anonymous> (file:///pencil.js/node_modules/nyc/node_modules/append-transform/index.js:62:4)
      at Module.load (internal/modules/cjs/loader.js:599:32)

It occur when I execute `npx nyc ava` where AVA requires `esm`. However, I get no exception when I do `npx ava` or when I use esm@3.0.74.

I tried every version of esm between 75 and 79 without any luck. I don't manage yet to isolate this error in a simple repo (still trying tho).

The weird stuff is that when I clean the .cache folder and rerun the command, I don't always get the same amount of exceptions.

**Comment by jdalton** [comment]
Hi @GMartigny!

This is likely a caching related issue. Though if you can create a repro repo for us we'll be able to dig in a bit more.

**Comment by GMartigny** [comment]
You're right, it was a caching issue. I manage to update my [repro repo](https://github.com/GMartigny/esmInstanceofBug) to trigger the bug every times.

It appear when I import a module twice via different mean in the same test suite. In my case: A.test _import_ A _import_ B then B.test _import_ B.

Just clone it and run:
```
npx lerna bootstrap
npx nyc ava #No issue
npx nyc ava #Cannot read 'f' of undefined
```

Clearing the cache allow to get back to no issue the first time.

**Comment by GMartigny** [comment]
Your reactivity is a boon ! Thanks a bunch.
