### ISSUE TITLE
cjs option not needed for requiring esm

### ISSUE THREAD

**Issue by tilgovi** [standard-things/esm#58]
Documentation says that the `cjs` option enables "require in ESM and loading ESM with require". The second part of this doesn't seem to be true. Loading ESM with require seems to always work.

**Comment by jdalton** [comment]
Hi @tilgovi!

I should clarify. Loading ESM from `require` won't work in any other place besides the bridge that requires `@std/esm`. So within subsequent loads of CJS it would require `import()`.

**Comment by tilgovi** [comment]
👍
