### ISSUE TITLE
ERR_MODULE_RESOLUTION_LEGACY with { cjs: { paths: true } }

### ISSUE THREAD

**Issue by mk-pmb** [standard-things/esm#582]
Hi!
Did I misread the readme or is it a bug that I get an `ERR_MODULE_RESOLUTION_LEGACY` error even though I have `{ paths: true }` as my cjs option?

Using the [`debug-legacy-paths` branch of `esmod-pmb`](https://github.com/mk-pmb/esmod-pmb-js/tree/debug-legacy-paths):

```text
$ nodejs test/lc1st.node.js
{ stdEsmVersion: '3.0.72',
  node: { version: '8.11.4', platform: 'linux', arch: 'ia32' },
  effectiveStdEsmOpts: { cjs: { paths: true }, mode: 'auto' } }
file:///…/nodejs/modules/esmod-pmb/test/lc1st.mjs:1
Error [ERR_MODULE_RESOLUTION_LEGACY]: lodash.lowerfirst not found by import ↩
  ↪in /…/nodejs/modules/esmod-pmb/test. Legacy behavior in require() would ↩
  ↪have found it at /…/lodash.lowerfirst/index.js
```

**Comment by mk-pmb** [comment]
Also I wonder, why does it have to search my global module paths at all? There's a version of 'lodash.lowerfirst` installed as a peer dep (has the same parent directory as `esmod-pmb` does). Shouldn't that one win?

**Comment by jdalton** [comment]
Hi @mk-pmb!

The `.mjs` file extension is locked down and does not get any `esm` interop/compat options extended to it. If you switch to the `.js` file extension then `esm` options will work.

**Comment by mk-pmb** [comment]
Could you make the error message remind about that? e.g. "Legacy behavior in require()<ins>, which is not available for *.mjs,</ins> would have…"

**Comment by jdalton** [comment]
That's not a bad idea. At the moment we are just matching whatever the builtin Node error is.

**Comment by mk-pmb** [comment]
:-) Thanks for your quick reply anyway. I'll see if I can hack a non-compliant resolver some way easier than forking esm.

**Comment by jdalton** [comment]
Cool! The `.js` extension is recommended the route until something materializes for `.mjs` _(timeline is unknown)_.

**Comment by mk-pmb** [comment]
When you upgrade the error, could you please also expose the filename where it would have been found, as some property of the error? e.g. `cjsLegacyResolvedFile`
