### ISSUE TITLE
"SyntaxError: Invalid or unexpected token" on every even-numbered run after cache deletion

### ISSUE THREAD

**Issue by mk-pmb** [standard-things/esm#583]
Sounds like it's the reverse version of https://github.com/standard-things/esm/issues/568 .

* If there is *no* cache, my fail whale test from [nodemjs](https://github.com/mk-pmb/nodemjs-node/) works as expected, i.e. throws and prints a stack trace.
* The next time, it exits with "SyntaxError: Invalid or unexpected token" instead.
* The 3rd time, it works again.
* The 4th time, unexpected token again.
* … and it repeats reliably.

```text
$ rm -r node_modules/.cache/

$ ./test/failWhale.mjs ; echo rv=$?
W: loaderArgs are currently ignored! []
D: remaining process.argv: [ '/usr/bin/node',
  '/mnt/…/nodemjs/test/failWhale.mjs' ]
rv=23

$ ./test/failWhale.mjs ; echo rv=$?
W: loaderArgs are currently ignored! []
D: remaining process.argv: [ '/usr/bin/node',
  '/mnt/…/nodemjs/test/failWhale.mjs' ]
file:///mnt/…/nodemjs/test/failWhale.mjs:1
#!/usr/bin/env nodemjs

SyntaxError: Invalid or unexpected token
rv=1

$ for N in {1..16}; do ./test/failWhale.mjs &>/dev/null; echo rv=$?; done
rv=23
rv=1
rv=23
rv=1
rv=23
rv=1
rv=23
rv=1
rv=23
rv=1
rv=23
rv=1
rv=23
rv=1
rv=23
rv=1
```

**Comment by mk-pmb** [comment]
:+1: Thanks! :-)

**Comment by jdalton** [comment]
Tests https://github.com/standard-things/esm/commit/c645d8fc367f3dddeaa0a60e7993df4584e01f0f

**Comment by mk-pmb** [comment]
I'd appreciate if you could release it to npm soon. I tried the commit syntax as dependency but somehow npm needs forever to install it this way.

**Comment by jdalton** [comment]
[v3.0.81](https://github.com/standard-things/esm/releases/tag/3.0.81) is released :tada:

**Comment by mk-pmb** [comment]
Thanks! :+1:  :tada:
