### ISSUE TITLE
Babel 7 beta >=56 with transpiling to CJS: "yield is a reserved word in strict mode"

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#585]
Happens on different random files under the different conditions:

```js
"main";_01f‍.x([["babelConfigWebDemo",()=>babelConfigWebDemo],["babelConfigWebStatic",()=>babelConfigWebStatic],["babelConfigWebBuild",()=>babelConfigWebBuild],["babelConfigReactNativeBuild",()=>babelConfigReactNativeBuild],["babelConfigNodeBuild",()=>babelConfigNodeBuild]]);let babelPresetReactNative;_01f‍.w("babel-preset-react-native",[["default",["babelPresetReactNative"],function(v){babelPresetReactNative=v}]]);yield;
```

```js
"main";let plugin;_255‍.w("@start/plugin",[["default",["plugin"],function(v){plugin=v}]]);yield;
```

I believe that `yield` at the end has been added by ESM loader and when Babel is applying `babel/plugin-transform-modules-commonjs` (I still have to build some files without `modules: false`) [it contains `"use strict"`](https://babeljs.io/docs/en/babel-plugin-transform-strict-mode.html).

Please let me know if it's still unclear: unfortunately I can't provide a repro-repo because the error is kinda phantom.

**Comment by jdalton** [comment]
Are you using `@babel/register`? If not you should be ignoring the `.cache` folder in transforms. I'll see if I can avoid storing the actual transform `yield` bit though.

**Comment by deepsweet** [comment]
Yes, it's `@babel/register`.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/0553fa0d27647f24c8a1e720ef4261be0b4049f8.

**Comment by deepsweet** [comment]
![](http://gifimage.net/wp-content/uploads/2017/01/You-are-Awesome-GIF-Image-for-Whatsapp-and-Facebook-12.gif)

**Comment by jdalton** [comment]
I need to pay off some test debt before bumping. You can expect a release in a day or so.

**Comment by jdalton** [comment]
Tests https://github.com/standard-things/esm/commit/0fdaff8265514798d1a97c0b6c3d5c5ffc6f2e72.
