### ISSUE TITLE
ESM cannot work with TypeScript compile-time types

### ISSUE THREAD

**Issue by stevefan1999** [standard-things/esm#587]
# Reproduction
Create a TypeScript file and export an arbitrary TS type artifact and a ES class, say like this:
`src/Foo.ts`
```ts
export interface Foo {
}

export class Bar {
}
```
And import it somewhere:

`src/main.ts`
```ts
import { Foo, Bar } from './Foo'
```

Compile the TS code to ES.Next/ES2015 and using node require hooks, attach ESM first then attach ts-node:
```
node -r esm -r ts-node/register/transpile-only -r tsconfig-paths/register ./src/main.ts
```

If you launch it, you'd see:
```
SyntaxError: Missing export name 'Foo' in ES module: file:///src/Foo.ts
```
This is because although TypeScript will gladly strip the compile-time-exclusive interfaces:
`src/Foo.js` (transpiled)
```js
export class Bar {
}
```
`src/main.js` (transpiled)
```ts
import { Bar } from './src/interfaces/Foo'
```
Yet ESM could not recognize the change and it read the original TS import sources instead.
Because this problem involves both TypeScript and ECMAScript module resolution, this is not going to be easy😥

Of course, the workaround is to move those type artifacts into `.d.ts` files and offload the type checkings to IDE tools, this is also recommended by TS guidelines.

**Comment by dnalborczyk** [comment]
interesting. this one might be indeed harder to tackle. either `esm` has to use some typescript parser and remove the type information (which I don't think is a good idea), or one could possibly run a typescript type stripper before `esm` and leave module syntax alone.

as a side note: this works seemless with [flow types](https://flow.org/en/docs/types/modules/), as they are using a different `import and export syntax`:

```
export type MyObject = { /* ... */ }
export interface MyInterface { /* ... */ }
```
```
import type { MyObject, MyInterface } from './exports'
```

**Comment by jdalton** [comment]
@stevefan1999 Could you create a repro repo. No promises, but if I can better understand the issue I can write documentation or suggestions for it.

**Comment by jdalton** [comment]
@stevefan1999 Without a repro I can't do much in terms of workarounds or documentation since I'm not super fluent in TypeScript. Please feel free to ping back with a repro whenever you get a chance and we'll dig in.

**Comment by stevefan1999** [comment]
🤔Interesting. So my provided example is actually invalid. But I still somewhat managed to recreate the real-life example:
https://github.com/stevefan1999/typescript-esm-repo

**Comment by jdalton** [comment]
In your example `Request` isn't exported from `express`. The `express` module exports a lowercase `request` which is found.
