### ISSUE TITLE
ESM may load module twice (for tests in monorepo)

### ISSUE THREAD

**Issue by apparebit** [standard-things/esm#588]
When developing in a monorepo with Yarn's workspaces, the repo's `node_modules` has symbolic links to individual packages. So, to use a local package from any of the repo's shared infrastructure, one can just use the package name ("`@namespace/package`") or even the name of a module inside the package ("`@namespace/package/module`"). However, since about 3.0.71, __esm__ treats the two cases inconsistently. For a local package, it uses the real path for the CJS cache `Module._cache`. For a module inside a local package, it preserves the symbolic link. That of course may lead to a module being loaded twice, which used to _not_ be the case. Mind you, it helped me make my code more robust. But this should at least be documented if not reverted.

I've isolated the behavior into a minimal monorepo at <https://github.com/apparebit/esm-seeing-double>:

```bash
git clone https://github.com/apparebit/esm-seeing-double
cd esm-seeing-double
yarn install
yarn test
```

**Comment by jdalton** [comment]
Thanks @apparebit for the clear repro!

**Comment by apparebit** [comment]
My pleasure, @jdalton. And thank you for the amazingly fast fix!

To try it out myself, do I just clone the esm repo, run `node script/build.js --prod`, and drop the result in node_modules?

**Comment by dnalborczyk** [comment]
@apparebit yes, that should do
```shell
npm clone ...
npm ci
npm run build:prod
```

then copy `esm`, `esm.js` and `index.js` into `node_modules/esm`

**Comment by apparebit** [comment]
I can confirm that the fix works, both for my local copy of [esm-seeing-double](https://github.com/apparebit/esm-seeing-double) and the actual monorepo [js-junction](https://github.com/apparebit/js-junction). Thank you! 😺

**Comment by jdalton** [comment]
[v3.0.82](https://github.com/standard-things/esm/releases/tag/3.0.82) is released :tada:
