### ISSUE TITLE
cjs interop: TypeError: 'set' on proxy: trap returned falsish for property

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#589]
I was poking around with cjs interop, and found this. under the assumtion that cjs modules should behave like cjs in es modules.

`esm v3.0.81`
`node v10.9.0`

```javascript
// foo.js
Object.defineProperty(exports, "foo", {
  value: "bar",
  enumerable: false, // default
  writable: false // default, set to true works
})
```

```javascript
// test.js
import assert from "assert"
import * as test from "./foo.js"

test.foo = "test"
assert.strictEqual(test.foo, "bar")
```

```shell
node -r esm test.js
```

```shell
TypeError: 'set' on proxy: trap returned falsish for property 'foo'
    at Object.<anonymous> (file:///repros/test/test.js:8:10)
    at Generator.next (<anonymous>)
```

@jdalton  do you have a good location for cjs interop tests?

**Comment by dnalborczyk** [comment]
[looking at this again](https://github.com/standard-things/esm/issues/517), I guess now I'm confused.

the above is definitely a bug, but now I'm entirely unsure about the expectations 😕 since `foo` is not `enumerable`, I guess it shouldn't show up in the namespace object? or does that rule apply only for `getter/setter`?

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/3c049bfea56fbea6d6117a9ca9bf961faf88d391. What you're seeing is the CJS interop of `options.cjs.mutableNamespace`. In strict mode (which ES Modules are in) setting a read-only property will throw an error. In this case when when trapped by a proxy it creates the ugly-proxy trap error. I've patches this to let it bubble up the real error. I'll need to review the other traps as well for similar conditions.
