### ISSUE TITLE
esm is creating additional node_modules/.cache folder in module root

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#590]
_under the assumption that this is not intended_

`esm v3.0.81`
`node v10.9.0`
`macOS Mojave`

**repro:**
```shell
node -r esm index.js
```

go to: `project-root/node_modules/esm`

I'm guessing that `project-root/node_modules/esm/[node_modules/.cache/esm]` should not be created?

the same is true when cache is being turned off:

```shell
ESM_OPTIONS='{cache:false}' node -r esm index.js
```

**Comment by jdalton** [comment]
This is a cache of the loader itself independent of any things the loader itself loads. It creates the cache if possible and doesn't error in environments that restrict it.

**Comment by dnalborczyk** [comment]
ah, cool, good to know!
