### ISSUE TITLE
Provide upgraded repl to other modules [proposal]

### ISSUE THREAD

**Issue by mk-pmb** [standard-things/esm#592]
Hi! Would it be possible to expose the upgraded REPL to modules loaded via esm?

**Comment by jdalton** [comment]
Hi @mk-pmb!

Do you have some pseudo code to express how you think it would work _(usage wise)_?

**Comment by mk-pmb** [comment]
#### loader.js

```javascript
const esmRqr = require('esm')(module);
esmRqr('./repldemo.mjs');
```

#### repldemo.mjs

```javascript
import repl from 'repl';
repl.start();
```

#### Try it with esm@3.0.81

```text
$ nodejs loader.js
> 3+2;                                [enter]
5
> import fs from 'fs';                [enter]
...                                   [enter]
...                                   [ctrl+c]
> fs = (await import('fs')).default;  [enter]
...                                   [ctrl+c]
>                                     [ctrl+d]
```

**Comment by mk-pmb** [comment]
I'm undecided whether it's a good idea to shadow the original `repl` module though. Maybe the module name should be something like `esm/repl`.

**Comment by jdalton** [comment]
Ah ok cool!

I think we'll hold off for until there's an easier way to tap into the REPL. I know that there has been some talk of allowing custom REPL implementations _(some interest from Node core and `ts-node` devs)_. One of the proposed ways was specifying an environment variable like `NODE_EXTERNAL_REPL_MODULE` with the path to the custom-repl.js. 

You should check out the WIP REPL rewrite over at https://github.com/nodejs/repl to see if it provides enough hooks for `esm` and others to leverage.

**Comment by mk-pmb** [comment]
> I think we'll hold off for until there's an easier way to tap into the REPL.

I'm not sure I understand the reason for your caution. Is the way `esm` currently hooks into the REPL (when no script name is given) very invasive or outright unstable?

**Comment by jdalton** [comment]
> I'm not sure I understand the reason for your caution. Is the way `esm` currently hooks into the REPL (when no script name is given) very invasive or outright unstable? 

It is invasive and is something that should eventually be replaced. I'm looking forward to a better way to hook in for sure.

>  If I invoke it with `nodejs -r esm`, the import statement and dynamic import work, albeit not with top-level await.

top-level `await` would work if you [compiled `esm` into Node](https://github.com/standard-things/esm/wiki/Compile-Node).
