### ISSUE TITLE
loader hooks

### ISSUE THREAD

**Issue by Janpot** [standard-things/esm#593]
Been looking for an issue around this but can't seem to find any. I'd like to be able to transform modules on the fly. More specifically, for my use-case, I'm interested in transpiling modules differently based on the query parameters they are imported with.
```js
import x from 'x?x=a'
import x from 'x?x=b'
```
Would an API for this considered for `esm` and what would it look like?
(https://nodejs.org/dist/latest-v9.x/docs/api/esm.html#esm_loader_hooks)

**Comment by dnalborczyk** [comment]
hi @Janpot 

could you elaborate on your use case? what does `I'm interested in transpiling modules differently` exactly mean?

the above examples are static imports. depending on your use case, you might be looking for `dynamic imports`:

```javascript
import('./x?a=b')
```

**Comment by Janpot** [comment]
> could you elaborate on your use case? what does `I'm interested in transpiling modules differently` exactly mean?

I'd like to transpile modules before they are instantiated. Like `@babel/register`, but then for `esm`. static or dynamic import alike. I tried adding `@babel/register` with a custom plugin, but it gets called only once per module, even when it gets instantiated twice.

I haven't look deeply yet in how `esm` achieves its functionality, but I suspect this behavior can't be achieved with external tools. 
I'd be interested in a high level overview on how `esm` works if that exists somewhere.

**Comment by dnalborczyk** [comment]
never mind, I think your question is about the possibility of loader hooks in `esm` in general :)
I got hung up on `transpiling modules differently`

**Comment by Janpot** [comment]
> transpile into what?
esm
> do you have a concrete example?
APM, mocking, adding tracing,...

**Comment by dnalborczyk** [comment]
one thing I don't understand is `based on the query parameters they are imported with`. once the module is loaded into memory, it's there to stay. although you can always change the query parameter to be passed on to the module.

> APM, mocking, adding tracing

I believe those things are done differently depending on the tools you want to use.

**Comment by Janpot** [comment]
> once the module is loaded into memory, it's there to stay

Modules will be loaded multiple times if the `import` specifier used to resolve them have a different query or fragment.

**Comment by dnalborczyk** [comment]
> Modules will be loaded multiple times if the import specifier used to resolve them have a different query or fragment.

correct.

I think I'm slowly getting what you're trying to do. the `loader hook` question can probably be answered by @jdalton . not sure if it's doable, or feasible - or if there are things he's waiting on to be flushed out first by the `node modules working group.`

**Comment by jdalton** [comment]
Hi @Janpot!

The `esm` loader already supports loading files as ESM and supports APM, mocking, adding tracing, etc. Existing CJS tools can work with `esm` so the hooks, mocking, coverage, and instrumentation supported for CJS carries over to `esm` without extra work.
