### ISSUE TITLE
Support passing custom information into the require-d module's import.meta [proposal]

### ISSUE THREAD

**Issue by mk-pmb** [standard-things/esm#594]
Could you add an option to esm's main factory's options and/or an individual require, to provide additional custom values for the to-be-imported module's `import.meta`?

**Comment by jdalton** [comment]
Hi @mk-pmb!

That's an interesting addition. What is your use case?

**Comment by mk-pmb** [comment]
Signaling the reason for import, esp. the role in which `nodemjs` had tried to load it. (pre-import, main file or regular.)

**Comment by jdalton** [comment]
With default CJS interop ESM modules will show up in `process.mainModule`, and `process._preload_modules`? Is that what you're looking for?

**Comment by mk-pmb** [comment]
In the long term, yes, when #320 gets in. Until then I'd use some proprietary properties like `import.meta.nodemjs.role`.

**Comment by jdalton** [comment]
Ah, so `import.meta` is something of scratch pad for a given module and is pre-populated by the runtime. In this case with only the `url` provided (limited usefulness). Your module can modify it and export its value to others but the runtime is limited on how it can mutate it. I think for now you'll be better off using the CJS interop/compat (with `.js`). We'll add other associated data to `import.meta` as it makes it's way into Node.
