### ISSUE TITLE
Async / parallel loading of modules

### ISSUE THREAD

**Issue by jkrems** [standard-things/esm#6]
The readme comparison currently doesn't contain that item (which might mean it's not decided yet?) but will `@std/esm` load files in parallel like the native node 10 solution might or will it load/parse each individual file in series like CommonJS?

**Comment by jdalton** [comment]
Hi @jkrems!

Uses of `import()` will defer loading off the current callstack. The `import x from "y"` syntax will process imports synchronously (just as CJS `require` would). The V8 team is working on module load optimizations that all of Node (CJS and ESM) should benefit from so we'll pick those up automagically when they land.
