### ISSUE TITLE
Should allow destructured imports of native modules

### ISSUE THREAD

**Issue by lhorie** [standard-things/esm#60]
Expected:

```
// should work
import {promisify} from 'util';
```

Actual:

`SyntaxError: Module 'util' does not provide an export named 'promisify'`

**Comment by jdalton** [comment]
Hi @lhorie!

The `@std/esm` loader follows [Node's rules](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#46-es-consuming-commonjs) by default, which means treating CJS modules *(even built-in)* as `{default:module.exports}`. However, you can [unlock](https://github.com/standard-things/esm#unlockables) named exports for CJS modules with the `"cjs":true` option.
