### ISSUE TITLE
[Feature Request] Ignore extensions

### ISSUE THREAD

**Issue by stevefan1999-personal** [standard-things/esm#604]
There should be a config to control what extensions should not be considered as a module, for example, Typescript definition files (`*.d.ts`) as they are not required in runtime.

**Comment by jdalton** [comment]
Hi @stevefan1999-personal!

I can dig this. Which option name do you prefer `ignoreExts` or `excludeExts`. 
I could also flip it to be a positive match or support extensions by way of a glob pattern.

**Comment by jdalton** [comment]
How are you requiring `*.d.ts` files? How is `esm` running into them?

**Comment by jdalton** [comment]
On thinking on this a bit more you should be transpiling your TS to output as ESM syntax this way it should remove the `*.d.ts` reference for you.

**Comment by stevefan1999-personal** [comment]
I was running into a subtle mistake I had mistakenly required `d.ts` for me in `event-emitter` so `require('d')` always return an empty object. Indeed, I have a `d.ts` in my package root directory, and renaming it did came back to normal. Thanks.
