### ISSUE TITLE
Causes tests to hang if using nyc and running multiple processes in parallel

### ISSUE THREAD

**Issue by roopakv** [standard-things/esm#605]
I'm going to try my best to explain the issue we are facing, and the various strategies I have tried :)

We initiate our tests by running `nyc npm shard-tests` and `shard-tests` simply splits all our test files in 4, forks 4 processes which run `mocha 'passed-in-files'`

It seems like any time we run many `nyc`s in parallel while requiring esm our tests timeout with an error
`Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves`

Running our tests without sharding but with nyc works.

My guess is that nyc is modifying require somehow and esm is doing the same, and they are somehow clashing.

I tried using the `cjs.extensions: true` but that didnt seem to help either.

I will try post a minimalistic example later tonight

**Comment by jdalton** [comment]
Thanks @roopakv!

I'll keep the issue open for a couple days to see if this a `esm` issue instead of an incidental issue.

**Comment by roopakv** [comment]
I haven't still been able to find a repro whcih i can share :( I have though in the process run our test suite ~100 times and here is what ive found

- Sharding our tests works fine until we use nyc
- The tests only fail on our CI. I think the macbook pro has enough CPU to get thru whatever is causing the hang
- Given enough time ~15 minutes (for what usually takes 3 minutes) each shard passes even on CI

This is where i am trying to create a repro -> https://github.com/roopakv/nyc-esm-parallel

This mimics what we do, but seems to pass fine on the ci machines.

**Comment by jdalton** [comment]
Thanks for that repro attempt @roopakv!

> I tried using the `cjs.extensions: true` but that didn't seem to help either.

All `esm` cjs options are enabled by default.

> Sharding our tests works fine until we use nyc

I couldn't repo the issue.
I also found similar test timings when I replaced `esm` with a simple CJS export
```js
//require = require('esm')(module);
//module.exports = require('./es6_constants');

module.exports = {
  SOMETHING: 2 * 60 * 1000,
  ANOTHER_CONST: 500,
  objectConst: {
    SAMPLE: {
      label: 'sample',
      id: 'sample'
    }
  }
}
```

> I haven't still been able to find a repro which i can share 

No worries. If/when you do please do ping back and I'll do my best to fix things.

**Comment by roopakv** [comment]
@jdalton finally figured out whats up. It seems like we simply went above memory and our CI machine just killed the process. Do you have an idea what esm's additional memory usage is? Our tests used to pass running 4 shards before I added esm

**Comment by jdalton** [comment]
> Do you have an idea what esm's additional memory usage is?

I don't. Do you know what your memory limit is? Also what version of Node are you running?
