### ISSUE TITLE
Requiring/Important a directory

### ISSUE THREAD

**Issue by mansona** [standard-things/esm#61]
Howdy Folks 👋 

we are currently using [node-require-directory](https://github.com/troygoode/node-require-directory) to nicely import each of the files in a directory. I have been trying to re-create it in a "standard" way with esm and I can't quite figure it out, or how It should work 🤔 

I'm currently just using the old require syntax in my modules, I didn't know you could mix and match until I was experimenting with this. 

I wanted to open this issue as a discussion piece and see if anyone would be interested in a more esm way of doing require-directory, and how people might expect it working.

**Comment by jdalton** [comment]
Hi @mansona!

You can use [dynamic import](https://github.com/tc39/proposal-dynamic-import) to:
```js
Promise
  .all(filePaths.map((filePath) => import(filePath)))
  .then((arrayOfExports) => {
    // reduce into desired object and return
  })
```
This would create an async flavor of `node-require-directory` that could work for both ESM and CJS.

**Comment by Jamesernator** [comment]
If the directory isn't changing automatically you might want to generate a module that exports each one that way you can still `import` it statically e.g. if you have files `operators/map.js` and `operators/filter.js` you might want to generate a file like:

```js
// generated file
export { default as map } from "./map.js"
export { default as filter } from "./filter.js"

// Then you can statically import it without needing to await
// a Promise or anything
import * as operators from "./operators.js"
```

I wrote a library a while ago for exactly this purpose called [folder-module](https://www.npmjs.com/package/folder-module), depending on your use case it might be sufficient.
