### ISSUE TITLE
SyntaxError: Identifier 'exports' has already been declared

### ISSUE THREAD

**Issue by EvgenyOrekhov** [standard-things/esm#619]
esm throws `SyntaxError` if a module declares a variable named `exports`.

a.js

```js
let exports;
export default 123;
```

b.js
```js
require = require("esm")(module);
const a = require("./a.js").default;
console.log(a);
```

Command: `node b.js`

Expected result: `123` should appear in the console, there should be no errors.

Actual result:

```text
file:///home/user/esm-bug/a.js:1
let exports;

SyntaxError: Identifier 'exports' has already been declared
    at new Script (vm.js:79:7)
```

There is no such error if I use native Node.js ES modules with the `--experimental-modules` flag.

**Comment by EvgenyOrekhov** [comment]
The error goes away if I rename `a.js` to `a.mjs`.

**Comment by jdalton** [comment]
Hi @EvgenyOrekhov!

By default `esm` ships with all the `cjs` options set to `true`. This means the `cjs.vars` option is `true` which means the module var values like `exports`, `module`, and `require` exist. You can set the specific `cjs` option to `false` or turn them all off. You should be cautious using `.mjs` as it turns off all `esm` options, including CJS interop.
