### ISSUE TITLE
Not working with babel-register

### ISSUE THREAD

**Issue by raine** [standard-things/esm#62]
```json
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "node": "current"
      }
    }]
  ]
}
```

```js
require('@std/esm')
require('babel-register')
require('./src/index')
// etc.
```

```
(function (exports, require, module, __filename, __dirname) { import path from 'path';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
```

Removing `require('babel-register')` fixes the issue but doesn't work because babel is used for some syntax transformations.

So the issue looks to be that babel is for some reason wrapping the files with a function that makes the import syntax not work because it should be at start before anything.

**Comment by jdalton** [comment]
That's interesting. Until just a few days ago `@std/esm` ran it's unit tests with `babel-register` so I know it's possible for them to work (assumed it was the norm). The `@std/esm` and `babel-register` should play well together. The `@std/esm` loader is designed to pass through to others like `babel-register`. Have you tried swapping the order of your require calls
```js
require('babel-register')
require('@std/esm')
```

**Comment by raine** [comment]
I tried swapping order, but that seems to break babel transformations.

Here's a broken test case: https://github.com/raine/esm-babel-test

```js
require('babel-register')
require('@std/esm')

require('./app')
```

```
% node start
/Users/raine/esm-babel-test/foo.js:2
export default {...foo}
                ^

SyntaxError: Unexpected token
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at Object.<anonymous> (/Users/raine/esm-babel-test/app.js)
    at Object.<anonymous> (/Users/raine/esm-babel-test/app.js)
    at Module._compile (module.js:573:30)
```

Swapped require order:

```
require('@std/esm') 
require('babel-register')

require('./app')
```

```
% node start
/Users/raine/esm-babel-test/app.js:1
(function (exports, require, module, __filename, __dirname) { import foo from './foo';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at loader (/Users/raine/esm-babel-test/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/raine/esm-babel-test/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```

**Comment by jdalton** [comment]
Thanks for the repro!

It looks like swapping the order did fix it. What you're seeing with `{...foo}` is the lack of object-rest-spread support. This is an [Acorn issue](https://github.com/ternjs/acorn/issues/388#issuecomment-321725923) at the moment. There's [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=756006) to track adding an Acorn plugin too. You should also file a bug on [babel-register](https://github.com/babel/babel/issues) to pass-through to other loads so that the order can work with
```js
require('@std/esm') 
require('babel-register')
```
as well.

**Comment by jdalton** [comment]
I've opened an issue on `babel-register` https://github.com/babel/babel/issues/6248.

\ @FND @tilgovi

**Comment by NathanielHill** [comment]
It looks like your problem is with `"modules": false`, and that using `esm` is unnecessary here.
