### ISSUE TITLE
importing module from re-exported file causes error

### ISSUE THREAD

**Issue by OmgImAlexis** [standard-things/esm#621]
`index.js` contains all the files from `components` exported as such.
```js
export { default as Config } from './config.vue';
```
<hr>

If I use `import { Config } from './components'` my tests end up with the following error.

```
➜  slim git:(feature/router-link) ✗ yarn ava test/specs/asset.spec.js --verbose
yarn run v1.9.4
warning package.json: No license field
$ /Users/xo/code/Medusa/themes-default/slim/node_modules/.bin/ava test/specs/asset.spec.js --verbose

  Uncaught exception in test/specs/asset.spec.js

  /Users/xo/code/Medusa/themes-default/slim/src/components/index.js:83

  TypeError: Cannot read property 'default' of undefined

  Object.get [as Config] (src/components/index.js:83:20)
  Object.<anonymous> (src/router.js:365:22)
  Object.<anonymous> (node_modules/esm/esm.js:1:214605)
  Object.o._compile (node_modules/esm/esm.js:1:210603)
  compile (node_modules/require-extension-hooks/src/hook.js:75:10)
  hook (node_modules/require-extension-hooks/src/hook.js:32:3)
  Zl (node_modules/esm/esm.js:1:209533)
  Object.<anonymous> (node_modules/esm/esm.js:1:209726)
  node_modules/esm/esm.js:1:211678
  node_modules/esm/esm.js:1:211732

  ✖ test/specs/asset.spec.js exited with a non-zero exit code: 1

  1 uncaught exception

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
<hr>

If I use `import Config from './components/config.vue` it works fine.
```
➜  slim git:(feature/router-link) ✗ yarn ava test/specs/asset.spec.js --verbose
yarn run v1.9.4
warning package.json: No license field
$ /Users/xo/code/Medusa/themes-default/slim/node_modules/.bin/ava test/specs/asset.spec.js --verbose

  ✔ renders default content for network
  ✔ renders image with API v2 path for network

  2 tests passed

✨  Done in 22.08s.
```
<hr>

If you could point me in the right direction that'd be appreciated and if you need more info just let me know. I'm not 100% sure where to start looking as from what I can tell the stack trace is showing the line number, etc. from the compiled file.

**Comment by jdalton** [comment]
Hi @OmgImAlexis!

Could you please create a small repro repo.
It would help me better identify the issue.

**Comment by alippai** [comment]
We use the following example, esm@3.0.34 works: 

A.js
```js
export default const A = 'A';
```

B.js
```js
import { default as Letter } from './A';
export { default as Letter } from './A';
console.log(Letter);
```

C.js
```js
import { Letter } from './B';
console.log(Letter);
```

**Comment by jdalton** [comment]
Hi @OmgImAlexis!

I'm just marking as `invalid` in the absence of a reproducible test case. If you have one at a later time please feel free to ping back and we'll do our best to investigate it.

**Comment by OmgImAlexis** [comment]
Sorry for the lack of reply. I'm still trying to track down where the actual issue is coming from so I can make an isolated test case. I do know it's in some way related to esm as I've never had this issue with our old babel setup.

**Comment by sharkykh** [comment]
@OmgImAlexis 
I'm gonna go on a limb here, and say it was just a circular import issue...
