### ISSUE TITLE
ESM disabling colored output?

### ISSUE THREAD

**Issue by damianobarbati** [standard-things/esm#622]
```
//node test.js
const console = require('better-console');
console.error('this is red');
```
vs
```
//node -r esm test.js
import console from 'better-console';
console.error('this is not red');
```

**Comment by damianobarbati** [comment]
Not sure because I just found out `assert` methods are able to print red messages.

```
$ node -r esm -e 'import { strict as assert } from "assert"; assert.deepStrictEqual(1, 2)'
```

**Comment by jdalton** [comment]
Hi @damianobarbati!

Thanks. The issue is that I was incorrectly detecting shadowed identifiers. My strategy for detection works great for ESM identifiers but didn't account for global identifiers. I've patches this locally and will merge when I have tests written.
