### ISSUE TITLE
export default from syntax

### ISSUE THREAD

**Issue by aemino** [standard-things/esm#63]
Hello! Reading the release post indicated to me that `export default from` was enabled by default by this package.

Using this code results in an "Unexpected token" error:

```js
// index.js
require('@std/esm');
require('./entry');

// entry.mjs
export foo from './foo';

// foo.mjs
export const foo = 'bar';
```

**Comment by jdalton** [comment]
Hi @aemino!

The release blog did not indicate that. It mentioned that it spurred champions for the language extension proposal.
