### ISSUE TITLE
Module loaded multiple times when imported by multiple module

### ISSUE THREAD

**Issue by ben-page** [standard-things/esm#633]
# Background
I have node module (let's call it `module-a`), which includes two modules as dependencies (`module-b` & `module-c`). `module-b` also has `module-c` as a dependencies. 
```
        module-a
   |               |
module-b        module-c
   |
module-c
```

# Issue
`esm` loads `module-c` twice. `module-a` and `module-b` are getting different copies of `module-c`. I verified this by adding a console log to the top of `module-c`.
```javascript
console.log((new Error('Loaded module-c').stack));
```
**Console Output:**
```
Error: Loaded module-c
    at Object.<anonymous> (C:\module-a\node_modules\module-c\lib\index.js:9:22)
    at Generator.next (<anonymous>)
    at Wl (C:\module-a\node_modules\esm\esm.js:1:207717)
    at C:\module-a\node_modules\esm\esm.js:1:208589
    at Jl (C:\module-a\node_modules\esm\esm.js:1:208895)
    at Object.x (C:\module-a\node_modules\esm\esm.js:1:244115)
    at Object.o._compile (C:\module-a\node_modules\esm\esm.js:1:210665)
    at Object.u (C:\module-a\node_modules\esm\esm.js:1:244481)
    at Object.l (C:\module-a\node_modules\esm\esm.js:1:243616)
    at Object.<anonymous> (C:\module-a\node_modules\esm\esm.js:1:241320)
Error: Loaded module-c
    at Object.<anonymous> (C:\module-a\node_modules\module-c\lib\index.js:9:22)
    at Generator.next (<anonymous>)
    at Wl (C:\module-a\node_modules\esm\esm.js:1:207717)
    at C:\module-a\node_modules\esm\esm.js:1:208589
    at Jl (C:\module-a\node_modules\esm\esm.js:1:208895)
    at Object.x (C:\module-a\node_modules\esm\esm.js:1:244115)
    at Object.o._compile (C:\module-a\node_modules\esm\esm.js:1:210665)
    at Object.u (C:\module-a\node_modules\esm\esm.js:1:244481)
    at Object.l (C:\module-a\node_modules\esm\esm.js:1:243616)
    at Object.<anonymous> (C:\module-a\node_modules\esm\esm.js:1:241320)
```

# Extra Details
All of these projects use `import`, but have a stub `main.js` for backward compatibility. Like this:
```javascript
/* eslint-disable no-global-assign */
'use strict';
require = require('esm')(module, {mainFields: ['module', 'main']});
module.exports = require('./index.js');
```

They all have `main` and `module` defined in the `package.json`.
```json
{
  "main": "lib/main.js",
  "module": "lib/index.js"
}
```

# Observations
1. Starting module-a with `node -r esm lib/index.js`  rather than `node lib/main.js` fixes the problem.
2. Adding a `.esmrc.js` to module-b also fixes the issue:
    ```javascript
    module.exports = {
        mainFields: ['module', 'main']
    };
    ```

I'm not sure what the correct behavior is, but this seems inconsistent. I did not expect using `-r esm` to behave differently than requiring `esm`.

**Comment by jdalton** [comment]
Hi @ben-page!

Could you create a simple repro repo for me to take a look at. It will help narrow down the issue.

**Comment by ben-page** [comment]
[esm.zip](https://github.com/standard-things/esm/files/2502501/esm.zip)
Extract the zip to a directory.

Run `npm run script` to run the `main.js` as a script (with `require = require('esm')`) and see the problem. Output (_`module-c` is loaded twice_):
```
loaded module c
loaded module b
loaded module c
loaded module a
running module a
running module c
running module b
running module c
```


If you run `npm run module` it will execute with `node -r lib/index.js` and the code will work as expected.
Output (_`module-c` is loaded once_):
```
loaded module c
loaded module b
loaded module a
running module a
running module c
running module b
running module c
```
_`module-c` is loaded once_

**Comment by jdalton** [comment]
Thanks @ben-page!

Could you re-upload the `esm.zip` I'm getting a -1 operation not permitted error trying to extract it.

**Comment by ben-page** [comment]
It seems like Github might be having trouble. I wont let me upload at all. However, I was able to download it and extract it. So you might try it again.

Alternatively, I uploaded it to my Google Drive. [https://drive.google.com/file/d/1oLNZRzzSKVEfffsCtNRGM4dk1PE6OhF2](https://drive.google.com/file/d/1oLNZRzzSKVEfffsCtNRGM4dk1PE6OhF2)

**Comment by ben-page** [comment]
[esm.zip](https://github.com/standard-things/esm/files/2503154/esm.zip) Now uploading is working.

**Comment by ben-page** [comment]
@jdalton any luck?

**Comment by jdalton** [comment]
Yes, I can repro the issue. It's not 100% a bug though so I'm digging into the bit that is.

**Comment by jdalton** [comment]
Ok digging into this more. The appears when running as a package loader _(so not `node -r esm`)_ because when running as a package loader each loader has its own internal state. In this case during the parse phase each loader has its own scratch cache. Because of this one loader can't see that the other loader has the same file in their scratch caches. When run as an application level loader _(so `node -r esm`)_ all the loaders are no longer isolated and share a common scratch cache. 

The solution is just like the entry cache I can detect that these loaders are identically configured and have them share their scratch cache which avoids the issue. I have this patched roughly locally.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/1db457b996e7a6d204a3093fb9e9e44cbb95e2e8; Tests https://github.com/standard-things/esm/commit/fddcd8d4548dce28271f79da7b1f882cb62626af.

**Comment by DaveStein** [comment]
@jdalton I am still able to reproduce the bug in my app. I am looking on how the hell I can reproduce it in a small example. Have been unable to reproduce outside of my app. However I'm fairly sure it's around the same thing because if I make a new "module C" one level up in my app, error goes away. Hopefully I'll have some actual details soon.

**Comment by DaveStein** [comment]
Is there a trick to see the dependency tree? I see my file loading twice and am curious what is making that happen while the stacktrace only shows esm.js

**Comment by DaveStein** [comment]
@jdalton Uh oh... 3.0.84 doesn't have this fix yet eh - I think I lost my mind trying to reproduce easily and then messed up reading the dates. It's a shame there's no emoji for seppuku

**Comment by jdalton** [comment]
Hi @DaveStein!

Your issue is different. You have mixed case
```js
import User from '../utils/user';
```
and 
```js
import User from '../utils/User';
```
which get treated as 2 distinct loads and cache entries in OS's like macOS.
