### ISSUE TITLE
Error when using with object spread in Node 8.4.0

### ISSUE THREAD

**Issue by trungdq88** [standard-things/esm#64]
📄 *index.js*
```
require('@std/esm');
module.exports = require('./test.js').default;
```

📄  *test.js*
```
function a() {
  var spread = { b: 2, c: 3 };
  var O = { a: 1, ...spread };
  return O !== spread && O.a + O.b + O.c === 6;
}
export const b = 123;
```

▶️ Run `node index.js` give error:
```
node index.js
/Users/dinhquangtrung/Documents/Projects/hac-web-3/test.js:3
  var O = { a: 1, ...spread };
                  ^

SyntaxError: Unexpected token
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dinhquangtrung/Documents/Projects/hac-web-3/index.js:2:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
```

❗️  If I remove the line `export const b = 123;`, then `node index.js` works fine.

```
$ node --version
v8.4.0

$ cat package.json | grep @std/esm -A 2
    "@std/esm": "^0.5.1",
    "body-parser": "^1.17.2",
    "classnames": "^2.2.5",
--
  "@std/esm": {
    "esm": "js"
  },
```

Please help.

**Comment by jdalton** [comment]
Hi @trungdq88!

See https://github.com/standard-things/esm/issues/14#issuecomment-322012346.

**Comment by trungdq88** [comment]
Thanks.

**Comment by jdalton** [comment]
@trungdq88 You should totally star the [Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=756006) too 😃

**Comment by trungdq88** [comment]
Ah, nice. 👍

**Comment by trungdq88** [comment]
I am allow to ask another quick question here?
Should `esm` resolve `import '../something';` to `import '../something/index.js';`?

**Comment by jdalton** [comment]
> Should `esm` resolve `import '../something';` to `import '../something/index.js';`?

It totally should. I notice it doesn't at the moment. I'll patch that asap.

**Comment by trungdq88** [comment]
Can I expect a new release with that patch soon?

**Comment by trungdq88** [comment]
Thanks for your work :)

**Comment by jdalton** [comment]
`@std/esm` v0.7.0+ should no longer choke on object rest spread syntax.
