### ISSUE TITLE
Weird behaviour with dynamic import of JSON: default is merged/mixed?

### ISSUE THREAD

**Issue by oles** [standard-things/esm#645]
First of all I want to thank you once more, @jdalton - this project is wonderful :clap: 

I've gone all in ESM on my recent projects, and it has been a pleasure modularizing all my stuff, especially when combined with https://github.com/ilearnio/module-alias

Now, I'm not sure what I've stumbled upon, but the value returned from `await import('./file.json')` contains the file **along** with a `default` property with the same content.

Is this as intended?

**Comment by jdalton** [comment]
Hi @oles!

Thank you! Yes, this is intended. We treat JSON as a CJS module since the results (to Node) are similar (behind the scenes it does `module.exports = JSON.parse(content)`. This means it has named exports (on by default) and also the a `default` export of the `module.exports` result.
