### ISSUE TITLE
Loading esm after appoptics-apm on Node 10.x results in cc error

### ISSUE THREAD

**Issue by onlywei** [standard-things/esm#646]
Hi,

I have a reproducible repository here: https://github.com/onlywei/appoptics-esm-node10
There are instructions in that repository to see the error.

I have verified that the node process indeed gets past appoptics-apm and is erroring when trying to load `esm`.

Also this works in Node 8.x. It only breaks in Node 10.x, which is now the LTS version of Node.

**Comment by onlywei** [comment]
@bmacnaughton

**Comment by jdalton** [comment]
Thanks @onlywei!

I found the issue. Working on a patch.

**Comment by bmacnaughton** [comment]
I can add the missing `.native` functions on the appoptics end. I'm suspecting that your patch might be uglier/harder than mine. If that works for you I'll get it out in the next release I do. Anyway, I've verified that it no longer causes the core dump in the simple test and that it passes our own tests but I haven't run it against any wider tests you might have in place.

I appreciate you isolating the issue in your code. Would you mind pointing me at where exactly it core dumps? I figured I'd find some C or C++ code in your repo but it's all JavaScript.

**Comment by jdalton** [comment]
Hi @bmacnaughton!

No worries on testing the core dump. That was a side-effect of the missing `.native` method. Our code would then take a more-risky route. The fix on the `esm` side is to not take the more risky route if the `.native` method is supposed to exist but doesn't (we'll add a Node version sniff). For appoptics a simple test to ensure the wrapped fs methods have the `.native` is fine.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/59f4ed018580316dedcad30763927bd7b714bc70.
