### ISSUE TITLE
Error occurs when circular importing.

### ISSUE THREAD

**Issue by leiysky** [standard-things/esm#651]
## Background
It works well with `esm 3.0.0` when using a circular import.
And the issue occured when using `esm 3.0.18` or `esm 3.0.84`, here is a simple [demo](https://github.com/leiysky/esm-demo).

## Detail
I have no idea to completely reproduce the issue. Actually the issue is much more complex than the demo.

I would try to describe the issue:

work dictionary: 
```
./utils
├── index.js
└── utils.js
```
utils.js:
```js
export const func = function(){}
```
index.js:
```js
// some imports
import { func } from './utils';

export * from './utils';

console.log(func); // ok

export function abc() {
  console.log(func); // func is not defined
}
```

It's very odd. 

I can imagine that maybe `func` didn't get its value when importing. But it did be imported, and has no value when imported by other module which has a circular import with `index.js`

I'm not sure if the actual issue is the same as that occurs in the demo.

**Comment by jdalton** [comment]
Thanks for the repo @leiysky!

**Comment by jdalton** [comment]
**Update:**

I have fixed this locally.

**Comment by jdalton** [comment]
Tests https://github.com/standard-things/esm/commit/b6a20cf7d054e5f6f90783d1111964ad61fe6e88.
