### ISSUE TITLE
Dynamically load/register module from string

### ISSUE THREAD

**Issue by Tundon** [standard-things/esm#663]
Recently got a requirement to load modules from remote server. Some research revealed solutions like [this module](https://github.com/floatdrop/require-from-string), whose core idea is as follow:
```javascript
const Module = require('module')
var m = new Module()
m._compile("[content from remote location]", "virtual/module/path.js")
console.log(m.exports)    //  the exports from the remote module
```
Though this solution would have some issues for me:
1.  the `import`/`export` won't work, I believe that's because it is using node module directly
2. circular dependencies won't work as elegantly as those in `esm` work

So my question is, is there any way we can register/create a virtual module while still go through `esm`?

**Comment by jdalton** [comment]
Hi @Tundon!

I took your example code above, put it into a file named `foo.js`:
```js
const Module = require('module')
var m = new Module()
m._compile("export { sep } from 'path'", "virtual/module/path.js")
console.log(m.exports)    //  the exports from the remote module
```
then ran it like `node -r esm ./foo.js` and it logged `{ sep: '/' }`.

**Comment by Tundon** [comment]
@jdalton Thanks for the help! I tried your snippets, and it does work. But if the module exports a class, it won't work
```javascript
const Module = require('module')
var m = new Module()
m._compile("export { sep } from 'path'\n export class Empty {}", "virtual/module/path.js")
console.log(m.exports)    //  the exports from the remote module
```
Only the `sep` got exported, the `Empty` is not there. Will this because of `esm` async nature?
Tho I tried adding following (I know it looks silly)
```javascript
setTimeout(() => console.log(m.exports))
```
it still doesn't have `Empty`. Did I miss something?

**Comment by jdalton** [comment]
Nope! It looks like this is resolved in the `master` branch version. So should export `Empty` when I publish the next release _(in the next couple of days)_.

**Comment by Tundon** [comment]
Got it! That's a great news for a good weekend! Happy weekend @jdalton !

**Comment by jdalton** [comment]
Ah, I see. In the current released version you need to add:
```js
m.loaded = true
```
so
```js
var m = new Module()
m._compile("export { sep } from 'path'\n export class Empty {}", "virtual/module/path.js")
m.loaded = true
console.log(m.exports)
```
In the next release setting `m.loaded` isn't a bad idea either.

**Comment by Tundon** [comment]
Thanks a lot! That worked, and saved my project! Cheers 🥃

**Comment by jdalton** [comment]
Is your project on GitHub somewhere? I'd dig checking it out.

**Comment by Tundon** [comment]
Nah, it is a kinda of private one. The tricky part is to load the module from remote location while still able to import dependencies from local modules.

I ended up using rollup to bundle all the code into a single file and use the trick we discussed here to dynamically compile it

I will creat a smaller repo on GitHub later to demo the dynamic loading part, you are very welcome to play around 🍻

Yun

**Comment by Tundon** [comment]
So [import-virtual-module](https://github.com/Tundon/import-virtual-module) is a small repo that I am using as an experiment.

In there, the virtual module could load real module just fine, but if another virtual module trying to import from previous virtual module, it will file (I think it may because of how node.js handles module resolution, it is always looking in file system)
