### ISSUE TITLE
Release or roadmap

### ISSUE THREAD

**Issue by alippai** [standard-things/esm#669]
Can you share some details when / what will be released next? The last release is dated to Sep 18, I assume something is blocking the next one

**Comment by jdalton** [comment]
Hi @alippai!

Good hunch! There was some blockage for a few weeks I was wrangling test262 compliance tests. I came out on top though. Now I'm getting things back in shape for a release. Ideally I wanted to have Jest and WASM support done but it looks like enough time has gone by that a release before they get 💯 would be a good idea. I should have a release this week. I'll update this issue when I release.

**Comment by alippai** [comment]
Keep up your awesome work! Also let me know if I can contribute, I have a little bit of spare time until next week

**Comment by jdalton** [comment]
@alippai Thank you!

If you're looking to contribute please see [this list](https://github.com/standard-things/esm/issues?utf8=%E2%9C%93&q=label%3A%22needs+tests%22) of issues that still need tests written. Knocking out a few in PRs would be very appreciated!
