### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by gauntface** [standard-things/esm#67]
Opening in case there was a clever trick to this.

I've just  moved off of a Rollup bundled set of tests to running directly with @std/esm so for that **THANK YOU SO FRIGGIN MUCH**.

One thing I can't get working is code coverage. It looks like `nyc` is either hooking into `require()`, covering just `.js` files or something else. It's simply not picking up anything to do with `.mjs` files.

Has anyone got any ideas for fixing this?

**Comment by gauntface** [comment]
Stupid me:

```
nyc --require @std/esm --extension .mjs mocha ./test/**/node/**/*.mjs
```

**Comment by jdalton** [comment]
🤘
