### ISSUE TITLE
Recursively invalidating cache.

### ISSUE THREAD

**Issue by thysultan** [standard-things/esm#670]
Repo: [https://github.com/thysultan/dio.js/tree/X](https://github.com/thysultan/dio.js/tree/X)

In the following: (`tests/Assert.js#L5`) i try to dynamically reload the module to run tests after mutation of environment variables(i.e NODE_ENV) to test dev environment branches.

```js
const {h, render, Component} = await import('../index.js?')
```

The issue is that trying to do this doesn't also invalidate the cache of modules that `index.js` imports.

I have attempted to no avail in altering the param query, and as a last resort setting the global `cache` option in `pkg.esm` to false.

**Comment by jdalton** [comment]
Hi @thysultan!

The `esm` loader lets you invalid caches as you would with CJS.
You can find the module entry in the `Module._cache` and `delete` it.
```js
import Module from "module"
delete Module._cache[modulePathOfFile]
```

or in your dynamic `import()` you can add a cache invalidator param
```js
await import(`../index.js?${Date.now()}`)
```

**Comment by thysultan** [comment]
@jdalton Unless i'm missing something, the issue is that the cache invalidator param(`import("../index.js?${Date.now()}")`) only seems to invalidate the cache for the entry file `index.js` but not the imports within `index.js` imports recursively.

**Comment by jdalton** [comment]
You are correct. If you're wanting to clear away more of the cache then deleting from the `Module._cache` is the way to do. For example deleting all non-`.mjs` cache can be done by
```js
Module._cache = { __proto__: null }
```

**Comment by thysultan** [comment]
Thank you.
