### ISSUE TITLE
esm error: Identifier '__global__' has already been declared

### ISSUE THREAD

**Issue by pvdlg** [standard-things/esm#671]
This is a follow up to https://github.com/avajs/eslint-plugin-ava/issues/210.

I finally found a way to reproduce the issue:
- Install the version of Atom
- Install the [linter-xo](https://atom.io/packages/linter-xo) Atom package
- Clone the https://github.com/semantic-release/gitlab and https://github.com/semantic-release/github repo and run `yarn install` in each
- Add those two project to Atom (File > Add Project folder)
- Open a js file from `semantic-release/gitlab` => it lints properly without errors
- Open a js file from `semantic-release/github` => The error happens

So after starting Atom it will work for the firt file opened and all the files in the same project. Opening a file from another project will cause the issue.
I'm guessing it's because for each project an instance of the linter will be created and esm fails during the creation of the second instance due to a conflict with the `__global__` variable.

**Comment by jdalton** [comment]
Thanks for the repro @pvdlg!

Fixed by https://github.com/standard-things/esm/commit/9c2ecdf21b696c02068a0ed34e00a361ada263f7#diff-332068872182b2165b3007bf6930b230.

**Comment by pvdlg** [comment]
@jdalton thanks for the fix! Do you plan to release it soon by any chance?

**Comment by jdalton** [comment]
Soonish. I should release before I start of more aggressive perf work. I'll ping back this thread when it's released.
