### ISSUE TITLE
Cannot use eval as name

### ISSUE THREAD

**Issue by StreetStrider** [standard-things/esm#673]
It seemes that I can't `var eval = …` or `function eval () {…`. Possible esm somewhere uses simple check for `substring eval`.

**Comment by jdalton** [comment]
Hi @StreetStrider!

Are you using eval like this in an ESM module? If not are you using it in CJS in strict mode, `"use strict"`?

**Comment by jdalton** [comment]
ES modules are in implicit strict mode. One of the restrictions on that is using `eval` as an identifier. This is the same restriction if you used `"use strict"`.

**Comment by StreetStrider** [comment]
@jdalton yes, I got plain script with, for instance, `var eval = 1` which is `use strict` implicitly (I understand). Looks like it is an actual restriction of strict mode which I previously know nothing about. But it's in the [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Making_eval_and_arguments_simpler).
