### ISSUE TITLE
In import I cannot use variable as module-name

### ISSUE THREAD

**Issue by d-adamkiewicz** [standard-things/esm#678]
Say I want something like

```javascript
const path = '/home/me/manifest.json';
import manifest from path;
/*
* this works
* import manifest from '/home/me/manifest.json'
*/
```
```bash
import manifest from path;
                     ^

SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```
this doesn't work by design? I cannot use variable as module-name?

**Comment by jdalton** [comment]
Hi @d-adamkiewicz!

Yes, this is by design and how modules work. The specifier for a static import must be a string literal.
However, you can pass a variable to asynchronous dynamic `import()`
