### ISSUE TITLE
Hooking the resolver / controlling ES module detection

### ISSUE THREAD

**Issue by guybedford** [standard-things/esm#68]
I'm really excited about the paths forward this project can enable and would like to explore if I could implement https://github.com/nodejs/node-eps/pull/60 on top of this project, as it would really help to be able to show the exact workflows.

In order to do this, I could try to integrate the rules directly into a fork, but more interestingly it might be nice to open up the resolver in the same way that ES modules in Node and the browser will likely be looking at having a hookable resolver in future.

A simple strawman for such a feature might look like:

```js
require('@std/esm').setResolver((name, parentModule) => {
  return {
    resolved: customResolve(name, parentModule),
    format: 'esm'
  };
});
```

Would there be interest in developing an API along these lines?

**Comment by jdalton** [comment]
Hi @guybedford!

I think a resolver is a nice way to handle it and allows others to customize. Do you know if there have been any APIs rough drafted for Node related to this?

As for prepping a patch, you might hold off until our next release. Our API is changing a bit to reduce reliance on pseudo private Node APIs. So instead of
```js
require("@std/esm")
module.export = require("./main.mjs").default
```
it will be
```js
module.exports = require("@std/esm")("./main.mjs").default
```

**Comment by bmeck** [comment]
We are roughly in talks but no EP has been made yet for resolution hooks.

**Comment by jdalton** [comment]
Cool! I'm up for helping on this end *(proofing out implementations and what not)*.

**Comment by guybedford** [comment]
@jdalton thanks for being open to this. I'm aiming to put together a draft spec here that could be turned into an EPS in due course. Will share the link when it's ready for feedback, then it would be great to be able to start working towards implementation.

**Comment by jdalton** [comment]
Thanks @guybedford!

That sounds like a plan : )
