### ISSUE TITLE
Packaging esm/electron-quick-start includes very large esm size

### ISSUE THREAD

**Issue by gmattie** [standard-things/esm#683]
Using **[Electron Packager](https://github.com/electron-userland/electron-packager)** to package an application with **[esm](https://github.com/standard-things/esm)** adds an additional ~600kb to the bundle size on Windows 10!

Is there anyway to mitigate this issue?  The packaged esm node package is bundled along with a 256kb "loader" file as well as a ".data.blob" cache file at 337kb.  Should those files be included?

I've forked the esm/electron-quick-start repo and added a build scripts for packaging that you may use to package your own Electron application with esm:  **https://github.com/gmattie/electron-quick-start**

Below is a screenshot of the packaged node_modules which details the size of esm.

![esmbundle](https://user-images.githubusercontent.com/933921/49339248-30429100-f5fd-11e8-86f4-a064344c5ef6.PNG)

**Comment by jdalton** [comment]
Hi @gmattie!

Thanks for trying `esm` out with Electron! Something to keep in mind is that the base-line Electron application is over 120MB (macOS) so the worry over a couple MB here or there may be misplaced. That said, you can try packaging the sample app without the `.cache` folders.

**Comment by gmattie** [comment]
Hey @jdalton, thanks for the reply.

I agree that Electron applications are quite large and that's the reason why I am trying to _trim the fat_ wherever possible.  Besides that, I assumed there was a problem because **esm** is much larger than the other dependencies when packaged.

I've updated my repo with caching options (both as a parameter and within package.json) but it doesn't seem to have any effect as the packaged application still includes all the esm cache files.

**index.js**
```
// eslint-disable-next-line no-global-assign
require = require('esm')(module, { cache: false });
require('./main.js');
```
**package.json**
```
"esm": {
    "cache": false
}
```

Is the syntax wrong?  Any ideas?

**Comment by gmattie** [comment]
Ok, I understand. 

However, if I _do_ disable caching with the above syntax, after closing the application a new folder `\node_modules\.cache\esm\` is written within the **esm** package that includes `.data.blob` (337kb) and `.data` (1kb) cache files.  Are those files still supposed to be written if caching is disabled?

**Comment by jdalton** [comment]
Ya that's just the loader's own cache, independent of other package cache configs.
