### ISSUE TITLE
Disabling "use strict" mode?

### ISSUE THREAD

**Issue by matthew-dean** [standard-things/esm#684]
Is there a way to turn off strict mode when interpreting a JS file? For example, I have a use case to use a `with` statement, but I get the error: `SyntaxError: Strict mode code may not include a with statement`

**Comment by dnalborczyk** [comment]
@matthew-dean   ES6 modules are running implicitly in `strict mode`, and therefore shouldn't be able to be disabled, as it violates the language spec. more info: https://ponyfoo.com/articles/es6-modules-in-depth#strict-mode

if the `with statement` is located in a commonjs module without a `use strict` directive it should be able to execute without an error.

**Comment by jdalton** [comment]
Hi @matthew-dean!

If your JS file is CJS then it you can run in it loose mode (non-strict) but as @dnalborczyk points out ES module code is implicitly strict by design.
