### ISSUE TITLE
SyntaxError: Invalid regular expression flags

### ISSUE THREAD

**Issue by matthew-dean** [standard-things/esm#685]
Getting an error when trying to load `esm` in a `vm2` context: `SyntaxError: Invalid regular expression flags`

It also outputs this chunk just before the error:
```js
const __global__ = this;(function (require, module, __jest__, __shared__) { "use strict";var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,Reflect:global.Reflect,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e,()=>e.a},r.r=function(){},r(r.s=2)})([(function(e,t){var r;t=e.exports=H,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";var i=256,n=Number.MAX_SA
```
Any ideas?

**Comment by jdalton** [comment]
Hi @matthew-dean!

Can you provide a simple repro repo?

**Comment by jdalton** [comment]
Okay!

This is because you didn't put the require path `${vmPath}` in quotes. So when the template string is processed it because something like `require(/Users/me/projects/esm-vm2/vm.js)` which is an invalid regexp literal. Changing it to `require("${vmPath}")` fixes the issue.

**Comment by matthew-dean** [comment]
DEEERP

**Comment by matthew-dean** [comment]
Sorry to bug ya lol.

**Comment by jdalton** [comment]
No problem. It let me find a case where we weren't masking the error stack. You shouldn't see that long line of code before the error. It turns out the errors thrown by vm2 aren't of the `Error` constructor so we didn't see them as maskable. I'll tweak our detection to cover that case.

**Comment by jdalton** [comment]
Fixed in master branch related to #681.

**Comment by jdalton** [comment]
**Update:**

Once I resolve that though you'll run into another issue of needing to allow specific builtin module access, so adding `require.builtin` of `["*"]` to the `vm2` options to pass that quickly, but then you'll run into an error 
```
TypeError: 'get' on proxy: property 'prototype' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '[object Object]' but got '[object Object]')
```
And that looks like a bug in `vm2` where it doesn't handle the access to `require('vm').Script.prototype` correctly.
```js
new VMScript(`require('vm').Script.prototype`) // Error
```

**Comment by matthew-dean** [comment]
Doesn't `require.builtin = ['*']` defeat much of the purpose of sandboxing? I know that's more of a vm2 question, but is there a way to limit it to just the builtins that `esm` is using?

Technically, I don't need `esm` to be sandboxed, but I want the code that `esm` is loading to be sandboxed, and that basically means choosing the environment, host or sandboxed, for all requires.

**Comment by jdalton** [comment]
I just used `require.builtin` to get things moving to the next stage of trying to get it working and then ran into the`vm2` bug.

**Comment by matthew-dean** [comment]
Ah. I wonder if you could do, in `vm2`...
```
require = require('esm')(module)
const vm = new NodeVM({
  console: 'inherit',
  sandbox: {require},
  require: {
    external: true,
    context: 'sandbox'
  }
})
```
I can't test it because of #681, but I wonder if injecting a require into the global VM sandbox is actually used, or if it has no effect (depending on how the require function is currently injected).

**Comment by matthew-dean** [comment]
Nope, tried it in my `esm-vm2` repo, got `SyntaxError: Unexpected token export`
