### ISSUE TITLE
Should .esm-cache be added to .gitignore

### ISSUE THREAD

**Issue by jimthedev** [standard-things/esm#69]
Perhaps I missed it in the readme but I just wanted to confirm if .esm-cache would be something you'd want in your gitignore file. Looking at this repo I see it in there and being a cache it seems like it'd be reasonable to just ignore it. Just wanting official confirmation of intent really. Thanks!

**Comment by jdalton** [comment]
Hi @jimthedev!

Yes, `.esm-cache` is something you'd want to add to your gitignore.
Would you be up for creating a PR to add a note to the readme?

**Comment by jimthedev** [comment]
👍 see #70.
