### ISSUE TITLE
Dynamic Import Hangs

### ISSUE THREAD

**Issue by dsanders11** [standard-things/esm#692]
@jdalton, sorry if I'm missing something obvious here, trying to get something working for a deadline so can't deep dive.

I can't seem to get `import()` to do anything in Electron. I have a reproduce case [here](https://github.com/dsanders11/electron-quick-start/tree/dynamic-import-hang), but I'll reproduce the code here since it's simple:

```javascript
import('./foo.js').then(module => {
  console.log('success', module)
}).catch(error => {
  console.error('error', error)
})
```

I'd expect that to either resolve or reject, but instead neither happens. I've tried a number of different things with no change:

* File suffix of `.mjs`
* Configuring `esm` to `"module": "all"`
* Various combinations of `import('foo.js')`,` import('./foo')`, etc

Any pointer in the right direction?

P.S. Can installed package names be used, like `import('events')`?

**Comment by jdalton** [comment]
Hi @dsanders11!

I can't speak to the failure of promise `resolve` or `reject` (I'll need to dig in more), but I can tell you what the issue is outside of that. If you're using `.mjs` then no `esm` options apply to it. This means `"mode": "all"` will not be respected by `.mjs` files and it will treat `.js` files as CJS with only a default export.

**Comment by jdalton** [comment]
If you're looking for ecosystem interop/support you should use `.js` instead of `.mjs`.

**Comment by dsanders11** [comment]
Good to know, but `.mjs` was just one of the various combination I tried to see if I could make the needle move at all.

For the moment I've fallen back to using `require()` to get a similar effect (but synchronous instead of aync).

**Comment by jdalton** [comment]
Have you tried Electron 3 stable?

**Comment by dsanders11** [comment]
@jdalton, yes, I just tried changing that branch to Electron 3 stable, same result.

**Comment by jdalton** [comment]
Thanks for the repro. I narrowed it down to something funky with builtin `setImmediate`. It looks like something is going wrong in their wrapper:

https://github.com/electron/electron/blob/539d6d20b73a29e363489f4b528eddf22a2a2e47/lib/common/init.js#L33-L34

**Comment by jdalton** [comment]
It's because I'm using `require('timers').setImmediate` and Electron wraps `window.setImmediate`. So I'm missing out on their special wrap.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/b85f6714a96710ef446be5a236134aca310d28a2. To see logs in the renderer thread you'll want to `mainWindow.webContents.openDevTools()` from `main.js`.

**Comment by dsanders11** [comment]
@jdalton, thanks for the quick fix! I've confirmed in the repro case that it's now acting as expected.
