### ISSUE TITLE
No "main" provided in package.json

### ISSUE THREAD

**Issue by zzolo** [standard-things/esm#693]
I am trying to require a module that has a "module" field in package.json, which is an ESM version, but has no "main" field.

The package I am trying to require is [layercake](https://github.com/mhkeller/layercake).

My use is a bit complex, since I am building things within Gulp, within Svelte, and `layercake` has it's own Svelte components, but my `esm` include looks like this:

```
require = require('esm')(module);
```

When I run things, I get the following error: `Error: Cannot find module 'layercake'`

If I manually add a "main" field to the package.json of `layercake` and set it to the same file as the "module" field, things work fine.

I assume there is some assumption about "main" that I don't know about and it would be great to understand that.  Or, maybe it's a bug, but I doubt that.

Thanks for the help and great library; sorry if this is a duplicate.

**Comment by jdalton** [comment]
Hi @zzolo!

Thank you for the kind words! You can use the `"mainFields"` options:
```json
"mainFields": ["main", "module"]
```

**Comment by zzolo** [comment]
Thanks for the speedy response.

If I do this, I still get the same error:

```
require = require('esm')(module, {
  mainFields: ['main', 'module']
});
```

**Comment by zzolo** [comment]
Was just working on that.  Here you go:
https://github.com/zzolo/esm-no-main-test

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/1657a1b5c63ed9903ba733f36b66d9ecb3861602.

**Comment by zzolo** [comment]
Awesome, thanks!
