### ISSUE TITLE
Unescaped `identifiers` regex causes DoS by heap exhaustion/infinite loop

### ISSUE THREAD

**Issue by leosbotelho** [standard-things/esm#694]
It's prevalent to import [Sanctuary](https://github.com/sanctuary-js/sanctuary) as `S` and [sanctuary-def](https://github.com/sanctuary-js/sanctuary-def) as `$`, i.e:
```javascript
import S from "sanctuary"
import $ from "sanctuary-def"
``` 
The problem is that [esm](https://github.com/standard-things/esm)'s [find-indexes](https://github.com/standard-things/esm/blob/d506f22c60259d7ab82826fbccf8aa50cc22528e/src/parse/find-indexes.js) is using the _unescaped identifiers in a regex_ (e.g: `S` and `$`), which, in this case, causes an infinite loop, i.e:
`pattern` becomes `new RegExp("\\b(?:S|$)\\b", "g")` which matches 0 characters, and therefore matches infinitely (e.g in the while loop).

Suggested bug fix: escape the `identifiers` used in the regex.

**Comment by jdalton** [comment]
Thank you @leosbotelho!

Patched https://github.com/standard-things/esm/commit/c41e001d81a5a52b0d2d1722b1c2af04d997c05b.

**Comment by leosbotelho** [comment]
You are very welcome. I'm sorry to bother.

@jdalton, I think it's enough to `identifiers.map(escapeRegExp).filter(({length}) => length > 0).join("|")` or similar.

Regarding `tests`, this seems to fix the issue.
