### ISSUE TITLE
Thank you for the work you are doing here.

### ISSUE THREAD

**Issue by uniqname** [standard-things/esm#695]
Just wanted to drop a quick thank you for your work on esm. We replaced our use of babel to transpile for es modules -- which is the only thing we were using babel for on our servver side -- and we saw some pretty radical improvements in startup and build time. esm contributed to reducing our CI pipeline time from 30+ minutes to 10 minutes, and our incremental local builds from 20+ seconds to 3 seconds. To be sure, esm wasn't the only thing we did to improve our process, but it was a significant player!

Thanks again!
Happy Holidays!

**Comment by jdalton** [comment]
Thank you for the kind words @uniqname!
I've been meaning to reply. 

Please feel free to pass along any other details on the wins attributed to `esm` 💪
