### ISSUE TITLE
Unable to debug using --inspect-brk (blank source code)

### ISSUE THREAD

**Issue by gurupras** [standard-things/esm#697]
When trying to debug using `node --inspect-brk=0.0.0.0:9634 https-server.js --dev`, the file `https-server.js` appears fine on my browser, however, the remaining files are all blank. As you can imagine, I'm having a really hard time debugging code.

**https-server.js**
![image](https://user-images.githubusercontent.com/2933207/50635577-bdd90f80-0f20-11e9-9a66-79b4ef547f6f.png)

The `backend/server/server` file referenced above has a `debugger` statement within it. The interpreter(?) correctly breaks at the debug point, however the code shows up blank.
![image](https://user-images.githubusercontent.com/2933207/50635627-eeb94480-0f20-11e9-806e-b93a33f7187d.png)

Here are the versions I'm using:
node: v8.11.4
esm: 3.0.84
Chrome: Version 70.0.3538.110 (Official Build) (64-bit) (not sure if relevant)

**Comment by jdalton** [comment]
Hi @gurupras!

We do support debugging in the Chrome inspector _(with file sources visible)_. This looks like [a bug/regression in the Chrome inspector](https://bugs.chromium.org/p/chromium/issues/list?q=component:Platform%3EDevTools). If you could provide a simple repro repo I could see if I can reproduce it.

**Comment by gurupras** [comment]
Not sure if this helps at all, but everything works fine if I run connect via Chrome on Windows (v71.0.3578.98). You're definitely right. It seems to be a problem with Chrome rather than `esm`.

**Comment by jdalton** [comment]
Cool! 

You should totally [file a bug](https://bugs.chromium.org/p/chromium/issues/list?q=component:Platform%3EDevTools) on them. In my experience they’ve been pretty responsive.

**Comment by gtarsia** [comment]
This is working for me with chrome v75.0.3745.4 (dev.
But it's not working with Chrome Dev v73.0.3683.86

Unfortunately the v75 version is also having problems to connect normally as explained here https://github.com/nodejs/node/issues/23693. So I have to connect manually to this url `chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=localhost:9229/{token}` with token being the token you get when you run node inspect (assuming 9229 is your port).

**Comment by june07** [comment]
https://blog.june07.com/nim-custom-devtools-url

May find NiM useful.

**Comment by jdalton** [comment]
Related https://github.com/nodejs/node/issues/26887.
