### ISSUE TITLE
Cannot install via npm or yarn

### ISSUE THREAD

**Issue by marvinhagemeister** [standard-things/esm#7]
Love this project! I've been quitely following this project along on twitter and finally wanted to try it out. Somehow I have a bit of trouble installing it. I'm not sure if this is the proper place to file this issue or if this should be opened at the npm registry:

```bash
# yarn
yarn add @std/esm
yarn add v0.27.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/@std%2fesm: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/myproject/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

# npm
npm i @std/esm
npm ERR! code E404
npm ERR! 404 Not Found: @std/esm@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myuser/.npm/_logs/2017-07-07T20_06_39_115Z-debug.log
```

Browsing the [npm registry via web client](https://www.npmjs.com/search?q=@std/esm&page=1&ranking=optimal) doesn't seem to know about a package called `@std/esm` either.
The content of the logfile gives no further clues as to why there is a `404`. Perhaps it's only published privately or something like that?

**Comment by jdalton** [comment]
Hi @marvinhagemeister!

Please see [the README note](https://github.com/standard-things/esm#-under-construction-).

**Comment by FND** [comment]
I noticed you've since removed that note (da96fa684ebff8e491dd324ac39a174185c7a86e), but ESM doesn't seem to be available via npm yet. Is that gonna happen anytime soon?

(I'm happy to be patient and grateful for your work on this - just curious.)

**Comment by jdalton** [comment]
Hi @FND!

Thanks for your interest!
I'm publishing the package this week (assuming I can get the blog post out 😄)

**Comment by FND** [comment]
Excellent, thank you!
