### ISSUE TITLE
correct module.exports syntax to be esm compliant

### ISSUE THREAD

**Issue by damianobarbati** [standard-things/esm#700]
@jdalton is this the correct way to export a ESM "default" with CJS?

https://github.com/turboMaCk/koa-sslify/blob/master/index.js#L162

I'm asking because I see a weird behaviour and I actually have to do the following with ESM:
```
import { default as sslify } from 'koa-sslify';
app.use(sslify.default({ port: 8443 }));
```

But in the CJS usage at https://github.com/turboMaCk/koa-sslify#usage I see: 
```
const sslify = require('koa-sslify').default; // factory with default options
app.use(sslify());
```
Which should be "ES6 import" ready and allow the following:

```
import sslify from 'koa-sslify';
app.use(sslify({ port: 8443 }));
```

**Comment by jdalton** [comment]
Hi @damianobarbati!

CJS is treated as the following be default with `esm`:
### cjs.js
```js
exports.a = "a"
```
### esm.js
```js
import cjs from "./cjs"
import { a } from "./cjs"
import * as ns from "./cjs"

console.log(cjs) // { a: "a" }
console.log(a) // "a"
console.log(ns) // { a: "a", default: { a: "a" } } 
```
With out interop option enabled by default if `koa-sslify` added a `module.exports.__esModule = true` we'd treat it like ESM so that it's provided `default` of `factory` would be used for `import factor from "koa-sslify"`

**Comment by damianobarbati** [comment]
Thanks 🙏🏻

**Comment by jdalton** [comment]
For background `__esModule = true` originated in Babel to indicate CJS/ESM interop. It has spread to others like Rollup, Webpack, and [TypeScript](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop) too.
