### ISSUE TITLE
Not Able to Import Named lodash exports in 2nd tier file

### ISSUE THREAD

**Issue by bobber205** [standard-things/esm#701]
web.js (entry point)
```js
require = require("esm")(module);
module.exports = require("./main.js");
```

```js
//somewhere in main.js
import TestRouter from './routers/test_router';
```

```js
//test_router.js
var TestRouter = require('express').Router();
import random from 'lodash-es/random';
module.exports = TestRouter;
```

I've seen other similar issues regarding this but most of them are about using experimental module support by naming files `.mjs`. I don't have any of these files.

The error I am getting when I try to do `node web.js` is

```
/path/path/legit_data/main.js:1
SyntaxError: Missing export name 'default' in ES module: file:///Users/alexwait/chirpify/legit_data/routers/test_router.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
```

I haven't used esm long but I'm sure I'm doing something wrong right? The same import line

```
import random from 'lodash-es/random';
```

works just fine if I put it in `main.js`

What can I do differently? 🙏

**Comment by dnalborczyk** [comment]
you are exporting the `TestRouter` object.

if you don't know what to expect from a commonjs module, you could import the namespace, and inspect it:

```javascript
import * as TestRouter from './routers/test_router'

console.log(TestRouter)
```
that should be also the object you are expecting.

that being said, I would not suggest mixing up commonjs and esmodule syntax in the same module, unles you are converting a project from commonjs to esmodules.

**Comment by bobber205** [comment]
I get what you're saying but the TestRouter file works fine if I comment out the import in test_router

**Comment by dnalborczyk** [comment]
I haven't mixed the usage of `commonjs` and `esmodules` in the same file, but it could be that `esm` thinks that it's dealing with an esmodule because of the import statement, not sure what rules `esm` follows when it sees both. It could also be a bug.

what I mean you should be using instead is something like this:

```javascript
import { Router } from 'express'
import random from 'lodash-es/random'

export default Router()
```

unless for some reason you have the need to mix cjs and esm.

**Comment by bobber205** [comment]
Ah now it makes total sense!

Sorry for the confusion.
