### ISSUE TITLE
3.1.0 breaks module.exports object intro

### ISSUE THREAD

**Issue by cabbiepete** [standard-things/esm#705]
updating from 3.0.84 to 3.1.0

It's probably an edge case but on updating we are now getting:

```
SyntaxError: Missing export name 'User' in ES module: file:///Users/cabbiepete/development/myhr/api-auth/server/db/models/index.js
```

index.js

```
'use strict';

var fs        = require('fs');
var path      = require('path');
var Sequelize = require('sequelize');
var basename  = path.basename(__filename);
var env       = process.env.NODE_ENV || 'development';
const config  = require(__dirname + '/../config/config.json')[env];
var debug = require('debug')('@myhr/api-auth/server/db/index')

debug('env: ', env);
debug('config: ', config);
var db        = {};

if (config.use_env_variable) {
  var sequelize = new Sequelize(process.env[config.use_env_variable], config);
} else {
  var sequelize = new Sequelize(config.database, config.username, config.password, config);
}

fs
  .readdirSync(__dirname)
  .filter(file => {
    return (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js');
  })
  .forEach(file => {
    var model = sequelize['import'](path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach(modelName => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;
```

Top of Login.js where it imports User from index.js

```
import { LoginEmail, User } from '../models';
```

models is the folder where index.js, Login.js, LoginEmail.js and User.js all reside. Index.js imports the other files and runs their default export function to make the object (LoginEmail/User) which it then exports.

@jdalton Are you already aware and expect this or should I work up a minimal repo that reproduces it?

**Comment by cabbiepete** [comment]
ESM settings from package.json also.

```
"esm": {
    "cjs": true,
    "mode": "auto"
  },
```

**Comment by dnalborczyk** [comment]
thank you, @cabbiepete !

a minimal repro would be indeed very helpful. I tried to repro, with no success.

**Comment by dnalborczyk** [comment]
could you check (debug) if `db[model.name] = model` sets the model name `User`?

btw, what is the reason to keep `cjs` module syntax in index.js?

**Comment by jdalton** [comment]
Hi @cabbiepete!

As @dnalborczyk mentioned a small repro repo can help us identify the issue more easily.
Related note: The options you provided [here](https://github.com/standard-things/esm/issues/705#issuecomment-454964776) are the default so can be omitted.

**Comment by jdalton** [comment]
Hi @cabbiepete!

This bug looks to be related to #707. I'm going to close for now. Please feel free to post a simple repro though for us to confirm.
