### ISSUE TITLE
Possible regression from 3.0.84

### ISSUE THREAD

**Issue by brandonweiss** [standard-things/esm#707]
Here’s a [PR](https://github.com/brandonweiss/promptconfig/pull/12) bumping esm from `3.0.84` to `3.1.0` and it failing. This is the [failing run](https://travis-ci.com/brandonweiss/promptconfig/jobs/171122113).

The error is `(0 , _prompt.default) is not a function`.

When I look at [this import statement](https://github.com/brandonweiss/promptconfig/blob/8b0ab54fd9e1291b333da5686814165cdf836e01/test/integration/color_test.js#L3) in the test, the value returned has changed on `3.1.0`.

On `3.0.84` it logs as `[Function: default]`
On `3.1.0` it logs as `{ default: [Function: default] }`

I’m running esm through [AVA’s require hook](https://github.com/brandonweiss/promptconfig/blob/a614357ffe9c513a686d35300d413f4dddc14704/package.json#L45).

Is there any other information that would be helpful?

**Comment by jdalton** [comment]
Thanks @brandonweiss! 

Looks like a possible regression in our __esModule+Babel interop. Should be a straight forward fix. You can expect a patch release this evening to resolve it.

**Comment by dnalborczyk** [comment]
for what it's worth:

I changed the PR to use `Ava v1.0.0-beta.7` (same version `esm` is using in it's scenario tests, and added the `babel-options` to turn off cjs. the docs are a bit unclear about this, if it should be, or even has to be done:  https://github.com/avajs/ava/blob/master/docs/recipes/es-modules.md  https://github.com/avajs/ava/blob/master/docs/recipes/babel.md#preserve-es-module-syntax

tests are passing then.

```json
  "ava": {
    "require": [
      "esm",
      "core-js/fn/array/flat-map",
      "core-js/fn/array/flatten"
    ],
    "babel": {
      "testOptions": {
        "presets": [
          [
            "module:ava/stage-4",
            {
              "modules": false
            }
          ]
        ]
      }
    }
  }
```

**Comment by jdalton** [comment]
I've upgraded our scenario test dep to `"ava": "^1.1.0"` and tests still pass. I'll look into adding another scenario test.

**Comment by brandonweiss** [comment]
@jdalton Thanks! ❤️

**Comment by jdalton** [comment]
After more digging the sub-loaded detection was a false lead. The issue is the assumptions we make about CJS files being loaded. In this case 
```
"core-js/fn/array/flat-map",
"core-js/fn/array/flatten"
```
We just need to track that they are being loaded via the `esm` enabled `require`.

**Comment by jdalton** [comment]
I have this fixed locally. Ended up not needing to track extra things.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/992adb99dec9d2ee76119cee24626ef0de031296; Tests https://github.com/standard-things/esm/commit/1c1aca09eb6e510597a7627ed42ba081541ad482.

**Comment by brandonweiss** [comment]
@jdalton Thanks! ❤️
