### ISSUE TITLE
Wrong behaviour in 3.1.0

### ISSUE THREAD

**Issue by damianobarbati** [standard-things/esm#709]
@jdalton I'm sorry but I could not figure out a proper title for this behaviour I encountered:

To reproduce:
```
yarn add @google-cloud/vision

// test.js
import vision from '@google-cloud/vision'; //either this one uncommented
const vision = require('@google-cloud/vision'); //or this one uncommented

node -r esm test.js // failure
node test.js // success
```

The error reported is:
```
/Users/damiano/Desktop/webapi.translated.com/node_modules/protobufjs/src/util.js:1
Error: Cannot find module './roots'
    at Object.<anonymous> (/Users/damiano/Desktop/webapi.translated.com/node_modules/protobufjs/src/util.js:9:13)
```

- the file /Users/damiano/Desktop/webapi.translated.com/node_modules/protobufjs/src/roots.js exists though
- without using "esm" and sticking to "require" works

Edit: confirmed regression in 3.1.0, reverting back to 3.0.84 works.

**Comment by togakangaroo** [comment]
seeing the same thing

**Comment by jdalton** [comment]
Hi @damianobarbati!

I've identified the issue, which involves the entry cache retrieving the incorrect entry per module object reference. I'm still digging to figure out why though.

**Comment by jdalton** [comment]
Okay, I've found the reason. It's because we look up module entries by their exports first. In this case `protobufjs/src/util.js` sets its `module.exports = require("./util/minimal")` so when we resolved the relative path of `./roots` it was resolving against `protobufjs/src/util/` instead of `protobufjs/src/`. Fix coming soon.

**Comment by jdalton** [comment]
Patch https://github.com/standard-things/esm/commit/bd0df92204c1e11969e4e33716c38a41d36d356e; Test https://github.com/standard-things/esm/commit/5a6515a18732dc8033d38f5a05572ccbef7827a6
