### ISSUE TITLE
How to stub dependencies with esm?

### ISSUE THREAD

**Issue by jzaefferer** [standard-things/esm#712]
This is primarily a support request, but might turn into an enhancement for docs!

I'm trying to migrate from babel to esm, and I'm currently stuck trying to make some mocks work again.

What I'm starting with is some common setup code for mocha-based tests, like this:
```
var util = require('../src/lib/billing/util')
sinon.stub(util, 'getPricing').returns(Promise.resolve({})
```
As far as I can tell, that stub silently fails, since namespace objects are immutable. 

---

Which I figured setting `cjs.mutableNamespace` to `true` would address, but I can't figure out how to do that. I did add this to my package.json:
```
  "esm": {
    "cjs": {
      "mutableNamespace": true
    }
  }
```
But then I get a new error that makes no sense to me:
```
SyntaxError: Missing export name 'diff' in ES module: [...]/node_modules/deep-diff/index.js
```
I suspect that I'm removing all `cjs` defaults by only setting the one option. But without examples for setting a single option and with no docs for the default values, I haven't been able to address that. I looked at https://github.com/standard-things/esm/blob/f15dfc7e2d571c020c28fa381c271edc3cfa07a8/src/package.js#L64-L97 but the `mode` option makes this confusing, too - is `mode: auto` the default or not?

---

If a reduced test case has any value here, let me know and I'll put something together.

**Comment by jdalton** [comment]
Hi @jzaefferer!

A reduced or small repro repo would help. The `mode` is `"auto"` by default and `cjs` interop, including `cjs.mutableNamespace` is enabled by default _(no need to opt-in)_ for all non-`.mjs` files. If you're trying to use `.mjs` you'll have a bad time because `esm` options don't extend to them _(they're locked down because their support is experimental in Node)_.

**Comment by jdalton** [comment]
@dnalborczyk 
> quick question, looking at the referenced code above, does mode: 'all' allow you to turn on `cjs` features as well? or does it apply to `auto detect` mode only? 

The `mode` option is all about parse goal detection (module/script-cjs).
It is separate from `cjs` features and should not affect them.

**Comment by dnalborczyk** [comment]
> The mode option is all about parse goal detection (module/script-cjs).
It is separate from cjs features and should not affect them.

that's what I thought.


but looking at the code snippet:

https://github.com/standard-things/esm/blob/f15dfc7e2d571c020c28fa381c271edc3cfa07a8/src/package.js#L85

```javascript
const autoOptions = {
  cjs: {
    cache: true,
    extensions: true,
    interop: true,
    mutableNamespace: true,
    namedExports: true,
    paths: true,
    topLevelReturn: false,
    vars: true
  },
  mode: "auto"
}
```

it looks like the `default cjs options` apply to `auto` mode only?

**Comment by jdalton** [comment]
`autoOptions` are the options automatically applied. I could rename that var to `zeroConfigOptions` instead. They are used as `zeroConfigOptions.cjs` or `zeroConfigOptions.mode` when either are `cjs` or `mode` are not provided.

**Comment by dnalborczyk** [comment]
gotcha, makes sense. I was confused about `autoOptions` combined with `mode: "auto"`.

**Comment by dnalborczyk** [comment]
@jzaefferer  just gave it a try, not sure if you tried to do something like this:

```javascript
// index.js
import { stub } from "sinon";
import * as util from "./util.js";

stub(util, "getPricing").returns(Promise.resolve("$2"));

util.getPricing().then(val => console.log(val));
```

```javascript
// util.js
export function getPricing() {
  return Promise.resolve("$1")
}
```

```bash
node -r esm index.js # output: $2
```

ps: make sure you're using the `esm` latest.

**Comment by jdalton** [comment]
@jzaefferer Feel free to ping back with a repro and we will dig in.

In the meantime @dnalborczyk would you please open a PR to add a scenario test for Sinon so we ensure we don't regress this stub/spy case.

**Comment by dnalborczyk** [comment]
> would you please open a PR to add a scenario test for Sinon so we ensure we don't regress this stub/spy case.

@jdalton yeah, sure, I'll have a look ...

**Comment by jzaefferer** [comment]
Hello @jdalton! Thanks for looking into this in the first place. I've finally managed to put together a reduced test case: https://github.com/jzaefferer/esm-mock-repro

I suspect there's a silly mistake in there in the way I'm requiring/importing modules, though it did work fine pre-esm (with babel).

**Comment by jdalton** [comment]
Hi @jzaefferer!

Thank you for the repro ❤️.

You've got a mix of things going on here. You don't need your `common.js` to be written in CJS. For example you could write it as:

#### common.js
```js
import chai, { expect } from 'chai'
import sinon from "sinon"
import * as util from "../src/util"

global.chai = chai
global.expect = expect
global.sinon = sinon

sinon.stub(util, 'getPricing').returns(Promise.resolve({
  plans: ['a', 'b', 'c']
}))
```
then
```js
const x = await util.getPricing()
expect(x).deep.equal({ plans: ['a', 'b', 'c'] })
```
passes.

The issue is that
```js
var util = require('../src/util')
```
Is not the namespace object of
```js
import * as util from "../src/util"
```
so if you stub the namespace object, the namespace object is stubbed. If you stub the exports then that's something else.

**Comment by dnalborczyk** [comment]
@jzaefferer did you look at any of the [examples](https://github.com/standard-things/esm/issues/712#issuecomment-456486096) above?

```javascript
import sinon from "sinon";
import { expect } from "chai";
import * as util from "../src/util";

describe("lib", () => {
  it("tests stuff", async () => {
    sinon.stub(util, "getPricing").returns(Promise.resolve(["a", "b", "c"]));
    const x = await util.getPricing();
    expect(x).deep.equal(["a", "b", "c"]);

    util.getPricing.restore();
    const y = await util.getPricing();

    expect(y).deep.equal(["ABC", "FOO", "BAR"]);
  });
});
```

usually you would use either the [cli options](https://github.com/jzaefferer/esm-mock-repro/blob/master/package.json#L4) or the [bridge (code)](https://github.com/jzaefferer/esm-mock-repro/blob/master/test/common.js#L1), not both. you can also install `sinon`, `chai` etc. globally, if needed. I couldn't find a reference to `common.js`. is that a `mocha` thing?

**Comment by jdalton** [comment]
👋 @jzaefferer!

I've been thinking about this and your case will be common. With a couple lines of code I can make the namespace object be returned from `require()` when the mutable namespace option is enabled. This would have prevented a hiccup in the first place. I'll add that soon.

**Comment by jdalton** [comment]
**Update:**

I added support for it. 😌

**Comment by jzaefferer** [comment]
Nice! I'm glad this contributed a little bit to the project :-)
