### ISSUE TITLE
Constructor check fail

### ISSUE THREAD

**Issue by GMartigny** [standard-things/esm#717]
Hi,
Since [3.1.0](https://github.com/standard-things/esm/releases/tag/3.1.0), the same issue as #551 re-appear.

I update [the repo](https://github.com/GMartigny/esmInstanceofBug) reproducing this bug.

![image](https://user-images.githubusercontent.com/2543511/51919685-42199800-23e4-11e9-9995-f9ec10395af6.png)
> It should log `true` both times

Thanks

**Comment by dnalborczyk** [comment]
thank you @GMartigny !

are `aposition` and `avector` symlinked modules? if so, could you commit those as well?

@jdalton looking at the old issue, I think we still need tests for this. I'm gonna look into it later today.

**Comment by jdalton** [comment]
Yep confirmed that line in the change was the issue.

**Comment by dnalborczyk** [comment]
@jdalton  ah, yeah! got side tracked. gonna look into it now.
