### ISSUE TITLE
CJS named imports not working

### ISSUE THREAD

**Issue by vrn-dev** [standard-things/esm#718]
I am using `apollo-server-express` package, and am importing a named export in my file:

`import { ApolloServer } from 'apollo-server-express`

When running esm using `nodemon` using `node -r esm index.js` I get the error:

> ..node_modules/apollo-server-express/dist/index.js does not provide an export named 'ApolloServer'

I have tried using the following configs in package.json and .esmrc:
```
{
    "await": true,
    "mainFields": [
      "module",
      "main"
    ],
    "cjs": {
      "interop": true,
      "namedExports": true,
      "vars": true,
      "cache": true,
      "extensions": true,
      "mutableNamespace": true,
      "paths": true
    }
  }
```

and the `apollo-server-express` package exports are like:

```
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
var apollo_server_core_1 = require("apollo-server-core");
exports.GraphQLUpload = apollo_server_core_1.GraphQLUpload;
exports.GraphQLExtension = apollo_server_core_1.GraphQLExtension;
exports.gql = apollo_server_core_1.gql;
exports.ApolloError = apollo_server_core_1.ApolloError;
exports.toApolloError = apollo_server_core_1.toApolloError;
exports.SyntaxError = apollo_server_core_1.SyntaxError;
exports.ValidationError = apollo_server_core_1.ValidationError;
exports.AuthenticationError = apollo_server_core_1.AuthenticationError;
exports.ForbiddenError = apollo_server_core_1.ForbiddenError;
exports.UserInputError = apollo_server_core_1.UserInputError;
exports.defaultPlaygroundOptions = apollo_server_core_1.defaultPlaygroundOptions;
__export(require("graphql-tools"));
__export(require("graphql-subscriptions"));
var ApolloServer_1 = require("./ApolloServer");
exports.ApolloServer = ApolloServer_1.ApolloServer;
exports.registerServer = ApolloServer_1.registerServer;
```

There is obviously a named export of ApolloServer, but it's still throwing the error.

I tried with Babel and it works.

#### EDIT 1

When I removed the await option, it parsed all the imports down my index.js file but threw the same `does not provide a named export` error on another package in another file down the tree.

#### EDIT 2
The package that was throwing the error above was `mongoose` and when I commented out the call to the namedExport function, everything worked.
Mongoose exports `new Mongoose(...)` and all the methods are defined on the object prototype like so 
`Mongoose.prototype.connect = function () {...}`
Does this effect `esm`'s ability to de-structure the import?

**Comment by dnalborczyk** [comment]
hey @vrn-dev 

I just tried a quick and simple repro, and it works fine. I'm also using `apollo-server`, as well as `apollo-server-hapi` for quite some time with `esm`.

in your example, are you still using babel? if so, did you turn off `es6 module transpilation`?

**Comment by jdalton** [comment]
Hi @vrn-dev!

To ensure we're all on the same page can you make sure you're using `esm` v3.2.0.

**Comment by vrn-dev** [comment]
> Hi @vrn-dev!
> 
> To ensure we're all on the same page can you make sure you're using `esm` v3.2.0.

I am using `esm` v3.2.0

> in your example, are you still using babel? if so, did you turn off es6 module transpilation?

I had removed babel. I tried both preloading `esm` module using `node -r esm index.js` and 
```
require = require('esm')(module);
module.exports = require('./src/index');
```
Still not working.

As per my 2nd edit, it resolved apollo exports and have moved on to throwing errors from the mongoose exports. If i remove mongoose connect call or don't de-structure the import then it's wokring:

```
import { connect } from 'mongoose'

connect('http://localhost:27017/test') // throws '...mongoose/index.js does not provide an export named 'connect'
```

```
import mongoose form 'mongoose'
connect('http://localhost:27017/test') // works!
```

Does the de-structuring not work because mongoose exports a `new Mongoose(...)` object and all the methods and properties are defined on the object prototype? or is it a bug with esm?

**Comment by dnalborczyk** [comment]
> Does the de-structuring not work 

it's not destructuring. the `ES6 import/export` syntax share a few similarities, but that's about it. it is important on what is being exported, in the world of commonjs it would be every own property on the `module.exports` object, if you import it with es6 module syntax.

> because mongoose exports a new Mongoose(...) object and all the methods and properties are defined on the object prototype?

yes, connect is part of the prototype:  https://github.com/Automattic/mongoose/blob/master/lib/index.js#L268  https://github.com/Automattic/mongoose/blob/master/lib/index.js#L995 , but that's not the reason the named import didn't work *(see above)*. although, with `destructuring` and `commonjs require` it would have worked:

```javascript
const { connect } = require('mongoose')
console.log(typeof connect) // function
```

if you are not sure about the exported namespace of a commonjs module, or any module for that matter, besides looking at the source code, you can always run `import * as ns from './xyz.js` and inspect the namespace object `ns`.

**Comment by jdalton** [comment]
Per our named export mapping we only consider own-enumerable properties of the exports object. In this case there is an expectation from Babel users which fits into our meet devs where they are today stance. I'll consider changing our named exports detection.

**Comment by dnalborczyk** [comment]
little more food for thought:

imagine the following, currently possible case:

a module was written [probably transpiled] as "dual" module: commonjs and es6, and consumed by some from [main] as commonjs, by others from [module] as ES6.

if some commonjs [main] user - and using the considered "prototype destructuring syntax" - would switch to the ES6 module version, their named import ("destructuring") would stop working.

**Comment by jdalton** [comment]
I want to avoid folks having to dig. I think I can make the `.js` case more flexible while still restricting existing `.mjs` case for built-ins. In your example you hit another self-imposed limitation, which is non-enumerable properties. I'll noodle on this.

**Comment by jdalton** [comment]
@dnalborczyk 

I think we're talking about different things.

>
```js
import { floor } from 'some-package'
console.log(typeof floor) // works, with your suggested changes
```

No, because the `floor` binding is not exported in the ESM module `index.js`

I'm talking about how we determine what export names to project for CJS modules. Currently we restrict to enumerable-own keys of a `module.exports` object. I'm suggesting that in our interop default we align closer with Babel to include non-enumerable own keys.

**Comment by dnalborczyk** [comment]
I'm not sure, I think we're talking about the same.

> No, because the floor binding is not exported in the ESM module index.js

correct, if loaded from an es6 module, but what happens if the es6 module also co-exists with a transpiled-to-commonjs-module, and is loaded as `common.js` over 'main'?

transpiled "roughly" to:
```javascript
module.exports = Math
```

**Comment by jdalton** [comment]
Babel transpiled code won't generate
```js
module.exports = Math
```
Here's an example [from the Babel REPL](https://babeljs.io/repl/#?babili=false&browsers=ie%2010&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAsqjABZwDeAvkA&debug=true&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015-loose&prettier=false&targets=&version=7.0.0-alpha.19&envVersion=2.0.0-beta.2):
```js
export default class Math {}
```
becomes:
```js
exports.__esModule = true
var Math = function Math() {}
exports.default = Math
```

**Comment by dnalborczyk** [comment]
ah, my bad!  in that case I guess it could be fine.

**Comment by jdalton** [comment]
I added support for grabbing class properties to `options.cjs.namedExports`. I also split out the namespace objects better for builtins so for example `options.cjs.namedExports` will allow folks to `import { promises } from "fs"` but won't be allowed in `.mjs`.
