### ISSUE TITLE
import foo from "./directory" doesn't find index.mjs

### ISSUE THREAD

**Issue by lachlanhunt** [standard-things/esm#72]
Trying to import "./directory/index.mjs" using:

    import foo from "./directory";

This gives the error:

    Error [ERR_MISSING_MODULE]: Cannot find module ./direcotry

It only works if I do this instead:

    import foo from "./directory/index";

**Comment by jdalton** [comment]
Hi @lachlanhunt!

Patched for #65.

**Comment by jdalton** [comment]
I'll be releasing an update in the next couple of days.

**Comment by jdalton** [comment]
Fixed by v0.6.0. Please note I've [changed some usage instructions](https://github.com/standard-things/esm#getting-started).
