### ISSUE TITLE
Using esm in npm package for Node.js

### ISSUE THREAD

**Issue by katelynsills** [standard-things/esm#723]
We're currently using esm in [SES](https://github.com/Agoric/SES), and it's been awesome. 

Now, we're trying to allow users to install SES as a package dependency in Node.js, as if everything was exported as a CommonJS module. I created [a PR to do this](https://github.com/Agoric/SES/pull/36), based on the [esm documentation](https://github.com/standard-things/esm#getting-started). 

But, @kumavis [pointed out](https://github.com/Agoric/SES/pull/36#discussion_r253337189) that this is overriding the `require` global, and may not work in a browserify context. 

@jdalton, @benjamn, is there a better way to use esm to allow ES modules to be packaged and used as a dependency in Node.js as if they were CommonJS modules? 

Thanks in advance!

**Comment by jdalton** [comment]
Hi @katelynsills!

> is there a better way to use esm to allow ES modules to be packaged and used as a dependency in Node.js as if they were CommonJS modules?

Yes, I'll head over to the PR and provide feedback.
