### ISSUE TITLE
3.2.0 -> 3.2.1 stubbing no longer works

### ISSUE THREAD

**Issue by Wildhoney** [standard-things/esm#727]
```javascript
import * as u from '../../utils.js';

// Later...

const cycleMiddlewareStub = stub(u, 'cycleMiddleware').throws(
    () => new Error('Yoko Onoooo...')
);
```

In `3.2.0` the stubbing of `cycleMiddleware` works perfectly, but when upgrading to `3.2.1` it no longer stubs &ndash; instead it gives the original function.

Not sure if it's a bug or I'm stubbing it wrong. If I'm doing it wrong, how should I do it now?

**Comment by jdalton** [comment]
Hi @Wildhoney!

Could you create a simple repro repo to demonstrate the issue?

**Comment by Wildhoney** [comment]
[Voila](https://github.com/Wildhoney/esm-3.2.1-bug).

Run `yarn && yarn test` to see the failure.

To see it passing, change `esm` to `3.2.0` in `package.json`, run `yarn` and re-run `yarn test`.

**Comment by jdalton** [comment]
Patches https://github.com/standard-things/esm/commit/39f31aa1e8aa9b1732effc39d93e5e757a2ef528, https://github.com/standard-things/esm/commit/e2bab78750139dc8ac96bcd8602c717c3bd5db81, https://github.com/standard-things/esm/commit/2b6152dacdb2934d3fd32716c8ded953108b0a93;

**Comment by jdalton** [comment]
Thanks @Wildhoney!

I've resolved the issue through a series of rework patches.

**Comment by Wildhoney** [comment]
Thanks @jdalton &ndash; that's a sizeable code change!

Is `3.2.4` the new version, as I've [upgraded it in the repo](https://github.com/Wildhoney/esm-3.2.1-bug) and still get the same issue.

**Comment by jdalton** [comment]
I have not published the release yet.

**Comment by jdalton** [comment]
**Update:**

[v3.2.5](https://github.com/standard-things/esm/releases/tag/3.2.5) is released 🎉
