### ISSUE TITLE
stubbing/testing esm 3.2.4

### ISSUE THREAD

**Issue by jamessouth** [standard-things/esm#728]
Hello, I've been through #712 and #727, but I can't fix my testing issue.  It seems similar, except I'm using a `default export`.  I have tried to stub but I can't find a way that works.  Test repo [here](https://github.com/jamessouth/test-issue-repo)

`yarn` and `yarn test`, it will fail.  comment out the `import` statement in `main.js` and it will pass...???  I'm testing `main` w/o an argument, so it isn't even using the import, just having the `import` statement causes a fail.  How to fix?

main.js
```javascript
import doSomething from './doSomething'; // comment out to pass, uncomment out to fail

export default async function main(arg) {
  try {
    if (!arg) {
      throw new Error('An arg is needed.');
    }
    console.log(await doSomething(arg));
  } catch (err) {
    console.log(err.message);
  }
}
```
control.test.js
```
import test from 'ava';
import sinon from 'sinon';
import main from './main';

function setupSpy() {
  sinon.spy(console, 'log');
}

function tearDownSpy() {
  console.log.restore();
}

test('test main - no arg - log error msg', async t => {
  setupSpy();
  // let stub = sinon.stub(main);
  // await stub();
  await main();
  t.true(console.log.callCount == 1);
  tearDownSpy();
  // stub.restore();
});
```

**Comment by jdalton** [comment]
Dup of #727.

**Comment by jdalton** [comment]
Thanks for the report @jamessouth.

Fixing #727 plus the follow-up patch should resolve your issue.

**Comment by jamessouth** [comment]
ok looking forward to it, thank you so much @jdalton!!! 😊

**Comment by jdalton** [comment]
**Update:**

[v3.2.5](https://github.com/standard-things/esm/releases/tag/3.2.5) is released 🎉
