### ISSUE TITLE
I am not sure if this is needed any more

### ISSUE THREAD

**Issue by frank-dspeed** [standard-things/esm#730]
Can you maybe post some information in the readme if this is any diffrent from using ```node --experimental_modules```

**Comment by jdalton** [comment]
Hi @frank-dspeed!

The `node --experimental-modules` can be seen as our baseline. By using `.mjs` with `esm` you get that. No named exports of CJS modules, no support for APM packages, no mocking/stubbing libraries, no code coverage, no to so many things. However, if you use `.js` all of those things will just work zero-config out of the box. The `esm` even works with the `--print`, `--eval`, `--check` flags of Node too.
