### ISSUE TITLE
jsdom integration 

### ISSUE THREAD

**Issue by justinfagnani** [standard-things/esm#732]
jsdom doesn't support `<script type=module>` ([issue](https://github.com/jsdom/jsdom/issues/2475)) and might not directly until Node supports modules. That leaves current modules unable to load "natively" in jsdom.

It would be very useful if esm could be used to implement `<script type=module>` and a module-supporting version of `runVMScript`.

I've tried to patch esm to allow setting the global object to the jsdom global, but so far I've failed. If I do manage to get the jsdom global object in place, I've end up removing access to objects that esm needs to operate, like `process`. Naively it seems like there needs to be support for running the esm loader in one context, but the modules in another - if that's not already how esm is structured.

**Comment by jdalton** [comment]
Hi @justinfagnani!

If you can figure out a way to accomplish this through existing CJS means (like with `@babel/register` or other such thing) then I can map it to `esm`. I want to be careful exposing things like the compiler and would feel better if there was an existing CJS-way that I could ensure works. For example `Module#_compile()` supports parsing ESM syntax with the `esm` loader.
