### ISSUE TITLE
Just a big thanks from the bottom of my heart!

### ISSUE THREAD

**Issue by Vadorequest** [standard-things/esm#733]
❤️ ❤️ ❤️ 

https://spectrum.chat/?t=705700ff-37ad-4e88-a418-cbd3143930f3

ESM made my life so much easier, took me a bit of looking around to see how it works but it just... worked.

**Comment by jdalton** [comment]
Thank you @Vadorequest!

I'm so happy it's a help to you 🙌

**Comment by Vadorequest** [comment]
@jdalton I created a https://github.com/Vadorequest/es2018-esm-examples repo to show usages, if you wanna reference it somewhere! :)
