### ISSUE TITLE
know of any non babel eslint plugin/parser for dynamic imports

### ISSUE THREAD

**Issue by dkebler** [standard-things/esm#736]
circa 2019.... with `await import('foo')`.   revisiting https://github.com/eslint/eslint/issues/9811

Looks like eslint community still doesn't appreciate the wonderful esm module as no one short of babel will support dynamic imports.  I don't want to use babel packages cause...well..I love esm.

I had hopes for this one, https://github.com/benmosher/eslint-plugin-import but they specially (https://github.com/benmosher/eslint-plugin-import/issues/700) won't ok dynamic imports (stage 4 after all).

Come across any eslint plugin/method to ok this?   Don't want to use acorn either, got dozens of my packages linting eslint via atom plugin and don't want to change for just a couple files.

The irritation is that any file with dynamic import will choke the linter and thus not lint anything beyond it. (luckily in my case it won't stop a build).

-------------

BTW major thumbs up appreciation.  I love `-r esm`.  All my code now refactored es6+/esm!  Rust never sleeps. Maybe it will be native in v12 or v13?  Geez, is the node project paying you for this work?

**Comment by dnalborczyk** [comment]
@dkebler  I haven't looked at it yet closely, but what speaks against `babel-eslint`? it's just a wrapper for `eslint`s parser.

I don't think anyone has anything against some specific language feature or some specific module. it's just that the spec might change, and projects don't want to invest the time - or just don't have the capacity to implement a feature which might change, or might even be entirely scrapped from the spec.

in therms of atom: usually one would use an `eslintrc` file in every project for eslint options, which in turn will be read by the atom plugin.

**Comment by jdalton** [comment]
Hi @dkebler!

I hear ya on the frustration side. For me I defer to `babel-eslint`. Besides supporting dynamic import I've also gotten it to accept opt-in top-level await support too.
