### ISSUE TITLE
More of a question than Issue about using esm

### ISSUE THREAD

**Issue by janusqa** [standard-things/esm#738]
I understand i have to put the below in file that is past to node when starting...

```
require = require('esm')(module /*, options*/);
module.exports = require('./main.index').default;
```
What about other files in the node app.  Do i need to only place this once in the file node calls to start and it will trickle down every where to every file or do i need to put it in every file that needs to use import/export

**Comment by dnalborczyk** [comment]
Hey @janusqa  yes, you would do it only once at the entry point of the project. there you can decide if you want to load it from the `cli` _or_ as a `bridge`, **not** both together.

from the cli,  _probably preferred, and quicker, if it fits your environment_:
```cli
node r -esm index.js
```
or as node.js script:
```javascript
// main.js
require = require('esm')(module);
module.exports = require('./index.js').default;
```

from there on `esm` resolves everything, no matter if commonjs or, if available, even es6-modules including everything in `node_modules` (cjs+es6) - depending on the `esm options` you want to use.

**Comment by janusqa** [comment]
@dnalborczyk 
Thank you for that.
If I have a module with bridge esm and someone else downloads this via npm for example but they are also using esm, there would be no conflicts right?

**Comment by dnalborczyk** [comment]
> If I have a module with bridge esm and someone else downloads this via npm for example but they are also using esm, there would be no conflicts right?

that's correct. in that case, as a module author, you'd point `main` in package.json to your bridge file (main.js) - that would be for users just using node.js with the regular require/commonjs. then ideally you'd also create a `module` field in package.json pointing to your es6 entry file, which would be picked up by users using `esm`, or any other module which can make sense of es6 modules (rollup, webpack, etc.)
