### ISSUE TITLE
TypeError: Cannot read property 'next' of undefined

### ISSUE THREAD

**Issue by ericelliott** [standard-things/esm#739]
I'm getting [a build error on Travis](https://travis-ci.org/ericelliott/autodux/builds/503391863?utm_source=github_status&utm_medium=notification) from ESM with the following error:

```
file:///home/travis/build/ericelliott/autodux/node_modules/riteway/node_modules/esm/esm.js:1
TypeError: Cannot read property 'next' of undefined
    at file:///home/travis/build/ericelliott/autodux/node_modules/riteway/node_modules/esm/esm.js:1
    at file:///home/travis/build/ericelliott/autodux/node_modules/riteway/node_modules/esm/esm.js:1
    at Object.apply (file:///home/travis/build/ericelliott/autodux/node_modules/riteway/node_modules/esm/esm.js:1)
    at file:///home/travis/build/ericelliott/autodux/node_modules/nyc/node_modules/append-transform/index.js:62:4
    at Object.<anonymous> (file:///home/travis/build/ericelliott/autodux/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Object.xh (file:///home/travis/build/ericelliott/autodux/node_modules/riteway/node_modules/esm/esm.js:1)
```

I can't reproduce this on my local machine, so debugging it is tricky.

Of note though is that the error is coming from esm in RITEway, and I'm also using esm in autodux, which depends on RITEway.

Am I doing this wrong?

**Comment by jdalton** [comment]
So the last update couple updates to `esm` allowed it to work with the nyc cache. I'm wondering if you update your `esm` version across the deps if the issue is resolve. If you do that and the issue isn't it could point to a gap in the nyc cache fix.

**Comment by dnalborczyk** [comment]
> I can't reproduce this on my local machine, so debugging it is tricky.

I can repro when running `npm run test-coverage-ci`, node v11.11.0, macOS

[although it also passes once in a while when run multiple times in a row.]

**Comment by jdalton** [comment]
I can repro it too, even on the same `esm` version. Digging in.

**Comment by jdalton** [comment]
I've isolated the problem.

**Comment by jdalton** [comment]
Fixed it locally.

**Comment by jdalton** [comment]
**Update:**

`esm` [v3.2.14](https://github.com/standard-things/esm/releases/tag/3.2.14) is released 🎉
