### ISSUE TITLE
What's the recommended usage for transitioning to mjs?

### ISSUE THREAD

**Issue by amio** [standard-things/esm#74]
How should we use this as a helper for transitioning to mjs? Such as:

package.json:
```javascript
{
  name: 'some-module',
  main: 'main.js',
  module: 'main.mjs'
}
```

main.js:
```javascript
require("@std/esm")
module.exports = require("./main.mjs").default
```

main.mjs:
```javascript
export default // ... real module code.
```

So that the majority in npm would be written in mjs at last.

Since `module` field in `package.json` is still a proposal, is there another recommended way for doing this?

**Comment by jdalton** [comment]
Hi @amio!

The `module` field doesn't really factor into things at the moment.
The suggested usage for the current released versions is to use a main cjs file to bootstrap loading esm files. If the `module` field doesn't become a thing when 2020 rolls around and you'd like to drop `@std/esm` then you'd simply swap the `main` field to `main.mjs`.
