### ISSUE TITLE
esm/jest implementation

### ISSUE THREAD

**Issue by dancalderon** [standard-things/esm#742]
This is a short but important issue.

I have tried every single solution for the jest integration, I couldn't make it work.

I have tried with 
.env
NODE_OPTIONS='-r esm' jest

With jest transformation.

I really don't want to convert all my import and exports into old JS just for Jest.

There's another way?

Thanks

**Comment by jdalton** [comment]
Hi @dancalderon!

We don't support `jest` as a `transform` target yet. You can watch #706 for updates though and browse our [scenario tests](https://github.com/standard-things/esm/tree/master/test/fixture/scenario) for `jest` scenarios we test for.
