### ISSUE TITLE
npx compatibility with multiple arguments

### ISSUE THREAD

**Issue by damianobarbati** [standard-things/esm#743]
I'm reporting a weird behaviours when using multiple npx node arguments (-n flag).
Not sure whether this happens because of esm or npx, anyway this is easy to reproduce (`dotenv` package needed):

```
NODE_ENV=development DOTENV_CONFIG_PATH=./config/development.env npx -n '-r dotenv/config' --config ./config/webpack.config.js --progress
```
=> it works

```
NODE_ENV=development DOTENV_CONFIG_PATH=./config/development.env npx -n '-r dotenv/config' -n '-r esm' webpack --config ./config/webpack.config.js --progress
```
=> it hangs

**Comment by jdalton** [comment]
Hi @damianobarbati!

I cannot reproduce on my end. Maybe it's something to do with the `./config/development.env` or `./config/webpack.config.js` or other things I don't have available (like your `esm`, `node`, or `npx` versions). Side note: Our docs suggest making `esm` the first Node `-r` script. 

If you create a small repro I'll be able to dig in.
