### ISSUE TITLE
cj dynamic import

### ISSUE THREAD

**Issue by OmgImAlexis** [standard-things/esm#744]
@jdalton I seem to be getting a similar issue to [this](https://github.com/standard-things/esm/issues/735) when using dynamic imports.

```
SyntaxError: The requested module 'file:///Users/xo/code/unraid/api/node_modules/express/index.js' does not provide an export named 'Router']
```

As per your comment https://github.com/standard-things/esm/issues/80#issuecomment-353198311.

```js
> Object.getOwnPropertyNames(require('express'))
[ 'length',
  'name',
  'prototype',
  'application',
  'request',
  'response',
  'Route',
  'Router',
  'json',
  'query',
  'static',
  'urlencoded',
  'bodyParser',
  'compress',
  'cookieSession',
  'session',
  'logger',
  'cookieParser',
  'favicon',
  'responseTime',
  'errorHandler',
  'timeout',
  'methodOverride',
  'vhost',
  'csrf',
  'directory',
  'limit',
  'multipart',
  'staticCache' ]
```

This is the file I'm using `await import` on.

```
➜  api git:(master) ✗ cat ./app/routes/api/index.js
import { Router } from 'express';
import { version } from '../../../package';

export const route = (_, res) => {
        res.send({
                status: 200,
                message: `Welcome to a UNRAID API v${version} server.`
        });
};

/**
 * API Welcome page
 *
 * @name Welcome
 * @path {GET} /
 */
export default new Router({ mergeParams: true })
        .get('/', route);
```

**Comment by jdalton** [comment]
Hi @OmgImAlexis!

I cannot repro with the code snippets you've provided. Your code snippet doesn't use dynamic import either so I may be missing a part of the scenario. Could you create a small repro repo for me to investigate?

**Comment by OmgImAlexis** [comment]
Sorry I forgot to add the rest of my comment on.

I'm using esm with jsdoc and a jsdoc plugin, here's a repo to show the issue. I've added a start script for you.

https://github.com/OmgImAlexis/dynamic-import-issue

**Comment by OmgImAlexis** [comment]
```console
$ node -r esm ./node_modules/.bin/jsdoc --configure ./jsdoc.conf
[file:///Users/xo/code/o_/index.js:1
SyntaxError: The requested module 'file:///Users/xo/code/o_/node_modules/express/index.js' does not provide an export named 'Router']
✨  Done in 3.29s.
➜  o_ git:(master) node -r esm
> import {Router} from 'express'
undefined
```

**Comment by OmgImAlexis** [comment]
[This is the commit](https://github.com/OmgImAlexis/jsdoc-http-plugin/commit/d27f0ff015b44b954e6a126bfa42bc25953faa38#diff-168726dbe96b3ce427e7fedce31bb0bcR36) that adds the dynamic import.

**Comment by jdalton** [comment]
Thanks @OmgImAlexis! 

I'm digging in.

**Comment by jdalton** [comment]
I've identified the issue, working through a proper fix.

**Comment by jdalton** [comment]
The complications are coming from interoperability with [`requizzle`](https://www.npmjs.com/package/requizzle) which is used by `jsdoc` to [create a custom `require`](https://github.com/jsdoc3/jsdoc/blob/10c004f823b2d8691441e1b0b8d296005b087ae1/jsdoc.js#L13-L23)

**Comment by jdalton** [comment]
**Update:**

`esm` [v3.2.15](https://github.com/standard-things/esm/releases/tag/3.2.15) is released 🎉

**Comment by OmgImAlexis** [comment]
@jdalton thank you so much. 🙏
