### ISSUE TITLE
Strange interaction with nodemjs

### ISSUE THREAD

**Issue by mk-pmb** [standard-things/esm#748]
Hi! I encountered [this strange interaction with nodemjs](https://github.com/mk-pmb/nodemjs-node/commit/3ea426f74a51be5ee6c7720ca02862122549c54a). Maybe something about the esm cache again?

The bug occurs when:
* The import statement is active
* esm version 3.2.12 or later (tested up to 3.2.16) is used

Reliable work-arounds:
* Comment-out the import statement
* Install esm version 3.2.11

For now I'll just downgrad to esm 3.2.11, but I'd appreciate if you could find a better fix.

__Update:__ You'll need to pin `esmod-pmb` to 0.1.7, because I'll release 0.1.8 with a fixed-version dep on the older esm to mitigate.

**Comment by jdalton** [comment]
Hi @mk-pmb!

Your setup is pretty unique so trying to figure out how to repro it is a bit challenging. I don't have a `nodejs` executable and when I remapped it to `node` I got:
> readlink: illegal option -- m

which suggests differences in the MacOS `readlink` utility. 
Feel free to browse https://github.com/standard-things/esm/compare/3.2.11...3.2.12 to see if you can pin point a specific commit.

**Comment by mk-pmb** [comment]
Thanks for the error report! I've dropped the requirement for GNU readline, now using nodejs instead. Also,

> As of 0.1.7, you can configure your favorite `nodejs` replacement via the `NODEJS_CMD` env var.

**Comment by jdalton** [comment]
I'm still having trouble setting up a repro. Any assistance would be welcomed. For example, if you could create a small repro repo with instructions that would be fantastic!

**Comment by mk-pmb** [comment]
Of course, no problem! I'll prepare a tarball.

**Comment by mk-pmb** [comment]
[tarball download](http://l.proggr.de/?1926p52ny): It's meant as the home directory of an Ubuntu user named `ci-test`. The demo runs with `./demo.sh`.

**Comment by jdalton** [comment]
😢I'm sorry @mk-pmb but I don't think I can run your repro. Sorry to ask you to do more legwork but the list of changes are https://github.com/standard-things/esm/compare/3.2.11...3.2.12. You could checkout each commit hash, build, and then test until your scenario breaks. This would let me know what the issue is. The good news is it's 16 commits and some can likely be skipped.

**Comment by mk-pmb** [comment]
No prob, thanks for your effort on free support! :-)
I found the null options, I'll send a PR.
