### ISSUE TITLE
RFC: Resolve and Load hooks

### ISSUE THREAD

**Issue by guybedford** [standard-things/esm#75]
Here's a draft of a spec for a "resolve" and a "load" hook - https://gist.github.com/guybedford/4d05de071f2433b3d3824ce48b38c5bd.

The goal is to try and work towards a specification here that could become a NodeJS EPS, so it's important to try to come up with something that solves the problems from the perspective of NodeJS users here first and foremost.

At the same time, I've tried to put together the simplest possible hooks with minimal API surface area to reduce the complexity. Having explored the boundaries of the WhatWG loader spec, I can speak from firsthand experience of how easy it is to go off track when given a meaty API :)

I believe the proposal above covers the use cases for being able to implement the features of this project itself on top of Node if this were the API provided, while also enabling use cases such as code coverage, APM and metrics.

Feedback very welcome - consensus is king.

**Comment by bmeck** [comment]
We might want to avoid strings for resolve, https://bugs.chromium.org/p/v8/issues/detail?id=6658&can=2&start=0&num=100&q=&colspec=ID%20Type%20Status%20Priority%20Owner%20Summary%20HW%20OS%20Component%20Stars&groupby=&sort= discusses that we can produce duplicate/missing identifiers and that Web has a few other bits of meta-data that need to be attached.

Where does `module` live in `module.registerResolve`? Some kind of `import {module} from ...` ? Seems sane.

We should also define the scoping rules for these hooks. Package level vs whole process.

Signed packages, webpackages, etc. probably would drop all hooks once you go into them.

**Comment by tilgovi** [comment]
Would it be worth commenting over at https://github.com/w3c/webcomponents/issues/645 to make some of those W3C folks aware of this? It seems like there are some parallel discussions going on that all relate to hooking module resolve / instantiate.

**Comment by tilgovi** [comment]
See, for instance, this comment: https://github.com/w3c/webcomponents/issues/645#issuecomment-323328247

I had commented to say that I liked the explicitness of `import * from './template.html' as DocumentFragment`, but if hooking the resolver can be scoped then using file extensions is less scary.

It might not be necessary to scope the hooks. If the hooks get the parent URL, well behaved hooks can scope themselves. Although, maybe that means that the load hook also needs metadata beyond the URL.

**Comment by bmeck** [comment]
@tilgovi it should rely on MIME for browser and file extension for server. So both must be taken into account. I'm not sure we have much we can do on web component side of taking that integration into account.

> If the hooks get the parent URL, well behaved hooks can scope themselves. Although, maybe that means that the load hook also needs metadata beyond the URL.

Currently they do not due to parallel loading and how ES spec works. You can have a single module in the graph with multiple dependents (parents).

**Comment by jdalton** [comment]
@guybedford This proposal is probably a better fit for its own repo than a gist. That way it can have its own place to grow. I've version bumped `@std/esm` so now its in a good place to experiment with APIs.

Related to #68.

**Comment by guybedford** [comment]
Thanks @jdalton. Sure I'll do that and see if I can get some work going here! If you think of anything that might sound like a stopper here just let me know, and no pressure at all to merge this work of course.

**Comment by guybedford** [comment]
I've created a GitHub repo, and simplified the proposal to just a resolve hook along with @bmeck's suggestions at https://github.com/guybedford/node-module-hooks. Further feedback and discussion at that repo is very welcome.
