### ISSUE TITLE
problem with "esm": "^3.2.17

### ISSUE THREAD

**Issue by janusqa** [standard-things/esm#750]
Hi I went from ```"esm": "^3.2.11"``` to ```"esm": "^3.2.17"``` and something stopped working.
I am using it with cypress.io.  I have been using it with full success in linux and partial success in windows. See from https://github.com/cypress-io/cypress/issues/3678.
This update has stopped it from working all together, to the point where I am not even getting any error output as to what could be the reason.

**Comment by jdalton** [comment]
Hi @janusqa!

Can you please step your version of `esm` up until it has a problem. This will help narrow down the possible issue.

**Comment by janusqa** [comment]
Hi @jdalton 
it was great up until ```"esm": "3.2.14"```,
From ```"esm": "3.2.15"``` onward to ```"esm": "3.2.17"```, it does not work for me in my situation.

**Comment by jdalton** [comment]
If you could create a small repro repo that would be helpful. Otherwise you can view the list of changes to see if anything jumps out https://github.com/standard-things/esm/compare/3.2.14...3.2.15.

**Comment by janusqa** [comment]
@jdalton 

https://github.com/janusqa/janusqa-cypress-test-tiny-plugin3-esm

I've set it in ```package.json``` to 3.2.14.
> npm install
> node_modules/.bin/cypress open

It should open successfully and a spec should load in less than 5 seconds.

change to 3.2.15
> npm install
> node_modules/.bin/cypress open

It should open and hang.

Will take a look at the changes.

**Comment by jdalton** [comment]
Thanks @janusqa!

I narrowed it down to https://github.com/standard-things/esm/commit/70bac763f55c3272f9e4064349f8764eb8fef743.

**Comment by OmgImAlexis** [comment]
I'm guessing this is related? Rolling back to `3.2.11` allowed my server to come back up.

```
TypeError: Cannot read property 'options' of null
    at /mnt/disks/code/api/node_modules/esm/esm.js:1:193023
    at Object.e (/mnt/disks/code/api/node_modules/esm/esm.js:1:193054)
    at Object.<anonymous> (/mnt/disks/code/api/node_modules/esm/esm.js:1:193840)
    at Object.apply (/mnt/disks/code/api/node_modules/esm/esm.js:1:193630)
    at Object.[nodejs.util.inspect.custom] (/mnt/disks/code/api/node_modules/esm/esm.js:1:198211)
    at formatValue (internal/util/inspect.js:453:31)
    at inspect (internal/util/inspect.js:193:10)
    at Object.formatWithOptions (util.js:85:12)
    at Object.Console.(anonymous function) (console.js:188:15)
    at Object.log (console.js:199:31)
```

**Comment by jdalton** [comment]
@OmgImAlexis No, I think you're issue is more related to #752

@janusqa I found the issue. It comes down to a single line of code. I'll patch it tomorrow.

**Comment by jdalton** [comment]
**Update:**

Patch https://github.com/standard-things/esm/commit/3953a53279aeec36844ce7bc13cc24deb3953388; Related to #333;

**Comment by jdalton** [comment]
The fix was to reintroduce a bug fix for Electron v1 _(which Cypress uses still)_.
With any luck this will improve Cypress support all-up 🎉

**Comment by janusqa** [comment]
Thanks! 
Do you know when it will be available in the npm?

**Comment by jdalton** [comment]
`esm` [v3.2.18](https://github.com/standard-things/esm/releases/tag/3.2.18) is released :tada:
