### ISSUE TITLE
tests fail on clean checkout. docs?

### ISSUE THREAD

**Issue by soldair** [standard-things/esm#751]
hey, trying to get started here and i'm looking for docs on test setup.
On a fresh clone of master the tests are failing. (node 10.15.3)

I also couldn't find any badges or other such things that i could use to reverse engineer the testing setup from build output. 

any help/suggestions would be appreciated.

**Comment by dnalborczyk** [comment]
@soldair  

```cli
git clone https://github.com/standard-things/esm.git
cd esm
npm ci
npm test
```

**Comment by soldair** [comment]
Yeah. This failed for me with a clean checkout. I'll try again and post more data here.

**Comment by jdalton** [comment]
Hi @soldair!

Check out our [travis-ci](https://travis-ci.org/standard-things/esm/builds) and [appveyor](https://ci.appveyor.com/project/jdalton/esm/history) runs.
