### ISSUE TITLE
Tests fail silently on Node.js v9.11.2

### ISSUE THREAD

**Issue by mk-pmb** [standard-things/esm#753]
Hi! Earlier when testing I discovered that failing tests on Node.js v9.11.2 produce a warning about promise rejectiions but nodejs still exits with return value 0. On latest master, the failure is completely silent. I'll make a PR.

**Comment by jdalton** [comment]
Hi @mk-pmb!

I don't want to deviate from whatever Node is allowing for a given version.
As [you point out](https://github.com/standard-things/esm/pull/754#issue-261626265) there are ways for folks [to induce](https://github.com/mk-pmb/p-fatal-js/blob/master/fatal.js) erroring if needed.

**Comment by mk-pmb** [comment]
This makes contributing a lot harder though, since I'd have to remember to hotpatch it each time I'm trying to run the tests. Otherweise I can have really dumb errors like change the formula in `test/fixture/math/math.cjs.js` to `a - b` and tests succeed with no indication that anything might be wrong.

**Comment by mk-pmb** [comment]
Also, even if node allows that behavior, why should your test suite ever be sloppy on promises? Tests are especially meant to report stuff that could be a problem.

**Comment by jdalton** [comment]
If you want to enforce specific rules you are free to. The `esm` loader is used by thousands of folks and I cannot force this kind of option on them, sorry.

**Comment by mk-pmb** [comment]
How would this affect users of the loader? It's a change only in the test script. If any of the scenario tests rely on unhandled rejections, the test should verify they're still not handled after the scenario ran, thereby handling the rejection at test suite level.

**Comment by jdalton** [comment]
Ah I didn't realize it was just for unit tests.

**Comment by mk-pmb** [comment]
Come to think of it. Should we test to ensure the loader doesn't make UPR fatal by accident?
