### ISSUE TITLE
Sourcemaps stopped working on latest chrome

### ISSUE THREAD

**Issue by cjh9** [standard-things/esm#756]
Hi, I have been using esm for half a year for a node project, it has been working really great. But just recently the sourcemaps stopped working, I think that it had to do with chrome being updated.

I've created a repro repo

https://github.com/cjh9/esm-sourcemaps-broken/

So basically I can see the raw file `main.js` and `test.js` but when I try to put a breakpoint I get redirected to an empty file. Also I tried to turn off the sourcemaps with 

`ESM_OPTIONS={'cjs':{'paths':true},'sourceMap':false} NODE_PATH=./ node --inspect -r esm main.js` 

but the inline sourcemaps are still there...

**Comment by jdalton** [comment]
Hi @cjh9!

Yep, it's a Chrome bug. I filed [here](https://bugs.chromium.org/p/chromium/issues/detail?id=941035). 
Please sign-in and ⭐️ it.

They said it looks related to another bug, [here](https://bugs.chromium.org/p/chromium/issues/detail?id=941697) too.

**Comment by cjh9** [comment]
Thanks @jdalton, but what about turning off the sourcemaps and debug in the raw code? Is it the correct way to specify the sourceMap option like this, `ESM_OPTIONS={'cjs':{'paths':true},'sourceMap':false} NODE_PATH=./ node --inspect -r esm main.js`?

When I run it like this I still get the inline sourcemap-string at the bottom of the file...

**Comment by jdalton** [comment]
At the moment `--inspect` trumps the `sourceMap` option.
Let me change that to respect a value of `false`.

**Comment by cjh9** [comment]
@jdalton super great, it works! Also, when regular sourcemaps start working again (hoping they fix the bug) is it possible to mark the raw file with a tag or something in the filename, or that it is removed completely? Right now the raw and the sourcemapped are side by side, but it's hard to know which one is which. Preferably so that the sourcemapped file turn up first in the list.

![sm1](https://user-images.githubusercontent.com/18718330/54532268-a8a04880-4987-11e9-8c16-5b9a84bb622e.png)

![sm2](https://user-images.githubusercontent.com/18718330/54532289-b48c0a80-4987-11e9-8d23-2efad7db9dd5.png)

**Comment by jdalton** [comment]
@cjh9 

You should file another bug on them to make that more clear too.
Please post a link here if/when you do

**Comment by jdalton** [comment]
**Update:***

It looks like the fix to [chromium bug #941697](https://bugs.chromium.org/p/chromium/issues/detail?id=941697) fixed the [chromium bug #941035](https://bugs.chromium.org/p/chromium/issues/detail?id=941035) I filed.

**Comment by jdalton** [comment]
**Update:**

`esm` [v3.2.19](https://github.com/standard-things/esm/releases/tag/3.2.19) is released :tada:
