### ISSUE TITLE
using webpack on node

### ISSUE THREAD

**Issue by veeramarni** [standard-things/esm#759]
I have tried

```
//index.ts
require = require('esm')(module, { cjs: true });
process.env.ENV_FILE !== null && (require('dotenv')).config({ path: process.env.ENV_FILE });
```

Error:

```
Error: Cannot find module 'dotenv'
Require stack:
- ./src/index.ts
```

Webpack with node-externals to only bundle the source code as one file, but it fails as above when trying to wrap with `esm` module.

Please let me know what I'm missing.

**Comment by jdalton** [comment]
Hi @veeramarni!

You should not include the CJS bridge in your webpack bundle. To bypass this add a `module` key to your package.json with the path to your ES entry module.

**Comment by veeramarni** [comment]
Not sure if I'm missing anything, following is the `package.json` file. Do I need to do anything to the `webpack.config.js` as I still get compile errors. 


```
//package.json
{
  "name": "backend-server",
  "version": "0.0.1",
  "main": "dist/index.js",
  "module": "dist/main.js",
....
}
```

Error:
```
(function (exports, require, module, __filename, __dirname) { import { from, Observable, Subscription } from 'rxjs';

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
```

I have looked into all other issues in the page but could not find my scenario so I want to understand how this works in my scenario where I use `webpack` for building `nodejs` modules as well as bundle the server code using `webpack` as well. I'm wondering if we have any `webpack` plugin to handle this scenario?

**Comment by veeramarni** [comment]
We use [spin watch](https://github.com/sysgears/spinjs) to start the server.

**Comment by jdalton** [comment]
See webpack's docs for [resolve .mainFields](https://webpack.js.org/configuration/resolve/#resolvemainfields). Depending on your target webpack will look at the `browser` or `module` field first. Visit your trusty webpack resources for further webpack help.

**Comment by veeramarni** [comment]
Ok, that helps with the modules I build by placing `main.js`. But what about the third party packages as I'm facing following issue.


```
backend-server/node_modules/abortable-rx/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { from, Observable, Subscription } from 'rxjs';

SyntaxError: Unexpected token {
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10                                                                     ^

```

**Comment by dnalborczyk** [comment]
@veeramarni 

I think what you are missing is that `webpack` support for `esm` goes as far as that you can declare your `webpack.config.js` file as an es6 module, which then can be loaded by `node` with `esm` and `webpack/webpack-dev-server`. everything thereafter is webpack's responsibility. the docs about esm's webpack support probably need some clarification on that toppic.
