### ISSUE TITLE
3.2.19: TypeError: n.next is not a function

### ISSUE THREAD

**Issue by deepsweet** [standard-things/esm#760]
```
TypeError: n.next is not a function
    Object.<anonymous> (test/Marionette.ts:1)
    Generator.next (<anonymous>)
    Object.replacementCompile (node_modules/append-transform/index.js:58:13)
    Object._compile (node_modules/pirates/lib/index.js:99:24)
```

Fine with `3.2.18`

[Project](https://github.com/deepsweet/foxr) to reproduce:

```
yarn
yarn upgrade
yarn start test
```

**Comment by deepsweet** [comment]
(some tests are still failing even with `3.2.18`, but it's related to other ESM 3.2 issues that I have. with `3.2.19` it fails at the very beginning, you can make any test `.only` to reproduce it faster)

**Comment by jdalton** [comment]
Ah yep, that's a typo on my part.

**Comment by jdalton** [comment]
**Update:**

`esm` [v3.2.20](https://github.com/standard-things/esm/releases/tag/3.2.20) is released 🎉
