### ISSUE TITLE
Expose consistent dynamic import

### ISSUE THREAD

**Issue by jkrems** [standard-things/esm#764]
I'm trying to write some code that uses `esm` to bootstrap a server. The code looks similar to this:

```js
for (const file of files) {
  const esmResult = esm(mainModule)(file);
  const ns = tryMyBestToGuessConvertToNamespace(esmResult);
  ns.default();
}
```

The problem is, right now this requires special casing for CommonJS files because `esm` will return `module.exports` for `.js` but the namespace object for `.mjs`. Would it be possible to expose something like the following?

```js
for (const file of files) {
  const ns = await esm(mainModule).import(file);
  ns.default();
}
```

**Comment by jkrems** [comment]
I did try to set `cjs.dedefault: false` in the options but it doesn't seem to make a difference.

**Comment by jkrems** [comment]
Also looks like checking `Symbol.toStringTag` won't work since the `.mjs` result won't be marked as a namespace object..?

**Comment by jdalton** [comment]
Hi @jkrems!

> The problem is, right now this requires special casing for CommonJS files because `esm` will return `module.exports` for `.js` but the namespace object for `.mjs`. 

The results of the `esm` bridge __are not__ namespace objects. For CJS they are traditional `module.exports` and for ESM they are what can be considered the equivalent of `module.exports`, though I have updated them on `master` to be a bit more rigid.

> I did try to set `cjs.dedefault: false` in the options but it doesn't seem to make a difference.

`esm` options __do not__ apply to `.mjs` files _(see [doc note](https://github.com/standard-things/esm#features))_. 

> Also looks like checking `Symbol.toStringTag` won't work since the `.mjs` result won't be marked as a namespace object..?

Right, because it's not a namespace object.

If you're bootstrapping a server could you use the application loader syntax?
```shell
node -r esm ./server.js
```

**Comment by jkrems** [comment]
> If you're bootstrapping a server could you use the application loader syntax?

Unfortunately not. I'm loading files by convention (think: controller files). So I need to call some function to load each of them after discovery. My heuristic seems to work so far but I guess another solution would be to poke a hole by creating a util file like this and load it via `esm`:

```
'use strict';

module.exports = function getNamespace(id) {
  // Assuming that dynamic import will definitely return a namespace object
  return import(id);
};
```

It would mean that I'd need to handle resolution myself or literally write the file to disk to get the proper context. I'll continue playing around with this.

**Comment by jdalton** [comment]
Okay. If you could use `node -r esm` you could have your entry script leverage dynamic `import()` plus top-level `await` (assuming you opt-in with the `await` option, so using `.js`).

**Comment by jkrems** [comment]
Unfortunately this is deep inside of a library (actually the [source is now in the open](https://github.com/groupon/nilo/blob/7fae5d46ea28f6dc3bfc7dbcfa243807041d7ce8/lib/project.js#L59-L75)). So I can't count on specific node options unfortunately. :(
