### ISSUE TITLE
Possible regression with native modules in ts-jest

### ISSUE THREAD

**Issue by charandas** [standard-things/esm#765]
@jdalton I wrote this tiny wrapper around the main grpc library. I get the following with `ts-jest`. If I skip the entrypoint `lib/index.js` [here](https://github.com/charandas/grpc-esm-repro/blob/master/test/e2e.spec.ts#L1) and instead import from `lib/main.js`, I can get tests to work provided I enable babel in the flow.

Do you know what might be happening? I am going to be using this wrapper in other projects, which use `jest` for their test setup, and I won't have the privilege of using `main.js` there, as the whole point of esm is to be able to use it from the entrypoint `index.js`.

```
❯ npm test

> grpc-esm-repro@1.0.0 test /Users/charandas/serve/opensource/grpc-esm-repro
> npm run jest


> grpc-esm-repro@1.0.0 jest /Users/charandas/serve/opensource/grpc-esm-repro
> jest

 FAIL  test/e2e.spec.ts
  ● Test suite failed to run

    Module did not self-register.

      at Runtime.requireModule (node_modules/jest-runtime/build/index.js:356:31)
      at Object.<anonymous> (node_modules/grpc/src/grpc_extension.js:32:13)

Test Suites: 1 failed, 1 total

**Comment by jdalton** [comment]
Hi @charandas!

I found the issue. This is related to the fact that Jest stores native modules on the primary module cache (not its own internal cache). We were deferring to Jest's cache within `esm` so missed the cache of the native module. I'll tweak things a bit to fix it.

**Comment by jdalton** [comment]
**Update:**

I've fixed this locally 👌

**Comment by charandas** [comment]
@jdalton is a release coming soon?

**Comment by charandas** [comment]
Thank you!

**Comment by jdalton** [comment]
`esm` [v3.2.21](https://github.com/standard-things/esm/releases/tag/3.2.21) is released :tada:
