### ISSUE TITLE
esm should throw failed import statement and file path with non-existing exports

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#766]
I was just trying to repro another bug regarding esm `error messages`, but noticed the following on the way (not a show-stopper, but a nice to have):

esm v3.2.20

minimal repro:

```javascript
// index.js
import A from './lib.js'
```

```javascript
// lib.js
export {};
```

```shell
node -r esm index.js

SyntaxError: The requested module 'file:///Users/daniel/dev/repros/esm/error-prop/lib.js' does not provide an export named 'default'
    at internal/main/run_main_module.js:21:11
```

compare to (renamed files to mjs) `node.js v11.12.0`:

```shell
node --experimental-modules index.mjs

file:///Users/daniel/dev/repros/esm/error-prop/index.mjs:1
import A from "./lib.mjs";
       ^
SyntaxError: The requested module './lib.mjs' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:88:21)
```

_update: fixed file names_

**Comment by jdalton** [comment]
Hi @dnalborczyk!

Is the referenced module incorrect? It looks like different module paths in both errors so not sure if that's the issue or if you refactored between the two. As for the snippet line and carrot in this case based on when the check is done I don't have that info to show, which is why it's missing (in other cases I have it, so I show it).

**Comment by dnalborczyk** [comment]
> Is the referenced module incorrect? It looks like different module paths in both errors so not sure if that's the issue or if you refactored between the two.

@jdalton   oh, yeah, sorry, just simplified the file name. gonna fix the above.

**Comment by dnalborczyk** [comment]
> As for the snippet line and carrot in this case based on when the check is done I don't have that info to show, which is why it's missing (in other cases I have it, so I show it).

if it's not feasible to implement that's fine. just thought I'll point it out ...

**Comment by dnalborczyk** [comment]
I have some other cases regarding [misleading] error messages which `--experimental-modules` seems to handle "more accurate", but depending on how everything is being resolved by `esm` it might be similar or related to the above. None of them are blocking, just more developer friendly.

Do you want me to file away anyways?

**Comment by jdalton** [comment]
@dnalborczyk 

> if it's not feasible to implement that's fine. just thought I'll point it out ...

Related patch to give a filename header: https://github.com/standard-things/esm/commit/950e74186acf7e2e733168b327f8d9747ad13427

> Do you want me to file away anyways?

Sure!

**Comment by dnalborczyk** [comment]
ah, nice!! will do!
