### ISSUE TITLE
repro misleading error messages

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#768]
repro for error message case which `--experimental-modules` seems to be more specific about:

```js
// index.js
import { ControllerA } from "./controllers/index.js"
```

```js
// /controllers/index.js
export { default as ControllerA } from "./ControllerA.js"
```

```js
// /controllers/ControllerA.js
export {}
```

esm:
```shell
node -r esm index.js
SyntaxError: The requested module 'file:///Users/daniel/dev/repros/esm/error-prop/controllers/index.js' does not provide an export named 'ControllerA'
    at internal/main/run_main_module.js:21:11
```

--experimental modules:
```shell
node --experimental-modules index.mjs
(node:3693) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/daniel/dev/repros/esm/error-prop/controllers/index.mjs:1
export { default as ControllerA } from "./ControllerA.mjs";
         ^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module './ControllerA.mjs' does not provide an export named 'default'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:88:21)
```

to be more specific:
`esm`: The requested module 'file:///Users/daniel/dev/repros/esm/error-prop/controllers/index.js' **does not provide an export named 'ControllerA'**
vs:
`--exp mod`: The requested module './ControllerA.mjs' **does not provide an export named 'default'**

when you compare the two above, --experimental-modules points out directly where and what is wrong. with esm you [kinda] don't know.

**Comment by jdalton** [comment]
Thanks @dnalborczyk!

I've got a fix for this locally.

**Comment by jdalton** [comment]
Patch https://github.com/standard-things/esm/commit/ee814da46bd8cd47a11ccde1935c0dede9239dbc.

@dnalborczyk Would you be up for adding a test?

**Comment by dnalborczyk** [comment]
>   Would you be up for adding a test?

@jdalton   yeah, will look into it!

**Comment by jdalton** [comment]
`esm` [v3.2.21](https://github.com/standard-things/esm/releases/tag/3.2.21) is released :tada:
