### ISSUE TITLE
Mixing commonjs and es6 work in 3.2.20 but not in 3.2.22

### ISSUE THREAD

**Issue by aldarund** [standard-things/esm#773]
main test script to launch
```js
const esm = require('esm')
const path = require('path')

const esmOptions = {
  cache: false,
  cjs: {
    cache: true,
    vars: true,
    namedExports: true
  }
}

const nuxtConfigFile = require.resolve(path.resolve('nuxt.config.js'))
const options = esm(module, esmOptions)(nuxtConfigFile)

console.log(options)
```
nuxt.config.js
```js
import path from 'path';

module.exports = {
  mode: "universal"
};
```

In 3.2.20 code work, in 3.2.22 its broken
```
ReferenceError: mode is not defined
    at Function.keys (<anonymous>)
    at getKeys (internal/util/inspect.js:385:21)
    at formatRaw (internal/util/inspect.js:617:12)
    at formatValue (internal/util/inspect.js:540:10)
    at inspect (internal/util/inspect.js:197:10)
    at Object.formatWithOptions (util.js:84:12)
    at Console.(anonymous function) (internal/console/constructor.js:274:15)
    at Console.log (internal/console/constructor.js:284:61)
    at Object.<anonymous> (d:\bb\te\test.js:13:9)
```

**Comment by jdalton** [comment]
Hi @aldarund!

Could you create a small repro repo for me to look at?

**Comment by aldarund** [comment]
@jdalton i pasted whole code in the ticket that cause the problem. Thats all, two small scripts to repro problem. You want me to create repo with this exact same two files ? :)

**Comment by jdalton** [comment]
Yes please. I've found many times things that folks may think aren't part of the scenario become meaningful. Also it couldn't hurt to specify which version of Node you're running too. Thanks!

**Comment by aldarund** [comment]
@jdalton as you want :) But as i said its that two files. Here it is -> https://codesandbox.io/s/nr779m9rw4
Node 10 there.
Locally same happens on node 11.
And there like 5-10 different users reported this issue on stackoverflow, discord and github repo for nuxt.js.

**Comment by jdalton** [comment]
Hi @aldarund!

Thank you for the repro. I see now. I didn't know we supported this but I patched it anyway 😄

**Comment by aldarund** [comment]
@jdalton thanks :) Any chance to release this in patch release anytime soon  ? :)
