### ISSUE TITLE
Rewriting of eval

### ISSUE THREAD

**Issue by katelynsills** [standard-things/esm#778]
We're running up against an issue in which `eval` is rewritten when run with esm. Here's a small program that reproduces the issue:

```js
function testEval() {
  const hello = (0, eval)('console.log("hello");')
}

const evalStr = `${testEval}`;
console.log(evalStr); 
```
If you run this without `-r esm` in Node, it logs the original function. However, if you run it with `-r esm`, your `eval` gets rewritten to something like `_43d‍.e`. 
<img width="467" alt="Screen Shot 2019-04-06 at 3 48 28 PM" src="https://user-images.githubusercontent.com/2441069/55676181-eeb04400-5883-11e9-927f-397cf276e912.png">

In our real workflow, this rewriting causes a ReferenceError, when `_43d‍.e` cannot be found. I imagine this is an intermediate step that somehow gets captured when the stringification occurs.

**Comment by jdalton** [comment]
Hi @katelynsills!

We instrument `eval` use to handle dynamic `import`. It's still on my todo to allow folks to disable various instrumentation.
