### ISSUE TITLE
Error when using with shelljs module

### ISSUE THREAD

**Issue by forceuser** [standard-things/esm#78]
Way to reproduce:
create `package.json`
```json
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.mjs",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@std/esm": "0.7.0",
    "shelljs": "0.7.8"
  }
}
```

run

```
npm i
```

create file `index.mjs`:

```js
import shell from "shelljs";
console.log(shell);
```
run
```
 node -r @std/esm "./index.mjs"
```
and you will get error: 

```
TypeError: common.register is not a function
 at Object.<anonymous> (***/node_modules/shelljs/src/cat.js:4:8)

```

for some reason ```shelljs/src/common.js``` exports empty object

https://github.com/shelljs/shelljs/blob/master/src/common.js

tested on Node v8.1.2,  v8.4.0, v6.11.2, v4.8.4

**Comment by jdalton** [comment]
Hi @forceuser!

I've narrowed it down to a cache tracking issue. It should be resolved and bumped by this evening.
