### ISSUE TITLE
module field in 3rd party module being ignored

### ISSUE THREAD

**Issue by dnalborczyk** [standard-things/esm#781]
`esm` does not seem to pick up the `module` field in `package.json` of a 3rd party module. I was under the impression that it did at some point in time. Is that intentional?

I looked through some issues, but couldn't find a definitive answer:

e.g. mentions only mjs files:
https://github.com/standard-things/esm/issues/627

**Comment by jdalton** [comment]
Hi @dnalborczyk!

You have to configure the "mainFields" option to specify which module fields are picked up. If you're specifying the mainFields option and it's still not picking it up then you'll likely need to use the `force` option to override the default package option.

**Comment by dnalborczyk** [comment]
> You have to configure the "mainFields" option to specify which module fields are picked up.

ah, cool. thank you! that works!
