### ISSUE TITLE
Node 11.12.0 ESM mangling line numbers

### ISSUE THREAD

**Issue by CodeOtter** [standard-things/esm#785]
My `package.json` has the following entries

```
  "esm": {
    "cjs": true,
     sourceMap: true
  },
  "ava": {
    "require": [
      "esm"
    ]
  },
```

When I run `ava`, errors return extreme wrong line numbers.

No .babelrc exists.  No other configuration override exists.

I did not have this problem a week ago. :(  I moved to ESM from Babel so I could get away from the utter insanity that is permanently-alpha transpiling and endlessly mangled line numbers, but alas, it found me here, too :(

**Comment by CodeOtter** [comment]
Aha!  This is a problem between the interaction of `nyc`, `esm`, and `ava`

Going to close ticket, but leave it here in case some poor soul stumbles across this problem in the future!

**Comment by jdalton** [comment]
How did you solve the issue?

**Comment by CodeOtter** [comment]
I didn't and, instead, I've opened up a new request for #790
