### ISSUE TITLE
[Node.js 12] Does not work with "type": "module" in "package.json"

### ISSUE THREAD

**Issue by cedx** [standard-things/esm#789]
I'm using the new [ES modules](https://nodejs.org/api/esm.html) features from Node.js 12 (the next LTS).

If I set my package to be an ESM one with the field `type` set to `module` in `package.json` file, the `esm` package stops working as expected.

```
import {spawn} from 'child_process';
       ^
SyntaxError: Unexpected token {
```

If I set the `type` field to `commonjs`, `esm` works as expected (but not my code which uses only ES modules).
It would be nice if `esm` could manage this case (i.e. that the new ESM parser is already enabled).

**Comment by dnalborczyk** [comment]
hey @cedx  this is related to #784 and should be fixed with the next release.

**Comment by cedx** [comment]
OK, closing as probable duplicate.
