### ISSUE TITLE
breaking changes in 0.6.0 for `node -r @std/esm`?

### ISSUE THREAD

**Issue by danhayden** [standard-things/esm#79]
Hi thanks for adding the release notes :)

I have upgraded to `0.7.0` and having issues using `node -r @std/esm` with the following config

```
"@std/esm": {
  "esm": "js",
  "cjs": true
}
```

```
(function (exports, require, module, __filename, __dirname) { import './env'

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at requireDefaultFromModule 
```

I then downgraded to `0.6.0` and got the same error,  I finally downgraded back to `0.5.1` and everything runs as expected.
I have been using the same setup since `0.1.1` without issue, this leads me to believe there was a breaking change in `0.6.0`

If you have an idea what could be causing this please let me know, thanks!

---

node: 8.4.0
npm: 5.3.0

**Comment by jdalton** [comment]
Not an intentional one 🐛

**Comment by jdalton** [comment]
@danhayden Could you create a simple repro repo? That would help a lot.

**Comment by danhayden** [comment]
Thanks for the rapid response @jdalton 
please see https://github.com/danhayden/esm-0.6.0-bug :)

**Comment by jdalton** [comment]
Thanks! I've found the issue. Expect it to be patched and bumped by this evening.

**Comment by jdalton** [comment]
The interesting thing here is you're not using Node, you're using `nps` which is requiring a file on its own so `@std/esm` is missing its preload detection for Node. The new API requires creating and using the loader from its factory function and no longer hooks the primary `require` method this means it's missing its detection. I have detection for `mocha` to work but would like a more generic approach for CLI tools. I'll look into it.

**Comment by mAAdhaTTah** [comment]
> I have detection for mocha to work but would like a more generic approach for CLI tools. I'll look into it.

This would be nice. I'm using `ava` to test my CLI app and would love to replace `require: babel-register` with `@std/esm`.

**Comment by jdalton** [comment]
I'm already detecting the root module so now I can take that and see if it's a "bin" field then enable the hook based on that.

**Comment by jdalton** [comment]
Patched by https://github.com/standard-things/esm/commit/400651ab5af23f9bb656aff509179a5f6d2a76d2.

**Comment by webpro** [comment]
Looks like I have a similar issue here, but I'm not exactly sure. I'm using @dtd/esm v0.7.0. With the same config as above, I'm seeing the same error when I install this CLI package globally (`npm install -g release-it@beta`). I'm requiring the file directly from the "bin" Node script: https://github.com/webpro/release-it/blob/v3/bin/release.js

However, when `npm link`-ing it, it works fine:

```
❯ npm install release-it@beta -g
/usr/local/bin/release-it -> /usr/local/lib/node_modules/release-it/bin/release.js
+ release-it@3.0.0-beta.0
added 210 packages in 24.634s
❯ which release-it 
/usr/local/bin/release-it
❯ release-it --version
/usr/local/lib/node_modules/release-it/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { version, help } from './cli';
                                                              ^^^^^^

SyntaxError: Unexpected token import
[...]
✘ ❯ cd Projects/release-it
❯ npm link
up to date in 2.53s
/usr/local/bin/release-it -> /usr/local/lib/node_modules/release-it/bin/release.js
/usr/local/lib/node_modules/release-it -> /Users/lars/Projects/release-it
❯ which release-it 
/usr/local/bin/release-it
❯ release-it --version
v3.0.0-beta.0
```

**Comment by webpro** [comment]
After installing globally, running it from the installed dir, also fine. But not from an arbitrary dir (without `node_modules`):
```
❯ pwd
/usr/local/lib/node_modules/release-it
❯ ./bin/release.js --version
v3.0.0-beta.0
❯ release-it --version
v3.0.0-beta.0
❯ cd ~
❯ release-it --version
/usr/local/lib/node_modules/release-it/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { version, help } from './cli';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/release-it/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```

From this, I think that babel-register receives the wrapped yet uncompiled module content. But I'm really wondering why basically `process.cwd()` or the absence of a local `./node_modules` dir influences this.

**Comment by jdalton** [comment]
You're issue is not related to #79. The in-file usage has changed in v0.6.0. See the [release notes](https://github.com/standard-things/esm/releases/tag/0.6.0). Please open a new issue if you have any other issues.

**Comment by webpro** [comment]
I'm terribly sorry @jdalton, thanks for your quick reply.
