### ISSUE TITLE
Overriding .terserrc to override compression

### ISSUE THREAD

**Issue by CodeOtter** [standard-things/esm#790]
Is there any way we can override the default `.terserrc` path here so we can turn off compression?

https://github.com/standard-things/esm/blob/3b5a1ea5ede7e36732d3c3194d1d19e2217122be/script/publish.js#L17

**Comment by dnalborczyk** [comment]
this is just for the build process of the `esm` module itself. would that change anything for https://github.com/standard-things/esm/issues/785 ?

to answer your question regardless:
> Is there any way we can override the default .terserrc path here so we can turn off compression?

you definitely can. you pull down the repo, modify the settings, and run your own build.
