### ISSUE TITLE
does not provide an export named

### ISSUE THREAD

**Issue by cj** [standard-things/esm#80]
when trying to do `import { Router } from 'express'` I get this error: `does not provide an export named 'Router'`.

It appears to happen with any project declared like this https://github.com/expressjs/express/blob/master/index.js#L11

**Comment by tilgovi** [comment]
Do you have `"cjs": true` configured in your `"@std/esm"` section of package.json? Without that, you cannot import named exports from CommonJS.

**Comment by jdalton** [comment]
Hi @cj!

As @tilgovi mentioned, by [Node's rules](https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#461-default-imports) importing named exports of CJS modules is not enabled by default. You can [unlock](https://github.com/standard-things/esm#unlockables) it with the `"cjs"` option.

**Comment by dkebler** [comment]
ok...bit dense here but I have tried all three ways to unlock and I still get the error.

added a line to package.json  like so
```
  "homepage": "https://github.com/uCOMmandIt/i2c#readme",
  "@std/esm": "cjs",
  "dependencies": {
```

then tried  below as .esmrc  or .esmrc.json file.

```
{
  "@std/esm": "cjs"
}

```


```
import { ipc } from 'node-ipc'
```
`/node_modules/node-ipc/node-ipc.js' does not provide an export named 'ipc'`
https://github.com/RIAEvangelist/node-ipc/blob/master/node-ipc.js

Assuming my attempts are correct....

My intention is to import a commonjs module (.js) that didn't export a name (or use default).
I just kinda assumed that this would not be a big issue mixing commmonjs exports many, many, many of which were never written with a "named" object exported just a `module.exports=`

**Comment by jdalton** [comment]
Hi @dkebler,

When I `Object.getOwnPropertyNames(require("node-ipc"))` I get 
```js
[ 'config',
  'connectTo',
  'connectToNet',
  'disconnect',
  'serve',
  'serveNet',
  'of',
  'server',
  'log',
  'IPC' ]
```

The property all-lowercase `ipc` isn't there.

**Comment by dkebler** [comment]
As you say no ipc key...turns out nothing to do with esm or using the node flag

This is what works
`import ipc from 'node-ipc'`

Duh, obviously new to es6 import and the braces are used when importing out a particular key from the module not the whole module.

nevermind :-)
