### ISSUE TITLE
Cannot use class field

### ISSUE THREAD

**Issue by chungchi300** [standard-things/esm#800]
https://github.com/tc39/proposal-class-fields

**Comment by jdalton** [comment]
Hi @chungchi300!

We support parsing class fields. However, the Node version you use must support them.

**Comment by chungchi300** [comment]
I mean does it support ESnext Class Fields?
The class fields proposal allows properties to be initialized at the top of a class:
```
class MyClass {

  a = 1;
  b = 2;
  c = 3;

}
```

**Comment by jdalton** [comment]
The `esm` loader supports whatever functionality native Node does. You can get class fields in Node 12 or `--harmony` I believe.

**Comment by dnalborczyk** [comment]
@chungchi300 could you verify your node version?

either run `node --version` in the terminal, or check `process.versions.node` in your node app. if it's not at least v12.0, you have to either run node.js with the `--harmony` flag, as @jdalton suggested, or use a transpiler, like [Babel](https://babeljs.io/).

if your node version is v12.x, and you are still running into this issue, could you provide some repro steps, or better, create a small repository?
