### ISSUE TITLE
Latest patch breaks 

### ISSUE THREAD

**Issue by omerts** [standard-things/esm#806]
3.2.22 works perfect, 3.2.23 break with the following:
![image](https://user-images.githubusercontent.com/4996164/57865040-90bd3780-7805-11e9-8701-23bceb4eee5d.png)

I am using node-fetch, it is even working without esm, just esm breaks it, in 3.2.23.

**Comment by s4l1h** [comment]
> /app/node_modules/puppeteer/lib/Page.js:44
>   static async create(client, target, ignoreHTTPSErrors, defaultViewport, screenshotTaskQueue) {
>                ^
> 
> SyntaxError: Invalid or unexpected token
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)

That's right.I have some problem.

**Comment by jdalton** [comment]
Dup of #804.
