### ISSUE TITLE
Usage example with the Serverless Framework

### ISSUE THREAD

**Issue by Vadorequest** [standard-things/esm#818]
I'm looking for a basica example of how to use ESM with the https://serverless.com/ framework.

I tried to look out to see if there was other related issue, found this one but wasn't really useful.
https://github.com/standard-things/esm/issues/586

From my first experience with ESM a few months ago -which was [awesome](https://medium.com/unly-org/how-esm-made-quick-prototyping-and-scripting-with-node-js-4a3749d40c5f)-, I'm very interested in using it with serverless, because I'm really tired of having to re-learn everything that's changed in babel/webpack since the last time I had to setup a project (so much time wasted)

I believe that loading a file, that loads esm itself nd then loads a ES7 .js file should just work, I'm gonna give it a try, but any direction would be appreciated.

**Comment by Vadorequest** [comment]
Indeed, it works just fine:

```
functions:
  status:
    handler: src/functions/_status.handler
    events:
      - http:
          method: GET
          path: /status
          cors: true
```

`/src/functions/_status.js`
```
// XXX See https://github.com/standard-things/esm#getting-started
// Set options as a parameter, environment variable, or rc file.
require = require('esm')(module);
module.exports = require('./status.js');

```

`/src/functions/status.js`
```
import RavenLambdaWrapper from 'serverless-sentry-lib';
import Raven from 'raven';
import moment from 'moment';

export const handler = RavenLambdaWrapper.handler(Raven, async (event, context) => {
  return {
    body: JSON.stringify({
      status: 'OK',
      processNodeEnv: process.env.NODE_ENV,
      time: moment().toISOString(),
      appName: process.env.APP_NAME,
      release: process.env.GIT_COMMIT_VERSION,
      releasedAt: process.env.DEPLOY_TIME,
      version: process.env.npm_package_version,
      nodejs: process.version,
    })
  };
});

```

With a couple limitations:

- No hot reloading, any code change require a server restart
- Not sure how it would handle frontend code that loads .scss/.sass/.svg files, not a concern in my case because I'm building an API but I wondered
- Not sure if that's a good idea at all

**Comment by jdalton** [comment]
Thank you for this @Vadorequest!

I believe you can mix some hot reloading in if you use something like [`node-hot-loader`](https://www.npmjs.com/package/node-hot-loader#express-hot-reload-example).

**Comment by Vadorequest** [comment]
A basic nodemon worked fine actually. (small app)

But I eventually got back to traditional Webpack (😢) because Jest wasn't supported by ESM yet.
