### ISSUE TITLE
esm seems to pre-load modules despite their order

### ISSUE THREAD

**Issue by vdeturckheim** [standard-things/esm#819]
Hello there,

If I have a simple module with the following, 
```js
import 'sqreen';
import 'express';
```
sqreen (that needs to be required before express) will see that express is already loaded when it starts (it is already present in `require.cache`). 
This happens with esm@3 and was not present in esm@2. Is there any special way to ensure the module is loaded before all other ones?

**Comment by jdalton** [comment]
Hi @vdeturckheim!

Because of how `sqreen` works you'll want to load it before `esm`.
See the our scenario test [here](https://github.com/standard-things/esm/blob/c910d5716624eb5c6126b3679e268cac6282fcab/test/scenario-tests.mjs#L195-L201).

**Comment by vdeturckheim** [comment]
Hey @jdalton thanks for the answer, I might have been confused by the README that I understand recommend to load `esm` after Sqreen (https://github.com/standard-things/esm#loading) right?

**Comment by jdalton** [comment]
Do as my code, not as my comment 🙃
