### ISSUE TITLE
Modules that export default modules as { namedModules } 

### ISSUE THREAD

**Issue by laggingreflex** [standard-things/esm#82]
I'm using this with [preact](https://github.com/developit/preact/) like this:

```
import {Component, render} from 'preact';
```

which throws

> SyntaxError: Module 'C:\\...\\node_modules\\preact\\dist\\preact.js' does not provide an export named 'Component'

`preact\dist\preact.js` exports like this:

```js
var preact = {
  h: h,
  createElement: h,
  cloneElement: cloneElement,
  Component: Component,
  render: render,
  rerender: rerender,
  options: options
};
if ('undefined' != typeof module) module.exports = preact; else self.preact = preact;
```

It works with Babel and Webpack.

**Comment by jdalton** [comment]
Hi @laggingreflex!

See #80.
