### ISSUE TITLE
"esm" package vs "@std/esm"

### ISSUE THREAD

**Issue by Vadorequest** [standard-things/esm#820]
I don't understand the difference between those two packages, nor when one should be used instead of the other.

**Comment by dnalborczyk** [comment]
hey @Vadorequest 

they are both the same thing. @std/esm was the former package name for all 0.x releases and was renamed to `esm` for all 3.x releases. @std/esm is `deprecated` and you should therefore use `esm`.

**Comment by Vadorequest** [comment]
I think a notice about that in the readme would clarify this topic once and for all ;)
thanks!
