### ISSUE TITLE
Support for importing data: URI

### ISSUE THREAD

**Issue by thgh** [standard-things/esm#823]
Example code:
```
import('data:application/javascript;charset=utf-8;base64,ZG9jdW1lbnQud3JpdGUoImhlbGxvIGZyb20gbW9kdWxlIik')
```
https://jsfiddle.net/wt4kyp36/

At least Chrome, Firefox and Safari support it.

**Comment by jdalton** [comment]
Hi @thgh!

This is on my list as a possible extension to `esm`, but I haven't gotten around to it. If you feel up for creating a PR though I'd totally add it.

**Comment by TomasHubelbauer** [comment]
@jdalton would it be possible to keep this issue open and mark it as `help-wanted` then? That way GitHub will surface it in a few places. I found this by chance when looking for something else and since it seems to be a roadmap item (no matter how far off) it strikes me as odd to see it closed.
