### ISSUE TITLE
repl/cjs vs mjs script import differences

### ISSUE THREAD

**Issue by jsg2021** [standard-things/esm#825]
I just updated a module in my project and it started failing. It went from cjs, to cjs-pretending-to-be-esm with `Object.definePropetry(module, { __esModule: {value: true }})`… however, using this test script in the repl (`node -r esm`) and pasting this in results in the correct behavior…

```js
import queue from 'p-queue'; // @ v6.0.2
console.log(queue);
```

however, if you put that in a file and `node -r esm test.mjs` it outputs the “incorrect” thing. Additionally, if you rename the test to `test.js` it results in the correct thing. 😕

**Comment by jsg2021** [comment]
This was probably a dumb question. I think the issue is that `p-queue` should expose a module entry point. Its currently compiled TypeScript which outputs webpack/babel-like fake-esm/cjs modules.

**Comment by jdalton** [comment]
Hi @jsg2021!

The `esm` loader [locks down](https://github.com/standard-things/esm#features) `.mjs` files (they get no extra `esm` options support).
