### ISSUE TITLE
Does it work with gulp 4?

### ISSUE THREAD

**Issue by mylastore** [standard-things/esm#826]
I am using gulp 4 with a task that run my main.js, I added the esm via the index.js configuration example and pointing to the main.js but when I run gulp Is complaining that I need to install @babel/register or babel-register plus it also does not recognize import statements and I am sure at this point esm is not loaded,  also try this on package.json `nodemon -r esm gulp` but get this 

```
[nodemon] starting `node -r esm ./gulp index.js`
Error: Cannot find module '/storage/projects/client/gulp'
```

**Comment by jdalton** [comment]
Hi @mylastore!

If you can produce a simple repro repo I'll try to spot the issue for ya :)

**Comment by mylastore** [comment]
@jdalton Thanks for the quick response I have this project hope you can test it here. https://github.com/mylastore/nodeshop

**Comment by jdalton** [comment]
I don't see `esm` in use in `nodeshop`.
Would you please create a branch with what you're trying to do?

**Comment by mylastore** [comment]
OOPS forgot to push, just push the new package.json

**Comment by jdalton** [comment]
Now I get
> Error: Cannot find module '/Users/johndavid.dalton/projects/nodeshop/gulp'

**Comment by mylastore** [comment]
exactly that's what I get but if run npm run gulp it works  see what I mean below 
`` "scripts": {
    "postinstall": "npm rebuild node-sass",
    "start": "node -r esm gulp",
    "gulp": "gulp",``

**Comment by jdalton** [comment]
That is because npm does some behind the scenes magic to resolve the local bin of `gulp` since it's a dep. When you explicitly call node you have to provide it a proper path.
> node -r esm ./node_modules/gulp/bin/gulp.js

**Comment by mylastore** [comment]
ah good to know wow thank you for your time and this awesome project
