### ISSUE TITLE
Syntax error on built loader

### ISSUE THREAD

**Issue by Lcfvs** [standard-things/esm#827]
Something wrong on package building.

**OS**: Windows 10
**node version**: v12.6.0
**npm version**: 6.9.0
**esm version**: 3.2.25 (`@latest`)

**node_modules/esm/esm/loader.js:204**
 ```js
if (0 === this.prerelease.length) this.prerelease = [0] else {
```

**Comment by jdalton** [comment]
Hi @Lcfvs!

Do you mean something is wrong when building from the `master` branch of the `standard-things/esm` repo? Or is this related to a project where you're using `esm` as part of a build step?

**Comment by Lcfvs** [comment]
Hi @jdalton 

I simply installed `esm` and used by `node -r esm index.js`, nothing exotic then. ;)

**Comment by jdalton** [comment]
Could you provide the `index.js` you're trying to run or better yet a simple repro repo with the exact config, package.json, etc. of your setup.

**Comment by Lcfvs** [comment]
Just made a gist, with the `package.json`, the fresh generated (install only, never ran) `loader.js` and a reformated version `reformated-loader.js`: https://gist.github.com/Lcfvs/a68a9c60a79e855874b86f9bf970c8a0#file-reformated-loader-js-L204

**Comment by jdalton** [comment]
Hmm. I cannot reproduce the error with our published package. Maybe some other process on your end has run over the file and caused it to be changed in some way.

**Comment by Lcfvs** [comment]
I don't see what process, it's a very new PC (just installed `node`, `git`, `phpstorm`, then `npm i` on my project.

**Comment by Lcfvs** [comment]
Hmmm, I don't know how you don't have the same thing on your end, that error is contained in your NPM tarball: `npm pack esm`.

**Comment by Lcfvs** [comment]
Ok, maybe a phpstorm eslint process, as suggested by @ljharb, sorry.
