### ISSUE TITLE
is esm es6 to es5 JavaScript compiler? 

### ISSUE THREAD

**Issue by mylastore** [standard-things/esm#830]
I am a bit confuse is esm es6 to es5 JavaScript compiler? ,since it says esm is babel-less.

**Comment by dnalborczyk** [comment]
`esm` is mainly focusing on parsing and loading ES6 modules (import/export) including interoperability with CommonJS modules (require/module.export/export).

> is esm es6 to es5 JavaScript compiler

to a certain degree you could see it that way. although everything happens in the background and you won't see the transpiled/compiled output.
