### ISSUE TITLE
esm works with .ts file but it is not mentioned in README

### ISSUE THREAD

**Issue by motss** [standard-things/esm#848]
I just discovered that `esm` support `.ts` files. It should be one of the features listed in README.

**Comment by nmccready** [comment]
Right this seems to work if it's a single `.ts` file which does not import other `.ts` files implicitly. The second problem is where I am banging my head.

IE: 
- this works and runs but gives ts lint errors `import debug from '../debug.ts';`
- this fails when ran but has no lint errors `import debug from '../debug.;` , debug.ts is not resolved as it is looking for debug.js . Is there an option to force esm to look for both extensions?

**Comment by nmccready** [comment]
@jdalton any ideas ?
