### ISSUE TITLE
[question] zero dependency ?

### ISSUE THREAD

**Issue by lorenzofox3** [standard-things/esm#849]
I see the package bundles some of its dev dependencies (acorn at least if I am not wrong). I am curious to know whether there is a technical reason or is it more for "marketing" (and write "zero dependency" in the readme)  ?  

Thanks

**Comment by sntran** [comment]
I'm not sure how you see the package bundled with dev dependencies. When I installed `esm`, I don't see `acorn` or anything else.

**Comment by TrySound** [comment]
@lorenzofox3 This allows to reduce startup time. Node does not spend a time to resolve dependencies. Also dependencies may have a lot of unused stuff which increases node_modules size.

See the difference of package size
https://packagephobia.now.sh/result?p=acorn
https://packagephobia.now.sh/result?p=esm

**Comment by lorenzofox3** [comment]
@TrySound Thanks, it indeed makes sense for a module loader :)
