### ISSUE TITLE
Why is it bundled in gzip?

### ISSUE THREAD

**Issue by laggingreflex** [standard-things/esm#85]
Size doesn't matter in Node, right? Webpack already supports import statements.

**Comment by jdalton** [comment]
Hi @laggingreflex!

> Size doesn't matter in Node, right? 

The size of `node_modules` has grown to the point of being [memeable](https://twitter.com/FischaelaMeer/status/894570174778572800):
> <img src="https://user-images.githubusercontent.com/4303/29985590-73a03430-8f14-11e7-95e3-3910f8aaceae.png" width=50%>

The `@std/esm` loader is designed to be a small (< 50kb), zero dependency, package so devs can feel comfortable reaching for it in any situation.

Node is also used in serverless environments like AWS Lambda and Azure functions where extra storage costs.
