### ISSUE TITLE
Is there quick overview how does this work?

### ISSUE THREAD

**Issue by techsin** [standard-things/esm#856]
I am interested in understanding how this magic occurring

**Comment by fregante** [comment]
He wrote an article a while back https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b

**Comment by techsin** [comment]
article certainly goes into detail of how to use it. But I was looking to see how does the code works. I wish I was able to understand that just by looking at the code.

**Comment by dnalborczyk** [comment]
@techsin  you probably have to start digging in and start debugging if you are really interested in how this works.
