### ISSUE TITLE
Building on windows results in faulty package

### ISSUE THREAD

**Issue by laggingreflex** [standard-things/esm#87]
I'm on Windows and I tried to fork it and build it myself but building results in a package that always results in this error:

```
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:28:11)
    at join (path.js:489:7)
    at Object.<anonymous> (C:\...\test\node_modules\@std\esm\esm.js.gz:1:53077)
    at e (C:\...\test\node_modules\@std\esm\esm.js.gz:1:219)
    at C:\...\test\node_modules\@std\esm\esm.js.gz:1:576
    at Object.<anonymous> (C:\...\test\node_modules\@std\esm\esm.js.gz:1:586)
    at Module._compile (module.js:573:30)
    at Object.<anonymous> (C:\...\test\node_modules\@std\esm\index.js:14:5)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

**Comment by jdalton** [comment]
Hi @laggingreflex!

I can't repro.
I'm running Windows 10, Node 8.x, with npm 4 and able to build from the repo.

**Comment by laggingreflex** [comment]
I'm on node 8.4 npm 5

I compared the `esm.js.gz` built by me with the npm-installed version and there's a size difference: 42.6kB (mine) vs 43kB (installed) so there's definitely something weird going on at my end. 

Could you could you upload your `./build/esm.js` produced via `build --dev` command (so that it's uncompressed)? I could compare that to mine to get a better idea what's missing in my build.

**Comment by jdalton** [comment]
The build size difference is expected since our master branch is where WIP bits are.

**Comment by jdalton** [comment]
Are you able to `npm i`, `npm test`, and `npm run test:prod` ?

**Comment by laggingreflex** [comment]
Tests are working, but can't use it outside the library for some reason. 

Setting the package version to 0.7.1 (from 0.7.0) and then building again **solves the issue**! Not sure why. 

I got this hint (of upgrading version) while debugging the webpack build. Somewhere the values being passed looked like this:

```
  map:
   { raw: [Function],
     versions: [ '0.7.0' ],
     wrappers: { '0.7.0': [Function: methodWrapper] } },
  range: '>=0.7.1 <0.8.0' }
```
