### ISSUE TITLE
Allow external modules as unlockable

### ISSUE THREAD

**Issue by MikeKovarik** [standard-things/esm#88]
Hello. I'd like to ask for option to enable loading external modules. I know there's an unsolvable issue for loading ES modules but I'm asking for plain old rolled-up *.JS files so that i can `import xyz from 'mylib'`. I'm developing couple of libraries that dependant on each other but at the same time I can't `npm link mylib` them due to symlinks conflicting with other tools in my workflow. So I'm at least keeping them in symlinked to the global node_modules which works ok with `require()` but with this module I'm hitting `ERR_MODULE_RESOLUTION_DEPRECATED` and I'd like to be able to bypass it.

**Comment by MikeKovarik** [comment]
Sorry, never mind. Turns out I'm way too sleepy and missed there's already the `"cjs":true`

**Comment by jdalton** [comment]
No problem @MikeKovarik!
