### ISSUE TITLE
Dynamic import() Error

### ISSUE THREAD

**Issue by durongzhang** [standard-things/esm#90]
Very happy to use this project, but also encountered a problem 
code is simple

package.json
![image](https://user-images.githubusercontent.com/15725537/30198914-edcccafe-9435-11e7-96a7-6b33f6386096.png)

index.js
![image](https://user-images.githubusercontent.com/15725537/30198926-f9f0713c-9435-11e7-854c-18155bd5ce27.png)

action.js
![image](https://user-images.githubusercontent.com/15725537/30198943-0c8f962e-9436-11e7-91ee-4b5af38f319e.png)

![image](https://user-images.githubusercontent.com/15725537/30199003-4bdd44d4-9436-11e7-8a65-aa880b37271b.png)

node: 8.4.0
yarn: 0.27.5
mac os

**Comment by jdalton** [comment]
Hi @durongzhang!

I can't reproduce the issue.
I noticed your `ctx.body = action.say` should be `ctx.body = action.default.say`.

Could create a simple repro repo.

**Comment by jdalton** [comment]
Found a repro in #50 :tada:

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/5837260ee3608e2e38b28f2fdeb4f27a6d437396.

**Comment by jdalton** [comment]
Fixed with v0.8.3 🎉
