### ISSUE TITLE
ReferenceError: _220‍ is not defined

### ISSUE THREAD

**Issue by arackaf** [standard-things/esm#91]
For some reason, when re-starting my app, after it's already been running, I get 

> ReferenceError: _220‍ is not defined

Deleting the `.esm-cache` folder from which this error comes fixes it. 

Am I supposed to be clearing all .esm-cache folders before starting my app, or is there something else going on?

**Comment by jdalton** [comment]
> Am I supposed to be clearing all .esm-cache folders before starting my app

Nope. You shouldn't have to do anything. Can you create a simple repro repo?

**Comment by arackaf** [comment]
I have a repo, unfortunately it's not as simple as it could be.

https://github.com/arackaf/booklist/tree/feature/sdt-esm

**Comment by arackaf** [comment]
Here's the full error

> c:\GIT\booklist>node app
ReferenceError: _220‍ is not defined
    at Object.<anonymous> (c:\GIT\booklist\node-dest\controllers\.esm-cache\620bce25220e3817.js)
    at Object.<anonymous> (c:\GIT\booklist\node-dest\controllers\.esm-cache\620bce25220e3817.js)

and here's `620bce25220e3817.js`

```
let httpPost,route,nonRoutable,controller;_220‍.w("easy-express-controllers",[["httpPost",function(v){httpPost=v}],["route",function(v){route=v}],["nonRoutable",function(v){nonRoutable=v}],["controller",function(v){controller=v}]]);let BookDAO;_220‍.w("../dataAccess/bookDAO",[["default",function(v){BookDAO=v}]]);var _dec, _class;




let bookController = (_dec = controller({ defaultVerb: "post" }), _dec(_class = class bookController {
  constructor() {}
  async setSubjects({ books, add, remove }) {
    try {
      let bookDao = new BookDAO(this.request.user.id);
      await bookDao.setBooksSubjects(books, add, remove);
      this.send({ success: true });
    } catch (errr) {
      console.log(errr);
    }
  }
  async setTags({ books, add, remove }) {
    try {
      let bookDao = new BookDAO(this.request.user.id);
      await bookDao.setBooksTags(books, add, remove);
      this.send({ success: true });
    } catch (errr) {
      console.log(errr);
    }
  }
}) || _class);


_220‍.d(bookController);
```

**Comment by jdalton** [comment]
The `_220` is the runtime alias based on the cache name *620bce25**220**e3817*. Do I just `npm start` kill the process and `npm start` again?

**Comment by arackaf** [comment]
No from a cli just run `node app`

Would running this app through an npm script solve this?

**Comment by arackaf** [comment]
> Would running this app through an npm script solve this?

Sorry, npm start will run `node app`, and the same error, for me, seems to ensue.

**Comment by jdalton** [comment]
`npm i` errors (using npm 5.4.1, and node 8.3.0)

**Comment by arackaf** [comment]
I trust you're only now running into this?

https://github.com/npm/npm/issues/18380 

I'd recommend npm 5.3.0, assuming you're on Windows

**Comment by jdalton** [comment]
I'm on OSX
```
npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN Booklist@0.1.0 No repository field.
npm WARN Booklist@0.1.0 No license field.

npm ERR! Cannot read property '0' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jdalton/.npm/_logs/2017-09-11T02_33_31_159Z-debug.log
```

**Comment by jdalton** [comment]
Happens with npm 5.3.0 too.

**Comment by arackaf** [comment]
Wow npm seems to really be slipping these days.  Fresh install works fine for me.

Is there anything I can do on my end to help you debug this?  Anything I should try?

**Comment by jdalton** [comment]
`rm -rf node_modules` then `npm i` again fixed it :P, looking into thing.

**Comment by jdalton** [comment]
`npm start` errors with
```
Error [ERR_MISSING_MODULE]: Cannot find module ./node-dest/app-helpers/promiseUtils
```

**Comment by arackaf** [comment]
SORRY john, run `gulp transpile-all`

**Comment by jdalton** [comment]
It looks like `booklist/node_modules/easy-express-controllers/util/createController.js`

is calling `classDec = require(classBasePath + '/' + controllerPath)`

Which is including 
`classBasePath` of  `../../../node-dest/controllers` and
`controllerPath` of `.esm-cache/0a085b677a0a1cbe`

So it's loading the cache file as a normal file. Probably some glob rule that needs to be tweaked.

**Comment by arackaf** [comment]
This is a bug in my easy-express-controllers - my library is sniffing these files out and then loading them.  I'll need to hard code this name as a blacklist

**Comment by jdalton** [comment]
Might start with ignoring `.` files and folders which would catch the cache folder. You can also customize the cache folder name with the `"cache"` option.
