### ISSUE TITLE
Failure using koa-compose

### ISSUE THREAD

**Issue by chrisveness** [standard-things/esm#92]
`@std/esm` looks great! But I seem to be having compatibility problems with [koa-compose](https://www.npmjs.com/package/koa-compose).

Minimal example:

_package.json:_

    {
      "name": "import-koa-compose",
      "version": "0.0.0",
      "scripts": {
        "start": "node -r @std/esm app.js"
      },
      "dependencies": {
        "@std/esm": "^0.8.3",
        "koa": "^2.3.0",
        "koa-compose": "^4.0.0"
      },
      "@std/esm": {
        "cjs": true,
        "esm": "js"
      }
    }

_app.js:_

    import Koa     from 'koa';
    import compose from 'koa-compose';

    const app = new Koa();

    import { middleware as appRespond }  from './respond.js';

    app.use(async function(ctx) {
        await compose(appRespond)(ctx);
    });

    app.listen(3000);

_respond.js:_

    //const Koa = require('koa'); // works using require (comment out the import!)
    import Koa from 'koa'; // fails using import (comment out the require!)

    const app = new Koa();

    app.use(async function(ctx) {
        ctx.body = 'Hello World';
    });

    module.exports = app;

If the _respond.js_ composed sub-app uses `require()`, all is fine, but if it uses `import`, then _npm start_ throws an error

    Module '/home/.../import-koa-compose/respond.js' does not provide an export named 'middleware'

Is there some easy way around this, or is there a real incompatibility?

I'm using node v8.4.0 on Linux.

**Comment by chrisveness** [comment]
On further thought, I expect should remove the `"cjs: true"` option from _package.json_, and `export` the `app` from _respond.js_ (rather than using `module.exports`), but I can't quite find the correct incantation!

**Comment by jdalton** [comment]
Hi @chrisveness!

Your mix of CJS `module.exports` and ESM `import` is the problem. Our `cjs` compat flag may expose things like `require` in ESM but your file is still ESM since it uses `import` so we'll be expecting you to use `export` to define its exports and not `module.exports`

**Comment by chrisveness** [comment]
Apologies for the noise, I've worked it out:

_app.js:_

    import Koa     from 'koa';
    import compose from 'koa-compose';

    const app = new Koa();

    import appRespond from './respond.js';

    app.use(async function(ctx) {
        await compose(appRespond)(ctx);
    });

    app.listen(3000);

_respond.js:_

    import Koa from 'koa'; // fails using import (comment out the require!)

    const app = new Koa();

    app.use(async function(ctx) {
        ctx.body = 'Hello World';
    });

    export default app.middleware;

... and all is fine!

[hangs head in shame]
