### ISSUE TITLE
Break async

### ISSUE THREAD

**Issue by aymericbeaumet** [standard-things/esm#94]
I have been facing a strange behavior in the REPL when defining an async method `delete` to an object literal:

```js
require('@std/esm');

// OK
({ async foobar() {} });

// KO
({ async delete() {} }); // syntax error
```

I cannot reproduce this issue with other restricted identifiers (like `throw`, `const`, `return`). Generators are working properly.

---

**node**: 8.4.0
**std/esm**: 0.9.0

**Comment by jdalton** [comment]
Thank you @aymericbeaumet!
