### ISSUE TITLE
AVA support and default export

### ISSUE THREAD

**Issue by dinoboff** [standard-things/esm#95]
With version 0.9.2, ava requires std/esm to transpile src modules and babel to transpile test modules. However without unlocking @std/esm "cjs" option, babel transpiled default import won't work with a std/esm default export value:

https://gist.github.com/dinoboff/6124a92531beada5429fe6729a94d76d

Anyway to support default export between test and source modules without unlocking std/esm "cjs" options?

**Comment by jdalton** [comment]
Hi @dinoboff!

Babel requires __esModule to be added to its exports in order to recognize a module as ESM. Since we follow Node's rules by default I moved compat to the cjs option where things like imports of named cjs exports (doable with Babel) are enabled too.

**Comment by dinoboff** [comment]
What are the implication of setting `__esModule`? I am guessing it related to `import()` in cjs module, but I don't see what could break (unlike other `cjs` unlockable features).

Could it have its one options? I would prefer not have to enable any of the other features the `cjs` option covers.

**Comment by jdalton** [comment]
The main issue with doing it by default is that Node won't. Impact wise its minimal since it's a non-enumerable double underbar prefix property that doesn't obstruct custom values. As usage of @std/esm picks up I'll keep an eye on usage and split this out as a standalone option if there's demand.
