### ISSUE TITLE
Jest compatibility

### ISSUE THREAD

**Issue by aemino** [standard-things/esm#97]
Hello,
This is less of an issue and more like a compatibility request. I've been trying to use Jest with this package and it doesn't seem that the two packages currently work very harmoniously. In my test files, I'm using the regular, un-modified `require` function to load `index.js`, which uses `@std/esm` to load other ESM files.

```js
// index.js
require = require('@std/esm')(module);

module.exports = require('./Registry').default;
// ... other exports
```

This is the resulting error when I try to run my tests with Jest. I'm using `npm run test` which runs `jest`. I saw this same stack trace in #28 but I thought I'd open a new issue just to keep things more organized.
![image](https://user-images.githubusercontent.com/13167687/30517996-fefee66c-9b25-11e7-9522-740a00cdb661.png)

Thanks!

**Comment by jdalton** [comment]
Hi @aemino!

What version of `@std/esm` are you using?
It shouldn't be exposing its internals when erroring (an older version accidentally did though).

Can you create a simple repro repo?

**Comment by aemino** [comment]
I'm using the latest version of `@std/esm`, version `0.9.2`.
I've created a simple repro at [aemino/esm-repro](https://github.com/aemino/esm-repro).

**Comment by jdalton** [comment]
Interesting. It looks like Jest is somehow creating a `module` object without an `exports` property.

**Comment by jdalton** [comment]
It looks like Jest is Mocking the `Module` constructor. When it does though it forgot to set its `constructor` property up so the modules it produces have a `.constructor` of `Object` instead of the actual constructor. So when I use `module.constructor` I get `Object` and when I pass an id to it I get a string object back which doesn't have an `exports` property.

**Comment by jdalton** [comment]
What's even more interesting is its `Object` of another realm so checks for `module.constructor === Object` will fail.

**Comment by jdalton** [comment]
Patched https://github.com/standard-things/esm/commit/ab92c9b32130616c4c555e6943fd119fc7536e9e.

**Comment by aemino** [comment]
Awesome! This solved the issue for me. Thank you very much for your work. 👍

**Comment by eliw00d** [comment]
@aemino How are you running jest? I tried to run it but get `Unexpected token import` in the test file.

**Comment by eliw00d** [comment]
I am having a different problem, where I get `Unexpected token import` errors when trying to run Jest tests. Here is a repro repo:

https://github.com/eliw00d/jest-esm

**Comment by jdalton** [comment]
@eliw00d Your `src/main/index.js` isn't being loaded by the loader. You've set it up for the loader to  load a few test files but beyond that the trail runs cold. I'm guessing Jest picks things up and loads them with its own loader *(it is mocking things)*. Normally your package entry script has a load hook-up too so you might try that.

**Comment by eliw00d** [comment]
Ah, I see now. But that could mean a lot of work rewriting tests to require the index rather than the file itself. Thanks.

**Comment by jdalton** [comment]
The tests don't have to require the index. Your package's entry point should be a CJS module that initializes the loader. At the moment your module entry is just a bare ESM module which won't work without a loader.

**Comment by kenotron** [comment]
Seeing as how this is the first google result from people search "esm jest," I'd like to post a solution that works.

Hacked up something that would work even if your tests are use esnext modules (say, from a typescript compile output):

https://github.com/kenotron/esm-jest

Inspiration is from here:

https://stackoverflow.com/questions/46433678/specify-code-to-run-before-any-jest-setup-happens

**Comment by kenotron** [comment]
I've updated this example with your PR, @jdalton - thanks! It looks much cleaner and adds caching 👍

**Comment by dandv** [comment]
@jdalton: how exactly can [NODE_OPTIONS](https://github.com/standard-things/esm/issues/97#issuecomment-330659360) be used to just run `jest` when the test file uses `import` syntax?

`NODE_OPTIONS='-r esm' npx jest` fails with `SyntaxError: Unexpected token {`.

@kenotron's solution is far from simple.

**Comment by jdalton** [comment]
Hi @dandv!

There isn't a clean way at the moment. However, in the next `esm` release you'll be able to specify `esm` as a `transform` in your `jest.config.json`:
```json
  "transform": {
    "\\.m?js$": "../esm"
  },
  "transformIgnorePatterns": []
```

**Comment by pi0** [comment]
@jdalton We are really looking forward to this solution <3

**Comment by jdalton** [comment]
Thanks @pi0!

Still in the process of cleaning it up. I got caught up with the Node+JS Interactive conference and improving support for new dynamic `import()` test262 tests.

**Comment by cabbiepete** [comment]
@jdalton I presume the next esm release will resolve the current jest with esm issue if you configure esm as a transform as above?

Putting this here to let you know in case you were not aware already.

```
TypeError: Jest: a transform must export a `process` function.
```

**Comment by jdalton** [comment]
@cabbiepete 
> I presume the next esm release will resolve the current jest with esm issue if you configure esm as a transform as above?

Correct. It's not available in the current installable release. It will be in the next release though.

**Comment by kenotron** [comment]
Do you know when you will have that release? Is that code available in a branch we can poke at?

**Comment by jdalton** [comment]
@kenotron It's in master branch but is not suitable for shipping and may be broken at the moment. Fixing some things so it's support is in flux.

**Comment by kenotron** [comment]
ooh ooh i'll settle for playing around with on master branch :) That's SOMETHING to hang on to :P

**Comment by rosendi** [comment]
@jdalton I know that this feature is still in progress, but installing esm from the master fails jest:

```
 TypeError: Cannot destructure property `dir` of 'undefined' or 'null'.

      at Object.<anonymous> (../../node_modules/esm/esm.js:233:26)
 ```

The snippet:

```
if (cachePath !== "") {
  const { dir } = shared.package // HERE package is undefined!
```

May be it helps you to land the upcoming release faster.

**Comment by kenotron** [comment]
I am trying out esm 3.1.0 with https://github.com/kenotron/esm-jest

It still fails :(

```
TypeError: Cannot read property 'next' of undefined
      at Object.n.(anonymous function) (node_modules/esm/esm.js:1:1796)
```

Basically it fails to find a ".next" from the _runResults

**Comment by jdalton** [comment]
Correct @kenotron! When trying to get Jest support finished I ran into some blockers that prevented it from making it into the 3.1.0 release. I'll be in a follow-up release for sure.

**Comment by kenotron** [comment]
you're not far! i started a new issue to track some issues that i'm finding here #706

**Comment by chrisdothtml** [comment]
For anyone wondering, you can still use the esm require approach in your tests without the jest `transform` option. e.g.

**my-module.test.js**

```js
const esmRequire = require('esm')(module)
const { foo } = esmRequire('./my-module.js')

describe('my es-module', () => {
//...
```

**my-module.js**
```js
export function foo () {
  //...
}
```

**Comment by edmand46** [comment]
Any news?

**Comment by jdalton** [comment]
Moved to #706.
