### ISSUE TITLE
Missing isMain arg on call to moduleLoad

### ISSUE THREAD

**Issue by clintwood** [standard-things/esm#99]
While digging around I noticed this call to [moduleLoad](https://github.com/standard-things/esm/blob/db543a81080248f53add952c02e0d4ee09a431ce/src/hook/require.js#L36) is missing `isMain` argument in call to `load` from [here](https://github.com/standard-things/esm/blob/master/src/module/esm/load.js#L15) shifting `loadOptions` one up in the parameter list. I'm not sure this is what was intended.

**Comment by jdalton** [comment]
Thanks @clintwood!
